# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
104: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'january': {'ru': 'январь', 'tg': 'январ', 'lemma': 'January'},
    'decides': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'change': {'ru': 'менять', 'tg': 'тағир додан', 'lemma': 'change'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'chosen': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'stop': {'ru': 'переставать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'eating': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'sugar': {'ru': 'сахар', 'tg': 'шакар', 'lemma': 'sugar'},
    'start': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'running': {'ru': 'бегать', 'tg': 'давидан', 'lemma': 'run'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'remembers': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'avoiding': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'exercise': {'ru': 'упражнение (физкультура)', 'tg': 'машқ', 'lemma': 'exercise'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'finding': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'excuse': {'ru': 'оправдание', 'tg': 'баҳона', 'lemma': 'excuse'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'enjoy': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'sleeping': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'more': {'ru': 'больше', 'tg': 'бештар', 'lemma': 'more'},
    'than': {'ru': 'чем', 'tg': 'нисбат ба', 'lemma': 'than'},
    'jogging': {'ru': 'бег трусцой', 'tg': 'давидан', 'lemma': 'jog'},
    'used': {'ru': 'раньше делал (привычка в прошлом)', 'tg': 'пештар мекард', 'lemma': 'used to'},
    'joke': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'colleagues': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'visiting': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'doctor': {'ru': 'врач', 'tg': 'духтур', 'lemma': 'doctor'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'healthier': {'ru': 'более здоровый', 'tg': 'солимтар', 'lemma': 'healthy'},
    'routine': {'ru': 'режим (рутина)', 'tg': 'тартибот', 'lemma': 'routine'},
    'waking': {'ru': 'просыпаться', 'tg': 'бедор шудан', 'lemma': 'wake up'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'hardest': {'ru': 'самый трудный', 'tg': 'душвортарин', 'lemma': 'hard'},
    'part': {'ru': 'часть', 'tg': 'қисм', 'lemma': 'part'},
    'kept': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'forgetting': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'set': {'ru': 'ставить (настраивать)', 'tg': 'танзим кардан', 'lemma': 'set'},
    'alarm': {'ru': 'будильник', 'tg': 'соати бедоркунӣ', 'lemma': 'alarm'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'slowly': {'ru': 'постепенно (медленно)', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'managed': {'ru': 'удаваться (справляться)', 'tg': 'муваффақ шудан', 'lemma': 'manage'},
    'build': {'ru': 'вырабатывать (строить)', 'tg': 'ба вуҷуд овардан', 'lemma': 'build'},
    'habit': {'ru': 'привычка', 'tg': 'одат', 'lemma': 'habit'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'less': {'ru': 'менее', 'tg': 'камтар', 'lemma': 'less'},
    'painful': {'ru': 'болезненный', 'tg': 'дардовар', 'lemma': 'painful'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'drinking': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'hoping': {'ru': 'надеяться', 'tg': 'умед доштан', 'lemma': 'hope'},
    'sleep': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'wife': {'ru': 'жена', 'tg': 'ҳамсар', 'lemma': 'wife'},
    'suggested': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'cooking': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'ordering': {'ru': 'заказывать', 'tg': 'фармоиш додан', 'lemma': 'order'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'preparing': {'ru': 'готовить', 'tg': 'тайёр кардан', 'lemma': 'prepare'},
    'meals': {'ru': 'еда (приём пищи)', 'tg': 'таом', 'lemma': 'meal'},
    'night': {'ru': 'ночь (вечер)', 'tg': 'шаб', 'lemma': 'night'},
    'march': {'ru': 'март', 'tg': 'март', 'lemma': 'March'},
    'learned': {'ru': 'научиться', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'expected': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'happen': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'mind': {'ru': 'возражать (быть против)', 'tg': 'эътироз доштан', 'lemma': 'mind'},
    'anymore': {'ru': 'больше (не)', 'tg': 'дигар', 'lemma': 'anymore'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'tying': {'ru': 'завязывать', 'tg': 'баст кардан', 'lemma': 'tie'},
    'shoelaces': {'ru': 'шнурки', 'tg': 'бандҳои пойафзол', 'lemma': 'shoelace'},
    'sunrise': {'ru': 'восход', 'tg': 'тулӯи офтоб', 'lemma': 'sunrise'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'habits': {'ru': 'привычка', 'tg': 'одат', 'lemma': 'habit'},
    'realizes': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realize'},
    'takes': {'ru': 'требовать (занимать время)', 'tg': 'талаб кардан', 'lemma': 'take'},
    'patience': {'ru': 'терпение', 'tg': 'сабр', 'lemma': 'patience'},
    'is': BE, 'he\'s': BE, 'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'don\'t': DO,
},
105: {
    'before': {'ru': 'до (перед)', 'tg': 'пеш аз', 'lemma': 'before'},
    'exam': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'starts': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'supervisor': {'ru': 'наблюдатель (надзиратель)', 'tg': 'нозир', 'lemma': 'supervisor'},
    'reads': {'ru': 'оглашать (читать)', 'tg': 'хондан', 'lemma': 'read out'},
    'rules': {'ru': 'правило', 'tg': 'қоида', 'lemma': 'rule'},
    'nervous': {'ru': 'нервничающий', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'students': {'ru': 'ученик', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'must': {'ru': 'обязаны (должны)', 'tg': 'бояд', 'lemma': 'must'},
    'switch': {'ru': 'выключать', 'tg': 'хомӯш кардан', 'lemma': 'switch off'},
    'phones': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'mustn\'t': {'ru': 'нельзя (не должны)', 'tg': 'набояд', 'lemma': 'must not'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'any': {'ru': 'какие-либо', 'tg': 'ягон', 'lemma': 'any'},
    'notes': {'ru': 'записи (заметки)', 'tg': 'қайдҳо', 'lemma': 'note'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'pens': {'ru': 'ручка', 'tg': 'қалам', 'lemma': 'pen'},
    'since': {'ru': 'так как (поскольку)', 'tg': 'зеро', 'lemma': 'since'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'provides': {'ru': 'предоставлять', 'tg': 'таъмин кардан', 'lemma': 'provide'},
    'them': {'ru': 'их', 'tg': 'онҳоро', 'lemma': 'they'},
    'have': {'ru': 'должны (обязаны)', 'tg': 'бояд', 'lemma': 'have to'},
    'valid': {'ru': 'действительный', 'tg': 'эътибордор', 'lemma': 'valid'},
    'student': {'ru': 'студенческий', 'tg': 'донишҷӯӣ', 'lemma': 'student'},
    'card': {'ru': 'билет (карта)', 'tg': 'корт', 'lemma': 'card'},
    'talk': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'anyone': {'ru': 'кто-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'once': {'ru': 'как только', 'tg': 'ҳамин ки', 'lemma': 'once'},
    'begins': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'warns': {'ru': 'предупреждать', 'tg': 'огоҳ кардан', 'lemma': 'warn'},
    'walking': {'ru': 'ходить', 'tg': 'қадам задан', 'lemma': 'walk'},
    'between': {'ru': 'между', 'tg': 'дар байни', 'lemma': 'between'},
    'desks': {'ru': 'парта', 'tg': 'парта', 'lemma': 'desk'},
    'latecomers': {'ru': 'опоздавшие', 'tg': 'дершудагон', 'lemma': 'latecomer'},
    'too': {'ru': 'слишком', 'tg': 'аз ҳад зиёд', 'lemma': 'too'},
    'much': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'much'},
    'still': {'ru': 'всё же (всё ещё)', 'tg': 'ба ҳар ҳол', 'lemma': 'still'},
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'same': {'ru': 'то же', 'tg': 'ҳамон', 'lemma': 'same'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'else': {'ru': 'ещё (другой)', 'tg': 'дигар', 'lemma': 'else'},
    'less': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'less'},
    'write': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'halfway': {'ru': 'на полпути', 'tg': 'дар нимаи роҳ', 'lemma': 'halfway'},
    'through': {'ru': 'через', 'tg': 'тавассути', 'lemma': 'through'},
    'girl': {'ru': 'девочка', 'tg': 'духтар', 'lemma': 'girl'},
    'raises': {'ru': 'поднимать', 'tg': 'бардоштан', 'lemma': 'raise'},
    'hand': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'ask': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'paper': {'ru': 'бумага', 'tg': 'коғаз', 'lemma': 'paper'},
    'that': {'ru': 'это', 'tg': 'ин', 'lemma': 'that'},
    'smiles': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'desk': {'ru': 'стол', 'tg': 'миз', 'lemma': 'desk'},
    'finish2': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'leave': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'wait': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'final': {'ru': 'финальный (последний)', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'bell': {'ru': 'звонок', 'tg': 'занг', 'lemma': 'bell'},
    'rings': {'ru': 'звенеть', 'tg': 'занг задан', 'lemma': 'ring'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'nervously': {'ru': 'нервно', 'tg': 'бо асабоният', 'lemma': 'nervously'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'enter': {'ru': 'входить', 'tg': 'даромадан', 'lemma': 'enter'},
    'building': {'ru': 'здание', 'tg': 'бино', 'lemma': 'building'},
    'officially': {'ru': 'официально', 'tg': 'расман', 'lemma': 'officially'},
    'ends': {'ru': 'заканчиваться', 'tg': 'тамом шудан', 'lemma': 'end'},
    'don\'t': DO, 'has': {'ru': 'должна (обязана)', 'tg': 'бояд', 'lemma': 'have to'}, 'shouldn\'t': {'ru': 'не следует', 'tg': 'набояд', 'lemma': 'should'},
},
106: {
    'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'decide': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'whether': {'ru': 'ли (стоит ли)', 'tg': 'оё', 'lemma': 'whether'},
    'change': {'ru': 'менять', 'tg': 'тағир додан', 'lemma': 'change'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'calls': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'older': {'ru': 'старший', 'tg': 'калонӣ', 'lemma': 'older'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'advice': {'ru': 'совет', 'tg': 'маслиҳат', 'lemma': 'advice'},
    'should': {'ru': 'следует', 'tg': 'бояд', 'lemma': 'should'},
    'make': {'ru': 'составлять (делать)', 'tg': 'тартиб додан', 'lemma': 'make'},
    'list': {'ru': 'список', 'tg': 'рӯйхат', 'lemma': 'list'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'bad': {'ru': 'плохой', 'tg': 'бад', 'lemma': 'bad'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'current': {'ru': 'текущий (нынешний)', 'tg': 'ҳозира', 'lemma': 'current'},
    'suggests': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'shouldn\'t': {'ru': 'не следует', 'tg': 'набояд', 'lemma': 'should'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'one': {'ru': 'один (в один)', 'tg': 'як', 'lemma': 'one'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'unhappy': {'ru': 'несчастный (недовольный)', 'tg': 'нохушнуд', 'lemma': 'unhappy'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'afraid': {'ru': 'бояться (испуганный)', 'tg': 'тарсида', 'lemma': 'afraid'},
    'starting': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'somewhere': {'ru': 'где-то', 'tg': 'ҷое', 'lemma': 'somewhere'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'talk': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'manager': {'ru': 'менеджер (начальник)', 'tg': 'менеҷер', 'lemma': 'manager'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'continues': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'maybe': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'maybe'},
    'improve': {'ru': 'улучшаться', 'tg': 'беҳтар шудан', 'lemma': 'improve'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'leaving': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'wonders': {'ru': 'задаваться вопросом', 'tg': 'фикр кардан', 'lemma': 'wonder'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'ask': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'higher': {'ru': 'более высокая', 'tg': 'баландтар', 'lemma': 'high'},
    'salary': {'ru': 'зарплата', 'tg': 'маош', 'lemma': 'salary'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'worst': {'ru': 'худший', 'tg': 'бадтарин', 'lemma': 'worst'},
    'answer': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'discussing': {'ru': 'обсуждать', 'tg': 'муҳокима кардан', 'lemma': 'discuss'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'possible': {'ru': 'возможный', 'tg': 'мумкин', 'lemma': 'possible'},
    'option': {'ru': 'вариант', 'tg': 'вариант', 'lemma': 'option'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'decides': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'trying': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'talking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'making': {'ru': 'принимать (решение)', 'tg': 'қабул кардан', 'lemma': 'make'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'decision': {'ru': 'решение', 'tg': 'қарор', 'lemma': 'decision'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'meeting': {'ru': 'встреча', 'tg': 'вохӯрӣ', 'lemma': 'meeting'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'much': {'ru': 'так много', 'tg': 'зиёд', 'lemma': 'much'},
    'beforehand': {'ru': 'заранее', 'tg': 'пешакӣ', 'lemma': 'beforehand'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'find': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'solution': {'ru': 'решение (выход)', 'tg': 'ҳал', 'lemma': 'solution'},
    'she\'s': BE, 'is': BE, 'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
},
107: {
    'rain': {'ru': 'дождь (идти дождём)', 'tg': 'борон боридан', 'lemma': 'rain'},
    'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'we\'ll': BE, 'picnic': {'ru': 'пикник', 'tg': 'сайругашт', 'lemma': 'picnic'},
    'park': {'ru': 'парк', 'tg': 'боғ', 'lemma': 'park'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'rains': {'ru': 'идти (о дожде)', 'tg': 'борон боридан', 'lemma': 'rain'},
    'move': {'ru': 'переносить (двигать)', 'tg': 'кӯчонидан', 'lemma': 'move'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'place': {'ru': 'дом (место)', 'tg': 'ҷой', 'lemma': 'place'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'agrees': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'wants': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'carry': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'heavy': {'ru': 'тяжёлый', 'tg': 'вазнин', 'lemma': 'heavy'},
    'basket': {'ru': 'корзина', 'tg': 'сабад', 'lemma': 'basket'},
    'mine': {'ru': 'мой (моё)', 'tg': 'аз они ман', 'lemma': 'mine'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'yours': {'ru': 'твой (ваш)', 'tg': 'аз они шумо', 'lemma': 'yours'},
    'another': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'another'},
    'replies': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'pointing': {'ru': 'указывать', 'tg': 'ишора кардан', 'lemma': 'point'},
    'different': {'ru': 'другой (иной)', 'tg': 'дигар', 'lemma': 'different'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'his': {'ru': 'его', 'tg': 'аз они ӯ', 'lemma': 'his'},
    'himself': {'ru': 'сам', 'tg': 'худаш', 'lemma': 'himself'},
    'checks': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'whose': {'ru': 'чей', 'tg': 'аз они кӣ', 'lemma': 'whose'},
    'blanket': {'ru': 'одеяло (плед)', 'tg': 'кӯрпа', 'lemma': 'blanket'},
    'bringing': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'hers': {'ru': 'её', 'tg': 'аз они вай', 'lemma': 'hers'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'bigger': {'ru': 'больше', 'tg': 'калонтар', 'lemma': 'big'},
    'one': {'ru': 'один (штука)', 'tg': 'як', 'lemma': 'one'},
    'brings': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'won\'t': {'ru': 'не будет (нужно)', 'tg': 'нахоҳад', 'lemma': 'will'},
    'need2': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'mine2': {'ru': 'мой', 'tg': 'аз они ман', 'lemma': 'mine'},
    'all': {'ru': 'вообще (всё)', 'tg': 'умуман', 'lemma': 'all'},
    'decides': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'arrives': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'they\'ll': BE, 'catch': {'ru': 'занимать (успевать)', 'tg': 'ишғол кардан', 'lemma': 'catch'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'spot': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'spot'},
    'near': {'ru': 'рядом (с)', 'tg': 'наздик', 'lemma': 'near'},
    'lake': {'ru': 'озеро', 'tg': 'кӯл', 'lemma': 'lake'},
    'forgets': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'simply': {'ru': 'просто', 'tg': 'танҳо', 'lemma': 'simply'},
    'share': {'ru': 'делиться', 'tg': 'тақсим кардан', 'lemma': 'share'},
    'else\'s': {'ru': 'чужой (другого)', 'tg': 'аз они дигарон', 'lemma': 'else'},
    'saturday': {'ru': 'суббота', 'tg': 'шанбе', 'lemma': 'Saturday'},
    'weather': {'ru': 'погода', 'tg': 'обу ҳаво', 'lemma': 'weather'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'changes': {'ru': 'меняться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'happen': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'exactly': {'ru': 'точно (в точности)', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'planned': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'whichever': {'ru': 'какой бы ни', 'tg': 'ҳар кадоме', 'lemma': 'whichever'},
    'remembers': {'ru': 'помнить (не забыть)', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'doesn\'t': DO, 'it\'s': BE, 'is': BE, 'he\'ll': BE,
},
108: {
    'won': {'ru': 'выигрывать', 'tg': 'бурдан', 'lemma': 'win'},
    'lottery': {'ru': 'лотерея', 'tg': 'лотерея', 'lemma': 'lottery'},
    'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'sea': {'ru': 'море', 'tg': 'баҳр', 'lemma': 'sea'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'break': {'ru': 'перерыв', 'tg': 'танаффус', 'lemma': 'break'},
    'wouldn\'t': {'ru': 'не бы', 'tg': 'намебуд', 'lemma': 'would'},
    'quit': {'ru': 'бросать (увольняться)', 'tg': 'тарк кардан', 'lemma': 'quit'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'part': {'ru': 'неполный (частичный)', 'tg': 'қисман', 'lemma': 'part-time'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'disagrees': {'ru': 'не соглашаться', 'tg': 'розӣ набудан', 'lemma': 'disagree'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'much': {'ru': 'столько', 'tg': 'чунон', 'lemma': 'much'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'immediately': {'ru': 'немедленно', 'tg': 'фавран', 'lemma': 'immediately'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'else': {'ru': 'ещё', 'tg': 'дигар', 'lemma': 'else'},
    'jokes': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'rich': {'ru': 'богатый', 'tg': 'бой', 'lemma': 'rich'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'relatives': {'ru': 'родственники', 'tg': 'хешовандон', 'lemma': 'relative'},
    'appear': {'ru': 'появляться', 'tg': 'пайдо шудан', 'lemma': 'appear'},
    'nowhere': {'ru': 'ниоткуда', 'tg': 'аз ҳеҷ ҷо', 'lemma': 'nowhere'},
    'asking': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'loans': {'ru': 'заём (кредит)', 'tg': 'қарз', 'lemma': 'loan'},
    'keep': {'ru': 'держать (хранить)', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'secret': {'ru': 'секрет', 'tg': 'сир', 'lemma': 'secret'},
    'warns': {'ru': 'предупреждать', 'tg': 'огоҳ кардан', 'lemma': 'warn'},
    'half': {'ru': 'наполовину', 'tg': 'ним', 'lemma': 'half'},
    'joking': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'imagine': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'first': {'ru': 'первый', 'tg': 'якум', 'lemma': 'first'},
    'million': {'ru': 'миллион', 'tg': 'миллион', 'lemma': 'million'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'others': {'ru': 'другие', 'tg': 'дигарон', 'lemma': 'other'},
    'invest': {'ru': 'инвестировать', 'tg': 'сармоягузорӣ кардан', 'lemma': 'invest'},
    'business': {'ru': 'бизнес', 'tg': 'тиҷорат', 'lemma': 'business'},
    'weren\'t': BE, 'problem': {'ru': 'проблема', 'tg': 'мушкилот', 'lemma': 'problem'},
    'still2': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'group': {'ru': 'группа', 'tg': 'гурӯҳ', 'lemma': 'group'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'wouldn\'t2': {'ru': 'не бы', 'tg': 'намебуд', 'lemma': 'would'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'miss': {'ru': 'скучать', 'tg': 'дилтанг шудан', 'lemma': 'miss'},
    'daily': {'ru': 'ежедневный', 'tg': 'ҳаррӯза', 'lemma': 'daily'},
    'routine': {'ru': 'рутина', 'tg': 'тартибот', 'lemma': 'routine'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'anything': {'ru': 'что-либо', 'tg': 'чизе', 'lemma': 'anything'},
    'returns': {'ru': 'возвращаться', 'tg': 'баргаштан', 'lemma': 'return'},
    'slightly': {'ru': 'немного', 'tg': 'андак', 'lemma': 'slightly'},
    'happier': {'ru': 'счастливее', 'tg': 'хушбахттар', 'lemma': 'happy'},
    'spent': {'ru': 'провести (потратить)', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'living': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'i\'d': BE, 'i\'ll': BE, 'would2': BE, 'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
},
109: {
    'known': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'other': {'ru': 'другой (друг друга)', 'tg': 'дигар', 'lemma': 'other'},
    'since': {'ru': 'с (с тех пор как)', 'tg': 'аз', 'lemma': 'since'},
    'primary': {'ru': 'начальный', 'tg': 'ибтидоӣ', 'lemma': 'primary school'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'now': {'ru': 'сейчас (уже)', 'tg': 'ҳозир', 'lemma': 'now'},
    'lived': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'different': {'ru': 'разный', 'tg': 'гуногун', 'lemma': 'different'},
    'cities': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'last': {'ru': 'последний (прошедший)', 'tg': 'охирин', 'lemma': 'last'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'stayed': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'close': {'ru': 'близкий', 'tg': 'наздик', 'lemma': 'close'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'wedding': {'ru': 'свадьба', 'tg': 'туй', 'lemma': 'wedding'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'hugging': {'ru': 'обнимать', 'tg': 'оғӯш кардан', 'lemma': 'hug'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'café': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'busy': {'ru': 'занятая', 'tg': 'серкор', 'lemma': 'busy'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'replies': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'met': {'ru': 'встречаться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'person': {'ru': 'лично (человек)', 'tg': 'шахсан', 'lemma': 'in person'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'visited': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'briefly': {'ru': 'ненадолго', 'tg': 'мухтасар', 'lemma': 'briefly'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'event': {'ru': 'мероприятие (событие)', 'tg': 'ҳодиса', 'lemma': 'event'},
    'then': {'ru': 'тогда (с тех пор)', 'tg': 'он вақт', 'lemma': 'then'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'spoken': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'speak'},
    'video': {'ru': 'видео', 'tg': 'видео', 'lemma': 'video'},
    'calls': {'ru': 'звонки', 'tg': 'занг', 'lemma': 'call'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'got': {'ru': 'заблудиться (получать)', 'tg': 'гум шудан', 'lemma': 'get lost'},
    'lost': {'ru': 'потерянный (заблудившийся)', 'tg': 'гумшуда', 'lemma': 'lost'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'recalling': {'ru': 'вспоминать', 'tg': 'ба ёд овардан', 'lemma': 'recall'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'took': {'ru': 'совершать (брать)', 'tg': 'кардан', 'lemma': 'take'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'same2': {'ru': 'той же', 'tg': 'ҳамон', 'lemma': 'same'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'feels': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'settled': {'ru': 'обустроенный (осевший)', 'tg': 'ҷойгиршуда', 'lemma': 'settled'},
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'spring': {'ru': 'весна', 'tg': 'баҳор', 'lemma': 'spring'},
    'explains': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'neighbours': {'ru': 'соседи', 'tg': 'ҳамсоягон', 'lemma': 'neighbour'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'order': {'ru': 'заказывать', 'tg': 'фармоиш додан', 'lemma': 'order'},
    'more': {'ru': 'ещё', 'tg': 'боз', 'lemma': 'more'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'hurry': {'ru': 'спешка', 'tg': 'шитоб', 'lemma': 'hurry'},
    'end': {'ru': 'заканчивать (конец)', 'tg': 'ба охир расондан', 'lemma': 'end'},
    'conversation': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'haven\'t': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'i\'ve': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'they\'ve': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'we\'re': BE,
},
110: {
    'runners': {'ru': 'бегун', 'tg': 'давандаҳо', 'lemma': 'runner'},
    'climb': {'ru': 'взбираться', 'tg': 'баромадан', 'lemma': 'climb'},
    'wooden': {'ru': 'деревянный', 'tg': 'чӯбин', 'lemma': 'wooden'},
    'wall': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'crawl': {'ru': 'ползти', 'tg': 'хазидан', 'lemma': 'crawl'},
    'low': {'ru': 'низкий', 'tg': 'паст', 'lemma': 'low'},
    'net': {'ru': 'сетка', 'tg': 'тӯр', 'lemma': 'net'},
    'jump': {'ru': 'прыгать', 'tg': 'ҷаҳидан', 'lemma': 'jump'},
    'across': {'ru': 'через', 'tg': 'аз', 'lemma': 'across'},
    'muddy': {'ru': 'грязный (илистый)', 'tg': 'лойолуд', 'lemma': 'muddy'},
    'pool': {'ru': 'бассейн (лужа)', 'tg': 'ҳавз', 'lemma': 'pool'},
    'stopping': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'runs': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'through': {'ru': 'через', 'tg': 'тавассути', 'lemma': 'through'},
    'forest': {'ru': 'лес', 'tg': 'ҷангал', 'lemma': 'forest'},
    'path': {'ru': 'тропа', 'tg': 'роҳ', 'lemma': 'path'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'splashes': {'ru': 'плюхаться', 'tg': 'ғарқ шудан', 'lemma': 'splash'},
    'straight': {'ru': 'прямо', 'tg': 'рост', 'lemma': 'straight'},
    'cold': {'ru': 'холодный', 'tg': 'сард', 'lemma': 'cold'},
    'river': {'ru': 'река', 'tg': 'дарё', 'lemma': 'river'},
    'crossing': {'ru': 'переправа', 'tg': 'гузаргоҳ', 'lemma': 'crossing'},
    'climbs': {'ru': 'взбираться', 'tg': 'баромадан', 'lemma': 'climb'},
    'steep': {'ru': 'крутой', 'tg': 'сарбаланд', 'lemma': 'steep'},
    'hill': {'ru': 'холм', 'tg': 'теппа', 'lemma': 'hill'},
    'breathing': {'ru': 'дышать', 'tg': 'нафас кашидан', 'lemma': 'breathe'},
    'heavily': {'ru': 'тяжело', 'tg': 'вазнин', 'lemma': 'heavily'},
    'slides': {'ru': 'скользить', 'tg': 'лағжидан', 'lemma': 'slide'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'side': {'ru': 'сторона', 'tg': 'тараф', 'lemma': 'side'},
    'purpose': {'ru': 'нарочно (цель)', 'tg': 'қасдан', 'lemma': 'on purpose'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'near': {'ru': 'около', 'tg': 'наздик', 'lemma': 'near'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'carry': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'heavy': {'ru': 'тяжёлый', 'tg': 'вазнин', 'lemma': 'heavy'},
    'tyre': {'ru': 'шина', 'tg': 'шина', 'lemma': 'tyre'},
    'point': {'ru': 'точка', 'tg': 'нуқта', 'lemma': 'point'},
    'before': {'ru': 'прежде чем', 'tg': 'пеш аз', 'lemma': 'before'},
    'put': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'put'},
    'down': {'ru': 'вниз', 'tg': 'поён', 'lemma': 'down'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'running': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'just': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'just'},
    'behind': {'ru': 'позади', 'tg': 'дар паси', 'lemma': 'behind'},
    'calls': {'ru': 'кричать (звать)', 'tg': 'фарёд задан', 'lemma': 'call'},
    'cheer': {'ru': 'подбадривать', 'tg': 'рӯҳбаланд кардан', 'lemma': 'cheer'},
    'picks': {'ru': 'ускорять (набирать темп)', 'tg': 'суръат афзудан', 'lemma': 'pick up'},
    'pace': {'ru': 'темп', 'tg': 'суръат', 'lemma': 'pace'},
    'pushes': {'ru': 'толкать', 'tg': 'тела додан', 'lemma': 'push'},
    'forward': {'ru': 'вперёд', 'tg': 'ба пеш', 'lemma': 'forward'},
    'final': {'ru': 'последний', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'field': {'ru': 'поле', 'tg': 'дашт', 'lemma': 'field'},
    'volunteers': {'ru': 'волонтёр', 'tg': 'ихтиёрчиён', 'lemma': 'volunteer'},
    'hand': {'ru': 'раздавать', 'tg': 'тақсим кардан', 'lemma': 'hand out'},
    'water': {'ru': 'вода', 'tg': 'об', 'lemma': 'water'},
    'bottles': {'ru': 'бутылка', 'tg': 'шиша', 'lemma': 'bottle'},
    'rush': {'ru': 'спешить', 'tg': 'шитоб кардан', 'lemma': 'rush'},
    'past': {'ru': 'мимо', 'tg': 'аз пеши', 'lemma': 'past'},
    'towards': {'ru': 'к (по направлению)', 'tg': 'ба сӯи', 'lemma': 'towards'},
    'finish': {'ru': 'финиш', 'tg': 'финиш', 'lemma': 'finish'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'last': {'ru': 'последний', 'tg': 'охирин', 'lemma': 'last'},
    'rope': {'ru': 'верёвка (канат)', 'tg': 'ресмон', 'lemma': 'rope'},
    'drops': {'ru': 'спрыгивать (падать)', 'tg': 'афтодан', 'lemma': 'drop'},
    'onto': {'ru': 'на', 'tg': 'ба рӯи', 'lemma': 'onto'},
    'soft': {'ru': 'мягкий', 'tg': 'мулоим', 'lemma': 'soft'},
    'sand': {'ru': 'песок', 'tg': 'рег', 'lemma': 'sand'},
    'crosses': {'ru': 'пересекать', 'tg': 'убур кардан', 'lemma': 'cross'},
    'line': {'ru': 'линия (финишная)', 'tg': 'хат', 'lemma': 'line'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'catches': {'ru': 'догонять', 'tg': 'расидан', 'lemma': 'catch up'},
    'minute': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'sit': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'rest': {'ru': 'отдыхать', 'tg': 'истироҳат кардан', 'lemma': 'rest'},
    'nearly': {'ru': 'чуть не (почти)', 'tg': 'қариб', 'lemma': 'nearly'},
    'gave': {'ru': 'сдаваться', 'tg': 'даст кашидан', 'lemma': 'give up'},
    'back': {'ru': 'назад (там)', 'tg': 'дар он ҷо', 'lemma': 'back'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'kept': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'going': {'ru': 'продолжать (идти)', 'tg': 'давом додан', 'lemma': 'going'},
    'anyway': {'ru': 'всё равно', 'tg': 'бо ин ҳама', 'lemma': 'anyway'},
    'has': {'ru': 'должен', 'tg': 'бояд', 'lemma': 'have to'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
},
111: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'bakery': {'ru': 'пекарня', 'tg': 'нонвойхона', 'lemma': 'bakery'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'opened': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'same': {'ru': 'те же', 'tg': 'ҳамон', 'lemma': 'same'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'bakers': {'ru': 'пекарь', 'tg': 'нонво', 'lemma': 'baker'},
    'before': {'ru': 'прежде чем', 'tg': 'пеш аз', 'lemma': 'before'},
    'anyone': {'ru': 'кто-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'else': {'ru': 'ещё (другой)', 'tg': 'дигар', 'lemma': 'else'},
    'awake': {'ru': 'проснувшийся', 'tg': 'бедор', 'lemma': 'awake'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'flour': {'ru': 'мука', 'tg': 'орд', 'lemma': 'flour'},
    'mixed': {'ru': 'смешивать', 'tg': 'омехтан', 'lemma': 'mix'},
    'water': {'ru': 'вода', 'tg': 'об', 'lemma': 'water'},
    'salt': {'ru': 'соль', 'tg': 'намак', 'lemma': 'salt'},
    'yeast': {'ru': 'дрожжи', 'tg': 'хамиртуруш', 'lemma': 'yeast'},
    'large': {'ru': 'большой', 'tg': 'калон', 'lemma': 'large'},
    'metal': {'ru': 'металлический', 'tg': 'металлӣ', 'lemma': 'metal'},
    'bowl': {'ru': 'миска', 'tg': 'коса', 'lemma': 'bowl'},
    'dough': {'ru': 'тесто', 'tg': 'хамир', 'lemma': 'dough'},
    'kneaded': {'ru': 'месить', 'tg': 'варзидан', 'lemma': 'knead'},
    'hand': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'until': {'ru': 'пока не', 'tg': 'то', 'lemma': 'until'},
    'becomes': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'smooth': {'ru': 'гладкий', 'tg': 'ҳамвор', 'lemma': 'smooth'},
    'afterwards': {'ru': 'после этого', 'tg': 'баъдтар', 'lemma': 'afterwards'},
    'left': {'ru': 'оставлять', 'tg': 'мондан', 'lemma': 'leave'},
    'rise': {'ru': 'подниматься (о тесте)', 'tg': 'бардам омадан', 'lemma': 'rise'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'covered': {'ru': 'накрывать', 'tg': 'пӯшондан', 'lemma': 'cover'},
    'thin': {'ru': 'тонкий', 'tg': 'борик', 'lemma': 'thin'},
    'cloth': {'ru': 'ткань (полотенце)', 'tg': 'матоъ', 'lemma': 'cloth'},
    'once': {'ru': 'как только', 'tg': 'ҳамин ки', 'lemma': 'once'},
    'risen': {'ru': 'подниматься', 'tg': 'бардам омадан', 'lemma': 'rise'},
    'shaped': {'ru': 'формировать', 'tg': 'шакл додан', 'lemma': 'shape'},
    'round': {'ru': 'круглый', 'tg': 'мудаввар', 'lemma': 'round'},
    'loaves': {'ru': 'буханка', 'tg': 'кулча', 'lemma': 'loaf'},
    'older': {'ru': 'старший', 'tg': 'калонсол', 'lemma': 'older'},
    'baker': {'ru': 'пекарь', 'tg': 'нонво', 'lemma': 'baker'},
    'done': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'thirty': {'ru': 'тридцать', 'tg': 'си', 'lemma': 'thirty'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'loaf': {'ru': 'буханка', 'tg': 'кулча', 'lemma': 'loaf'},
    'placed': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'place'},
    'carefully': {'ru': 'аккуратно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'hot': {'ru': 'горячий', 'tg': 'гарм', 'lemma': 'hot'},
    'oven': {'ru': 'печь (духовка)', 'tg': 'танӯр', 'lemma': 'oven'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'baked': {'ru': 'печь', 'tg': 'пухтан', 'lemma': 'bake'},
    'exactly': {'ru': 'ровно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'forty': {'ru': 'сорок', 'tg': 'чил', 'lemma': 'forty'},
    'while': {'ru': 'пока', 'tg': 'дар ҳоле ки', 'lemma': 'while'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'being': {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'},
    'smell': {'ru': 'запах', 'tg': 'бӯй', 'lemma': 'smell'},
    'fills': {'ru': 'заполнять', 'tg': 'пур кардан', 'lemma': 'fill'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'customers': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'queuing': {'ru': 'стоять в очереди', 'tg': 'дар навбат истодан', 'lemma': 'queue'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'seven': {'ru': 'семь', 'tg': 'ҳафт', 'lemma': 'seven'},
    'taken': {'ru': 'вынимать (брать)', 'tg': 'гирифтан', 'lemma': 'take out'},
    'sold': {'ru': 'продавать', 'tg': 'фурӯхтан', 'lemma': 'sell'},
    'within': {'ru': 'в течение', 'tg': 'дар зарфи', 'lemma': 'within'},
    'made': {'ru': 'делать (изготавливать)', 'tg': 'сохтан', 'lemma': 'make'},
    'any': {'ru': 'какие-либо', 'tg': 'ягон', 'lemma': 'any'},
    'machines': {'ru': 'машина (аппарат)', 'tg': 'дастгоҳ', 'lemma': 'machine'},
    'curious': {'ru': 'любопытный', 'tg': 'кунҷков', 'lemma': 'curious'},
    'customer': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'way': {'ru': 'способ (путь)', 'tg': 'тарз', 'lemma': 'way'},
    'is': BE, 'isn\'t': BE, 'it\'s': BE, 'who': {'ru': 'который', 'tg': 'ки', 'lemma': 'who'},
},
}

for sid, keys in {105: ['finish2'], 107: ['need2', 'mine2'], 108: ['still2', 'wouldn\'t2', 'would2'], 109: ['same2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
