# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
112: {
    'used': {'ru': 'раньше делал (привычка в прошлом)', 'tg': 'пештар мекард', 'lemma': 'used to'},
    'teach': {'ru': 'преподавать', 'tg': 'таълим додан', 'lemma': 'teach'},
    'maths': {'ru': 'математика', 'tg': 'математика', 'lemma': 'maths'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'thirty': {'ru': 'тридцать', 'tg': 'си', 'lemma': 'thirty'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'visits': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'autumn': {'ru': 'осень', 'tg': 'тирамоҳ', 'lemma': 'autumn'},
    'building': {'ru': 'здание', 'tg': 'бино', 'lemma': 'building'},
    'look': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'completely': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'completely'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'current': {'ru': 'нынешний', 'tg': 'ҳозира', 'lemma': 'current'},
    'students': {'ru': 'ученик', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'pointing': {'ru': 'указывать', 'tg': 'ишора кардан', 'lemma': 'point'},
    'modern': {'ru': 'современный', 'tg': 'муосир', 'lemma': 'modern'},
    'hallway': {'ru': 'коридор', 'tg': 'долон', 'lemma': 'hallway'},
    'wooden': {'ru': 'деревянный', 'tg': 'чӯбин', 'lemma': 'wooden'},
    'desks': {'ru': 'парта', 'tg': 'парта', 'lemma': 'desk'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'tree': {'ru': 'дерево', 'tg': 'дарахт', 'lemma': 'tree'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'canteen': {'ru': 'столовая', 'tg': 'ошхона', 'lemma': 'canteen'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'find': {'ru': 'находить (считать)', 'tg': 'ёфтан', 'lemma': 'find'},
    'hard': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'hard'},
    'imagine': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'computers': {'ru': 'компьютер', 'tg': 'компютер', 'lemma': 'computer'},
    'walk': {'ru': 'идти пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'get': {'ru': 'добираться', 'tg': 'расидан', 'lemma': 'get'},
    'here': {'ru': 'сюда', 'tg': 'ин ҷо', 'lemma': 'here'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'continues': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'surprised': {'ru': 'удивлённый', 'tg': 'ҳайрон', 'lemma': 'surprised'},
    'faces': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'give': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'extra': {'ru': 'дополнительный', 'tg': 'иловагӣ', 'lemma': 'extra'},
    'classes': {'ru': 'занятия', 'tg': 'дарсҳо', 'lemma': 'class'},
    'saturdays': {'ru': 'суббота', 'tg': 'шанбе', 'lemma': 'Saturday'},
    'offer': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'anymore': {'ru': 'больше (не)', 'tg': 'дигар', 'lemma': 'anymore'},
    'enjoy': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'teaching': {'ru': 'преподавать', 'tg': 'таълим додан', 'lemma': 'teach'},
    'student': {'ru': 'ученик', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'curiously': {'ru': 'с любопытством', 'tg': 'бо кунҷковӣ', 'lemma': 'curiously'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'strict': {'ru': 'строгий', 'tg': 'сахтгир', 'lemma': 'strict'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'looking': {'ru': 'оглядываясь', 'tg': 'бознигарӣ', 'lemma': 'look back'},
    'back': {'ru': 'назад', 'tg': 'бозгашт', 'lemma': 'back'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'leaves': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'reminds': {'ru': 'напоминать', 'tg': 'ёдовар шудан', 'lemma': 'remind'},
    'homework': {'ru': 'домашнее задание', 'tg': 'вазифаи хонагӣ', 'lemma': 'homework'},
    'much': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'much'},
    'harder': {'ru': 'труднее', 'tg': 'душвортар', 'lemma': 'hard'},
    'day': {'ru': 'время (эпоха)', 'tg': 'замон', 'lemma': 'day'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'quite': {'ru': 'вполне (совсем)', 'tg': 'комилан', 'lemma': 'quite'},
    'believes': {'ru': 'верить', 'tg': 'бовар кардан', 'lemma': 'believe'},
    'doesn\'t': DO, 'wasn\'t': BE, 'was': BE,
},
113: {
    'might': {'ru': 'возможно (могу)', 'tg': 'мумкин аст', 'lemma': 'might'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'hiking': {'ru': 'поход (пешие прогулки)', 'tg': 'сайругашт', 'lemma': 'hiking'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'weather': {'ru': 'погода', 'tg': 'обу ҳаво', 'lemma': 'weather'},
    'stays': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'replies': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'surprised': {'ru': 'удивлённый', 'tg': 'ҳайрон', 'lemma': 'surprised'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'enjoy': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'crowded': {'ru': 'многолюдный', 'tg': 'серодам', 'lemma': 'crowded'},
    'places': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'weekends': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'neither': {'ru': 'тоже нет (ни то, ни другое)', 'tg': 'ҳам не', 'lemma': 'neither'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'similar': {'ru': 'похожий', 'tg': 'монанд', 'lemma': 'similar'},
    'plans': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'sound': {'ru': 'звучать', 'tg': 'ба назар расидан', 'lemma': 'sound'},
    'invite': {'ru': 'приглашать', 'tg': 'даъват кардан', 'lemma': 'invite'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'yet': {'ru': 'ещё', 'tg': 'ҳанӯз', 'lemma': 'yet'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'alone': {'ru': 'один (одна)', 'tg': 'танҳо', 'lemma': 'alone'},
    'free': {'ru': 'свободный', 'tg': 'озод', 'lemma': 'free'},
    'discover': {'ru': 'обнаруживать', 'tg': 'ошкор кардан', 'lemma': 'discover'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'going': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'mountain': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'trail': {'ru': 'тропа', 'tg': 'роҳ', 'lemma': 'trail'},
    'roughly': {'ru': 'примерно', 'tg': 'тахминан', 'lemma': 'roughly'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'hiked': {'ru': 'ходить в поход', 'tg': 'сайругашт кардан', 'lemma': 'hike'},
    'before': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'before'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'shorter': {'ru': 'короче', 'tg': 'кӯтоҳтар', 'lemma': 'short'},
    'path': {'ru': 'тропа', 'tg': 'роҳ', 'lemma': 'path'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'longer': {'ru': 'более длинный', 'tg': 'дарозтар', 'lemma': 'long'},
    'one': {'ru': 'та (штука)', 'tg': 'он', 'lemma': 'one'},
    'too': {'ru': 'слишком', 'tg': 'аз ҳад зиёд', 'lemma': 'too'},
    'difficult': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'difficult'},
    'afternoon': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'quietly': {'ru': 'тихо (незаметно)', 'tg': 'ором', 'lemma': 'quietly'},
    'arranged': {'ru': 'договариваться', 'tg': 'мувофиқа кардан', 'lemma': 'arrange'},
    'meet': {'ru': 'встретиться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'entrance': {'ru': 'вход', 'tg': 'дарвозаи вуруд', 'lemma': 'entrance'},
    'saturday': {'ru': 'суббота', 'tg': 'шанбе', 'lemma': 'Saturday'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'picnic': {'ru': 'пикник', 'tg': 'сайругашт', 'lemma': 'picnic'},
    'adds': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'looks': {'ru': 'похоже (выглядит)', 'tg': 'намудор мешавад', 'lemma': 'looks like'},
    'needs': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'hike': {'ru': 'идти в поход', 'tg': 'сайругашт кардан', 'lemma': 'hike'},
    'don\'t': DO, 'haven\'t': HAVE, 'have': HAVE, 'i\'ve': HAVE, 'nobody\'s': BE,
},
114: {
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'meeting': {'ru': 'встреча (совещание)', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'started': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'left': {'ru': 'покидать (уходить)', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'sudden': {'ru': 'внезапный', 'tg': 'ногаҳонӣ', 'lemma': 'sudden'},
    'traffic': {'ru': 'пробка (движение)', 'tg': 'бандубасти роҳ', 'lemma': 'traffic jam'},
    'jam': {'ru': 'пробка', 'tg': 'бандубаст', 'lemma': 'jam'},
    'delayed': {'ru': 'задерживать', 'tg': 'таъхир кардан', 'lemma': 'delay'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'reached': {'ru': 'достигать', 'tg': 'расидан', 'lemma': 'reach'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'discussion': {'ru': 'обсуждение', 'tg': 'муҳокима', 'lemma': 'discussion'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'earlier': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'earlier'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'sent': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'email': {'ru': 'электронное письмо', 'tg': 'номаи электронӣ', 'lemma': 'email'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'moving': {'ru': 'переносить (менять)', 'tg': 'иваз кардан', 'lemma': 'move'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'checked': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'since': {'ru': 'с (с тех пор как)', 'tg': 'аз', 'lemma': 'since'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'realized': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realize'},
    'missed': {'ru': 'пропускать', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'decision': {'ru': 'решение', 'tg': 'қарор', 'lemma': 'decision'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'project': {'ru': 'проект', 'tg': 'лоиҳа', 'lemma': 'project'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'team': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'deadline': {'ru': 'срок (дедлайн)', 'tg': 'мӯҳлат', 'lemma': 'deadline'},
    'one': {'ru': 'тот (штука)', 'tg': 'он', 'lemma': 'one'},
    'known': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'felt': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'annoyed': {'ru': 'раздражённый', 'tg': 'асабонӣ', 'lemma': 'annoyed'},
    'called': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'directly': {'ru': 'напрямую', 'tg': 'бевосита', 'lemma': 'directly'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'discovered': {'ru': 'обнаруживать', 'tg': 'ошкор кардан', 'lemma': 'discover'},
    'tried': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'silent': {'ru': 'беззвучный', 'tg': 'бесадо', 'lemma': 'silent'},
    'all': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'all'},
    'lunchtime': {'ru': 'обеденное время', 'tg': 'вақти нисфирӯзӣ', 'lemma': 'lunchtime'},
    'accepted': {'ru': 'принимать (соглашаться)', 'tg': 'қабул кардан', 'lemma': 'accept'},
    'mistake': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'partly': {'ru': 'частично', 'tg': 'қисман', 'lemma': 'partly'},
    'promised': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'himself': {'ru': 'себе (сам)', 'tg': 'ба худ', 'lemma': 'himself'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'had': HAVE, 'hadn\'t': HAVE, 'was': BE, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'},
},
115: {
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'starts': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'arguing': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'earlier': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'earlier'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'shopping': {'ru': 'покупки', 'tg': 'харид', 'lemma': 'shopping'},
    'replies': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'told': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'try': {'ru': 'попытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'definitely': {'ru': 'определённо', 'tg': 'бешубҳа', 'lemma': 'definitely'},
    'daughter': {'ru': 'дочь', 'tg': 'духтар', 'lemma': 'daughter'},
    'mentions': {'ru': 'упоминать', 'tg': 'ёдовар шудан', 'lemma': 'mention'},
    'grandma': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandma'},
    'soup': {'ru': 'суп', 'tg': 'шӯрбо', 'lemma': 'soup'},
    'needed': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'more': {'ru': 'больше', 'tg': 'бештар', 'lemma': 'more'},
    'salt': {'ru': 'соль', 'tg': 'намак', 'lemma': 'salt'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'no': {'ru': 'никакого (не)', 'tg': 'ҳеҷ', 'lemma': 'no'},
    'such': {'ru': 'такое', 'tg': 'чунин', 'lemma': 'such'},
    'thing': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'broke': {'ru': 'ломать (разбить)', 'tg': 'шикастан', 'lemma': 'break'},
    'vase': {'ru': 'ваза', 'tg': 'гулдон', 'lemma': 'vase'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'looking': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'around': {'ru': 'вокруг', 'tg': 'атроф', 'lemma': 'around'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'answers': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'directly': {'ru': 'напрямую', 'tg': 'бевосита', 'lemma': 'directly'},
    'son': {'ru': 'сын', 'tg': 'писар', 'lemma': 'son'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'broken': {'ru': 'сломанный', 'tg': 'шикаста', 'lemma': 'broken'},
    'touched': {'ru': 'трогать', 'tg': 'даст расондан', 'lemma': 'touch'},
    'happened': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'trying': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'change': {'ru': 'сменить (менять)', 'tg': 'иваз кардан', 'lemma': 'change'},
    'subject': {'ru': 'тема', 'tg': 'мавзӯъ', 'lemma': 'subject'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'wanted': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'join': {'ru': 'присоединиться', 'tg': 'ҳамроҳ шудан', 'lemma': 'join'},
    'choir': {'ru': 'хор', 'tg': 'хор', 'lemma': 'choir'},
    'raised': {'ru': 'поднимать', 'tg': 'бардоштан', 'lemma': 'raise'},
    'hand': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'wants': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'dessert': {'ru': 'десерт', 'tg': 'десерт', 'lemma': 'dessert'},
    'time2': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'goes': {'ru': 'подниматься (вставать)', 'tg': 'бардошта шудан', 'lemma': 'go up'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'single': {'ru': 'единственный (ни один)', 'tg': 'ягон', 'lemma': 'single'},
    'argument': {'ru': 'спор', 'tg': 'баҳс', 'lemma': 'argument'},
    'later2': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'washing': {'ru': 'мыть', 'tg': 'шустан', 'lemma': 'wash'},
    'dishes': {'ru': 'посуда', 'tg': 'зарфҳо', 'lemma': 'dish'},
    'smiles': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'thinking': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'you\'d': BE, 'he\'d': BE, 'had': HAVE,
},
116: {
    'sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'cooks': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'huge': {'ru': 'огромный', 'tg': 'бузург', 'lemma': 'huge'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'finds': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'excuse': {'ru': 'повод (оправдание)', 'tg': 'баҳона', 'lemma': 'excuse'},
    'believes': {'ru': 'верить (считать)', 'tg': 'бовар доштан', 'lemma': 'believe'},
    'cooking': {'ru': 'готовка', 'tg': 'пухтупаз', 'lemma': 'cooking'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'way': {'ru': 'способ', 'tg': 'роҳ', 'lemma': 'way'},
    'show': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'love': {'ru': 'любовь', 'tg': 'муҳаббат', 'lemma': 'love'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'lets': {'ru': 'позволять', 'tg': 'иҷозат додан', 'lemma': 'let'},
    'leave': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'hungry': {'ru': 'голодный', 'tg': 'гурусна', 'lemma': 'hungry'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'stirring': {'ru': 'помешивать', 'tg': 'ҳам задан', 'lemma': 'stir'},
    'pot': {'ru': 'кастрюля', 'tg': 'дег', 'lemma': 'pot'},
    'soup': {'ru': 'суп', 'tg': 'шӯрбо', 'lemma': 'soup'},
    'uncle': {'ru': 'дядя', 'tg': 'тағо', 'lemma': 'uncle'},
    'argues': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'football': {'ru': 'футбол', 'tg': 'футбол', 'lemma': 'football'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'cousin': {'ru': 'двоюродный брат', 'tg': 'амакбача', 'lemma': 'cousin'},
    'famously': {'ru': 'общеизвестно', 'tg': 'машҳуран', 'lemma': 'famously'},
    'stubborn': {'ru': 'упрямый', 'tg': 'якрав', 'lemma': 'stubborn'},
    'helping': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'much': {'ru': 'сколько', 'tg': 'чанд', 'lemma': 'much'},
    'needs': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'confidently': {'ru': 'уверенно', 'tg': 'боэътимод', 'lemma': 'confidently'},
    'reaching': {'ru': 'тянуться', 'tg': 'даст дароз кардан', 'lemma': 'reach'},
    'stops': {'ru': 'останавливать', 'tg': 'боздоштан', 'lemma': 'stop'},
    'trust': {'ru': 'доверять', 'tg': 'бовар кардан', 'lemma': 'trust'},
    'seasoning': {'ru': 'приправа', 'tg': 'ҳанут', 'lemma': 'seasoning'},
    'disastrous': {'ru': 'катастрофический', 'tg': 'фалокатовар', 'lemma': 'disastrous'},
    'rice': {'ru': 'рис', 'tg': 'биринҷ', 'lemma': 'rice'},
    'incident': {'ru': 'случай (инцидент)', 'tg': 'ҳодиса', 'lemma': 'incident'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'little': {'ru': 'младшая', 'tg': 'хурд', 'lemma': 'little'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'shy': {'ru': 'застенчивый', 'tg': 'шармгин', 'lemma': 'shy'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'adults': {'ru': 'взрослый', 'tg': 'калонсол', 'lemma': 'adult'},
    'relaxed': {'ru': 'расслабленный', 'tg': 'ором', 'lemma': 'relaxed'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'terrible': {'ru': 'ужасный', 'tg': 'даҳшатнок', 'lemma': 'terrible'},
    'jokes': {'ru': 'шутка', 'tg': 'шӯхӣ', 'lemma': 'joke'},
    'meanwhile': {'ru': 'тем временем', 'tg': 'дар айни ҳол', 'lemma': 'meanwhile'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'setting': {'ru': 'накрывать (стол)', 'tg': 'чидан', 'lemma': 'set'},
    'counting': {'ru': 'считать', 'tg': 'шумурдан', 'lemma': 'count'},
    'plates': {'ru': 'тарелка', 'tg': 'табақ', 'lemma': 'plate'},
    'forgets': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'mention': {'ru': 'упоминать', 'tg': 'ёдовар шудан', 'lemma': 'mention'},
    'guest': {'ru': 'гость', 'tg': 'меҳмон', 'lemma': 'guest'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'expecting': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'aunt': {'ru': 'тётя', 'tg': 'хола', 'lemma': 'aunt'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'properly': {'ru': 'толком (как следует)', 'tg': 'дуруст', 'lemma': 'properly'},
    'met': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'wants': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'smell': {'ru': 'запах', 'tg': 'бӯй', 'lemma': 'smell'},
    'fresh': {'ru': 'свежий', 'tg': 'тоза', 'lemma': 'fresh'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'fills': {'ru': 'наполнять', 'tg': 'пур кардан', 'lemma': 'fill'},
    'realise': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'loud': {'ru': 'громкий', 'tg': 'баланд', 'lemma': 'loud'},
    'chaotic': {'ru': 'хаотичный', 'tg': 'бетартиб', 'lemma': 'chaotic'},
    'miss': {'ru': 'скучать', 'tg': 'дилтанг шудан', 'lemma': 'miss'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'move': {'ru': 'съезжать (переезжать)', 'tg': 'кӯч бастан', 'lemma': 'move out'},
    'is': BE, 'she\'s': BE, 'doesn\'t': DO, 'we\'re': BE, 'she\'d': BE,
},
117: {
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'summer': {'ru': 'лето', 'tg': 'тобистон', 'lemma': 'summer'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'taking': {'ru': 'везти (брать)', 'tg': 'бурдан', 'lemma': 'take'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'coast': {'ru': 'побережье', 'tg': 'соҳил', 'lemma': 'coast'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'booked': {'ru': 'бронировать', 'tg': 'фармоиш додан', 'lemma': 'book'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'going': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
    'happen': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'leaving': {'ru': 'уезжать', 'tg': 'рафтан', 'lemma': 'leave'},
    'first': {'ru': 'первое', 'tg': 'якум', 'lemma': 'first'},
    'july': {'ru': 'июль', 'tg': 'июл', 'lemma': 'July'},
    'announced': {'ru': 'объявлять', 'tg': 'эълон кардан', 'lemma': 'announce'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'showing': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'confirmation': {'ru': 'подтверждение', 'tg': 'тасдиқ', 'lemma': 'confirmation'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'terrified': {'ru': 'напуганный', 'tg': 'сахт тарсида', 'lemma': 'terrified'},
    'long': {'ru': 'долгий', 'tg': 'дароз', 'lemma': 'long'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'journeys': {'ru': 'поездка (путешествие)', 'tg': 'сафар', 'lemma': 'journey'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'flying': {'ru': 'лететь', 'tg': 'парвоз кардан', 'lemma': 'fly'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'driving': {'ru': 'ехать (на машине)', 'tg': 'мошин рондан', 'lemma': 'drive'},
    'adventure': {'ru': 'приключение', 'tg': 'саргузашт', 'lemma': 'adventure'},
    'complain': {'ru': 'жаловаться', 'tg': 'шикоят кардан', 'lemma': 'complain'},
    'way': {'ru': 'путь', 'tg': 'роҳ', 'lemma': 'way'},
    'honestly': {'ru': 'честно', 'tg': 'самимона', 'lemma': 'honestly'},
    'telling': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'bring': {'ru': 'приводить (приносить)', 'tg': 'овардан', 'lemma': 'bring'},
    'boyfriend': {'ru': 'парень (бойфренд)', 'tg': 'дӯстписар', 'lemma': 'boyfriend'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'makes': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'little': {'ru': 'немного', 'tg': 'андак', 'lemma': 'little'},
    'complicated': {'ru': 'сложный', 'tg': 'мураккаб', 'lemma': 'complicated'},
    'sleep': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'rearrange': {'ru': 'перестраивать', 'tg': 'дубора танзим кардан', 'lemma': 'rearrange'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'spend': {'ru': 'проводить (время)', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'beach': {'ru': 'пляж', 'tg': 'соҳил', 'lemma': 'beach'},
    'insist': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'visiting': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'historical': {'ru': 'исторический', 'tg': 'таърихӣ', 'lemma': 'historical'},
    'site': {'ru': 'достопримечательность', 'tg': 'ҷои таърихӣ', 'lemma': 'site'},
    'nearby': {'ru': 'поблизости', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'whether': {'ru': 'хотим ли (или нет)', 'tg': 'оё', 'lemma': 'whether'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'join': {'ru': 'присоединиться', 'tg': 'ҳамроҳ шудан', 'lemma': 'join'},
    'too': {'ru': 'тоже', 'tg': 'низ', 'lemma': 'too'},
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'hating': {'ru': 'ненавидеть', 'tg': 'нафрат доштан', 'lemma': 'hate'},
    'miss': {'ru': 'пропускать (скучать)', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'firmly': {'ru': 'твёрдо', 'tg': 'қатъӣ', 'lemma': 'firmly'},
    'excitement': {'ru': 'волнение (возбуждение)', 'tg': 'ҳаяҷон', 'lemma': 'excitement'},
    'suspect': {'ru': 'подозревать', 'tg': 'шубҳа кардан', 'lemma': 'suspect'},
    'none': {'ru': 'никто (ни один)', 'tg': 'ҳеҷ кадом', 'lemma': 'none'},
    'forgets': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'worse': {'ru': 'хуже', 'tg': 'бадтар', 'lemma': 'worse'},
    'are': BE, 'we\'re': BE, 'it\'s': BE, 'who\'s': BE, 'has': HAVE, 'i\'ll': BE, 'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'}, 'won\'t': {'ru': 'не будет', 'tg': 'нахоҳад', 'lemma': 'will'}, 'she\'ll': BE, 'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
},
118: {
    'called': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'news': {'ru': 'новость', 'tg': 'хабар', 'lemma': 'news'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'expected': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'degree': {'ru': 'диплом (степень)', 'tg': 'дараҷа', 'lemma': 'degree'},
    'passed': {'ru': 'сдавать (проходить)', 'tg': 'супоридан', 'lemma': 'pass'},
    'final': {'ru': 'финальный', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'exams': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'hard': {'ru': 'усердно', 'tg': 'сахт', 'lemma': 'hard'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'told': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'relief': {'ru': 'облегчение', 'tg': 'сабукӣ', 'lemma': 'relief'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'studied': {'ru': 'учиться', 'tg': 'таҳсил кардан', 'lemma': 'study'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'barely': {'ru': 'едва', 'tg': 'базӯр', 'lemma': 'barely'},
    'nearly': {'ru': 'чуть не', 'tg': 'қариб', 'lemma': 'nearly'},
    'gave': {'ru': 'сдаваться', 'tg': 'даст кашидан', 'lemma': 'give up'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'changed': {'ru': 'меняться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'enormously': {'ru': 'значительно (сильно)', 'tg': 'бенихоят', 'lemma': 'enormously'},
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'alone': {'ru': 'одна', 'tg': 'танҳо', 'lemma': 'alone'},
    'took': {'ru': 'требовать (брать)', 'tg': 'талаб кардан', 'lemma': 'take'},
    'real': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'real'},
    'courage': {'ru': 'смелость', 'tg': 'ҷасорат', 'lemma': 'courage'},
    'saved': {'ru': 'копить (сохранять)', 'tg': 'пасандоз кардан', 'lemma': 'save'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'rent': {'ru': 'снимать (арендовать)', 'tg': 'ба иҷора гирифтан', 'lemma': 'rent'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'flat': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'flat'},
    'imagined': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'right': {'ru': 'сразу', 'tg': 'дарҳол', 'lemma': 'right after'},
    'interview': {'ru': 'собеседование', 'tg': 'мусоҳиба', 'lemma': 'interview'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'sounding': {'ru': 'звучать', 'tg': 'ба назар расидан', 'lemma': 'sound'},
    'amazed': {'ru': 'изумлённый', 'tg': 'ҳайратзада', 'lemma': 'amazed'},
    'luck': {'ru': 'удача', 'tg': 'бахт', 'lemma': 'luck'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'visited': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'briefly': {'ru': 'ненадолго', 'tg': 'мухтасар', 'lemma': 'briefly'},
    'spring': {'ru': 'весна', 'tg': 'баҳор', 'lemma': 'spring'},
    'much': {'ru': 'насколько', 'tg': 'чанд', 'lemma': 'much'},
    'felt': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'genuinely': {'ru': 'искренне', 'tg': 'самимона', 'lemma': 'genuinely'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'anxious': {'ru': 'встревоженный', 'tg': 'нигарон', 'lemma': 'anxious'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'unrecognisable': {'ru': 'неузнаваемый', 'tg': 'ношинос', 'lemma': 'unrecognisable'},
    'hanging': {'ru': 'вешать (трубку)', 'tg': 'қатъ кардан', 'lemma': 'hang up'},
    'promised': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'visit': {'ru': 'навестить', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'soon': {'ru': 'скоро', 'tg': 'ба зудӣ', 'lemma': 'soon'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'planning': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'cook': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'herself': {'ru': 'сама', 'tg': 'худаш', 'lemma': 'herself'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'she\'s': BE, 'i\'ve': HAVE, 'have': HAVE, 'she\'ll': BE,
},
119: {
    'building': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'now': {'ru': 'уже (сейчас)', 'tg': 'ҳозир', 'lemma': 'now'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'saving': {'ru': 'копить', 'tg': 'пасандоз кардан', 'lemma': 'save'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'since': {'ru': 'с (с тех пор как)', 'tg': 'аз', 'lemma': 'since'},
    'before': {'ru': 'до', 'tg': 'пеш аз', 'lemma': 'before'},
    'born': {'ru': 'родиться', 'tg': 'таваллуд шудан', 'lemma': 'be born'},
    'buying': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'materials': {'ru': 'материалы', 'tg': 'маводҳо', 'lemma': 'material'},
    'whenever': {'ru': 'всякий раз, когда', 'tg': 'ҳар вақте ки', 'lemma': 'whenever'},
    'could': {'ru': 'мог', 'tg': 'метавонист', 'lemma': 'could'},
    'afford': {'ru': 'позволить себе', 'tg': 'иқтидор доштан', 'lemma': 'afford'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'explains': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'embarrassed': {'ru': 'смущённый', 'tg': 'хиҷолатманд', 'lemma': 'embarrassed'},
    'whenever2': {'ru': 'всякий раз, когда', 'tg': 'ҳар вақте ки', 'lemma': 'whenever'},
    'guests': {'ru': 'гости', 'tg': 'меҳмонон', 'lemma': 'guest'},
    'ask': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'laying': {'ru': 'укладывать', 'tg': 'фарш кардан', 'lemma': 'lay'},
    'tiles': {'ru': 'плитка', 'tg': 'кошин', 'lemma': 'tile'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'himself': {'ru': 'сам', 'tg': 'худаш', 'lemma': 'himself'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'choosing': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'paint': {'ru': 'краска', 'tg': 'ранг', 'lemma': 'paint'},
    'colours': {'ru': 'цвет', 'tg': 'ранг', 'lemma': 'colour'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'changing': {'ru': 'менять', 'tg': 'тағир додан', 'lemma': 'change'},
    'mind': {'ru': 'мнение (ум)', 'tg': 'фикр', 'lemma': 'mind'},
    'constantly': {'ru': 'постоянно', 'tg': 'доимо', 'lemma': 'constantly'},
    'dreaming': {'ru': 'мечтать', 'tg': 'орзу кардан', 'lemma': 'dream'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'land': {'ru': 'земля (участок)', 'tg': 'замин', 'lemma': 'land'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'dirt': {'ru': 'земля (грязь)', 'tg': 'хок', 'lemma': 'dirt'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'determined': {'ru': 'упорный (решительный)', 'tg': 'қатъӣ', 'lemma': 'determined'},
    'weeds': {'ru': 'сорняк', 'tg': 'алафи бегона', 'lemma': 'weed'},
    'long': {'ru': 'долго', 'tg': 'дароз', 'lemma': 'long'},
    'living': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'proper': {'ru': 'настоящий (нормальный)', 'tg': 'дурустӣ', 'lemma': 'proper'},
    'roof': {'ru': 'крыша', 'tg': 'бом', 'lemma': 'roof'},
    'aunt': {'ru': 'тётя', 'tg': 'хола', 'lemma': 'aunt'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'recently': {'ru': 'недавно', 'tg': 'ба наздикӣ', 'lemma': 'recently'},
    'half': {'ru': 'наполовину', 'tg': 'ним', 'lemma': 'half'},
    'joking': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'inside': {'ru': 'внутри', 'tg': 'дарун', 'lemma': 'inside'},
    'work': {'ru': 'работа', 'tg': 'кор', 'lemma': 'work'},
    'progress': {'ru': 'прогресс (в процессе)', 'tg': 'пешрафт', 'lemma': 'progress'},
    'helping': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'mostly': {'ru': 'в основном', 'tg': 'бештар', 'lemma': 'mostly'},
    'painting': {'ru': 'красить', 'tg': 'ранг кардан', 'lemma': 'paint'},
    'walls': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'badly': {'ru': 'плохо', 'tg': 'бад', 'lemma': 'badly'},
    'technique': {'ru': 'техника (метод)', 'tg': 'усул', 'lemma': 'technique'},
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'mess': {'ru': 'беспорядок', 'tg': 'бетартибӣ', 'lemma': 'mess'},
    'exciting': {'ru': 'захватывающий', 'tg': 'ҳаяҷонбахш', 'lemma': 'exciting'},
    'slowly': {'ru': 'медленно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'become': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'home': {'ru': 'дом (родной)', 'tg': 'хона', 'lemma': 'home'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'process': {'ru': 'процесс', 'tg': 'раванд', 'lemma': 'process'},
    'itself': {'ru': 'сам', 'tg': 'худаш', 'lemma': 'itself'},
    'truly': {'ru': 'поистине', 'tg': 'дар ҳақиқат', 'lemma': 'truly'},
    'done': {'ru': 'сделанный (готовый)', 'tg': 'тамомшуда', 'lemma': 'done'},
    'isn\'t': BE, 'they\'ve': HAVE, 'he\'s': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'}, 'she\'s': HAVE, 'has': HAVE, 'is': BE, 'there\'s': BE, 'i\'ve': HAVE, 'they\'ll': BE,
},
}

for sid, keys in {115: ['time2', 'later2'], 119: ['whenever2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
