# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
78: {
    'likes': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'taking': {'ru': 'снимать (фотографировать)', 'tg': 'акс гирифтан', 'lemma': 'take photos'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'takes': {'ru': 'снимать (фотографировать)', 'tg': 'акс гирифтан', 'lemma': 'take'},
    'everywhere': {'ru': 'везде', 'tg': 'дар ҳама ҷо', 'lemma': 'everywhere'},
    'park': {'ru': 'парк', 'tg': 'боғ', 'lemma': 'park'},
    'market': {'ru': 'рынок', 'tg': 'бозор', 'lemma': 'market'},
    'roof': {'ru': 'крыша', 'tg': 'бом', 'lemma': 'roof'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'camera': {'ru': 'камера (фотоаппарат)', 'tg': 'камера', 'lemma': 'camera'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'loves': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'visits': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'saturday': {'ru': 'суббота', 'tg': 'шанбе', 'lemma': 'Saturday'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'photographs': {'ru': 'фотографировать', 'tg': 'акс гирифтан', 'lemma': 'photograph'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'colourful': {'ru': 'красочный', 'tg': 'рангоранг', 'lemma': 'colourful'},
    'carpets': {'ru': 'ковёр', 'tg': 'қолин', 'lemma': 'carpet'},
    'sees': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'calls': {'ru': 'звать', 'tg': 'даъват кардан', 'lemma': 'call'},
    'girl': {'ru': 'девочка', 'tg': 'духтар', 'lemma': 'girl'},
    'come': {'ru': 'иди(те)', 'tg': 'биёед', 'lemma': 'come'},
    'here': {'ru': 'сюда', 'tg': 'ин ҷо', 'lemma': 'here'},
    'afraid': {'ru': 'испуганный', 'tg': 'тарсида', 'lemma': 'afraid'},
    'goes': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'show': {'ru': 'показать', 'tg': 'нишон додан', 'lemma': 'show'},
    'shows': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'pictures': {'ru': 'фотография (картина)', 'tg': 'расм', 'lemma': 'picture'},
    'looks': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'long': {'ru': 'долгий', 'tg': 'дароз', 'lemma': 'long'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'your': {'ru': 'твой (ваш)', 'tg': 'аз они шумо', 'lemma': 'your'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'like': {'ru': 'так, как', 'tg': 'мисли', 'lemma': 'like'},
    'this': {'ru': 'это', 'tg': 'ин', 'lemma': 'this'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
    'print': {'ru': 'печатать', 'tg': 'чоп кардан', 'lemma': 'print'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'granddaughter': {'ru': 'внучка', 'tg': 'набера', 'lemma': 'granddaughter'},
    'canada': {'ru': 'Канада', 'tg': 'Канада', 'lemma': 'Canada'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'send': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'misses': {'ru': 'скучать', 'tg': 'дилтанг шудан', 'lemma': 'miss'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'brings': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'gives': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'carpet': {'ru': 'ковёр', 'tg': 'қолин', 'lemma': 'carpet'},
    'artist': {'ru': 'художник', 'tg': 'рассом', 'lemma': 'artist'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'photo': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'is': BE, 'isn\'t': BE,
},
79: {
    'date': {'ru': 'дата', 'tg': 'сана', 'lemma': 'date'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'wife': {'ru': 'жена', 'tg': 'ҳамсар', 'lemma': 'wife'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'twelfth': {'ru': 'двенадцатое', 'tg': 'дувоздаҳум', 'lemma': 'twelfth'},
    'june': {'ru': 'июнь', 'tg': 'июн', 'lemma': 'June'},
    'why': {'ru': 'почему', 'tg': 'чаро', 'lemma': 'why'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'reason': {'ru': 'причина', 'tg': 'сабаб', 'lemma': 'reason'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'face': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'thinks': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'hard': {'ru': 'усердно (напряжённо)', 'tg': 'сахт', 'lemma': 'hard'},
    'mother\'s': {'ru': 'мамин', 'tg': 'аз они модар', 'lemma': 'mother'},
    'birthday': {'ru': 'день рождения', 'tg': 'зодрӯз', 'lemma': 'birthday'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'first': {'ru': 'первое', 'tg': 'якум', 'lemma': 'first'},
    'doesn\'t': DO,
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'calls': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'salom': {'ru': 'привет', 'tg': 'салом', 'lemma': 'salom'},
    'quick': {'ru': 'быстрый', 'tg': 'тез', 'lemma': 'quick'},
    'question': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'when': {'ru': 'когда', 'tg': 'кай', 'lemma': 'when'},
    'mum\'s': {'ru': 'мамин', 'tg': 'аз они модар', 'lemma': 'mum'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'serious': {'ru': 'серьёзный', 'tg': 'ҷиддӣ', 'lemma': 'serious'},
    'buying': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'flowers': {'ru': 'цветы', 'tg': 'гул', 'lemma': 'flower'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'drives': {'ru': 'ехать', 'tg': 'рондан', 'lemma': 'drive'},
    'biggest': {'ru': 'самый большой', 'tg': 'бузургтарин', 'lemma': 'biggest'},
    'flower': {'ru': 'цветок', 'tg': 'гул', 'lemma': 'flower'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'buys': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'roses': {'ru': 'роза', 'tg': 'садбарг', 'lemma': 'rose'},
    'cake': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'card': {'ru': 'открытка', 'tg': 'открытка', 'lemma': 'card'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'meets': {'ru': 'встречаться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'opens': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'door': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'cakes': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'sons': {'ru': 'сын', 'tg': 'писар', 'lemma': 'son'},
    'dear': {'ru': 'дорогой', 'tg': 'азиз', 'lemma': 'dear'},
    'boys': {'ru': 'мальчик', 'tg': 'писарбача', 'lemma': 'boy'},
    'smiles': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'thank': {'ru': 'благодарить', 'tg': 'ташаккур гуфтан', 'lemma': 'thank'},
    'father\'s': {'ru': 'папин', 'tg': 'аз они падар', 'lemma': 'father'},
    'brothers': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'chair': {'ru': 'стул', 'tg': 'курсӣ', 'lemma': 'chair'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'sit': {'ru': 'сядь(те)', 'tg': 'нишинед', 'lemma': 'sit'},
    'let\'s': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'let'},
    'celebrate': {'ru': 'праздновать', 'tg': 'ҷашн гирифтан', 'lemma': 'celebrate'},
    'is': BE, 'it\'s': BE, 'are': BE,
},
80: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'attic': {'ru': 'чердак', 'tg': 'болохона', 'lemma': 'attic'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'boxes': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'photo': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'men': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'front': {'ru': 'перед', 'tg': 'пеш', 'lemma': 'front'},
    'who': {'ru': 'кто', 'tg': 'кӣ', 'lemma': 'who'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'left': {'ru': 'левый', 'tg': 'чап', 'lemma': 'left'},
    'grandfather': {'ru': 'дедушка', 'tg': 'бобо', 'lemma': 'grandfather'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'don\'t': DO,
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'curious': {'ru': 'любопытный', 'tg': 'кунҷков', 'lemma': 'curious'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'back': {'ru': 'обратная сторона', 'tg': 'пушт', 'lemma': 'back'},
    'showed': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'oldest': {'ru': 'самый старый', 'tg': 'калонсолтарин', 'lemma': 'old'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'quiet': {'ru': 'тихий (молчаливый)', 'tg': 'ором', 'lemma': 'quiet'},
    'minute': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'oh': {'ru': 'ох', 'tg': 'оҳ', 'lemma': 'oh'},
    'that': {'ru': 'тот', 'tg': 'он', 'lemma': 'that'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'students': {'ru': 'студент', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'funny': {'ru': 'весёлый', 'tg': 'хушмуомила', 'lemma': 'funny'},
    'kind': {'ru': 'добрый', 'tg': 'меҳрубон', 'lemma': 'kind'},
    'khorog': {'ru': 'Хорог', 'tg': 'Хоруғ', 'lemma': 'Khorog'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'there': {'ru': 'там', 'tg': 'дар он ҷо', 'lemma': 'there'},
    'that2': {'ru': 'этот', 'tg': 'ин', 'lemma': 'that'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'son': {'ru': 'сын', 'tg': 'писар', 'lemma': 'son'},
    'online': {'ru': 'онлайн', 'tg': 'онлайн', 'lemma': 'online'},
    'families': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'because': {'ru': 'потому что', 'tg': 'зеро', 'lemma': 'because'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'door2': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'past': {'ru': 'прошлое', 'tg': 'гузашта', 'lemma': 'past'},
    'were': BE, 'was': BE, 'wasn\'t': BE,
},
82: {
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'mother\'s': {'ru': 'мамин', 'tg': 'аз они модар', 'lemma': 'mother'},
    'birthday': {'ru': 'день рождения', 'tg': 'зодрӯз', 'lemma': 'birthday'},
    'made': {'ru': 'делать (готовить)', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'chocolate': {'ru': 'шоколад', 'tg': 'шоколад', 'lemma': 'chocolate'},
    'cake': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'left': {'ru': 'оставлять', 'tg': 'мондан', 'lemma': 'leave'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'came': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'back': {'ru': 'назад', 'tg': 'бозгашт', 'lemma': 'back'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'empty': {'ru': 'пустой', 'tg': 'холӣ', 'lemma': 'empty'},
    'plate': {'ru': 'тарелка', 'tg': 'табақ', 'lemma': 'plate'},
    'who': {'ru': 'кто', 'tg': 'кӣ', 'lemma': 'who'},
    'ate': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'investigation': {'ru': 'расследование', 'tg': 'тафтишот', 'lemma': 'investigation'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'didn\'t': DO,
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'lesson': {'ru': 'урок', 'tg': 'дарс', 'lemma': 'lesson'},
    'half': {'ru': 'половина', 'tg': 'ним', 'lemma': 'half'},
    'past': {'ru': 'после (о времени)', 'tg': 'аз', 'lemma': 'past'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'watched': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'football': {'ru': 'футбол', 'tg': 'футбол', 'lemma': 'football'},
    'living': {'ru': 'гостиная', 'tg': 'меҳмонхона', 'lemma': 'living room'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'all': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'all'},
    'afternoon': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'little': {'ru': 'младший (маленький)', 'tg': 'хурд', 'lemma': 'little'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'true': {'ru': 'правда', 'tg': 'ҳақиқат', 'lemma': 'true'},
    'no': {'ru': 'никакой', 'tg': 'ягон', 'lemma': 'no'},
    'hands': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'clean': {'ru': 'чистый', 'tg': 'тоза', 'lemma': 'clean'},
    'heard': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'sound': {'ru': 'звук', 'tg': 'садо', 'lemma': 'sound'},
    'under': {'ru': 'под', 'tg': 'дар зери', 'lemma': 'under'},
    'cat': {'ru': 'кошка', 'tg': 'гурба', 'lemma': 'cat'},
    'look': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'cream': {'ru': 'крем', 'tg': 'қаймоқ', 'lemma': 'cream'},
    'white': {'ru': 'белый', 'tg': 'сафед', 'lemma': 'white'},
    'nose': {'ru': 'нос', 'tg': 'бинӣ', 'lemma': 'nose'},
    'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'dangerous': {'ru': 'опасный', 'tg': 'хатарнок', 'lemma': 'dangerous'},
    'called': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'vet': {'ru': 'ветеринар', 'tg': 'ветеринар', 'lemma': 'vet'},
    'fine': {'ru': 'в порядке', 'tg': 'хуб', 'lemma': 'fine'},
    'itself': {'ru': 'сам', 'tg': 'худаш', 'lemma': 'itself'},
    'floor': {'ru': 'пол', 'tg': 'фарш', 'lemma': 'floor'},
    'behind': {'ru': 'за (позади)', 'tg': 'дар паси', 'lemma': 'behind'},
    'door': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'found2': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'guilty': {'ru': 'виновный', 'tg': 'гунаҳкор', 'lemma': 'guilty'},
    'dirty': {'ru': 'грязный', 'tg': 'ифлос', 'lemma': 'dirty'},
    'was': BE, 'wasn\'t': BE, 'were': BE,
},
83: {
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'tell': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'scary': {'ru': 'страшный', 'tg': 'даҳшатнок', 'lemma': 'scary'},
    'stories': {'ru': 'история', 'tg': 'ҳикоя', 'lemma': 'story'},
    'rich': {'ru': 'богатый', 'tg': 'бой', 'lemma': 'rich'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'ghosts': {'ru': 'призрак', 'tg': 'арвоҳ', 'lemma': 'ghost'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'check': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'opened': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'gate': {'ru': 'ворота', 'tg': 'дарвоза', 'lemma': 'gate'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'inside': {'ru': 'внутри', 'tg': 'дарун', 'lemma': 'inside'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'dust': {'ru': 'пыль', 'tg': 'чанг', 'lemma': 'dust'},
    'spiders': {'ru': 'паук', 'tg': 'тортанак', 'lemma': 'spider'},
    'walls': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'any': {'ru': 'какой-либо', 'tg': 'ягон', 'lemma': 'any'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'library': {'ru': 'библиотека', 'tg': 'китобхона', 'lemma': 'library'},
    'hundreds': {'ru': 'сотни', 'tg': 'садҳо', 'lemma': 'hundred'},
    'books': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'piano': {'ru': 'фортепиано', 'tg': 'пианино', 'lemma': 'piano'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'wall': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'kind': {'ru': 'добрый', 'tg': 'меҳрубон', 'lemma': 'kind'},
    'eyes': {'ru': 'глаз', 'tg': 'чашм', 'lemma': 'eye'},
    'around': {'ru': 'вокруг', 'tg': 'атрофи', 'lemma': 'around'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'that': {'ru': 'тот', 'tg': 'он', 'lemma': 'that'},
    'doctor': {'ru': 'врач', 'tg': 'духтур', 'lemma': 'doctor'},
    'free': {'ru': 'бесплатный', 'tg': 'ройгон', 'lemma': 'free'},
    'hospital': {'ru': 'больница', 'tg': 'беморхона', 'lemma': 'hospital'},
    'poor': {'ru': 'бедный', 'tg': 'камбағал', 'lemma': 'poor'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'spent': {'ru': 'тратить', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'medicine': {'ru': 'лекарство', 'tg': 'дору', 'lemma': 'medicine'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'make': {'ru': 'делать (создавать)', 'tg': 'сохтан', 'lemma': 'make'},
    'museum': {'ru': 'музей', 'tg': 'осорхона', 'lemma': 'museum'},
    'only2': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'forgot': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'was': BE, 'were': BE, 'weren\'t': BE, 'wasn\'t': BE, 'is': BE,
},
84: {
    'sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'uncle': {'ru': 'дядя', 'tg': 'тағо', 'lemma': 'uncle'},
    'cooks': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'about': {'ru': 'около', 'tg': 'тахминан', 'lemma': 'about'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'market': {'ru': 'рынок', 'tg': 'бозор', 'lemma': 'market'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'much': {'ru': 'сколько (много)', 'tg': 'чанд', 'lemma': 'much'},
    'rice': {'ru': 'рис', 'tg': 'биринҷ', 'lemma': 'rice'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'ask': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'kilos': {'ru': 'килограмм', 'tg': 'килограмм', 'lemma': 'kilo'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'carrots': {'ru': 'морковь', 'tg': 'сабзӣ', 'lemma': 'carrot'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'meat': {'ru': 'мясо', 'tg': 'гӯшт', 'lemma': 'meat'},
    'mountain': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'yellow': {'ru': 'жёлтый', 'tg': 'зард', 'lemma': 'yellow'},
    'checks': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'carefully': {'ru': 'внимательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'these': {'ru': 'эти', 'tg': 'ин', 'lemma': 'these'},
    'those': {'ru': 'те', 'tg': 'он', 'lemma': 'those'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'some': {'ru': 'немного', 'tg': 'баъзе', 'lemma': 'some'},
    'oil': {'ru': 'масло', 'tg': 'равған', 'lemma': 'oil'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'onions': {'ru': 'лук', 'tg': 'пиёз', 'lemma': 'onion'},
    'little': {'ru': 'немного', 'tg': 'андак', 'lemma': 'little'},
    'garlic': {'ru': 'чеснок', 'tg': 'сир', 'lemma': 'garlic'},
    'how': {'ru': 'сколько (как)', 'tg': 'чанд', 'lemma': 'how'},
    'many': {'ru': 'многие (сколько)', 'tg': 'чанд', 'lemma': 'many'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'salt': {'ru': 'соль', 'tg': 'намак', 'lemma': 'salt'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'hand': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'starts': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'fire': {'ru': 'огонь', 'tg': 'оташ', 'lemma': 'fire'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'smell': {'ru': 'запах', 'tg': 'бӯй', 'lemma': 'smell'},
    'fantastic': {'ru': 'потрясающий', 'tg': 'аҷоиб', 'lemma': 'fantastic'},
    'adds': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'water': {'ru': 'вода', 'tg': 'об', 'lemma': 'water'},
    'wait': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'don\'t': DO,
    'touch': {'ru': 'трогать', 'tg': 'даст расондан', 'lemma': 'touch'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'ready': {'ru': 'готовый', 'tg': 'тайёр', 'lemma': 'ready'},
    'talk': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'talk'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'busy': {'ru': 'занятый', 'tg': 'серкор', 'lemma': 'busy'},
    'cousin': {'ru': 'двоюродный брат', 'tg': 'амакбача', 'lemma': 'cousin'},
    'asks2': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'pot': {'ru': 'котёл', 'tg': 'дег', 'lemma': 'pot'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'left': {'ru': 'оставшийся', 'tg': 'боқимонда', 'lemma': 'left'},
    'is': BE, 'are': BE,
},
85: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'august': {'ru': 'август', 'tg': 'август', 'lemma': 'August'},
    'village': {'ru': 'деревня', 'tg': 'деҳа', 'lemma': 'village'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'championship': {'ru': 'чемпионат', 'tg': 'чемпионат', 'lemma': 'championship'},
    'whose': {'ru': 'чей', 'tg': 'аз они кӣ', 'lemma': 'whose'},
    'melon': {'ru': 'дыня', 'tg': 'харбуза', 'lemma': 'melon'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'takes': {'ru': 'относиться (принимать)', 'tg': 'қабул кардан', 'lemma': 'take'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'seriously': {'ru': 'серьёзно', 'tg': 'ҷиддӣ', 'lemma': 'seriously'},
    'melons': {'ru': 'дыня', 'tg': 'харбуза', 'lemma': 'melon'},
    'sweeter': {'ru': 'слаще', 'tg': 'ширинтар', 'lemma': 'sweet'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'every2': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'bigger': {'ru': 'больше', 'tg': 'калонтар', 'lemma': 'big'},
    'rounder': {'ru': 'круглее', 'tg': 'мудаввартар', 'lemma': 'round'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'main': {'ru': 'главный', 'tg': 'асосӣ', 'lemma': 'main'},
    'truly': {'ru': 'поистине', 'tg': 'дар ҳақиқат', 'lemma': 'truly'},
    'enormous': {'ru': 'огромный', 'tg': 'азим', 'lemma': 'enormous'},
    'heavier': {'ru': 'тяжелее', 'tg': 'вазнинтар', 'lemma': 'heavy'},
    'cat': {'ru': 'кошка', 'tg': 'гурба', 'lemma': 'cat'},
    'football': {'ru': 'футбол', 'tg': 'футбол', 'lemma': 'football'},
    'happier': {'ru': 'счастливее', 'tg': 'хушбахттар', 'lemma': 'happy'},
    'child': {'ru': 'ребёнок', 'tg': 'кӯдак', 'lemma': 'child'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'competition': {'ru': 'соревнование', 'tg': 'мусобиқа', 'lemma': 'competition'},
    'judges': {'ru': 'судья', 'tg': 'довар', 'lemma': 'judge'},
    'walked': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'smaller': {'ru': 'меньше', 'tg': 'хурдтар', 'lemma': 'small'},
    'neighbour\'s': {'ru': 'соседский', 'tg': 'аз они ҳамсоя', 'lemma': 'neighbour'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'paler': {'ru': 'бледнее', 'tg': 'рангпарида-тар', 'lemma': 'pale'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'came': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'old': {'ru': 'старый (возраст)', 'tg': 'синну сол', 'lemma': 'old'},
    'cart': {'ru': 'тележка', 'tg': 'арава', 'lemma': 'cart'},
    'very2': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'round': {'ru': 'круглый', 'tg': 'мудаввар', 'lemma': 'round'},
    'cut': {'ru': 'резать', 'tg': 'буридан', 'lemma': 'cut'},
    'tried': {'ru': 'пробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'piece': {'ru': 'кусок', 'tg': 'пора', 'lemma': 'piece'},
    'faces': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'changed': {'ru': 'менять(ся)', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'honey': {'ru': 'мёд', 'tg': 'асал', 'lemma': 'honey'},
    'size': {'ru': 'размер', 'tg': 'андоза', 'lemma': 'size'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'taste': {'ru': 'вкус', 'tg': 'таъм', 'lemma': 'taste'},
    'more': {'ru': 'более', 'tg': 'бештар', 'lemma': 'more'},
    'took': {'ru': 'брать (получать)', 'tg': 'гирифтан', 'lemma': 'take'},
    'prize': {'ru': 'приз', 'tg': 'ҷоиза', 'lemma': 'prize'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'going': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
    'secret': {'ru': 'секретный', 'tg': 'махфӣ', 'lemma': 'secret'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'we\'ll': {'ru': 'мы (буд. время)', 'tg': 'мо хоҳем', 'lemma': 'we'},
    'is': BE, 'was': BE,
},
87: {
    'last': {'ru': 'последний', 'tg': 'охирин', 'lemma': 'last'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'sitting': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'roof': {'ru': 'крыша', 'tg': 'бом', 'lemma': 'roof'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'lights': {'ru': 'огни (свет)', 'tg': 'нурҳо', 'lemma': 'light'},
    'below': {'ru': 'внизу', 'tg': 'поён', 'lemma': 'below'},
    'future': {'ru': 'будущее', 'tg': 'оянда', 'lemma': 'future'},
    'front': {'ru': 'перед', 'tg': 'пеш', 'lemma': 'front'},
    'what': {'ru': 'что', 'tg': 'чӣ', 'lemma': 'what'},
    'going': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
    'do': DO, 'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'study': {'ru': 'изучать', 'tg': 'омӯхтан', 'lemma': 'study'},
    'medicine': {'ru': 'медицина', 'tg': 'тиб', 'lemma': 'medicine'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'doctor': {'ru': 'врач', 'tg': 'духтур', 'lemma': 'doctor'},
    'like': {'ru': 'как (подобно)', 'tg': 'мисли', 'lemma': 'like'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'computer': {'ru': 'компьютер', 'tg': 'компютер', 'lemma': 'computer'},
    'club': {'ru': 'клуб', 'tg': 'клуб', 'lemma': 'club'},
    'kids': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'kid'},
    'learn': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'programming': {'ru': 'программирование', 'tg': 'барномасозӣ', 'lemma': 'programming'},
    'there': {'ru': 'там', 'tg': 'дар он ҷо', 'lemma': 'there'},
    'quiet': {'ru': 'тихий (молчаливый)', 'tg': 'ором', 'lemma': 'quiet'},
    'minute': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'chef': {'ru': 'шеф-повар', 'tg': 'сарошпаз', 'lemma': 'chef'},
    'cook': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'country': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'famous': {'ru': 'известный', 'tg': 'машҳур', 'lemma': 'famous'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'ask': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'look': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'stars': {'ru': 'звезда', 'tg': 'ситора', 'lemma': 'star'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'world': {'ru': 'мир', 'tg': 'дунё', 'lemma': 'world'},
    'one': {'ru': 'однажды', 'tg': 'як рӯз', 'lemma': 'one day'},
    'write': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'boring': {'ru': 'скучный', 'tg': 'дилгиркунанда', 'lemma': 'boring'},
    'jokes': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'chapter': {'ru': 'глава', 'tg': 'боб', 'lemma': 'chapter'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'long': {'ru': 'долго (долгий)', 'tg': 'дароз', 'lemma': 'long'},
    'is': BE, 'are': BE, 'am': BE,
},
}

DICTS[78].pop('show', None)
for sid, keys in {80: ['that2', 'door2'], 82: ['found2'], 83: ['only2'], 84: ['asks2'], 85: ['every2', 'very2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
