import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
62: {
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'got': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'get up'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'walk': {'ru': 'гулять (прогулка)', 'tg': 'сайр кардан', 'lemma': 'walk'},
    'met': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'our': {'ru': 'наш', 'tg': 'аз они мо', 'lemma': 'our'},
    'holidays': {'ru': 'отпуск (каникулы)', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'shopping': {'ru': 'делать покупки', 'tg': 'харид кардан', 'lemma': 'shopping'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'dress': {'ru': 'платье', 'tg': 'курта', 'lemma': 'dress'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'present': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'present'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'watched': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'did': DO, 'didn\'t': DO,
    'some': {'ru': 'немного', 'tg': 'баъзе', 'lemma': 'some'},
    'housework': {'ru': 'домашняя работа', 'tg': 'кори хона', 'lemma': 'housework'},
    'cooked': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'radio': {'ru': 'радио', 'tg': 'радио', 'lemma': 'radio'},
    'felt': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'was': BE,
},
63: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'train': {'ru': 'поезд', 'tg': 'поезд', 'lemma': 'train'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'platform': {'ru': 'платформа', 'tg': 'платформа', 'lemma': 'platform'},
    'tall': {'ru': 'высокий', 'tg': 'баланд', 'lemma': 'tall'},
    'blonde': {'ru': 'блондинка', 'tg': 'мӯйзарин', 'lemma': 'blonde'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'smell': {'ru': 'запах', 'tg': 'бӯй', 'lemma': 'smell'},
    'next': {'ru': 'рядом (с)', 'tg': 'дар паҳлӯи', 'lemma': 'next'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'that\'s': {'ru': 'это', 'tg': 'ин', 'lemma': 'that'},
    'interesting': {'ru': 'интересный', 'tg': 'ҷолиб', 'lemma': 'interesting'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'would': {'ru': 'хотел бы', 'tg': 'мехостам', 'lemma': 'would'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'tickets': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'hall': {'ru': 'зал', 'tg': 'толор', 'lemma': 'hall'},
    'seats': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'exchanged': {'ru': 'обмениваться', 'tg': 'мубодила кардан', 'lemma': 'exchange'},
    'messages': {'ru': 'сообщение', 'tg': 'паём', 'lemma': 'message'},
    'turned': {'ru': 'включать', 'tg': 'даргирондан', 'lemma': 'turn on'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'light': {'ru': 'свет', 'tg': 'равшанӣ', 'lemma': 'light'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'meet': {'ru': 'знакомиться (встречать)', 'tg': 'шинос шудан', 'lemma': 'meet'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'surprise': {'ru': 'сюрприз', 'tg': 'ғайричашмдошт', 'lemma': 'surprise'},
    'was': BE, 'is': BE, 'am': BE, 'didn\'t': DO,
},
64: {
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'ticket': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'put': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'put'},
    'bag': {'ru': 'сумка', 'tg': 'сумка', 'lemma': 'bag'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'hall': {'ru': 'зал', 'tg': 'толор', 'lemma': 'hall'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'seat': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'orchestra': {'ru': 'оркестр', 'tg': 'оркестр', 'lemma': 'orchestra'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'find': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'looked': {'ru': 'смотреть (искать)', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'coat': {'ru': 'пальто', 'tg': 'палто', 'lemma': 'coat'},
    'didn\'t': DO,
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'this': {'ru': 'это', 'tg': 'ин', 'lemma': 'this'},
    'your': {'ru': 'твой (ваш)', 'tg': 'аз они шумо', 'lemma': 'your'},
    'floor': {'ru': 'пол', 'tg': 'фарш', 'lemma': 'floor'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'thank': {'ru': 'благодарить', 'tg': 'ташаккур гуфтан', 'lemma': 'thank'},
    'dropped': {'ru': 'ронять', 'tg': 'афтондан', 'lemma': 'drop'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'keep': {'ru': 'сохранять (держать)', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'souvenir': {'ru': 'сувенир', 'tg': 'ёдгорӣ', 'lemma': 'souvenir'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'lose': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'was': BE, 'is': BE,
},
65: {
    'got': {'ru': 'садиться (на транспорт)', 'tg': 'савор шудан', 'lemma': 'get on'},
    'train': {'ru': 'поезд', 'tg': 'поезд', 'lemma': 'train'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'seat': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'excuse': {'ru': 'извинять', 'tg': 'бубахшед', 'lemma': 'excuse'},
    'your': {'ru': 'твой (ваш)', 'tg': 'аз они шумо', 'lemma': 'your'},
    'sorry': {'ru': 'извини(те)', 'tg': 'бубахшед', 'lemma': 'sorry'},
    'didn\'t': DO,
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'looked': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'ticket': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'made': {'ru': 'делать (совершать)', 'tg': 'кардан', 'lemma': 'make'},
    'mistake': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'moved': {'ru': 'переходить (двигаться)', 'tg': 'ҳаракат кардан', 'lemma': 'move'},
    'smelled': {'ru': 'чувствовать запах', 'tg': 'бӯй кардан', 'lemma': 'smell'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'perfume': {'ru': 'духи', 'tg': 'атр', 'lemma': 'perfume'},
    'next': {'ru': 'рядом (с)', 'tg': 'дар паҳлӯи', 'lemma': 'next'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'exchanged': {'ru': 'обмениваться', 'tg': 'мубодила кардан', 'lemma': 'exchange'},
    'numbers': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'would': {'ru': 'хотел бы', 'tg': 'мехостам', 'lemma': 'would'},
    'like2': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'are': BE, 'was': BE,
},
66: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'dark': {'ru': 'тёмный', 'tg': 'торик', 'lemma': 'dark'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'see': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'anything': {'ru': 'что-нибудь', 'tg': 'чизе', 'lemma': 'anything'},
    'turned': {'ru': 'включать', 'tg': 'даргирондан', 'lemma': 'turn on'},
    'light': {'ru': 'свет', 'tg': 'равшанӣ', 'lemma': 'light'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'message': {'ru': 'сообщение', 'tg': 'паём', 'lemma': 'message'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'said': {'ru': 'говорить (гласить)', 'tg': 'гуфтан', 'lemma': 'say'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'remembered': {'ru': 'вспоминать', 'tg': 'дар ёд овардан', 'lemma': 'remember'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'tickets': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'hall': {'ru': 'зал', 'tg': 'толор', 'lemma': 'hall'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'seat': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'started': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'closed': {'ru': 'закрывать', 'tg': 'пӯшидан', 'lemma': 'close'},
    'eyes': {'ru': 'глаз', 'tg': 'чашм', 'lemma': 'eye'},
    'smelled': {'ru': 'чувствовать запах', 'tg': 'бӯй кардан', 'lemma': 'smell'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'perfume': {'ru': 'духи', 'tg': 'атр', 'lemma': 'perfume'},
    'opened': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'next': {'ru': 'рядом (с)', 'tg': 'дар паҳлӯи', 'lemma': 'next'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'back': {'ru': 'в ответ (назад)', 'tg': 'дар ҷавоб', 'lemma': 'back'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'too': {'ru': 'тоже', 'tg': 'низ', 'lemma': 'too'},
    'exchanged': {'ru': 'обмениваться', 'tg': 'мубодила кардан', 'lemma': 'exchange'},
    'numbers': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'was': BE, 'me': {'ru': 'я тоже (мне)', 'tg': 'ман низ', 'lemma': 'me'},
},
67: {
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'train': {'ru': 'поезд', 'tg': 'поезд', 'lemma': 'train'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'that\'s': {'ru': 'это', 'tg': 'ин', 'lemma': 'that'},
    'interesting': {'ru': 'интересный', 'tg': 'ҷолиб', 'lemma': 'interesting'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'it\'s': {'ru': 'это', 'tg': 'ин', 'lemma': 'it'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'exchanged': {'ru': 'обмениваться', 'tg': 'мубодила кардан', 'lemma': 'exchange'},
    'ideas': {'ru': 'идея', 'tg': 'ғоя', 'lemma': 'idea'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'stopped': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'have': {'ru': 'быть должным (нужно)', 'tg': 'бояд', 'lemma': 'have to'},
    'wait': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'tickets': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'concerts': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'grateful': {'ru': 'благодарный', 'tg': 'миннатдор', 'lemma': 'grateful'},
    'that2': {'ru': 'тот', 'tg': 'он', 'lemma': 'that'},
    'ride': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'ride'},
    'changed': {'ru': 'менять', 'tg': 'тағир додан', 'lemma': 'change'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'was': BE, 'is': BE, 'am': BE,
},
68: {
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'from': {'ru': 'из', 'tg': 'аз', 'lemma': 'from'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'lesson': {'ru': 'урок', 'tg': 'дарс', 'lemma': 'lesson'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'nervous': {'ru': 'нервный', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'classroom': {'ru': 'класс (кабинет)', 'tg': 'синфхона', 'lemma': 'classroom'},
    'warm': {'ru': 'тёплый', 'tg': 'гарм', 'lemma': 'warm'},
    'friendly': {'ru': 'дружелюбный', 'tg': 'дӯстона', 'lemma': 'friendly'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'accent': {'ru': 'акцент', 'tg': 'лаҳҷа', 'lemma': 'accent'},
    'funny': {'ru': 'смешной', 'tg': 'хандаовар', 'lemma': 'funny'},
    'twelve': {'ru': 'двенадцать', 'tg': 'дувоздаҳ', 'lemma': 'twelve'},
    'students': {'ru': 'ученик', 'tg': 'хонанда', 'lemma': 'student'},
    'class': {'ru': 'класс', 'tg': 'синф', 'lemma': 'class'},
    'twins': {'ru': 'близнецы', 'tg': 'дугоникҳо', 'lemma': 'twins'},
    'world': {'ru': 'мир', 'tg': 'дунё', 'lemma': 'world'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'question': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'easy': {'ru': 'лёгкий', 'tg': 'осон', 'lemma': 'easy'},
    'what\'s': {'ru': 'что (есть)', 'tg': 'чист', 'lemma': 'what'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'answer': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'short': {'ru': 'короткий', 'tg': 'кӯтоҳ', 'lemma': 'short'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'smiles': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'classmates': {'ru': 'одноклассник', 'tg': 'ҳамсинф', 'lemma': 'classmate'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'difficult': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'difficult'},
    'mistakes': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'ok': {'ru': 'хорошо (нормально)', 'tg': 'хуб', 'lemma': 'okay'},
    'they\'re': {'ru': 'они (являются)', 'tg': 'онҳо ҳастанд', 'lemma': 'they'},
    'enemies': {'ru': 'враг', 'tg': 'душман', 'lemma': 'enemy'},
    'am': BE, 'is': BE, 'he\'s': BE, 'are': BE,
},
69: {
    'monday': {'ru': 'понедельник', 'tg': 'душанбе', 'lemma': 'Monday'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'centre': {'ru': 'центр', 'tg': 'марказ', 'lemma': 'centre'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'bag': {'ru': 'сумка', 'tg': 'сумка', 'lemma': 'bag'},
    'heavy': {'ru': 'тяжёлый', 'tg': 'вазнин', 'lemma': 'heavy'},
    'there\'s': {'ru': 'там есть', 'tg': 'ҳаст', 'lemma': 'there is'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'free': {'ru': 'свободный', 'tg': 'озод', 'lemma': 'free'},
    'seat': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'next': {'ru': 'рядом (с)', 'tg': 'дар паҳлӯи', 'lemma': 'next'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'excuse': {'ru': 'извинять', 'tg': 'бубахшед', 'lemma': 'excuse'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'sits': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'rings': {'ru': 'звонить (о звонке)', 'tg': 'занг задан', 'lemma': 'ring'},
    'hello': {'ru': 'привет (алло)', 'tg': 'салом', 'lemma': 'hello'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'angry': {'ru': 'сердитый', 'tg': 'хашмгин', 'lemma': 'angry'},
    'looks': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'out': {'ru': 'наружу', 'tg': 'берун', 'lemma': 'out'},
    'window': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'wait': {'ru': 'подожди(те)', 'tg': 'сабр кунед', 'lemma': 'wait'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'right': {'ru': 'правильный', 'tg': 'дуруст', 'lemma': 'right'},
    'these': {'ru': 'эти', 'tg': 'ин', 'lemma': 'these'},
    'shops': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'familiar': {'ru': 'знакомый', 'tg': 'шинос', 'lemma': 'familiar'},
    'number': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'wrong': {'ru': 'неправильный (не тот)', 'tg': 'нодуруст', 'lemma': 'wrong'},
    'face': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'red': {'ru': 'красный', 'tg': 'сурх', 'lemma': 'red'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'stop': {'ru': 'остановка', 'tg': 'истгоҳ', 'lemma': 'stop'},
    'far': {'ru': 'далеко', 'tg': 'дур', 'lemma': 'far'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'is': BE, 'isn\'t': BE, 'am': BE, 'are': BE, 'aren\'t': BE,
},
}

for sid in (65, 67):
    d = DICTS[sid]
    d.pop('like2', None)
    d.pop('that2', None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
