# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
136: {
    'interview': {'ru': 'интервью', 'tg': 'мусоҳиба', 'lemma': 'interview'},
    'began': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'journalist': {'ru': 'журналист', 'tg': 'журналист', 'lemma': 'journalist'},
    'wondered': {'ru': 'размышлять (задаваться вопросом)', 'tg': 'фикр кардан', 'lemma': 'wonder'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'phrase': {'ru': 'формулировать', 'tg': 'ифода кардан', 'lemma': 'phrase'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'question': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'approved': {'ru': 'одобрять', 'tg': 'тасдиқ кардан', 'lemma': 'approve'},
    'project': {'ru': 'проект', 'tg': 'лоиҳа', 'lemma': 'project'},
    'anyone': {'ru': 'кто-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'ultimately': {'ru': 'в конечном счёте', 'tg': 'дар ниҳоят', 'lemma': 'ultimately'},
    'take': {'ru': 'взять (на себя)', 'tg': 'ба ӯҳда гирифтан', 'lemma': 'take'},
    'responsibility': {'ru': 'ответственность', 'tg': 'масъулият', 'lemma': 'responsibility'},
    'failed': {'ru': 'провалиться', 'tg': 'ноком шудан', 'lemma': 'fail'},
    'circling': {'ru': 'кружить (крутиться)', 'tg': 'давр задан', 'lemma': 'circle'},
    'mind': {'ru': 'ум (сознание)', 'tg': 'ақл', 'lemma': 'mind'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'minister\'s': {'ru': 'министрский', 'tg': 'аз они вазир', 'lemma': 'minister'},
    'office': {'ru': 'офис (кабинет)', 'tg': 'идора', 'lemma': 'office'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'called': {'ru': 'вызывать (звать)', 'tg': 'даъват кардан', 'lemma': 'call in'},
    'carefully': {'ru': 'осторожно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'could': {'ru': 'могли бы', 'tg': 'метавонед', 'lemma': 'could'},
    'tell': {'ru': 'сказать', 'tg': 'гуфтан', 'lemma': 'tell'},
    'originally': {'ru': 'изначально', 'tg': 'аслан', 'lemma': 'originally'},
    'proposed': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'propose'},
    'policy': {'ru': 'политика (курс)', 'tg': 'сиёсат', 'lemma': 'policy'},
    'minister': {'ru': 'министр', 'tg': 'вазир', 'lemma': 'minister'},
    'paused': {'ru': 'делать паузу', 'tg': 'таваққуф кардан', 'lemma': 'pause'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'unprepared': {'ru': 'неподготовленный', 'tg': 'номуҳайё', 'lemma': 'unprepared'},
    'such': {'ru': 'такая', 'tg': 'чунин', 'lemma': 'such'},
    'directness': {'ru': 'прямота', 'tg': 'росткорӣ', 'lemma': 'directness'},
    'rather': {'ru': 'предпочёл бы', 'tg': 'тарҷеҳ медиҳам', 'lemma': 'would rather'},
    'replied': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'evasively': {'ru': 'уклончиво', 'tg': 'канорагирона', 'lemma': 'evasively'},
    'goals': {'ru': 'цель', 'tg': 'ҳадаф', 'lemma': 'goal'},
    'pressed': {'ru': 'настаивать (давить)', 'tg': 'исрор кардан', 'lemma': 'press'},
    'further': {'ru': 'дальше', 'tg': 'минбаъд', 'lemma': 'further'},
    'asking': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'evidence': {'ru': 'доказательство', 'tg': 'далел', 'lemma': 'evidence'},
    'convinced': {'ru': 'убеждать', 'tg': 'қонеъ кардан', 'lemma': 'convince'},
    'committee': {'ru': 'комитет', 'tg': 'кумита', 'lemma': 'committee'},
    'whether': {'ru': 'ли', 'tg': 'оё', 'lemma': 'whether'},
    'raised': {'ru': 'поднимать (озвучивать)', 'tg': 'бардоштан', 'lemma': 'raise'},
    'concerns': {'ru': 'опасение', 'tg': 'нигаронӣ', 'lemma': 'concern'},
    'beforehand': {'ru': 'заранее', 'tg': 'пешакӣ', 'lemma': 'beforehand'},
    'answered': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'vaguely': {'ru': 'расплывчато', 'tg': 'мубҳам', 'lemma': 'vaguely'},
    'avoiding': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'resembled': {'ru': 'напоминать', 'tg': 'монанд будан', 'lemma': 'resemble'},
    'subject': {'ru': 'конкретный (предметный)', 'tg': 'мушаххас', 'lemma': 'subject'},
    'individuals': {'ru': 'личность (человек)', 'tg': 'шахс', 'lemma': 'individual'},
    'frustrated': {'ru': 'раздосадованный', 'tg': 'ноумед', 'lemma': 'frustrated'},
    'persistent': {'ru': 'настойчивый', 'tg': 'пофишор', 'lemma': 'persistent'},
    'final': {'ru': 'последний', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'direct': {'ru': 'прямой', 'tg': 'мустақим', 'lemma': 'direct'},
    'held': {'ru': 'нести (ответственность)', 'tg': 'бардоштан', 'lemma': 'hold accountable'},
    'accountable': {'ru': 'ответственный', 'tg': 'масъул', 'lemma': 'accountable'},
    'fails': {'ru': 'провалиться', 'tg': 'ноком шудан', 'lemma': 'fail'},
    'long': {'ru': 'долгий', 'tg': 'дароз', 'lemma': 'long'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'unexpectedly': {'ru': 'неожиданно', 'tg': 'ногаҳон', 'lemma': 'unexpectedly'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'considered': {'ru': 'рассматривать', 'tg': 'дида баромадан', 'lemma': 'consider'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'walking': {'ru': 'выходить (идти)', 'tg': 'баромадан', 'lemma': 'walk out'},
    'afterwards': {'ru': 'после этого', 'tg': 'баъдтар', 'lemma': 'afterwards'},
    'revealing': {'ru': 'показательный (раскрывающий)', 'tg': 'ошкоркунанда', 'lemma': 'revealing'},
    'answer': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'entire': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'entire'},
    'come': {'ru': 'происходить (исходить)', 'tg': 'баромадан', 'lemma': 'come from'},
    'rather2': {'ru': 'а не', 'tg': 'на', 'lemma': 'rather than'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'thought': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'avoid': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'answering': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'far': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'far'},
    'ones': {'ru': 'те (штуки)', 'tg': 'онҳо', 'lemma': 'one'},
    'i\'d': {'ru': 'предпочёл бы', 'tg': 'тарҷеҳ медиҳам', 'lemma': 'would rather'}, 'had': HAVE, 'hadn\'t': DO, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'},
},
137: {
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'get': {'ru': 'ладить', 'tg': 'муросо кардан', 'lemma': 'get along'},
    'along': {'ru': 'вместе', 'tg': 'бо ҳамдигар', 'lemma': 'along'},
    'most': {'ru': 'большая часть', 'tg': 'бештари', 'lemma': 'most'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'whatever': {'ru': 'что бы ни', 'tg': 'ҳар чи', 'lemma': 'whatever'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'assume': {'ru': 'предполагать', 'tg': 'гумон кардан', 'lemma': 'assume'},
    'siblings': {'ru': 'братья и сёстры', 'tg': 'хоҳару бародарон', 'lemma': 'sibling'},
    'grew': {'ru': 'расти', 'tg': 'калон шудан', 'lemma': 'grow up'},
    'sharing': {'ru': 'делить', 'tg': 'муштарак истифода бурдан', 'lemma': 'share'},
    'one': {'ru': 'одна', 'tg': 'як', 'lemma': 'one'},
    'bedroom': {'ru': 'спальня', 'tg': 'хобгоҳ', 'lemma': 'bedroom'},
    'still': {'ru': 'всё же', 'tg': 'ба ҳар ҳол', 'lemma': 'still'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'family': {'ru': 'семейный (семья)', 'tg': 'оилавӣ', 'lemma': 'family'},
    'gathering': {'ru': 'сбор (встреча)', 'tg': 'ҷамъомад', 'lemma': 'gathering'},
    'seems': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'bring': {'ru': 'вызывать (выявлять)', 'tg': 'ба вуҷуд овардан', 'lemma': 'bring out'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'rivalry': {'ru': 'соперничество', 'tg': 'рақобат', 'lemma': 'rivalry'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'disagreement': {'ru': 'разногласие', 'tg': 'ихтилоф', 'lemma': 'disagreement'},
    'started': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'small': {'ru': 'маленький (незначительный)', 'tg': 'хурд', 'lemma': 'small'},
    'whose': {'ru': 'чья', 'tg': 'аз они кӣ', 'lemma': 'whose'},
    'turn': {'ru': 'очередь', 'tg': 'навбат', 'lemma': 'turn'},
    'host': {'ru': 'принимать (гостей)', 'tg': 'мизбонӣ кардан', 'lemma': 'host'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'argued': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'less': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'less'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'each': {'ru': 'друг друга', 'tg': 'ҳамдигар', 'lemma': 'each other'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'hosting': {'ru': 'принимать (гостей)', 'tg': 'мизбонӣ кардан', 'lemma': 'host'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'insisted': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'certain': {'ru': 'уверенный', 'tg': 'мутмаин', 'lemma': 'certain'},
    'louder': {'ru': 'громче', 'tg': 'баландтар', 'lemma': 'loud'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'quieter': {'ru': 'тише', 'tg': 'оромтар', 'lemma': 'quiet'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'got': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'get'},
    'hoping': {'ru': 'надеяться', 'tg': 'умед доштан', 'lemma': 'hope'},
    'resolve': {'ru': 'решить (уладить)', 'tg': 'ҳал кардан', 'lemma': 'resolve'},
    'ourselves': {'ru': 'сами', 'tg': 'худамон', 'lemma': 'ourselves'},
    'longer': {'ru': 'дольше', 'tg': 'дарозтар', 'lemma': 'long'},
    'argument': {'ru': 'спор', 'tg': 'баҳс', 'lemma': 'argument'},
    'continued': {'ru': 'продолжаться', 'tg': 'давом ёфтан', 'lemma': 'continue'},
    'sillier': {'ru': 'глупее', 'tg': 'аблаҳтар', 'lemma': 'silly'},
    'feel': {'ru': 'казаться (чувствоваться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'until': {'ru': 'пока не', 'tg': 'то', 'lemma': 'until'},
    'neither': {'ru': 'ни тот ни другой', 'tg': 'ҳеҷ кадом', 'lemma': 'neither'},
    'quite': {'ru': 'вполне', 'tg': 'комилан', 'lemma': 'quite'},
    'mattered': {'ru': 'иметь значение', 'tg': 'аҳамият доштан', 'lemma': 'matter'},
    'much': {'ru': 'так сильно', 'tg': 'он қадар', 'lemma': 'much'},
    'place': {'ru': 'место (изначально)', 'tg': 'аввал', 'lemma': 'in the first place'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'interrupted': {'ru': 'перебивать', 'tg': 'вокеъ шудан', 'lemma': 'interrupt'},
    'calmly': {'ru': 'спокойно', 'tg': 'ором', 'lemma': 'calmly'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'care': {'ru': 'заботиться (переживать)', 'tg': 'ғамхорӣ кардан', 'lemma': 'care'},
    'sooner': {'ru': 'скорее', 'tg': 'зудтар', 'lemma': 'sooner'},
    'stop': {'ru': 'переставать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'arguing': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'eat': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'embarrassed': {'ru': 'смущённый', 'tg': 'хиҷолатманд', 'lemma': 'embarrassed'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'suspect': {'ru': 'подозревать (полагать)', 'tg': 'гумон кардан', 'lemma': 'suspect'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'shown': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'however': {'ru': 'какими бы ни', 'tg': 'ҳарчанд', 'lemma': 'however'},
    'unnecessary': {'ru': 'ненужный', 'tg': 'бефоида', 'lemma': 'unnecessary'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'turn2': {'ru': 'оказываться', 'tg': 'баромадан', 'lemma': 'turn out'},
    'do': DO, 'didn\'t': DO, 'we\'d': BE, 'we\'ve': HAVE,
},
138: {
    'recovering': {'ru': 'восстанавливаться', 'tg': 'барқарор шудан', 'lemma': 'recover'},
    'knee': {'ru': 'колено (коленный)', 'tg': 'зону', 'lemma': 'knee'},
    'surgery': {'ru': 'операция', 'tg': 'ҷарроҳӣ', 'lemma': 'surgery'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'progress': {'ru': 'прогресс', 'tg': 'пешрафт', 'lemma': 'progress'},
    'painfully': {'ru': 'мучительно', 'tg': 'дардовар', 'lemma': 'painfully'},
    'slow': {'ru': 'медленный', 'tg': 'суст', 'lemma': 'slow'},
    'physiotherapy': {'ru': 'физиотерапия', 'tg': 'физиотерапия', 'lemma': 'physiotherapy'},
    'exercises': {'ru': 'упражнение', 'tg': 'машқ', 'lemma': 'exercise'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'single': {'ru': 'каждый (единственный)', 'tg': 'ҳар як', 'lemma': 'single'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'improvement': {'ru': 'улучшение', 'tg': 'беҳбудӣ', 'lemma': 'improvement'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'feels': {'ru': 'казаться (ощущаться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'invisible': {'ru': 'невидимый', 'tg': 'ноаён', 'lemma': 'invisible'},
    'physiotherapist': {'ru': 'физиотерапевт', 'tg': 'физиотерапевт', 'lemma': 'physiotherapist'},
    'noticed': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'real': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'real'},
    'changes': {'ru': 'изменение', 'tg': 'тағйирот', 'lemma': 'change'},
    'regained': {'ru': 'восстанавливать', 'tg': 'барқарор кардан', 'lemma': 'regain'},
    'full': {'ru': 'полный', 'tg': 'пурра', 'lemma': 'full'},
    'movement': {'ru': 'подвижность (движение)', 'tg': 'ҳаракат', 'lemma': 'movement'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'comparing': {'ru': 'сравнивать', 'tg': 'муқоиса кардан', 'lemma': 'compare'},
    'measurements': {'ru': 'измерение', 'tg': 'ченак', 'lemma': 'measurement'},
    'appointment': {'ru': 'приём (визит)', 'tg': 'вохӯрӣ', 'lemma': 'appointment'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'limping': {'ru': 'хромать', 'tg': 'ланг задан', 'lemma': 'limp'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'whenever': {'ru': 'всякий раз, когда', 'tg': 'ҳар вақте ки', 'lemma': 'whenever'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'worries': {'ru': 'беспокоить', 'tg': 'ташвиш додан', 'lemma': 'worry'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'should': {'ru': 'следует', 'tg': 'бояд', 'lemma': 'should'},
    'working': {'ru': 'работать (трудиться)', 'tg': 'кор кардан', 'lemma': 'work'},
    'incredibly': {'ru': 'невероятно', 'tg': 'бениҳоят', 'lemma': 'incredibly'},
    'hard': {'ru': 'усердно', 'tg': 'сахт', 'lemma': 'hard'},
    'reassured': {'ru': 'успокаивать', 'tg': 'ором кардан', 'lemma': 'reassure'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'showing': {'ru': 'проявляться (показывать)', 'tg': 'зоҳир шудан', 'lemma': 'show'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'yet': {'ru': 'ещё', 'tg': 'ҳанӯз', 'lemma': 'yet'},
    'climbed': {'ru': 'подниматься', 'tg': 'баромадан', 'lemma': 'climb'},
    'stairs': {'ru': 'лестница', 'tg': 'зинапоя', 'lemma': 'stairs'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'unassisted': {'ru': 'без посторонней помощи', 'tg': 'бе кӯмаки касе', 'lemma': 'unassisted'},
    'felt': {'ru': 'чувствоваться', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'genuine': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'genuine'},
    'achievement': {'ru': 'достижение', 'tg': 'дастовард', 'lemma': 'achievement'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'remarkably': {'ru': 'на удивление', 'tg': 'аҷиб', 'lemma': 'remarkably'},
    'patient': {'ru': 'терпеливый', 'tg': 'сабур', 'lemma': 'patient'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'sighing': {'ru': 'вздыхать', 'tg': 'оҳ кашидан', 'lemma': 'sigh'},
    'ask': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'help': {'ru': 'помощь', 'tg': 'кӯмак', 'lemma': 'help'},
    'reaching': {'ru': 'дотягиваться', 'tg': 'даст расондан', 'lemma': 'reach'},
    'simple': {'ru': 'простой', 'tg': 'сода', 'lemma': 'simple'},
    'counting': {'ru': 'считать', 'tg': 'шумурдан', 'lemma': 'count'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'run': {'ru': 'бегать', 'tg': 'давидан', 'lemma': 'run'},
    'obsessively': {'ru': 'одержимо', 'tg': 'бо ҳарис', 'lemma': 'obsessively'},
    'perhaps': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'perhaps'},
    'keeps': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'reminding': {'ru': 'напоминать', 'tg': 'ёдовар шудан', 'lemma': 'remind'},
    'healing': {'ru': 'исцеление (заживление)', 'tg': 'шифо', 'lemma': 'healing'},
    'rush': {'ru': 'торопить', 'tg': 'шитоб кунондан', 'lemma': 'rush'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'walked': {'ru': 'идти пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'corner': {'ru': 'угловой', 'tg': 'гӯшагӣ', 'lemma': 'corner'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'crutches': {'ru': 'костыли', 'tg': 'асо', 'lemma': 'crutch'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'absurdly': {'ru': 'до нелепости', 'tg': 'бемаънӣ', 'lemma': 'absurdly'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'used': {'ru': 'раньше было', 'tg': 'пештар буд', 'lemma': 'used to'},
    'completely': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'completely'},
    'ordinary': {'ru': 'обычный', 'tg': 'оддӣ', 'lemma': 'ordinary'},
    'i\'ve': HAVE, 'i\'m': BE, 'has': HAVE, 'you\'ve': HAVE, 'it\'s': BE, 'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
},
139: {
    'charity': {'ru': 'благотворительный', 'tg': 'хайрия', 'lemma': 'charity'},
    'gala': {'ru': 'гала-вечер', 'tg': 'шоми тантанавӣ', 'lemma': 'gala'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'focused': {'ru': 'сосредоточиваться', 'tg': 'тамаркуз кардан', 'lemma': 'focus'},
    'entirely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'entirely'},
    'supporting': {'ru': 'поддерживать', 'tg': 'дастгирӣ кардан', 'lemma': 'support'},
    'elderly': {'ru': 'пожилые', 'tg': 'солхӯрдагон', 'lemma': 'elderly'},
    'homeless': {'ru': 'бездомные', 'tg': 'бехонумонон', 'lemma': 'homeless'},
    'across': {'ru': 'по всему', 'tg': 'дар саросари', 'lemma': 'across'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'groups': {'ru': 'группа', 'tg': 'гурӯҳ', 'lemma': 'group'},
    'organisers': {'ru': 'организатор', 'tg': 'ташкилкунанда', 'lemma': 'organiser'},
    'felt': {'ru': 'считать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'overlooked': {'ru': 'упускать из виду', 'tg': 'нодида гирифтан', 'lemma': 'overlook'},
    'guests': {'ru': 'гость', 'tg': 'меҳмон', 'lemma': 'guest'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'long': {'ru': 'длинный', 'tg': 'дароз', 'lemma': 'long'},
    'formal': {'ru': 'официальный (парадный)', 'tg': 'расмӣ', 'lemma': 'formal'},
    'gowns': {'ru': 'платье (вечернее)', 'tg': 'курта', 'lemma': 'gown'},
    'evening\'s': {'ru': 'вечерняя', 'tg': 'аз они шаб', 'lemma': 'evening'},
    'real': {'ru': 'настоящая', 'tg': 'воқеӣ', 'lemma': 'real'},
    'purpose': {'ru': 'цель', 'tg': 'мақсад', 'lemma': 'purpose'},
    'raising': {'ru': 'собирать (средства)', 'tg': 'ҷамъ кардан', 'lemma': 'raise'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'shelter': {'ru': 'приют', 'tg': 'паноҳгоҳ', 'lemma': 'shelter'},
    'downtown': {'ru': 'в центре города', 'tg': 'марказ', 'lemma': 'downtown'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'sat': {'ru': 'стоять (лежать)', 'tg': 'меистод', 'lemma': 'sit'},
    'round': {'ru': 'круглый', 'tg': 'мудаввар', 'lemma': 'round'},
    'antique': {'ru': 'антикварный', 'tg': 'антиқа', 'lemma': 'antique'},
    'wooden': {'ru': 'деревянный', 'tg': 'чӯбин', 'lemma': 'wooden'},
    'box': {'ru': 'коробка (ящик)', 'tg': 'қуттӣ', 'lemma': 'box'},
    'donations': {'ru': 'пожертвование', 'tg': 'хайрия', 'lemma': 'donation'},
    'handcrafted': {'ru': 'изготовленный вручную', 'tg': 'дастӣ сохташуда', 'lemma': 'handcrafted'},
    'specifically': {'ru': 'специально', 'tg': 'махсус', 'lemma': 'specifically'},
    'organiser': {'ru': 'организатор', 'tg': 'ташкилкунанда', 'lemma': 'organiser'},
    'kind': {'ru': 'добрый', 'tg': 'меҳрубон', 'lemma': 'kind'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'herself': {'ru': 'сама', 'tg': 'худаш', 'lemma': 'herself'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'poor': {'ru': 'бедные', 'tg': 'камбағалон', 'lemma': 'poor'},
    'deserved': {'ru': 'заслуживать', 'tg': 'сазовор будан', 'lemma': 'deserve'},
    'attention': {'ru': 'внимание', 'tg': 'диққат', 'lemma': 'attention'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'received': {'ru': 'получать', 'tg': 'гирифтан', 'lemma': 'receive'},
    'unemployed': {'ru': 'безработные', 'tg': 'бекорон', 'lemma': 'unemployed'},
    'lazy': {'ru': 'ленивый', 'tg': 'танбал', 'lemma': 'lazy'},
    'reminded': {'ru': 'напоминать', 'tg': 'ёдовар шудан', 'lemma': 'remind'},
    'room': {'ru': 'зал (комната)', 'tg': 'толор', 'lemma': 'room'},
    'firmly': {'ru': 'твёрдо', 'tg': 'қатъӣ', 'lemma': 'firmly'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'unlucky': {'ru': 'невезучий', 'tg': 'бадбахт', 'lemma': 'unlucky'},
    'deserve': {'ru': 'заслуживать', 'tg': 'сазовор будан', 'lemma': 'deserve'},
    'compassion': {'ru': 'сострадание', 'tg': 'дилсӯзӣ', 'lemma': 'compassion'},
    'judgment': {'ru': 'осуждение', 'tg': 'қазоват', 'lemma': 'judgment'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'violinist': {'ru': 'скрипач', 'tg': 'скрипканавоз', 'lemma': 'violinist'},
    'performed': {'ru': 'исполнять', 'tg': 'иҷро кардан', 'lemma': 'perform'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'classical': {'ru': 'классический', 'tg': 'классикӣ', 'lemma': 'classical'},
    'piece': {'ru': 'произведение (пьеса)', 'tg': 'асар', 'lemma': 'piece'},
    'volunteers': {'ru': 'волонтёр', 'tg': 'ихтиёрчӣ', 'lemma': 'volunteer'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'collected': {'ru': 'собирать', 'tg': 'ҷамъ кардан', 'lemma': 'collect'},
    'guest': {'ru': 'гость', 'tg': 'меҳмон', 'lemma': 'guest'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'elegant': {'ru': 'элегантный', 'tg': 'бошукӯҳ', 'lemma': 'elegant'},
    'dark': {'ru': 'тёмный', 'tg': 'торик', 'lemma': 'dark'},
    'green': {'ru': 'зелёный', 'tg': 'сабз', 'lemma': 'green'},
    'silk': {'ru': 'шёлковый', 'tg': 'абрешимӣ', 'lemma': 'silk'},
    'dress': {'ru': 'платье', 'tg': 'курта', 'lemma': 'dress'},
    'donated': {'ru': 'жертвовать', 'tg': 'хайрия кардан', 'lemma': 'donate'},
    'unusually': {'ru': 'необычно', 'tg': 'ғайриоддӣ', 'lemma': 'unusually'},
    'large': {'ru': 'большой', 'tg': 'калон', 'lemma': 'large'},
    'amount': {'ru': 'сумма (количество)', 'tg': 'миқдор', 'lemma': 'amount'},
    'remaining': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'anonymous': {'ru': 'анонимный', 'tg': 'номаълум', 'lemma': 'anonymous'},
    'night': {'ru': 'ночь (вечер)', 'tg': 'шаб', 'lemma': 'night'},
    'little': {'ru': 'маленькие', 'tg': 'хурд', 'lemma': 'little'},
    'boxes': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'unexpectedly': {'ru': 'неожиданно', 'tg': 'ногаҳон', 'lemma': 'unexpectedly'},
    'predicted': {'ru': 'предсказывать', 'tg': 'пешгӯӣ кардан', 'lemma': 'predict'},
    'sick': {'ru': 'больные', 'tg': 'беморон', 'lemma': 'sick'},
    'benefit': {'ru': 'получать пользу', 'tg': 'фоида бурдан', 'lemma': 'benefit'},
    'directly': {'ru': 'напрямую', 'tg': 'бевосита', 'lemma': 'directly'},
    'present': {'ru': 'присутствующий', 'tg': 'ҳозир', 'lemma': 'present'},
    'course': {'ru': 'конечно', 'tg': 'албатта', 'lemma': 'of course'},
    'situation': {'ru': 'ситуация', 'tg': 'вазъият', 'lemma': 'situation'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'moved': {'ru': 'трогать (волновать)', 'tg': 'мутаассир кардан', 'lemma': 'move'},
    'strangers': {'ru': 'незнакомцы', 'tg': 'бегонагон', 'lemma': 'stranger'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'evenings': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'difference': {'ru': 'разница (изменение к лучшему)', 'tg': 'фарқ', 'lemma': 'difference'},
    'were': BE, 'weren\'t': BE, 'aren\'t': BE, 'had': HAVE,
},
140: {
    'connecting': {'ru': 'стыковочный', 'tg': 'иловагӣ', 'lemma': 'connecting flight'},
    'flight': {'ru': 'рейс', 'tg': 'парвоз', 'lemma': 'flight'},
    'cancelled': {'ru': 'отменять', 'tg': 'бекор кардан', 'lemma': 'cancel'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'travelling': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'fourteen': {'ru': 'четырнадцать', 'tg': 'чордаҳ', 'lemma': 'fourteen'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'straight': {'ru': 'подряд', 'tg': 'паиҳам', 'lemma': 'straight'},
    'sitting': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'gate': {'ru': 'выход на посадку', 'tg': 'дарвоза', 'lemma': 'gate'},
    'nearly': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'nearly'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'announcement': {'ru': 'объявление', 'tg': 'эълон', 'lemma': 'announcement'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'came': {'ru': 'приходить (прозвучать)', 'tg': 'омадан', 'lemma': 'come'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'terminal': {'ru': 'терминал', 'tg': 'терминал', 'lemma': 'terminal'},
    'groaned': {'ru': 'стонать (охать)', 'tg': 'нола кардан', 'lemma': 'groan'},
    'unison': {'ru': 'унисон (все разом)', 'tg': 'якдилона', 'lemma': 'unison'},
    'such': {'ru': 'такая', 'tg': 'чунин', 'lemma': 'such'},
    'chaotic': {'ru': 'хаотичный', 'tg': 'бетартиб', 'lemma': 'chaotic'},
    'scene': {'ru': 'сцена (картина)', 'tg': 'манзара', 'lemma': 'scene'},
    'airport': {'ru': 'аэропорт', 'tg': 'фурудгоҳ', 'lemma': 'airport'},
    'staff': {'ru': 'персонал', 'tg': 'кормандон', 'lemma': 'staff'},
    'struggled': {'ru': 'изо всех сил стараться', 'tg': 'мубориза бурдан', 'lemma': 'struggle'},
    'manage': {'ru': 'справляться (управлять)', 'tg': 'идора кардан', 'lemma': 'manage'},
    'crowd': {'ru': 'толпа', 'tg': 'издиҳом', 'lemma': 'crowd'},
    'forming': {'ru': 'формироваться', 'tg': 'ташкил ёфтан', 'lemma': 'form'},
    'customer': {'ru': 'клиентский', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'service': {'ru': 'обслуживание', 'tg': 'хизматрасонӣ', 'lemma': 'service'},
    'desk': {'ru': 'стойка (стол)', 'tg': 'миз', 'lemma': 'desk'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'checking': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'updates': {'ru': 'обновление', 'tg': 'навсозӣ', 'lemma': 'update'},
    'obsessively': {'ru': 'одержимо', 'tg': 'бо ҳарис', 'lemma': 'obsessively'},
    'refreshing': {'ru': 'обновлять', 'tg': 'навсозӣ кардан', 'lemma': 'refresh'},
    'app': {'ru': 'приложение', 'tg': 'барнома', 'lemma': 'app'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'running': {'ru': 'бегать', 'tg': 'давидан', 'lemma': 'run'},
    'increasingly': {'ru': 'всё более', 'tg': 'торафт', 'lemma': 'increasingly'},
    'wild': {'ru': 'дикий (буйный)', 'tg': 'ваҳшӣ', 'lemma': 'wild'},
    'circles': {'ru': 'круг', 'tg': 'давра', 'lemma': 'circle'},
    'seating': {'ru': 'посадочная (зона)', 'tg': 'нишаст', 'lemma': 'seating area'},
    'area': {'ru': 'зона (площадь)', 'tg': 'минтақа', 'lemma': 'area'},
    'since': {'ru': 'с', 'tg': 'аз', 'lemma': 'since'},
    'dawn': {'ru': 'рассвет', 'tg': 'субҳидам', 'lemma': 'dawn'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'minor': {'ru': 'мелкий (незначительный)', 'tg': 'ночиз', 'lemma': 'minor'},
    'inconveniences': {'ru': 'неудобство', 'tg': 'нороҳатӣ', 'lemma': 'inconvenience'},
    'felt': {'ru': 'казаться (чувствоваться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'unbearable': {'ru': 'невыносимый', 'tg': 'тоқатфарсо', 'lemma': 'unbearable'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'rebooking': {'ru': 'перебронирование', 'tg': 'аз нав фармоиш', 'lemma': 'rebooking'},
    'queue': {'ru': 'очередь', 'tg': 'навбат', 'lemma': 'queue'},
    'struck': {'ru': 'завязать (разговор)', 'tg': 'сар кардан', 'lemma': 'strike up'},
    'conversation': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'stranger': {'ru': 'незнакомец', 'tg': 'бегона', 'lemma': 'stranger'},
    'stuck': {'ru': 'застрять', 'tg': 'банд шудан', 'lemma': 'stuck'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'following': {'ru': 'после (следуя)', 'tg': 'пас аз', 'lemma': 'following'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'connection': {'ru': 'стыковка (рейс)', 'tg': 'парвози алоқа', 'lemma': 'connection'},
    'story': {'ru': 'история', 'tg': 'ҳикоя', 'lemma': 'story'},
    'disaster': {'ru': 'катастрофа', 'tg': 'фалокат', 'lemma': 'disaster'},
    'ours': {'ru': 'наша', 'tg': 'аз они мо', 'lemma': 'ours'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'manageable': {'ru': 'терпимый (управляемый)', 'tg': 'қобили идора', 'lemma': 'manageable'},
    'comparison': {'ru': 'сравнение', 'tg': 'муқоиса', 'lemma': 'comparison'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'standing': {'ru': 'стоять', 'tg': 'истодан', 'lemma': 'stand'},
    'line': {'ru': 'очередь', 'tg': 'навбат', 'lemma': 'line'},
    'agent': {'ru': 'агент', 'tg': 'агент', 'lemma': 'agent'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'seats': {'ru': 'место (сиденье)', 'tg': 'ҷой', 'lemma': 'seat'},
    'much': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'much'},
    'later': {'ru': 'более поздний', 'tg': 'баъдина', 'lemma': 'later'},
    'boarded': {'ru': 'садиться (на борт)', 'tg': 'савор шудан', 'lemma': 'board'},
    'awake': {'ru': 'бодрствующий', 'tg': 'бедор', 'lemma': 'awake'},
    'over': {'ru': 'более', 'tg': 'зиёда аз', 'lemma': 'over'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'fallen': {'ru': 'засыпать (падать)', 'tg': 'хоб рафтан', 'lemma': 'fall asleep'},
    'asleep': {'ru': 'спящий', 'tg': 'хоб', 'lemma': 'asleep'},
    'takeoff': {'ru': 'взлёт', 'tg': 'парвоз', 'lemma': 'takeoff'},
    'impromptu': {'ru': 'импровизированный (внезапный)', 'tg': 'ногаҳонӣ', 'lemma': 'impromptu'},
    'marathon': {'ru': 'марафон', 'tg': 'марафон', 'lemma': 'marathon'},
    'looking': {'ru': 'оглядываясь', 'tg': 'бознигарӣ', 'lemma': 'look back'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'ordeal': {'ru': 'испытание (мучение)', 'tg': 'озмоиш', 'lemma': 'ordeal'},
    'oddly': {'ru': 'странным образом', 'tg': 'аҷиб', 'lemma': 'oddly'},
    'memorable': {'ru': 'запоминающийся', 'tg': 'ба ёдмонда', 'lemma': 'memorable'},
    'chapter': {'ru': 'глава', 'tg': 'боб', 'lemma': 'chapter'},
    'had': HAVE, 'we\'d': HAVE, 'was': BE,
},
141: {
    'definitely': {'ru': 'определённо', 'tg': 'бешубҳа', 'lemma': 'definitely'},
    'rehearsed': {'ru': 'репетировать', 'tg': 'репетитсия кардан', 'lemma': 'rehearse'},
    'presentation': {'ru': 'презентация', 'tg': 'презентатсия', 'lemma': 'presentation'},
    'dozen': {'ru': 'дюжина', 'tg': 'даҳҳо', 'lemma': 'dozen'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'nerves': {'ru': 'нервы', 'tg': 'асаб', 'lemma': 'nerve'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'noticed': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'fortunately': {'ru': 'к счастью', 'tg': 'хушбахтона', 'lemma': 'fortunately'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'offered': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'listen': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'final': {'ru': 'последний', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'actual': {'ru': 'настоящая', 'tg': 'воқеӣ', 'lemma': 'actual'},
    'meeting': {'ru': 'встреча (совещание)', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'spoke': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'confidently': {'ru': 'уверенно', 'tg': 'боэътимод', 'lemma': 'confidently'},
    'introduction': {'ru': 'вступление', 'tg': 'муқаддима', 'lemma': 'introduction'},
    'carefully': {'ru': 'тщательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'explaining': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'chart': {'ru': 'диаграмма (график)', 'tg': 'диаграмма', 'lemma': 'chart'},
    'moving': {'ru': 'переходить', 'tg': 'гузаштан', 'lemma': 'move'},
    'next': {'ru': 'следующий', 'tg': 'навбатӣ', 'lemma': 'next'},
    'slide': {'ru': 'слайд', 'tg': 'слайд', 'lemma': 'slide'},
    'obviously': {'ru': 'очевидно', 'tg': 'равшан аст', 'lemma': 'obviously'},
    'prepared': {'ru': 'готовиться (подготовить)', 'tg': 'омода кардан', 'lemma': 'prepare'},
    'thoroughly': {'ru': 'тщательно', 'tg': 'пурра', 'lemma': 'thoroughly'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'encouragingly': {'ru': 'ободряюще', 'tg': 'рӯҳбаландкунанда', 'lemma': 'encouragingly'},
    'gently': {'ru': 'мягко (деликатно)', 'tg': 'мулоим', 'lemma': 'gently'},
    'pointed': {'ru': 'указывать', 'tg': 'ишора кардан', 'lemma': 'point out'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'spoke2': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'quickly': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'quickly'},
    'complicated': {'ru': 'сложный', 'tg': 'мураккаб', 'lemma': 'complicated'},
    'sections': {'ru': 'раздел', 'tg': 'қисм', 'lemma': 'section'},
    'nodded': {'ru': 'кивать', 'tg': 'сар ҷунбондан', 'lemma': 'nod'},
    'deliberately': {'ru': 'намеренно', 'tg': 'қасдан', 'lemma': 'deliberately'},
    'slowed': {'ru': 'замедлять', 'tg': 'суст кардан', 'lemma': 'slow down'},
    'pace': {'ru': 'темп', 'tg': 'суръат', 'lemma': 'pace'},
    'repeating': {'ru': 'повторять', 'tg': 'такрор кардан', 'lemma': 'repeat'},
    'tricky': {'ru': 'сложный (хитрый)', 'tg': 'мушкил', 'lemma': 'tricky'},
    'part': {'ru': 'часть', 'tg': 'қисм', 'lemma': 'part'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'attempt': {'ru': 'попытка', 'tg': 'кӯшиш', 'lemma': 'attempt'},
    'sounded': {'ru': 'звучать', 'tg': 'садо додан', 'lemma': 'sound'},
    'far': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'far'},
    'natural': {'ru': 'естественный', 'tg': 'табиӣ', 'lemma': 'natural'},
    'less': {'ru': 'менее', 'tg': 'камтар', 'lemma': 'less'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'suggested': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'pause': {'ru': 'делать паузу', 'tg': 'таваққуф кардан', 'lemma': 'pause'},
    'briefly': {'ru': 'кратко', 'tg': 'мухтасар', 'lemma': 'briefly'},
    'answering': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'anticipated': {'ru': 'предполагаемый (ожидаемый)', 'tg': 'интизоршуда', 'lemma': 'anticipated'},
    'questions': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'rather': {'ru': 'а не', 'tg': 'ба ҷои', 'lemma': 'rather than'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'rushing': {'ru': 'торопиться', 'tg': 'шитоб кардан', 'lemma': 'rush'},
    'explanation': {'ru': 'объяснение', 'tg': 'шарҳ', 'lemma': 'explanation'},
    'practised': {'ru': 'практиковать (тренировать)', 'tg': 'машқ кардан', 'lemma': 'practise'},
    'too': {'ru': 'тоже', 'tg': 'низ', 'lemma': 'too'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'full': {'ru': 'целую (полную)', 'tg': 'пурра', 'lemma': 'full'},
    'responding': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'respond'},
    'instantly': {'ru': 'мгновенно', 'tg': 'фавран', 'lemma': 'instantly'},
    'authoritative': {'ru': 'авторитетный (уверенный)', 'tg': 'боэътимод', 'lemma': 'authoritative'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'enjoyed': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'public': {'ru': 'публичный (публика)', 'tg': 'ҷамъиятӣ', 'lemma': 'public speaking'},
    'speaking': {'ru': 'выступление (речь)', 'tg': 'нутқ', 'lemma': 'speaking'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'practice': {'ru': 'практика', 'tg': 'машқ', 'lemma': 'practice'},
    'certainly': {'ru': 'конечно', 'tg': 'албатта', 'lemma': 'certainly'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'hiding': {'ru': 'скрывать', 'tg': 'пинҳон кардан', 'lemma': 'hide'},
    'real2': {'ru': 'настоящая', 'tg': 'воқеӣ', 'lemma': 'real'},
    'began': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'remembered': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'advice': {'ru': 'совет', 'tg': 'маслиҳат', 'lemma': 'advice'},
    'speaking2': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'pausing': {'ru': 'делать паузу', 'tg': 'таваққуф кардан', 'lemma': 'pause'},
    'thoughtfully': {'ru': 'вдумчиво', 'tg': 'ботааммул', 'lemma': 'thoughtfully'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'needed': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'quite': {'ru': 'весьма', 'tg': 'комилан', 'lemma': 'quite'},
    'sincerely': {'ru': 'искренне', 'tg': 'самимона', 'lemma': 'sincerely'},
    'clearest': {'ru': 'самая ясная', 'tg': 'равшантарин', 'lemma': 'clear'},
    'department': {'ru': 'отдел', 'tg': 'шӯъба', 'lemma': 'department'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'had': HAVE, 'hadn\'t': HAVE, 'she\'d': HAVE, 'you\'ve': HAVE,
},
142: {
    'environmental': {'ru': 'экологический', 'tg': 'экологӣ', 'lemma': 'environmental'},
    'scientists': {'ru': 'учёный', 'tg': 'олим', 'lemma': 'scientist'},
    'predict': {'ru': 'предсказывать', 'tg': 'пешгӯӣ кардан', 'lemma': 'predict'},
    'entire': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'entire'},
    'hillside': {'ru': 'склон холма', 'tg': 'домани теппа', 'lemma': 'hillside'},
    'recovered': {'ru': 'восстанавливаться', 'tg': 'барқарор шудан', 'lemma': 'recover'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'devastating': {'ru': 'разрушительный', 'tg': 'харобиовар', 'lemma': 'devastating'},
    'fire': {'ru': 'пожар', 'tg': 'сӯхтор', 'lemma': 'fire'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'forest': {'ru': 'лес', 'tg': 'ҷангал', 'lemma': 'forest'},
    'knew': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'changed': {'ru': 'меняться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'considerably': {'ru': 'значительно', 'tg': 'ба таври назаррас', 'lemma': 'considerably'},
    'volunteers': {'ru': 'волонтёр', 'tg': 'ихтиёрчӣ', 'lemma': 'volunteer'},
    'planting': {'ru': 'сажать', 'tg': 'шинондан', 'lemma': 'plant'},
    'saplings': {'ru': 'саженцы', 'tg': 'ниҳол', 'lemma': 'sapling'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'spring': {'ru': 'весна', 'tg': 'баҳор', 'lemma': 'spring'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'autumn': {'ru': 'осень', 'tg': 'тирамоҳ', 'lemma': 'autumn'},
    'planted': {'ru': 'сажать', 'tg': 'шинондан', 'lemma': 'plant'},
    'over': {'ru': 'более', 'tg': 'зиёда аз', 'lemma': 'over'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'thousand': {'ru': 'тысяча', 'tg': 'ҳазор', 'lemma': 'thousand'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'trees': {'ru': 'дерево', 'tg': 'дарахт', 'lemma': 'tree'},
    'across': {'ru': 'по всем', 'tg': 'дар саросари', 'lemma': 'across'},
    'burned': {'ru': 'сгоревший', 'tg': 'сӯхта', 'lemma': 'burned'},
    'slopes': {'ru': 'склон', 'tg': 'домана', 'lemma': 'slope'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'walking': {'ru': 'идти', 'tg': 'қадам задан', 'lemma': 'walk'},
    'blackened': {'ru': 'почерневший', 'tg': 'сиёҳшуда', 'lemma': 'blackened'},
    'earth': {'ru': 'земля', 'tg': 'замин', 'lemma': 'earth'},
    'hard': {'ru': 'трудно', 'tg': 'душвор', 'lemma': 'hard'},
    'imagine': {'ru': 'вообразить', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'picnicking': {'ru': 'устраивать пикник', 'tg': 'сайругашт кардан', 'lemma': 'picnic'},
    'beneath': {'ru': 'под', 'tg': 'дар зери', 'lemma': 'beneath'},
    'sprouted': {'ru': 'прорастать', 'tg': 'сабзидан', 'lemma': 'sprout'},
    'lead': {'ru': 'главный (ведущий)', 'tg': 'асосӣ', 'lemma': 'lead'},
    'scientist': {'ru': 'учёный', 'tg': 'олим', 'lemma': 'scientist'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'canopy': {'ru': 'полог (крона)', 'tg': 'болопӯш', 'lemma': 'canopy'},
    'fully': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'fully'},
    'returns': {'ru': 'возвращаться', 'tg': 'баргаштан', 'lemma': 'return'},
    'entirely2': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'entirely'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'generation': {'ru': 'поколение', 'tg': 'насл', 'lemma': 'generation'},
    'birds': {'ru': 'птица', 'tg': 'парранда', 'lemma': 'bird'},
    'insects': {'ru': 'насекомое', 'tg': 'ҳашарот', 'lemma': 'insect'},
    'established': {'ru': 'обосновываться', 'tg': 'ҷойгир шудан', 'lemma': 'establish'},
    'themselves': {'ru': 'сами', 'tg': 'худашон', 'lemma': 'themselves'},
    'species': {'ru': 'вид (биологический)', 'tg': 'намуд', 'lemma': 'species'},
    'survive': {'ru': 'выживать', 'tg': 'зинда мондан', 'lemma': 'survive'},
    'previous': {'ru': 'предыдущий', 'tg': 'пешина', 'lemma': 'previous'},
    'older': {'ru': 'старый (более старый)', 'tg': 'қадимтар', 'lemma': 'old'},
    'structure': {'ru': 'структура', 'tg': 'сохтор', 'lemma': 'structure'},
    'standing': {'ru': 'стоять', 'tg': 'истодан', 'lemma': 'stand'},
    'nearly': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'nearly'},
    'metres': {'ru': 'метр', 'tg': 'метр', 'lemma': 'metre'},
    'tall': {'ru': 'высокий', 'tg': 'баланд', 'lemma': 'tall'},
    'assuming': {'ru': 'если предположить', 'tg': 'агар гумон кунем', 'lemma': 'assuming'},
    'rainfall': {'ru': 'осадки (дождь)', 'tg': 'борон', 'lemma': 'rainfall'},
    'remains': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'steady': {'ru': 'стабильный', 'tg': 'устувор', 'lemma': 'steady'},
    'local': {'ru': 'местный', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'schoolchildren': {'ru': 'школьники', 'tg': 'мактаббачагон', 'lemma': 'schoolchildren'},
    'adopted': {'ru': 'взять шефство (усыновить)', 'tg': 'сарпарастӣ кардан', 'lemma': 'adopt'},
    'individual': {'ru': 'отдельный', 'tg': 'алоҳида', 'lemma': 'individual'},
    'promising': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'visit': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'track': {'ru': 'отслеживать', 'tg': 'пайгирӣ кардан', 'lemma': 'track'},
    'progress': {'ru': 'прогресс', 'tg': 'пешрафт', 'lemma': 'progress'},
    'shade': {'ru': 'тень', 'tg': 'соя', 'lemma': 'shade'},
    'helped': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'plant': {'ru': 'сажать', 'tg': 'шинондан', 'lemma': 'plant'},
    'strange': {'ru': 'странно', 'tg': 'аҷиб', 'lemma': 'strange'},
    'truly': {'ru': 'поистине', 'tg': 'дар ҳақиқат', 'lemma': 'truly'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'today\'s': {'ru': 'сегодняшний', 'tg': 'имрӯза', 'lemma': 'today'},
    'grown': {'ru': 'стареть (расти)', 'tg': 'пир шудан', 'lemma': 'grow old'},
    'themselves2': {'ru': 'сами', 'tg': 'худашон', 'lemma': 'themselves'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'perhaps': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'perhaps'},
    'continuing': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'transformations': {'ru': 'преобразование', 'tg': 'тағйирот', 'lemma': 'transformation'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'take': {'ru': 'занимать (время)', 'tg': 'вақт гирифтан', 'lemma': 'take'},
    'longer': {'ru': 'дольше', 'tg': 'дарозтар', 'lemma': 'long'},
    'single': {'ru': 'единственная (одна)', 'tg': 'ягона', 'lemma': 'single'},
    'human': {'ru': 'человеческая', 'tg': 'инсонӣ', 'lemma': 'human'},
    'lifetime': {'ru': 'жизнь (продолжительность жизни)', 'tg': 'умр', 'lemma': 'lifetime'},
    'allows': {'ru': 'позволять', 'tg': 'иҷозат додан', 'lemma': 'allow'},
    'witness': {'ru': 'наблюдать (быть свидетелем)', 'tg': 'шоҳид будан', 'lemma': 'witness'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'}, 'they\'ll': BE, 'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистанд', 'lemma': 'can'}, 'haven\'t': {'ru': 'не имеют', 'tg': 'надоранд', 'lemma': 'have'},
},
143: {
    'grandfather': {'ru': 'дедушка', 'tg': 'бобо', 'lemma': 'grandfather'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'understand': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'sky': {'ru': 'небо', 'tg': 'осмон', 'lemma': 'sky'},
    'harvest': {'ru': 'урожай', 'tg': 'ҳосил', 'lemma': 'harvest'},
    'clouds': {'ru': 'облако', 'tg': 'абр', 'lemma': 'cloud'},
    'gather': {'ru': 'собираться', 'tg': 'ҷамъ шудан', 'lemma': 'gather'},
    'low': {'ru': 'низко', 'tg': 'паст', 'lemma': 'low'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'explain': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'rain': {'ru': 'дождь (идти дождём)', 'tg': 'борон боридан', 'lemma': 'rain'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'follow': {'ru': 'следовать', 'tg': 'пайравӣ кардан', 'lemma': 'follow'},
    'afternoon': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'wind': {'ru': 'ветер', 'tg': 'бод', 'lemma': 'wind'},
    'shifts': {'ru': 'менять(ся)', 'tg': 'тағир ёфтан', 'lemma': 'shift'},
    'direction': {'ru': 'направление', 'tg': 'самт', 'lemma': 'direction'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'farmers': {'ru': 'фермер', 'tg': 'деҳқон', 'lemma': 'farmer'},
    'around': {'ru': 'вокруг', 'tg': 'атроф', 'lemma': 'around'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'storm': {'ru': 'буря', 'tg': 'тӯфон', 'lemma': 'storm'},
    'isn\'t': BE, 'far': {'ru': 'далеко', 'tg': 'дур', 'lemma': 'far'},
    'behind': {'ru': 'позади', 'tg': 'дар паси', 'lemma': 'behind'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'trusted': {'ru': 'доверять', 'tg': 'бовар кардан', 'lemma': 'trust'},
    'weather': {'ru': 'погода', 'tg': 'обу ҳаво', 'lemma': 'weather'},
    'app': {'ru': 'приложение', 'tg': 'барнома', 'lemma': 'app'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'insisting': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'watch': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'birds': {'ru': 'птица', 'tg': 'парранда', 'lemma': 'bird'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'predict': {'ru': 'предсказывать', 'tg': 'пешгӯӣ кардан', 'lemma': 'predict'},
    'accurately': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'accurately'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'until': {'ru': 'пока не', 'tg': 'то', 'lemma': 'until'},
    'rains': {'ru': 'дождь (осадки)', 'tg': 'боронҳо', 'lemma': 'rain'},
    'arrive': {'ru': 'приходить', 'tg': 'расидан', 'lemma': 'arrive'},
    'fields': {'ru': 'поле', 'tg': 'дашт', 'lemma': 'field'},
    'remain': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'dangerously': {'ru': 'опасно', 'tg': 'хатарнок', 'lemma': 'dangerously'},
    'dry': {'ru': 'сухой', 'tg': 'хушк', 'lemma': 'dry'},
    'threatening': {'ru': 'угрожать', 'tg': 'таҳдид кардан', 'lemma': 'threaten'},
    'entire': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'entire'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'warned': {'ru': 'предупреждать', 'tg': 'огоҳ кардан', 'lemma': 'warn'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'lose': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'half': {'ru': 'половина', 'tg': 'ним', 'lemma': 'half'},
    'wheat': {'ru': 'пшеница', 'tg': 'гандум', 'lemma': 'wheat'},
    'crop': {'ru': 'урожай (культура)', 'tg': 'ҳосил', 'lemma': 'crop'},
    'soon': {'ru': 'как только', 'tg': 'ҳамин ки', 'lemma': 'as soon as'},
    'dark': {'ru': 'тёмный', 'tg': 'торик', 'lemma': 'dark'},
    'appeared': {'ru': 'появляться', 'tg': 'пайдо шудан', 'lemma': 'appear'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'rushed': {'ru': 'спешить', 'tg': 'шитоб кардан', 'lemma': 'rush'},
    'outside': {'ru': 'наружу', 'tg': 'берун', 'lemma': 'outside'},
    'prepare': {'ru': 'готовить', 'tg': 'тайёр кардан', 'lemma': 'prepare'},
    'irrigation': {'ru': 'ирригационный', 'tg': 'обёрӣ', 'lemma': 'irrigation'},
    'channels': {'ru': 'канал', 'tg': 'ҷӯй', 'lemma': 'channel'},
    'case': {'ru': 'случай', 'tg': 'ҳолат', 'lemma': 'case'},
    'arrives': {'ru': 'приходить', 'tg': 'расидан', 'lemma': 'arrive'},
    'predicted': {'ru': 'предсказывать', 'tg': 'пешгӯӣ кардан', 'lemma': 'predict'},
    'relax': {'ru': 'расслабляться', 'tg': 'ором шудан', 'lemma': 'relax'},
    'fully': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'fully'},
    'celebrate': {'ru': 'праздновать', 'tg': 'ҷашн гирифтан', 'lemma': 'celebrate'},
    'water': {'ru': 'вода', 'tg': 'об', 'lemma': 'water'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'reaches': {'ru': 'достигать', 'tg': 'расидан', 'lemma': 'reach'},
    'furthest': {'ru': 'самый дальний', 'tg': 'дуртарин', 'lemma': 'furthest'},
    'season': {'ru': 'сезон', 'tg': 'мавсим', 'lemma': 'season'},
    'begins': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'whether': {'ru': 'ли', 'tg': 'оё', 'lemma': 'whether'},
    'anxious': {'ru': 'тревожный', 'tg': 'нигарон', 'lemma': 'anxious'},
    'waiting': {'ru': 'ожидание', 'tg': 'интизорӣ', 'lemma': 'waiting'},
    'worth': {'ru': 'стоящий (того)', 'tg': 'арзанда', 'lemma': 'worth it'},
    'then': {'ru': 'до тех пор', 'tg': 'то он вақт', 'lemma': 'then'},
    'watches': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'horizon': {'ru': 'горизонт', 'tg': 'уфуқ', 'lemma': 'horizon'},
    'hopeful': {'ru': 'полный надежды', 'tg': 'умедвор', 'lemma': 'hopeful'},
    'nervous': {'ru': 'нервный', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'way': {'ru': 'способ (манера)', 'tg': 'тарз', 'lemma': 'way'},
    'farming': {'ru': 'фермерский', 'tg': 'деҳқонӣ', 'lemma': 'farming'},
    'families': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'claimed': {'ru': 'утверждать', 'tg': 'даъво кардан', 'lemma': 'claim'},
    'reliably': {'ru': 'надёжно', 'tg': 'боэътимод', 'lemma': 'reliably'},
    'he\'d': {'ru': 'объяснял бы', 'tg': 'мефаҳмонд', 'lemma': 'explain'}, 'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'}, 'we\'ll': BE, 'doesn\'t': DO,
},
}

for sid, keys in {136: ['rather2'], 137: ['turn2'], 139: ['entirely2' if False else '__none__'], 141: ['spoke2', 'real2', 'speaking2'], 142: ['entirely2', 'themselves2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
