# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
144: {
    'accepted': {'ru': 'принимать', 'tg': 'қабул кардан', 'lemma': 'accept'},
    'scholarship': {'ru': 'стипендия', 'tg': 'стипендия', 'lemma': 'scholarship'},
    'abroad': {'ru': 'за границей', 'tg': 'хориҷа', 'lemma': 'abroad'},
    'fifteen': {'ru': 'пятнадцать', 'tg': 'понздаҳ', 'lemma': 'fifteen'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'living': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'completely': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'completely'},
    'different': {'ru': 'другая', 'tg': 'дигар', 'lemma': 'different'},
    'country': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'perhaps': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'perhaps'},
    'teaching': {'ru': 'преподавать', 'tg': 'таълим додан', 'lemma': 'teach'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'hometown': {'ru': 'родной город', 'tg': 'зодгоҳ', 'lemma': 'hometown'},
    'heard': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'afraid': {'ru': 'бояться', 'tg': 'тарсидан', 'lemma': 'afraid'},
    'leaving': {'ru': 'покидать', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'fluent': {'ru': 'свободно владеющий', 'tg': 'моҳир', 'lemma': 'fluent'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'more': {'ru': 'более', 'tg': 'бештар', 'lemma': 'more'},
    'languages': {'ru': 'язык', 'tg': 'забон', 'lemma': 'language'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'old': {'ru': 'бывший (старый)', 'tg': 'кӯҳна', 'lemma': 'old'},
    'classmate': {'ru': 'одноклассник', 'tg': 'ҳамсинф', 'lemma': 'classmate'},
    'similar': {'ru': 'похожий', 'tg': 'монанд', 'lemma': 'similar'},
    'offer': {'ru': 'предложение', 'tg': 'пешниҳод', 'lemma': 'offer'},
    'sends': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'occasional': {'ru': 'редкий (изредка)', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasional'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'conferences': {'ru': 'конференция', 'tg': 'конфронс', 'lemma': 'conference'},
    'cities': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'films': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'wonder': {'ru': 'задаваться вопросом', 'tg': 'фикр кардан', 'lemma': 'wonder'},
    'braver': {'ru': 'смелее', 'tg': 'ҷасуртар', 'lemma': 'brave'},
    'back': {'ru': 'тогда (назад)', 'tg': 'он вақт', 'lemma': 'back then'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'happier': {'ru': 'счастливее', 'tg': 'хушбахттар', 'lemma': 'happy'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'carrying': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'entirely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'entirely'},
    'separate': {'ru': 'отдельный', 'tg': 'ҷудогона', 'lemma': 'separate'},
    'set': {'ru': 'набор', 'tg': 'маҷмӯа', 'lemma': 'set'},
    'regrets': {'ru': 'сожаление', 'tg': 'пушаймонӣ', 'lemma': 'regret'},
    'stayed': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'single': {'ru': 'холостой (незамужняя)', 'tg': 'муҷаррад', 'lemma': 'single'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'marrying': {'ru': 'жениться', 'tg': 'оиладор шудан', 'lemma': 'marry'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'imagine': {'ru': 'вообразить', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'gone': {'ru': 'идти (пойти)', 'tg': 'рафтан', 'lemma': 'go'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'way': {'ru': 'путь (сторона)', 'tg': 'роҳ', 'lemma': 'way'},
    'missed': {'ru': 'пропускать (упустить)', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'version': {'ru': 'версия', 'tg': 'нусха', 'lemma': 'version'},
    'messy': {'ru': 'беспорядочный', 'tg': 'бетартиб', 'lemma': 'messy'},
    'familiar': {'ru': 'знакомый', 'tg': 'шинос', 'lemma': 'familiar'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'frustrating': {'ru': 'раздражающий', 'tg': 'асабонӣ кунанда', 'lemma': 'frustrating'},
    'undeniably': {'ru': 'бесспорно', 'tg': 'бешубҳа', 'lemma': 'undeniably'},
    'mine': {'ru': 'моя (моё)', 'tg': 'аз они ман', 'lemma': 'mine'},
    'meanwhile': {'ru': 'тем временем', 'tg': 'дар айни ҳол', 'lemma': 'meanwhile'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'opposite': {'ru': 'противоположное', 'tg': 'муқобил', 'lemma': 'opposite'},
    'left': {'ru': 'уезжать', 'tg': 'рафтан', 'lemma': 'leave'},
    'sitting': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'surrounded': {'ru': 'окружённый', 'tg': 'иҳоташуда', 'lemma': 'surrounded'},
    'wondering': {'ru': 'размышлять', 'tg': 'фикр кардан', 'lemma': 'wonder'},
    'own': {'ru': 'собственная', 'tg': 'худи', 'lemma': 'own'},
    'unlived': {'ru': 'непрожитый', 'tg': 'зиста нашуда', 'lemma': 'unlived'},
    'alternative': {'ru': 'альтернатива', 'tg': 'алтернатива', 'lemma': 'alternative'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'recently': {'ru': 'недавно', 'tg': 'ба наздикӣ', 'lemma': 'recently'},
    'agreeing': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'either': {'ru': 'любой (из нас)', 'tg': 'ҳар кадоме', 'lemma': 'either'},
    'chosen': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'differently': {'ru': 'по-другому', 'tg': 'дигар хел', 'lemma': 'differently'},
    'anyway': {'ru': 'всё равно', 'tg': 'бо ин ҳама', 'lemma': 'anyway'},
    'imagining': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'had': HAVE, 'hadn\'t': HAVE, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'wouldn\'t': HAVE, 'i\'ve': HAVE, 'we\'d': BE,
},
145: {
    'wish': {'ru': 'желать (жаль)', 'tg': 'кош', 'lemma': 'wish'},
    'kept': {'ru': 'поддерживать (сохранять)', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'touch': {'ru': 'связь (контакт)', 'tg': 'алоқа', 'lemma': 'touch'},
    'closest': {'ru': 'самый близкий', 'tg': 'наздиктарин', 'lemma': 'close'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'letting': {'ru': 'позволять', 'tg': 'иҷозат додан', 'lemma': 'let'},
    'friendship': {'ru': 'дружба', 'tg': 'дӯстӣ', 'lemma': 'friendship'},
    'quietly': {'ru': 'тихо (незаметно)', 'tg': 'ором', 'lemma': 'quietly'},
    'disappear': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'disappear'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'inseparable': {'ru': 'неразлучный', 'tg': 'ҷудонашаванда', 'lemma': 'inseparable'},
    'once': {'ru': 'когда-то', 'tg': 'замоне', 'lemma': 'once'},
    'understood': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'conversations': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'rarer': {'ru': 'реже', 'tg': 'нодиртар', 'lemma': 'rare'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'stopped': {'ru': 'прекращаться', 'tg': 'бас шудан', 'lemma': 'stop'},
    'altogether': {'ru': 'совсем', 'tg': 'тамоман', 'lemma': 'altogether'},
    'respond': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'respond'},
    'last': {'ru': 'последний', 'tg': 'охирин', 'lemma': 'last'},
    'message': {'ru': 'сообщение', 'tg': 'паём', 'lemma': 'message'},
    'sent': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'assumed': {'ru': 'предполагать', 'tg': 'гумон кардан', 'lemma': 'assume'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'friendships': {'ru': 'дружба', 'tg': 'дӯстӣ', 'lemma': 'friendship'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'survive': {'ru': 'выживать', 'tg': 'зинда мондан', 'lemma': 'survive'},
    'real': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'real'},
    'effort': {'ru': 'усилие', 'tg': 'кӯшиш', 'lemma': 'effort'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'wishes': {'ru': 'желать', 'tg': 'орзу кардан', 'lemma': 'wish'},
    'learned': {'ru': 'учить (выучить)', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'language': {'ru': 'язык', 'tg': 'забон', 'lemma': 'language'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'giving': {'ru': 'сдаваться', 'tg': 'даст кашидан', 'lemma': 'give up'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'lessons': {'ru': 'урок', 'tg': 'дарс', 'lemma': 'lesson'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'biggest': {'ru': 'самое большое', 'tg': 'бузургтарин', 'lemma': 'biggest'},
    'regret': {'ru': 'сожаление', 'tg': 'пушаймонӣ', 'lemma': 'regret'},
    'twenties': {'ru': 'двадцатые (возраст)', 'tg': 'бистсолагӣ', 'lemma': 'twenties'},
    'go': {'ru': 'вернуться (пойти)', 'tg': 'баргаштан', 'lemma': 'go back'},
    'prioritise': {'ru': 'расставлять приоритеты', 'tg': 'афзалият додан', 'lemma': 'prioritise'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'recognise': {'ru': 'признавать (осознавать)', 'tg': 'эътироф кардан', 'lemma': 'recognise'},
    'wishing': {'ru': 'желание', 'tg': 'орзу', 'lemma': 'wishing'},
    'rarely': {'ru': 'редко', 'tg': 'кам', 'lemma': 'rarely'},
    'changes': {'ru': 'менять', 'tg': 'тағир додан', 'lemma': 'change'},
    'anything': {'ru': 'что-либо', 'tg': 'чизе', 'lemma': 'anything'},
    'itself': {'ru': 'само по себе', 'tg': 'худаш', 'lemma': 'itself'},
    'recently': {'ru': 'недавно', 'tg': 'ба наздикӣ', 'lemma': 'recently'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'photograph': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photograph'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'forgotten': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'quite': {'ru': 'весьма', 'tg': 'комилан', 'lemma': 'quite'},
    'desperately': {'ru': 'отчаянно', 'tg': 'сахт', 'lemma': 'desperately'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'funny': {'ru': 'смешной', 'tg': 'хандаовар', 'lemma': 'funny'},
    'openly': {'ru': 'открыто', 'tg': 'ошкоро', 'lemma': 'openly'},
    'rather': {'ru': 'а не', 'tg': 'ба ҷои', 'lemma': 'rather than'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'mourning': {'ru': 'оплакивать', 'tg': 'мотам гирифтан', 'lemma': 'mourn'},
    'romantic': {'ru': 'романтический', 'tg': 'ошиқона', 'lemma': 'romantic'},
    'relationships': {'ru': 'отношения', 'tg': 'муносибат', 'lemma': 'relationship'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'thinking': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'honest': {'ru': 'честный', 'tg': 'самимӣ', 'lemma': 'honest'},
    'step': {'ru': 'шаг', 'tg': 'қадам', 'lemma': 'step'},
    'towards': {'ru': 'к (по направлению)', 'tg': 'ба сӯи', 'lemma': 'towards'},
    'reaching': {'ru': 'связываться (протянуть)', 'tg': 'даст дароз кардан', 'lemma': 'reach out'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'awkward': {'ru': 'неловкий', 'tg': 'ноӯҳда', 'lemma': 'awkward'},
    'feel': {'ru': 'ощущаться (чувствоваться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'had': HAVE, 'hadn\'t': HAVE, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'i\'ve': HAVE, 'they\'ve': HAVE, 'could': {'ru': 'мог(ла) бы', 'tg': 'метавонистам', 'lemma': 'could'},
},
146: {
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'abroad': {'ru': 'за границу', 'tg': 'хориҷа', 'lemma': 'abroad'},
    'used': {'ru': 'раньше делал', 'tg': 'пештар мекард', 'lemma': 'used to'},
    'feel': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'completely': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'completely'},
    'lost': {'ru': 'потерянный', 'tg': 'гумшуда', 'lemma': 'lost'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'time': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'left': {'ru': 'покидать', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'apartment': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'apartment'},
    'unable': {'ru': 'неспособный', 'tg': 'қодир набуда', 'lemma': 'unable'},
    'read': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'basic': {'ru': 'простой (базовый)', 'tg': 'оддӣ', 'lemma': 'basic'},
    'signs': {'ru': 'вывеска (знак)', 'tg': 'нишона', 'lemma': 'sign'},
    'understand': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'simple': {'ru': 'простой', 'tg': 'сода', 'lemma': 'simple'},
    'conversations': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'silence': {'ru': 'тишина', 'tg': 'хомӯшӣ', 'lemma': 'silence'},
    'small': {'ru': 'маленький (лёгкий)', 'tg': 'хурд', 'lemma': 'small talk'},
    'talk': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'talk'},
    'disappearing': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'disappear'},
    'entirely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'entirely'},
    'replaced': {'ru': 'заменять', 'tg': 'иваз кардан', 'lemma': 'replace'},
    'awkward': {'ru': 'неловкий', 'tg': 'ноӯҳда', 'lemma': 'awkward'},
    'constant': {'ru': 'постоянный', 'tg': 'доимӣ', 'lemma': 'constant'},
    'translation': {'ru': 'перевод', 'tg': 'тарҷума', 'lemma': 'translation'},
    'happening': {'ru': 'происходить', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'inside': {'ru': 'внутри', 'tg': 'дарун', 'lemma': 'inside'},
    'head': {'ru': 'голова', 'tg': 'сар', 'lemma': 'head'},
    'slowly': {'ru': 'постепенно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'getting': {'ru': 'привыкать', 'tg': 'одат кардан', 'lemma': 'get used to'},
    'ordering': {'ru': 'заказывать', 'tg': 'фармоиш додан', 'lemma': 'order'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'pointing': {'ru': 'указывать (пальцем)', 'tg': 'ишора кардан', 'lemma': 'point'},
    'rather': {'ru': 'а не', 'tg': 'ба ҷои', 'lemma': 'rather than'},
    'speaking': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'seems': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'mind': {'ru': 'возражать', 'tg': 'эътироз доштан', 'lemma': 'mind'},
    'anymore': {'ru': 'больше', 'tg': 'дигар', 'lemma': 'anymore'},
    'panic': {'ru': 'паниковать', 'tg': 'ба ошуфтагӣ афтодан', 'lemma': 'panic'},
    'supermarkets': {'ru': 'супермаркет', 'tg': 'мағозаи калон', 'lemma': 'supermarket'},
    'overwhelmed': {'ru': 'ошеломлённый', 'tg': 'мутаассир', 'lemma': 'overwhelmed'},
    'unfamiliar': {'ru': 'незнакомый', 'tg': 'ношинос', 'lemma': 'unfamiliar'},
    'packaging': {'ru': 'упаковка', 'tg': 'бастабандӣ', 'lemma': 'packaging'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'recognising': {'ru': 'узнавать', 'tg': 'шинохтан', 'lemma': 'recognise'},
    'least': {'ru': 'по крайней мере', 'tg': 'ҳадди ақал', 'lemma': 'at least'},
    'basics': {'ru': 'основы', 'tg': 'асосҳо', 'lemma': 'basics'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'decades': {'ru': 'десятилетие', 'tg': 'даҳсола', 'lemma': 'decade'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'remembers': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'disorienting': {'ru': 'дезориентирующий', 'tg': 'гумроҳкунанда', 'lemma': 'disorienting'},
    'first': {'ru': 'первые', 'tg': 'аввалин', 'lemma': 'first'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'felt': {'ru': 'чувствоваться', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'fully': {'ru': 'полностью', 'tg': 'пурра', 'lemma': 'fully'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'strange': {'ru': 'странное', 'tg': 'аҷиб', 'lemma': 'strange'},
    'becomes': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'ordinary': {'ru': 'обычное', 'tg': 'оддӣ', 'lemma': 'ordinary'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'quite': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'quite'},
    'noticing': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'happened': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'home': {'ru': 'домой (дом)', 'tg': 'хона', 'lemma': 'home'},
    'single': {'ru': 'каждый (единственный)', 'tg': 'ҳар як', 'lemma': 'single'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'desperate': {'ru': 'отчаянно нуждающийся', 'tg': 'сахт мӯҳтоҷ', 'lemma': 'desperate'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'comfortable': {'ru': 'удобный (привычный)', 'tg': 'бароҳат', 'lemma': 'comfortable'},
    'weekly': {'ru': 'еженедельный', 'tg': 'ҳарҳафтаина', 'lemma': 'weekly'},
    'colleagues': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'gotten': {'ru': 'привыкать', 'tg': 'одат кардан', 'lemma': 'get used to'},
    'occasional': {'ru': 'случайный (иногда)', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasional'},
    'grammar': {'ru': 'грамматика', 'tg': 'грамматика', 'lemma': 'grammar'},
    'mistakes': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'myself': {'ru': 'сам (себя)', 'tg': 'худам', 'lemma': 'myself'},
    'looking': {'ru': 'оглядываясь', 'tg': 'бознигарӣ', 'lemma': 'look back'},
    'confusing': {'ru': 'запутанный', 'tg': 'печида', 'lemma': 'confusing'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'barely': {'ru': 'едва', 'tg': 'базӯр', 'lemma': 'barely'},
    'recognise': {'ru': 'узнавать', 'tg': 'шинохтан', 'lemma': 'recognise'},
    'anxious': {'ru': 'тревожный', 'tg': 'нигарон', 'lemma': 'anxious'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'thoroughly': {'ru': 'полностью', 'tg': 'пурра', 'lemma': 'thoroughly'},
    'impossibly': {'ru': 'невероятно', 'tg': 'ба таври ғайриимкон', 'lemma': 'impossibly'},
    'foreign': {'ru': 'чужой (иностранный)', 'tg': 'бегона', 'lemma': 'foreign'},
    'wasn\'t': BE, 'i\'m': BE, 'she\'s': BE, 'i\'ve': HAVE,
},
147: {
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'asked': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'filing': {'ru': 'система хранения документов', 'tg': 'бойгонӣ', 'lemma': 'filing system'},
    'system': {'ru': 'система', 'tg': 'система', 'lemma': 'system'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'else': {'ru': 'ещё (другие)', 'tg': 'дигар', 'lemma': 'else'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'learned': {'ru': 'научиться', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'accept': {'ru': 'принимать', 'tg': 'қабул кардан', 'lemma': 'accept'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'question': {'ru': 'вопрос (сомнение)', 'tg': 'савол', 'lemma': 'question'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'struggling': {'ru': 'мучиться', 'tg': 'мубориза бурдан', 'lemma': 'struggle'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'managing': {'ru': 'справляться', 'tg': 'муваффақ шудан', 'lemma': 'manage'},
    'organise': {'ru': 'организовать', 'tg': 'мураттаб кардан', 'lemma': 'organise'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'would': {'ru': 'не могли бы вы', 'tg': 'мехостед', 'lemma': 'would you mind'},
    'mind': {'ru': 'возражать', 'tg': 'эътироз доштан', 'lemma': 'mind'},
    'explaining': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'asked2': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'politely': {'ru': 'вежливо', 'tg': 'бо эҳтиром', 'lemma': 'politely'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'embarrassed': {'ru': 'смущённая', 'tg': 'хиҷолатманд', 'lemma': 'embarrassed'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'confused': {'ru': 'растерянный', 'tg': 'гаранг', 'lemma': 'confused'},
    'repeating': {'ru': 'повторять', 'tg': 'такрор кардан', 'lemma': 'repeat'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'told': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'honestly': {'ru': 'честно', 'tg': 'самимона', 'lemma': 'honestly'},
    'remembering': {'ru': 'вспоминать', 'tg': 'ба ёд овардан', 'lemma': 'remember'},
    'kind': {'ru': 'добрый', 'tg': 'меҳрубон', 'lemma': 'kind'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'own': {'ru': 'собственные', 'tg': 'худи', 'lemma': 'own'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'persuaded': {'ru': 'убедить', 'tg': 'бовар кунондан', 'lemma': 'persuade'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'simpler': {'ru': 'проще', 'tg': 'соддатар', 'lemma': 'simple'},
    'method': {'ru': 'метод', 'tg': 'усул', 'lemma': 'method'},
    'developed': {'ru': 'разрабатывать', 'tg': 'инкишоф додан', 'lemma': 'develop'},
    'official': {'ru': 'официальный', 'tg': 'расмӣ', 'lemma': 'official'},
    'entirely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'entirely'},
    'stopped': {'ru': 'переставать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'taking': {'ru': 'делать (записи)', 'tg': 'гирифтан', 'lemma': 'take notes'},
    'notes': {'ru': 'заметки', 'tg': 'қайдҳо', 'lemma': 'note'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'listen': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'relief': {'ru': 'облегчение', 'tg': 'сабукӣ', 'lemma': 'relief'},
    'face': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'save': {'ru': 'сохранить', 'tg': 'нигоҳ доштан', 'lemma': 'save'},
    'backup': {'ru': 'резервная', 'tg': 'эҳтиётӣ', 'lemma': 'backup'},
    'copy': {'ru': 'копия', 'tg': 'нусха', 'lemma': 'copy'},
    'reminded': {'ru': 'напоминать', 'tg': 'ёдовар шудан', 'lemma': 'remind'},
    'recalling': {'ru': 'вспоминать', 'tg': 'ба ёд овардан', 'lemma': 'recall'},
    'forgot': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'lost': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'promised': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'believed': {'ru': 'верить', 'tg': 'бовар кардан', 'lemma': 'believe'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'overheard': {'ru': 'случайно услышать', 'tg': 'тасодуфан шунидан', 'lemma': 'overhear'},
    'helping': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'exact': {'ru': 'тот же самый', 'tg': 'ҳамон', 'lemma': 'exact'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'patiently': {'ru': 'терпеливо', 'tg': 'бо сабр', 'lemma': 'patiently'},
    'taught': {'ru': 'учить', 'tg': 'омӯзондан', 'lemma': 'teach'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'awkward': {'ru': 'неловкие', 'tg': 'ноӯҳда', 'lemma': 'awkward'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'teaching': {'ru': 'учить (обучать)', 'tg': 'таълим додан', 'lemma': 'teach'},
    'means': {'ru': 'означать', 'tg': 'маъно доштан', 'lemma': 'mean'},
    'watching': {'ru': 'наблюдать', 'tg': 'мушоҳида кардан', 'lemma': 'watch'},
    'don\'t': DO, 'i\'d': HAVE, 'could': {'ru': 'мог', 'tg': 'метавонистам', 'lemma': 'could'},
},
148: {
    'contract': {'ru': 'договор', 'tg': 'шартнома', 'lemma': 'contract'},
    'signed': {'ru': 'подписывать', 'tg': 'имзо кардан', 'lemma': 'sign'},
    'sometime': {'ru': 'когда-то', 'tg': 'вақте', 'lemma': 'sometime'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'could': {'ru': 'мог', 'tg': 'метавонист', 'lemma': 'could'},
    'say': {'ru': 'сказать', 'tg': 'гуфтан', 'lemma': 'say'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'when': {'ru': 'когда', 'tg': 'кай', 'lemma': 'when'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'frustrated': {'ru': 'раздосадованный', 'tg': 'ноумед', 'lemma': 'frustrated'},
    'insisted': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'removed': {'ru': 'убирать (удалять)', 'tg': 'бартараф кардан', 'lemma': 'remove'},
    'copy': {'ru': 'копия', 'tg': 'нусха', 'lemma': 'copy'},
    'filing': {'ru': 'картотечный', 'tg': 'бойгонӣ', 'lemma': 'filing cabinet'},
    'cabinet': {'ru': 'шкаф (картотека)', 'tg': 'ҷевон', 'lemma': 'cabinet'},
    'deliberately': {'ru': 'намеренно', 'tg': 'қасдан', 'lemma': 'deliberately'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'disappeared': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'disappear'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'searching': {'ru': 'искать', 'tg': 'ҷустуҷӯ кардан', 'lemma': 'search'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'drawer': {'ru': 'ящик', 'tg': 'ҷевон', 'lemma': 'drawer'},
    'third': {'ru': 'третий', 'tg': 'сеюм', 'lemma': 'third'},
    'time': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'assistant': {'ru': 'помощник', 'tg': 'ёрдамчӣ', 'lemma': 'assistant'},
    'suggested': {'ru': 'предполагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'perhaps': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'perhaps'},
    'document': {'ru': 'документ', 'tg': 'ҳуҷҷат', 'lemma': 'document'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'certain': {'ru': 'уверенная', 'tg': 'мутмаин', 'lemma': 'certain'},
    'watching': {'ru': 'наблюдать', 'tg': 'мушоҳида кардан', 'lemma': 'watch'},
    'client': {'ru': 'клиент', 'tg': 'муштарӣ', 'lemma': 'client'},
    'sign': {'ru': 'подписывать', 'tg': 'имзо кардан', 'lemma': 'sign'},
    'personally': {'ru': 'лично', 'tg': 'шахсан', 'lemma': 'personally'},
    'rather': {'ru': 'предпочла бы', 'tg': 'тарҷеҳ медиҳам', 'lemma': 'would rather'},
    'accuse': {'ru': 'обвинять', 'tg': 'айбдор кардан', 'lemma': 'accuse'},
    'anyone': {'ru': 'кого-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'proof': {'ru': 'доказательство', 'tg': 'далел', 'lemma': 'proof'},
    'carefully': {'ru': 'осторожно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'aware': {'ru': 'осознающий', 'tg': 'огоҳ', 'lemma': 'aware'},
    'tense': {'ru': 'напряжённый', 'tg': 'шиддатнок', 'lemma': 'tense'},
    'become': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'moved': {'ru': 'перемещать', 'tg': 'ҳаракат додан', 'lemma': 'move'},
    'accidentally': {'ru': 'случайно', 'tg': 'тасодуфан', 'lemma': 'accidentally'},
    'another': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'another'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'offered': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'tidying': {'ru': 'убирать', 'tg': 'тартиб додан', 'lemma': 'tidy'},
    'shared': {'ru': 'общий', 'tg': 'муштарак', 'lemma': 'shared'},
    'desk': {'ru': 'стол', 'tg': 'миз', 'lemma': 'desk'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'checked': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'immediately': {'ru': 'немедленно', 'tg': 'фавран', 'lemma': 'immediately'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'assuming': {'ru': 'предполагать', 'tg': 'гумон кардан', 'lemma': 'assume'},
    'safely': {'ru': 'надёжно', 'tg': 'бехатар', 'lemma': 'safely'},
    'filed': {'ru': 'подшивать', 'tg': 'бойгонӣ кардан', 'lemma': 'file'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'nearly': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'nearly'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'mistakenly': {'ru': 'ошибочно', 'tg': 'ба хато', 'lemma': 'mistakenly'},
    'entirely2': {'ru': 'совершенно', 'tg': 'комилан', 'lemma': 'entirely'},
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'double': {'ru': 'дважды', 'tg': 'дучанд', 'lemma': 'double-check'},
    'checked2': {'ru': 'перепроверять', 'tg': 'аз нав тафтиш кардан', 'lemma': 'double-check'},
    'myself': {'ru': 'сам', 'tg': 'худам', 'lemma': 'myself'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'relieved': {'ru': 'испытывающий облегчение', 'tg': 'сабукшуда', 'lemma': 'relieved'},
    'still': {'ru': 'всё же', 'tg': 'ба ҳар ҳол', 'lemma': 'still'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'annoyed': {'ru': 'раздражённая', 'tg': 'асабонӣ', 'lemma': 'annoyed'},
    'created': {'ru': 'создавать', 'tg': 'эҷод кардан', 'lemma': 'create'},
    'clearer': {'ru': 'более ясная', 'tg': 'равшантар', 'lemma': 'clear'},
    'continue': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'relying': {'ru': 'полагаться', 'tg': 'такя кардан', 'lemma': 'rely on'},
    'memory': {'ru': 'память', 'tg': 'хотира', 'lemma': 'memory'},
    'alone': {'ru': 'одной (только)', 'tg': 'танҳо', 'lemma': 'alone'},
    'malicious': {'ru': 'злонамеренный', 'tg': 'бадхоҳона', 'lemma': 'malicious'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'misplaced': {'ru': 'класть не туда', 'tg': 'нодуруст ҷойгир кардан', 'lemma': 'misplace'},
    'busy': {'ru': 'занятый', 'tg': 'серкор', 'lemma': 'busy'},
    'distracted': {'ru': 'рассеянный', 'tg': 'бепарво', 'lemma': 'distracted'},
    'afternoon': {'ru': 'вторая половина дня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'must': {'ru': 'должно быть', 'tg': 'бояд', 'lemma': 'must'},
    'can\'t': {'ru': 'не может', 'tg': 'наметавонад', 'lemma': 'can'}, 'i\'d': {'ru': 'предпочла бы', 'tg': 'тарҷеҳ медиҳам', 'lemma': 'would rather'}, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'should': {'ru': 'следовало бы', 'tg': 'мебоист', 'lemma': 'should'}, 'had': HAVE, 'didn\'t': DO,
},
149: {
    'soup': {'ru': 'суп', 'tg': 'шӯрбо', 'lemma': 'soup'},
    'tasted': {'ru': 'иметь вкус', 'tg': 'таъм доштан', 'lemma': 'taste'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'explain': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'why': {'ru': 'почему', 'tg': 'чаро', 'lemma': 'why'},
    'smelled': {'ru': 'пахнуть', 'tg': 'бӯй додан', 'lemma': 'smell'},
    'richer': {'ru': 'богаче (насыщеннее)', 'tg': 'бойтар', 'lemma': 'rich'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'chef': {'ru': 'повар', 'tg': 'ошпаз', 'lemma': 'chef'},
    'added': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'new': {'ru': 'новое', 'tg': 'нав', 'lemma': 'new'},
    'recipe': {'ru': 'рецепт', 'tg': 'дастур', 'lemma': 'recipe'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'tasting': {'ru': 'пробовать (на вкус)', 'tg': 'чашидан', 'lemma': 'taste'},
    'carefully': {'ru': 'внимательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'slightly': {'ru': 'немного', 'tg': 'андак', 'lemma': 'slightly'},
    'off': {'ru': 'не так (неправильно)', 'tg': 'нодуруст', 'lemma': 'off'},
    'quite': {'ru': 'точно', 'tg': 'дуруст', 'lemma': 'quite'},
    'identify': {'ru': 'определить', 'tg': 'муайян кардан', 'lemma': 'identify'},
    'missing': {'ru': 'отсутствующий (недостающий)', 'tg': 'намерасида', 'lemma': 'missing'},
    'ingredient': {'ru': 'ингредиент', 'tg': 'ҷузъ', 'lemma': 'ingredient'},
    'either': {'ru': 'тоже', 'tg': 'ҳам', 'lemma': 'either'},
    'tastes': {'ru': 'иметь вкус', 'tg': 'таъм доштан', 'lemma': 'taste'},
    'though': {'ru': 'как будто', 'tg': 'гӯё', 'lemma': 'as though'},
    'forgot': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'cumin': {'ru': 'зира (кумин)', 'tg': 'зира', 'lemma': 'cumin'},
    'suggested': {'ru': 'предполагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'sounding': {'ru': 'звучать', 'tg': 'садо додан', 'lemma': 'sound'},
    'fairly': {'ru': 'довольно', 'tg': 'хеле', 'lemma': 'fairly'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'uncertainty': {'ru': 'неуверенность', 'tg': 'номуайянӣ', 'lemma': 'uncertainty'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'least': {'ru': 'по крайней мере', 'tg': 'ҳадди ақал', 'lemma': 'at least'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'like': {'ru': 'как (подобно)', 'tg': 'мисли', 'lemma': 'like'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'warm': {'ru': 'тёплый', 'tg': 'гарм', 'lemma': 'warm'},
    'familiar': {'ru': 'знакомый', 'tg': 'шинос', 'lemma': 'familiar'},
    'looked': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'darker': {'ru': 'темнее', 'tg': 'сиёҳтар', 'lemma': 'dark'},
    'golden': {'ru': 'золотистый', 'tg': 'тиллоӣ', 'lemma': 'golden'},
    'colour': {'ru': 'цвет', 'tg': 'ранг', 'lemma': 'colour'},
    'uncle': {'ru': 'дядя', 'tg': 'тағо', 'lemma': 'uncle'},
    'ever': {'ru': 'вечно', 'tg': 'ҳамеша', 'lemma': 'ever'},
    'dramatic': {'ru': 'драматичный', 'tg': 'драматикӣ', 'lemma': 'dramatic'},
    'declared': {'ru': 'заявлять', 'tg': 'эълон кардан', 'lemma': 'declare'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'meal': {'ru': 'еда (блюдо)', 'tg': 'таом', 'lemma': 'meal'},
    'prepared': {'ru': 'готовить', 'tg': 'тайёр кардан', 'lemma': 'prepare'},
    'ate': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'portions': {'ru': 'порция', 'tg': 'ҳисса', 'lemma': 'portion'},
    'regardless': {'ru': 'несмотря ни на что', 'tg': 'сарфи назар', 'lemma': 'regardless'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'sounded': {'ru': 'звучать', 'tg': 'садо додан', 'lemma': 'sound'},
    'busier': {'ru': 'более шумная', 'tg': 'серодамтар', 'lemma': 'busy'},
    'too': {'ru': 'тоже', 'tg': 'низ', 'lemma': 'too'},
    'pots': {'ru': 'кастрюля', 'tg': 'дегҳо', 'lemma': 'pot'},
    'clattering': {'ru': 'греметь', 'tg': 'ғарингос задан', 'lemma': 'clatter'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'voices': {'ru': 'голос', 'tg': 'овоз', 'lemma': 'voice'},
    'stressed': {'ru': 'напряжённые', 'tg': 'шиддатнок', 'lemma': 'stressed'},
    'relaxed': {'ru': 'расслабленные', 'tg': 'ором', 'lemma': 'relaxed'},
    'nervous': {'ru': 'нервничающая', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'react': {'ru': 'реагировать', 'tg': 'вокуниш нишон додан', 'lemma': 'react'},
    'change': {'ru': 'изменение', 'tg': 'тағйирот', 'lemma': 'change'},
    'sounds': {'ru': 'звучать', 'tg': 'садо додан', 'lemma': 'sound'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'embarrassed': {'ru': 'смущённая', 'tg': 'хиҷолатманд', 'lemma': 'embarrassed'},
    'unexpected': {'ru': 'неожиданный', 'tg': 'ногаҳонӣ', 'lemma': 'unexpected'},
    'reactions': {'ru': 'реакция', 'tg': 'вокуниш', 'lemma': 'reaction'},
    'knew': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'truth': {'ru': 'правда', 'tg': 'ҳақиқат', 'lemma': 'truth'},
    'somehow': {'ru': 'каким-то образом', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'disappointment': {'ru': 'разочарование', 'tg': 'ноумедӣ', 'lemma': 'disappointment'},
    'curious': {'ru': 'любопытный', 'tg': 'кунҷков', 'lemma': 'curious'},
    'appreciation': {'ru': 'признательность (оценка)', 'tg': 'қадрдонӣ', 'lemma': 'appreciation'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'wisely': {'ru': 'мудро', 'tg': 'оқилона', 'lemma': 'wisely'},
    'wrong': {'ru': 'неправильно', 'tg': 'нодуруст', 'lemma': 'wrong'},
    'simply2': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'feels': {'ru': 'казаться (чувствоваться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'}, 'had': HAVE, 'she\'d': HAVE, 'everyone\'s': BE,
},
150: {
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'hill': {'ru': 'холм', 'tg': 'теппа', 'lemma': 'hill'},
    'built': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'wealthy': {'ru': 'богатый', 'tg': 'сарватманд', 'lemma': 'wealthy'},
    'merchant': {'ru': 'купец', 'tg': 'тоҷир', 'lemma': 'merchant'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'completed': {'ru': 'завершать', 'tg': 'ба анҷом расондан', 'lemma': 'complete'},
    'windows': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'believed': {'ru': 'полагать', 'tg': 'гумон кардан', 'lemma': 'believe'},
    'imported': {'ru': 'импортировать', 'tg': 'ворид кардан', 'lemma': 'import'},
    'distant': {'ru': 'далёкий', 'tg': 'дур', 'lemma': 'distant'},
    'country': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'unusual': {'ru': 'необычный', 'tg': 'ғайриоддӣ', 'lemma': 'unusual'},
    'luxury': {'ru': 'роскошь', 'tg': 'айшу ишрат', 'lemma': 'luxury'},
    'such': {'ru': 'такой', 'tg': 'чунин', 'lemma': 'such'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'every': {'ru': 'каждые', 'tg': 'ҳар', 'lemma': 'every'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'roof': {'ru': 'крыша', 'tg': 'бом', 'lemma': 'roof'},
    'gets': {'ru': 'ремонтироваться (получать)', 'tg': 'таъмир мешавад', 'lemma': 'get repaired'},
    'repaired': {'ru': 'ремонтировать', 'tg': 'таъмир кардан', 'lemma': 'repair'},
    'same': {'ru': 'та же', 'tg': 'ҳамон', 'lemma': 'same'},
    'local': {'ru': 'местная', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'rumours': {'ru': 'слухи', 'tg': 'овозаҳо', 'lemma': 'rumour'},
    'surrounding': {'ru': 'окружающий', 'tg': 'иҳотакунанда', 'lemma': 'surrounding'},
    'properly': {'ru': 'толком', 'tg': 'дуруст', 'lemma': 'properly'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'thought': {'ru': 'полагать', 'tg': 'гумон кардан', 'lemma': 'think'},
    'fire': {'ru': 'пожар', 'tg': 'сӯхтор', 'lemma': 'fire'},
    'destroyed': {'ru': 'разрушать', 'tg': 'нобуд кардан', 'lemma': 'destroy'},
    'part': {'ru': 'часть', 'tg': 'қисм', 'lemma': 'part'},
    'original': {'ru': 'первоначальный', 'tg': 'аслӣ', 'lemma': 'original'},
    'structure': {'ru': 'строение (структура)', 'tg': 'сохтор', 'lemma': 'structure'},
    'decades': {'ru': 'десятилетие', 'tg': 'даҳсола', 'lemma': 'decade'},
    'records': {'ru': 'записи (документы)', 'tg': 'ҳуҷҷатҳо', 'lemma': 'record'},
    'period': {'ru': 'период', 'tg': 'давра', 'lemma': 'period'},
    'reportedly': {'ru': 'по слухам', 'tg': 'гуфта мешавад', 'lemma': 'reportedly'},
    'lost': {'ru': 'теряться', 'tg': 'гум шудан', 'lemma': 'lose'},
    'local2': {'ru': 'местные', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'told': {'ru': 'говорить (рассказывать)', 'tg': 'гуфтан', 'lemma': 'tell'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'designed': {'ru': 'проектировать', 'tg': 'тарҳрезӣ кардан', 'lemma': 'design'},
    'disappeared': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'disappear'},
    'mysteriously': {'ru': 'таинственно', 'tg': 'сирри', 'lemma': 'mysteriously'},
    'confirm': {'ru': 'подтверждать', 'tg': 'тасдиқ кардан', 'lemma': 'confirm'},
    'originated': {'ru': 'зарождаться (происходить)', 'tg': 'сарчашма гирифтан', 'lemma': 'originate'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'gate': {'ru': 'ворота', 'tg': 'дарвоза', 'lemma': 'gate'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'fixed': {'ru': 'чинить', 'tg': 'таъмир кардан', 'lemma': 'fix'},
    'broken': {'ru': 'сломанный', 'tg': 'вайроншуда', 'lemma': 'broken'},
    'long': {'ru': 'так долго', 'tg': 'дароз', 'lemma': 'long'},
    'residents': {'ru': 'жители', 'tg': 'сокинон', 'lemma': 'resident'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'rumoured': {'ru': 'ходят слухи', 'tg': 'овоза шудааст', 'lemma': 'rumoured'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'sold': {'ru': 'продавать', 'tg': 'фурӯхтан', 'lemma': 'sell'},
    'apparently': {'ru': 'по-видимому', 'tg': 'зоҳиран', 'lemma': 'apparently'},
    'repeated': {'ru': 'повторять', 'tg': 'такрор кардан', 'lemma': 'repeat'},
    'decade': {'ru': 'десятилетие', 'tg': 'даҳсола', 'lemma': 'decade'},
    'current': {'ru': 'нынешний', 'tg': 'ҳозира', 'lemma': 'current'},
    'owner': {'ru': 'владелец', 'tg': 'соҳиб', 'lemma': 'owner'},
    'elderly': {'ru': 'пожилая', 'tg': 'солхӯрда', 'lemma': 'elderly'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'interior': {'ru': 'интерьер', 'tg': 'дохилӣ', 'lemma': 'interior'},
    'renovated': {'ru': 'ремонтировать', 'tg': 'таъмир кардан', 'lemma': 'renovate'},
    'refuses': {'ru': 'отказываться', 'tg': 'рад кардан', 'lemma': 'refuse'},
    'discuss': {'ru': 'обсуждать', 'tg': 'муҳокима кардан', 'lemma': 'discuss'},
    'neglected': {'ru': 'запущенный (заброшенный)', 'tg': 'партофташуда', 'lemma': 'neglect'},
    'beforehand': {'ru': 'заранее', 'tg': 'пешакӣ', 'lemma': 'beforehand'},
    'whatever': {'ru': 'что бы ни', 'tg': 'ҳар чи', 'lemma': 'whatever'},
    'happened': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'generations': {'ru': 'поколение', 'tg': 'насл', 'lemma': 'generation'},
    'spoken': {'ru': 'говорить (о ком-то)', 'tg': 'гап задан', 'lemma': 'speak of'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'revealing': {'ru': 'раскрывать', 'tg': 'ошкор кардан', 'lemma': 'reveal'},
    'much': {'ru': 'слишком много', 'tg': 'аз ҳад зиёд', 'lemma': 'much'},
    'somehow': {'ru': 'каким-то образом', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'disturb': {'ru': 'потревожить', 'tg': 'халалдор кардан', 'lemma': 'disturb'},
    'secret': {'ru': 'секрет', 'tg': 'сир', 'lemma': 'secret'},
    'hiding': {'ru': 'скрывать', 'tg': 'пинҳон кардан', 'lemma': 'hide'},
    'is': BE, 'has': HAVE, 'it\'s': BE, 'won\'t': HAVE,
},
151: {
    'meeting': {'ru': 'встреча (совещание)', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'marketing': {'ru': 'маркетинговый', 'tg': 'маркетингӣ', 'lemma': 'marketing'},
    'director': {'ru': 'директор', 'tg': 'директор', 'lemma': 'director'},
    'suggested': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'delaying': {'ru': 'откладывать', 'tg': 'ба таъхир андохтан', 'lemma': 'delay'},
    'product': {'ru': 'продукт', 'tg': 'маҳсулот', 'lemma': 'product'},
    'launch': {'ru': 'запуск', 'tg': 'оғоз', 'lemma': 'launch'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'sales': {'ru': 'продажи (отдел продаж)', 'tg': 'фурӯш', 'lemma': 'sales'},
    'team': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'strongly': {'ru': 'решительно', 'tg': 'қатъиян', 'lemma': 'strongly'},
    'disagreed': {'ru': 'не соглашаться', 'tg': 'розӣ набудан', 'lemma': 'disagree'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'underestimating': {'ru': 'недооценивать', 'tg': 'кам баҳо додан', 'lemma': 'underestimate'},
    'testing': {'ru': 'тестирование', 'tg': 'санҷиш', 'lemma': 'testing'},
    'phase': {'ru': 'этап (фаза)', 'tg': 'марҳила', 'lemma': 'phase'},
    'take': {'ru': 'занять (время)', 'tg': 'вақт гирифтан', 'lemma': 'take'},
    'surprised': {'ru': 'удивлять', 'tg': 'ҳайрон кардан', 'lemma': 'surprise'},
    'several': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'several'},
    'colleagues': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'raised': {'ru': 'поднимать (озвучивать)', 'tg': 'бардоштан', 'lemma': 'raise'},
    'same': {'ru': 'то же', 'tg': 'ҳамон', 'lemma': 'same'},
    'concern': {'ru': 'опасение', 'tg': 'нигаронӣ', 'lemma': 'concern'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'earlier': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'earlier'},
    'finance': {'ru': 'финансовый', 'tg': 'молиявӣ', 'lemma': 'finance'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'warned': {'ru': 'предупреждать', 'tg': 'огоҳ кардан', 'lemma': 'warn'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'promises': {'ru': 'обещание', 'tg': 'ваъда', 'lemma': 'promise'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'realistically': {'ru': 'реально', 'tg': 'воқеъбинона', 'lemma': 'realistically'},
    'keep': {'ru': 'выполнять (держать)', 'tg': 'риоя кардан', 'lemma': 'keep'},
    'tone': {'ru': 'тон', 'tg': 'оҳанг', 'lemma': 'tone'},
    'noticeably': {'ru': 'заметно', 'tg': 'намоён', 'lemma': 'noticeably'},
    'sharper': {'ru': 'резче', 'tg': 'тезтар', 'lemma': 'sharp'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'insisted': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'original': {'ru': 'первоначальный', 'tg': 'аслӣ', 'lemma': 'original'},
    'deadline': {'ru': 'срок', 'tg': 'мӯҳлат', 'lemma': 'deadline'},
    'remained': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'achievable': {'ru': 'достижимый', 'tg': 'дастрас', 'lemma': 'achievable'},
    'refusing': {'ru': 'отказываться', 'tg': 'рад кардан', 'lemma': 'refuse'},
    'accept': {'ru': 'принимать', 'tg': 'қабул кардан', 'lemma': 'accept'},
    'further': {'ru': 'дальнейшую', 'tg': 'минбаъда', 'lemma': 'further'},
    'delay': {'ru': 'задержка', 'tg': 'таъхир', 'lemma': 'delay'},
    'denied': {'ru': 'отрицать', 'tg': 'инкор кардан', 'lemma': 'deny'},
    'ignoring': {'ru': 'игнорировать', 'tg': 'сарфи назар кардан', 'lemma': 'ignore'},
    'earlier2': {'ru': 'ранние', 'tg': 'пешина', 'lemma': 'earlier'},
    'warnings': {'ru': 'предупреждение', 'tg': 'огоҳинома', 'lemma': 'warning'},
    'own': {'ru': 'собственные', 'tg': 'худи', 'lemma': 'own'},
    'notes': {'ru': 'записи', 'tg': 'қайдҳо', 'lemma': 'note'},
    'previous': {'ru': 'предыдущий', 'tg': 'гузашта', 'lemma': 'previous'},
    'meetings': {'ru': 'встреча', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'otherwise': {'ru': 'обратное', 'tg': 'баръакс', 'lemma': 'otherwise'},
    'assistant': {'ru': 'помощник', 'tg': 'ёрдамчӣ', 'lemma': 'assistant'},
    'advised': {'ru': 'советовать', 'tg': 'маслиҳат додан', 'lemma': 'advise'},
    'acknowledge': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'acknowledge'},
    'mistake': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'openly': {'ru': 'открыто', 'tg': 'ошкоро', 'lemma': 'openly'},
    'rather': {'ru': 'а не', 'tg': 'ба ҷои', 'lemma': 'rather than'},
    'continuing': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'deny': {'ru': 'отрицать', 'tg': 'инкор кардан', 'lemma': 'deny'},
    'defensively': {'ru': 'оборонительно (защищаясь)', 'tg': 'дифоъкорона', 'lemma': 'defensively'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'making': {'ru': 'совершать', 'tg': 'кардан', 'lemma': 'make'},
    'error': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'error'},
    'timeline': {'ru': 'график (сроки)', 'tg': 'ҷадвали вақт', 'lemma': 'timeline'},
    'rare': {'ru': 'редкий', 'tg': 'нодир', 'lemma': 'rare'},
    'uncomfortable': {'ru': 'неловкий', 'tg': 'ноороҳат', 'lemma': 'uncomfortable'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'lead': {'ru': 'ведущий (главный)', 'tg': 'асосӣ', 'lemma': 'lead'},
    'compromising': {'ru': 'идти на компромисс', 'tg': 'мувофиқа кардан', 'lemma': 'compromise'},
    'slightly': {'ru': 'немного', 'tg': 'андак', 'lemma': 'slightly'},
    'later': {'ru': 'более поздняя', 'tg': 'дертар', 'lemma': 'later'},
    'date': {'ru': 'дата', 'tg': 'сана', 'lemma': 'date'},
    'satisfied': {'ru': 'удовлетворять', 'tg': 'қаноатманд кардан', 'lemma': 'satisfy'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'urgency': {'ru': 'срочность', 'tg': 'таъҷилӣ', 'lemma': 'urgency'},
    'realistic': {'ru': 'реалистичный', 'tg': 'воқеъбинона', 'lemma': 'realistic'},
    'needs': {'ru': 'потребности', 'tg': 'ниёзҳо', 'lemma': 'need'},
    'reluctantly': {'ru': 'неохотно', 'tg': 'бо дилу нохоҳам', 'lemma': 'reluctantly'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'tolerated': {'ru': 'допускать (терпеть)', 'tg': 'таҳаммул кардан', 'lemma': 'tolerate'},
    'afterwards': {'ru': 'после этого', 'tg': 'баъдтар', 'lemma': 'afterwards'},
    'privately': {'ru': 'лично (наедине)', 'tg': 'шахсан', 'lemma': 'privately'},
    'respected': {'ru': 'уважать', 'tg': 'эҳтиром кардан', 'lemma': 'respect'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'acknowledging': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'acknowledge'},
    'denying': {'ru': 'отрицать', 'tg': 'инкор кардан', 'lemma': 'deny'},
    'remarked': {'ru': 'заметить (сказать)', 'tg': 'қайд кардан', 'lemma': 'remark'},
    'fault': {'ru': 'вина', 'tg': 'айб', 'lemma': 'fault'},
    'turns': {'ru': 'оказываться', 'tg': 'баромадан', 'lemma': 'turn out'},
    'persuasive': {'ru': 'убедительный', 'tg': 'қобили бовар', 'lemma': 'persuasive'},
    'denial': {'ru': 'отрицание', 'tg': 'инкор', 'lemma': 'denial'},
    'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистанд', 'lemma': 'can'}, 'who\'d': HAVE, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'he\'d': DO,
},
}

for sid, keys in {148: ['entirely2', 'checked2'], 149: ['simply2'], 150: ['local2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
