import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.db.database import AsyncSessionLocal
from app.models.model_content import StoryQuestions

Q = {
    136: [
        ("What is the journalist's final question?", 'Какой финальный вопрос задаёт журналистка?', 'Саволи ниҳоии рӯзноманигор чист?',
         ['Who will be held accountable if it fails?', 'Who approved the budget?', 'When will the project finish?'], 'Who will be held accountable if it fails?',
         "Her final, direct question is 'Who will be held accountable if this fails?'", 'Её финальный прямой вопрос: «Кто будет нести ответственность, если это провалится?»', 'Саволи охирини рӯшани ӯ: «Агар ноком шавад, кӣ ҷавобгар мешавад?»'),
        ('Does the minister answer directly?', 'Отвечает ли министр прямо?', 'Оё вазир мустақим ҷавоб медиҳад?',
         ['No, he avoids answering', 'Yes, immediately', 'He answers with a joke'], 'No, he avoids answering',
         'The minister is evasive and admits nobody had really considered the question.', 'Министр уклоняется от ответа и признаёт, что этот вопрос никто толком не рассматривал.', 'Вазир аз ҷавоб саркашӣ мекунад ва эътироф мекунад, ки ин саволро ҳеҷ кас ҷиддӣ баррасӣ накардааст.'),
        ('What does the journalist realize afterwards?', 'Что журналистка понимает потом?', 'Рӯзноманигор баъдтар чиро мефаҳмад?',
         ['The most revealing answer came from what he had not said', 'The minister lied about everything', 'The interview was cancelled'], 'The most revealing answer came from what he had not said',
         'She realizes his silence and avoidance revealed more than his actual answers.', 'Она понимает, что его молчание и уклончивость сказали больше, чем его настоящие ответы.', 'Вай мефаҳмад, ки хомӯшӣ ва саркашии ӯ бештар аз ҷавобҳои воқеиаш гуфт.'),
    ],
    137: [
        ('What did the argument start about?', 'С чего начался спор?', 'Баҳс аз чӣ сар шуд?',
         ['Whose turn it was to host Sunday lunch', 'Who broke a plate', 'Who was late'], 'Whose turn it was to host Sunday lunch',
         'The disagreement started small, about whose turn it was to host Sunday lunch.', 'Разногласие началось с мелочи — чья очередь принимать воскресный обед.', 'Ихтилоф аз чизи хурд сар шуд — навбати кӣ будани хӯроки нисфирӯзии якшанбе.'),
        ('Who interrupts to calm them down?', 'Кто вмешивается, чтобы их успокоить?', 'Барои ором кардани онҳо кӣ дахолат мекунад?',
         ['Their mother', 'Their father', 'A neighbour'], 'Their mother',
         'Their mother interrupts calmly to stop the argument.', 'Их мать спокойно вмешивается, чтобы остановить спор.', 'Модарашон бо оромӣ дахолат мекунад, то баҳсро бас кунад.'),
        ('What do they agree to do next time?', 'О чём они договариваются на следующий раз?', 'Онҳо барои дафъаи оянда дар бораи чӣ мувофиқа мекунанд?',
         ['Host together', 'Not have Sunday lunch anymore', 'Ask their mother to host'], 'Host together',
         'They agree to host Sunday lunch together next time.', 'Они договариваются вместе принимать воскресный обед в следующий раз.', 'Онҳо мувофиқа мекунанд, ки дафъаи оянда якҷоя мизбонӣ кунанд.'),
    ],
    138: [
        ('What is the narrator recovering from?', 'От чего восстанавливается рассказчик?', 'Ровӣ пас аз чӣ сиҳат меёбад?',
         ['Knee surgery', 'A broken arm', 'A car accident'], 'Knee surgery',
         "The narrator has been recovering from knee surgery for almost two months.", 'Рассказчик восстанавливается после операции на колене почти два месяца.', 'Ровӣ пас аз ҷарроҳии зону қариб ду моҳ сиҳат ёфта истодааст.'),
        ('How long has recovery taken so far?', 'Сколько времени заняло восстановление на данный момент?', 'Сиҳатёбӣ то ҳол чанд вақтро гирифт?',
         ['Almost two months', 'A week', 'A year'], 'Almost two months',
         'The recovery has taken almost two months so far.', 'На данный момент восстановление заняло почти два месяца.', 'Сиҳатёбӣ то ҳол қариб ду моҳро гирифт.'),
        ('What milestone happens this morning?', 'Какое достижение происходит этим утром?', 'Имрӯз субҳ кадом дастовард рӯй медиҳад?',
         ['Walking to the shop without crutches', 'Running a full kilometre', 'Climbing a mountain'], 'Walking to the shop without crutches',
         'For the first time, the narrator walks to the corner shop without crutches.', 'Впервые рассказчик идёт до углового магазина без костылей.', 'Бори аввал ровӣ бе асо то мағозаи гӯшагӣ пиёда меравад.'),
    ],
    139: [
        ('Who does the charity gala support?', 'Кого поддерживает благотворительный вечер?', 'Шоми хайрия киро дастгирӣ мекунад?',
         ['The elderly and the homeless', 'Sick children', 'Students'], 'The elderly and the homeless',
         'The gala focused on supporting the elderly and the homeless across the city.', 'Вечер был посвящён поддержке пожилых людей и бездомных по всему городу.', 'Шом ба дастгирии пиронсолон ва бехонумонҳо дар саросари шаҳр бахшида шуд.'),
        ('What is on each table for donations?', 'Что стоит на каждом столе для пожертвований?', 'Барои хайрия дар ҳар миз чӣ гузошта шудааст?',
         ['A small wooden box', 'A glass jar', 'An envelope'], 'A small wooden box',
         'On each table sat a small antique wooden box for donations.', 'На каждом столе стояла маленькая старинная деревянная коробка для пожертвований.', 'Дар ҳар миз қуттии хурди чӯбини кӯҳна барои хайрия гузошта шуда буд.'),
        ('What does the organiser say about the unemployed?', 'Что организатор говорит о безработных?', 'Ташкилотчӣ дар бораи бекорон чӣ мегӯяд?',
         ["They aren't lazy, they're unlucky", 'They should try harder', 'They need more training'], "They aren't lazy, they're unlucky",
         "She reminds the room 'The unemployed aren't lazy, they're simply unlucky.'", 'Она напоминает залу: «Безработные не ленивы, им просто не повезло».', 'Вай ба ҳозирон мегӯяд: «Бекорон танбал нестанд, онҳо танҳо бахташон наомадааст».'),
    ],
    140: [
        ('How long had they already been travelling when the flight was cancelled?', 'Сколько времени они уже путешествовали, когда рейс отменили?', 'Вақте ки парвоз бекор шуд, онҳо аллакай чанд вақт сафар мекарданд?',
         ['Fourteen hours', 'Five hours', 'Two days'], 'Fourteen hours',
         'They had already been travelling for fourteen hours straight.', 'Они уже путешествовали четырнадцать часов без остановки.', 'Онҳо аллакай чордаҳ соат бефосила сафар мекарданд.'),
        ('How long had they been sitting at the gate before the announcement?', 'Сколько они сидели у выхода на посадку до объявления?', 'Онҳо то эълон назди дар чанд вақт нишастанд?',
         ['Nearly three hours', 'Thirty minutes', 'Five hours'], 'Nearly three hours',
         'They had been sitting at the gate for nearly three hours when the announcement came.', 'Они сидели у выхода почти три часа, когда прозвучало объявление.', 'Онҳо назди дар қариб се соат нишаста буданд, вақте ки эълон садо дод.'),
        ('What happened to the children before takeoff on the new flight?', 'Что случилось с детьми перед взлётом нового рейса?', 'Пеш аз парвози нав ба фарзандон чӣ шуд?',
         ['They fell asleep', 'They started crying', 'They felt sick'], 'They fell asleep',
         'The children had fallen asleep before takeoff, exhausted from the wait.', 'Дети уснули перед взлётом, измученные ожиданием.', 'Кӯдакон пеш аз парвоз аз хастагии интизорӣ хоб рафтанд.'),
    ],
    141: [
        ('What does the colleague suggest before answering questions?', 'Что коллега советует перед ответом на вопросы?', 'Ҳамкор пеш аз ҷавоб додан ба саволҳо чӣ маслиҳат медиҳад?',
         ['Pause briefly', 'Answer immediately', 'Skip difficult questions'], 'Pause briefly',
         'He suggests she pause briefly before answering anticipated questions.', 'Он советует ей ненадолго остановиться, прежде чем отвечать на ожидаемые вопросы.', 'Ӯ маслиҳат медиҳад, ки пеш аз ҷавоб додан ба саволҳои интизорӣ каме таваққуф кунад.'),
        ('How many times had she rehearsed before this?', 'Сколько раз она репетировала до этого?', 'Ӯ то ин пеш чанд маротиба машқ карда буд?',
         ['More than a dozen times', 'Twice', 'Never'], 'More than a dozen times',
         'She had definitely rehearsed the presentation more than a dozen times.', 'Она точно репетировала презентацию больше дюжины раз.', 'Вай мутмаин пешниҳодро зиёда аз даҳ маротиба машқ карда буд.'),
        ('What did her manager say afterwards?', 'Что сказал её руководитель потом?', 'Раҳбараш баъдтар чӣ гуфт?',
         ['It was the clearest presentation of the year', 'It needed more work', 'It was too long'], 'It was the clearest presentation of the year',
         'Her manager admitted it had been the clearest presentation the department had seen all year.', 'Её руководитель признал, что это была самая ясная презентация за весь год.', 'Раҳбараш эътироф кард, ки ин равшантарин пешниҳод дар тамоми сол буд.'),
    ],
    142: [
        ('How many trees will volunteers have planted by next autumn?', 'Сколько деревьев волонтёры высадят к следующей осени?', 'Волонтёрҳо то тирамоҳи оянда чанд дарахт мешинонанд?',
         ['Over ten thousand', 'One thousand', 'A hundred'], 'Over ten thousand',
         'By next autumn, volunteers will have planted over ten thousand young trees.', 'К следующей осени волонтёры высадят более десяти тысяч молодых деревьев.', 'То тирамоҳи оянда волонтёрҳо зиёда аз даҳ ҳазор ниҳоли ҷавон мешинонанд.'),
        ('What year do scientists predict the hillside will have recovered?', 'К какому году, по прогнозам учёных, склон восстановится?', 'Олимон пешбинӣ мекунанд, ки шеваи кӯҳ то кадом сол барқарор мешавад?',
         ['2040', '2030', '2050'], '2040',
         'By 2040, scientists predict the hillside will have recovered.', 'К 2040 году, по прогнозам учёных, склон восстановится.', 'То соли 2040, тибқи пешбинии олимон, шева барқарор мешавад.'),
        ('Who has adopted individual trees?', 'Кто взял индивидуальные деревья под опеку?', 'Дарахтони алоҳидаро кӣ ба сарпарастӣ гирифтааст?',
         ['Local schoolchildren', 'The government', 'Tourists'], 'Local schoolchildren',
         'Local schoolchildren have adopted individual trees and promised to track their progress.', 'Местные школьники взяли отдельные деревья под опеку и обещали следить за их ростом.', 'Хонандагони мактабҳои маҳаллӣ дарахтони алоҳидаро гирифта, пешрафти онҳоро пайгирӣ карданро ваъда доданд.'),
    ],
    143: [
        ('What does grandfather watch instead of a weather app?', 'За чем дедушка наблюдает вместо приложения погоды?', 'Бобо ба ҷои барномаи обу ҳаво ба чӣ нигоҳ мекунад?',
         ['Birds', 'The clouds only', 'The moon'], 'Birds',
         'He insists that watching the birds predicts the weather more accurately.', 'Он утверждает, что наблюдение за птицами точнее предсказывает погоду.', 'Ӯ таъкид мекунад, ки нигоҳ ба паррандаҳо обу ҳаворо дурусттар пешгӯӣ мекунад.'),
        ("What will happen if it doesn't rain by next week?", 'Что произойдёт, если к следующей неделе не пойдёт дождь?', 'Агар то ҳафтаи оянда борон наборад, чӣ мешавад?',
         ['They will lose half the wheat crop', 'Nothing will change', 'The harvest will improve'], 'They will lose half the wheat crop',
         "Grandfather warns 'we'll lose half the wheat crop' if it doesn't rain soon.", 'Дедушка предупреждает: «мы потеряем половину урожая пшеницы», если скоро не пойдёт дождь.', 'Бобо огоҳ мекунад: «нисфи ҳосили гандумро гум мекунем», агар зуд борон наборад.'),
        ('What do the family prepare when dark clouds appear?', 'Что готовит семья, когда появляются тёмные тучи?', 'Ҳангоми пайдо шудани абрҳои торик оила чиро тайёр мекунад?',
         ['The irrigation channels', 'The harvest tools', 'The storage barn'], 'The irrigation channels',
         'The family rushes to prepare the irrigation channels, just in case.', 'Семья спешит подготовить оросительные каналы на всякий случай.', 'Оила барои эҳтиёт каналҳои обёриро тайёр мекунад.'),
    ],
    144: [
        ('What did the narrator not accept fifteen years ago?', 'Что рассказчик не принял пятнадцать лет назад?', 'Ровӣ понздаҳ сол пеш чиро қабул накард?',
         ['A scholarship abroad', 'A job offer', 'A marriage proposal'], 'A scholarship abroad',
         'The narrator did not accept a scholarship abroad fifteen years ago.', 'Пятнадцать лет назад рассказчик не принял стипендию за рубежом.', 'Понздаҳ сол пеш ровӣ стипендияи хориҷиро қабул накард.'),
        ('What did the old classmate do instead?', 'Что сделала бывшая одноклассница вместо этого?', 'Ҳамсинфи собиқ ба ҷои ин чӣ кард?',
         ['Accepted a similar offer and moved abroad', 'Also stayed home', 'Became a teacher locally'], 'Accepted a similar offer and moved abroad',
         'The old classmate accepted a similar offer and now sends photos from conferences abroad.', 'Бывшая одноклассница приняла похожее предложение и теперь присылает фото с конференций за границей.', 'Ҳамсинфи собиқ пешниҳоди монандро қабул кард ва ҳоло аз конфронсҳои хориҷӣ акс мефиристад.'),
        ('What does the narrator have that they might not have if they had chosen differently?', 'Что есть у рассказчика, чего могло бы не быть при другом выборе?', 'Агар интихоби дигар мекард, ровӣ чиро надошт?',
         ['Two children', 'A big house', 'Fluency in three languages'], 'Two children',
         'The narrator has two children they cannot imagine life without.', 'У рассказчика есть двое детей, без которых он не представляет жизни.', 'Ровӣ ду фарзанд дорад, ки бе онҳо ҳаётро тасаввур карда наметавонад.'),
    ],
    145: [
        ('Who does the narrator wish they had kept in touch with?', 'С кем рассказчик хотел бы поддерживать связь?', 'Ровӣ мехост, ки бо кӣ алоқаро нигоҳ медошт?',
         ['Their closest friend from university', 'A cousin', 'A former teacher'], 'Their closest friend from university',
         'The narrator wishes they had kept in touch with their closest university friend.', 'Рассказчик хотел бы поддерживать связь со своим самым близким другом из университета.', 'Ровӣ мехост, ки бо наздиктарин дӯсти донишгоҳиаш алоқаро нигоҳ медошт.'),
        ('When was the last message sent?', 'Когда было отправлено последнее сообщение?', 'Паёми охирин кай фиристода шуд?',
         ['Almost a year ago', 'Last week', 'Five years ago'], 'Almost a year ago',
         'The last message was sent almost a year ago.', 'Последнее сообщение было отправлено почти год назад.', 'Паёми охирин қариб як сол пеш фиристода шуда буд.'),
        ("What is the sister's biggest regret?", 'О чём больше всего жалеет сестра?', 'Хоҳар аз чӣ бештар афсӯс мехӯрад?',
         ['Not learning a second language properly', 'Not travelling more', 'Not studying harder'], 'Not learning a second language properly',
         "The sister's biggest regret is giving up on learning a second language.", 'Самое большое сожаление сестры — что она бросила изучение второго языка.', 'Афсӯси калонтарини хоҳар — тарк кардани омӯзиши забони дуюм аст.'),
    ],
    146: [
        ('What did the narrator used to panic about in supermarkets?', 'Из-за чего рассказчик раньше паниковал в супермаркетах?', 'Ровӣ пештар дар мағозаҳо аз чӣ ба ҳарос меафтод?',
         ['Unfamiliar packaging', 'High prices', 'Long queues'], 'Unfamiliar packaging',
         'The narrator used to panic in supermarkets, overwhelmed by unfamiliar packaging.', 'Рассказчик раньше паниковал в супермаркетах, ошеломлённый незнакомой упаковкой.', 'Ровӣ пештар дар мағозаҳо аз бастабандии ношинос ба ҳарос меафтод.'),
        ('How often does the narrator call home now compared to before?', 'Как часто рассказчик звонит домой сейчас по сравнению с раньше?', 'Ровӣ ҳоло нисбат ба пештар чанд вақт як маротиба ба хона занг мезанад?',
         ['Weekly now, used to be daily', 'Daily now, used to be weekly', 'Never now, used to be daily'], 'Weekly now, used to be daily',
         'The narrator used to call every day, but now calls weekly.', 'Рассказчик раньше звонил каждый день, а теперь звонит раз в неделю.', 'Ровӣ пештар ҳар рӯз занг мезад, ҳоло ҳар ҳафта занг мезанад.'),
        ('What does the neighbour say about getting used to a new place?', 'Что сосед говорит о привыкании к новому месту?', 'Ҳамсоя дар бораи одат кардан ба ҷои нав чӣ мегӯяд?',
         ['You never fully get used to everything, but the strange becomes ordinary', 'You get used to everything in a week', 'It never gets easier'], 'You never fully get used to everything, but the strange becomes ordinary',
         "She says 'You never fully get used to everything... but eventually the strange becomes ordinary.'", 'Она говорит: «Ко всему полностью не привыкнешь... но со временем странное становится обычным».', 'Вай мегӯяд: «Ба ҳама чиз пурра одат намекунӣ... вале дар ниҳоят аҷиб оддӣ мешавад».'),
    ],
    147: [
        ('What does the new colleague ask for help with?', 'С чем новая коллега просит помочь?', 'Ҳамкори нав дар кадом кор кӯмак мехоҳад?',
         ['The filing system', 'Her computer password', 'The office phone'], 'The filing system',
         'She asks for help understanding the filing system.', 'Она просит помочь разобраться в системе учёта документов.', 'Вай дар фаҳмидани системаи бойгонӣ кӯмак металабад.'),
        ('What does the narrator remind her to do?', 'О чём рассказчик напоминает ей?', 'Ровӣ ба вай чиро ёдоварӣ мекунад?',
         ['Save a backup copy', 'Ask the manager first', 'Print everything'], 'Save a backup copy',
         "The narrator reminds her 'Remember to save a backup copy,' recalling their own mistake.", 'Рассказчик напоминает: «Не забудь сохранить резервную копию», вспоминая свою собственную ошибку.', 'Ровӣ ёдоварӣ мекунад: «Нусхаи эҳтиётиро сабт кардан фаромӯш накун», ба ёди хатогии худ.'),
        ('What does the narrator overhear later?', 'Что рассказчик слышит позже?', 'Ровӣ баъдтар чиро мешунавад?',
         ['The colleague teaching someone else the same system', 'The colleague complaining about the job', 'The colleague quitting'], 'The colleague teaching someone else the same system',
         'The narrator overhears the colleague patiently teaching someone else the exact same system.', 'Рассказчик слышит, как коллега терпеливо учит кого-то той же самой системе.', 'Ровӣ мешунавад, ки ҳамкор ба каси дигар ҳамон системаро бо сабр меомӯзонад.'),
    ],
    148: [
        ('What did the manager think happened to the signed document?', 'Что, по мнению менеджера, случилось с подписанным документом?', 'Менеҷер фикр мекард, ки ба ҳуҷҷати имзошуда чӣ шудааст?',
         ['Someone removed it deliberately', 'It was never signed', 'It was sent by post'], 'Someone removed it deliberately',
         'The manager insisted that someone must have removed it deliberately.', 'Менеджер настаивала, что кто-то намеренно убрал его.', 'Менеҷер таъкид кард, ки касе онро қасдан бардоштааст.'),
        ('Where was the document eventually found?', 'Где документ в итоге нашли?', 'Ҳуҷҷат дар ниҳоят дар куҷо ёфт шуд?',
         ["Filed under a different client's name", 'In the manager\'s bag', 'It was never found'], "Filed under a different client's name",
         'It was mistakenly filed under an entirely different client\'s name.', 'Он был по ошибке подшит под именем совершенно другого клиента.', 'Он ба хатогӣ ба номи мизоҷи тамоман дигар бойгонӣ шуда буд.'),
        ('What does the assistant admit?', 'В чём признаётся помощница?', 'Ёрдамчӣ чиро эътироф мекунад?',
         ['She should have double-checked the filing herself', 'She lost the document on purpose', 'She never saw the document'], 'She should have double-checked the filing herself',
         "The assistant admits 'I should have double-checked the filing myself.'", 'Помощница признаётся: «Мне следовало самой перепроверить документы».', 'Ёрдамчӣ эътироф мекунад: «Бояд худам бойгониро дубора месанҷидам».'),
    ],
    149: [
        ('What does grandmother think is missing from the soup?', 'Чего, по мнению бабушки, не хватает в супе?', 'Бибӣ фикр мекунад, ки дар шӯрбо чӣ намерасад?',
         ['Cumin', 'Salt', 'Pepper'], 'Cumin',
         "Grandmother suggests 'It tastes as though someone forgot the cumin.'", 'Бабушка предполагает: «На вкус как будто забыли зиру».', 'Бибӣ мегӯяд: «Мазаш чунин аст, ки гӯё зираро фаромӯш кардаанд».'),
        ('What does the chef eventually admit?', 'В чём в итоге признаётся повар?', 'Ошпаз дар ниҳоят чиро эътироф мекунад?',
         ['She tried a completely new recipe', 'She forgot to cook the soup', 'She used old ingredients'], 'She tried a completely new recipe',
         'The chef admits she tried a completely new recipe.', 'Повар признаётся, что попробовала совершенно новый рецепт.', 'Ошпаз эътироф мекунад, ки рецепти тамоман наверо санҷидааст.'),
        ('Does the soup taste better once they know the truth?', 'Становится ли суп вкуснее, когда они узнают правду?', 'Пас аз фаҳмидани ҳақиқат, оё шӯрбо болаззаттар мешавад?',
         ['Yes', 'No', "It stays the same"], 'Yes',
         'Once they know the truth, the soup somehow tastes better to them.', 'Как только они узнают правду, суп почему-то кажется им вкуснее.', 'Пас аз донистани ҳақиқат, шӯрбо ба назари онҳо болаззаттар менамояд.'),
    ],
    150: [
        ('Who is said to have built the house?', 'Кто, по слухам, построил дом?', 'Гуфта мешавад, ки хонаро кӣ сохтааст?',
         ['A wealthy merchant', 'A famous doctor', 'A local farmer'], 'A wealthy merchant',
         'It is said that the house was built by a wealthy merchant.', 'Говорят, что дом был построен богатым купцом.', 'Гуфта мешавад, ки хонаро тоҷири бой сохтааст.'),
        ('What are the windows believed to have been?', 'Чем, как полагают, были окна?', 'Тирезаҳо гумон меравад, ки чӣ будаанд?',
         ['Imported from a distant country', 'Made locally by hand', 'Added recently'], 'Imported from a distant country',
         'The windows are believed to have been imported from a distant country.', 'Считается, что окна были привезены из далёкой страны.', 'Гумон меравад, ки тирезаҳо аз кишвари дур оварда шудаанд.'),
        ('What happened to the gate last year?', 'Что случилось с воротами в прошлом году?', 'Соли гузашта ба дарвоза чӣ шуд?',
         ['It was finally fixed', 'It was removed', 'It burned down'], 'It was finally fixed',
         'Last year, the gate was finally fixed after being broken for years.', 'В прошлом году ворота наконец починили после многих лет поломки.', 'Соли гузашта дарвоза пас аз солҳои вайроншавӣ ниҳоят таъмир шуд.'),
    ],
    151: [
        ('What did the marketing director suggest?', 'Что предложил директор по маркетингу?', 'Директори маркетинг чӣ пешниҳод кард?',
         ['Delaying the product launch', 'Cancelling the product', 'Doubling the budget'], 'Delaying the product launch',
         'The marketing director suggested delaying the product launch.', 'Директор по маркетингу предложил отложить запуск продукта.', 'Директори маркетинг ба таъхир андохтани оғози маҳсулотро пешниҳод кард.'),
        ('What does he eventually admit?', 'В чём он в итоге признаётся?', 'Ӯ дар ниҳоят чиро эътироф мекунад?',
         ['Making an error in the original timeline', 'Lying to the team', 'Missing the meeting'], 'Making an error in the original timeline',
         'He eventually admits making an error in the original timeline.', 'В итоге он признаётся, что допустил ошибку в первоначальном графике.', 'Ӯ дар ниҳоят эътироф мекунад, ки дар ҷадвали аввалия хато кардааст.'),
        ('What does the sales lead suggest?', 'Что предлагает руководитель отдела продаж?', 'Роҳбари фурӯш чӣ пешниҳод мекунад?',
         ['Compromising on a slightly later date', 'Keeping the original date', 'Launching immediately'], 'Compromising on a slightly later date',
         'The sales lead suggests compromising on a slightly later date.', 'Руководитель отдела продаж предлагает компромисс — немного более позднюю дату.', 'Роҳбари фурӯш созишро дар санаи каме дертар пешниҳод мекунад.'),
    ],
    152: [
        ('What did the bookshop owner start to attract customers?', 'Что начала владелица книжного магазина, чтобы привлечь покупателей?', 'Соҳиби мағозаи китоб барои ҷалби мизоҷон чиро сар кард?',
         ['A small reading club', 'A discount programme', 'A book delivery service'], 'A small reading club',
         'She started a small reading club so regular customers would return weekly.', 'Она открыла небольшой книжный клуб, чтобы постоянные клиенты возвращались каждую неделю.', 'Вай клуби хурди хониш кушод, то мизоҷони доимӣ ҳар ҳафта баргарданд.'),
        ('What is she now planning to add?', 'Что она сейчас планирует добавить?', 'Вай ҳоло чиро илова карданӣ аст?',
         ['A small café corner', 'A second shop', 'An online store'], 'A small café corner',
         'She is now planning a small café corner so customers linger longer.', 'Сейчас она планирует небольшой уголок кафе, чтобы клиенты задерживались дольше.', 'Вай ҳоло гӯшаи хурди кафе нақша мегирад, то мизоҷон дертар бимонанд.'),
        ('Why do locals keep choosing the shop over online retailers?', 'Почему местные жители продолжают выбирать магазин, а не онлайн-продавцов?', 'Сокинони маҳаллӣ чаро мағозаро аз фурӯшандагони онлайн авло медонанд?',
         ['They value her personal recommendations', 'The shop is cheaper', 'They dislike the internet'], 'They value her personal recommendations',
         'Locals value the personal recommendations she gives so generously.', 'Местные жители ценят её щедрые личные рекомендации.', 'Сокинони маҳаллӣ тавсияҳои шахсии саховатманди вайро қадр мекунанд.'),
    ],
    153: [
        ('Who do they call for advice about the move?', 'Кому они звонят за советом по переезду?', 'Онҳо барои маслиҳат оид ба кӯчиш ба кӣ занг мезананд?',
         ['Their aunt', 'A moving company', 'A friend'], 'Their aunt',
         "They call the narrator's aunt, who has moved houses many times.", 'Они звонят тёте рассказчика, которая много раз переезжала.', 'Онҳо ба холаи ровӣ занг мезананд, ки борҳо кӯчидааст.'),
        ('What advice does the narrator find online?', 'Какой совет рассказчик находит в интернете?', 'Ровӣ дар интернет кадом маслиҳатро меёбад?',
         ['Label boxes by room, not by category', 'Hire professional movers', 'Pack early'], 'Label boxes by room, not by category',
         'The narrator finds advice to label boxes by room, not by category.', 'Рассказчик находит совет подписывать коробки по комнатам, а не по категориям.', 'Ровӣ маслиҳат меёбад, ки қуттиҳоро на аз рӯи навъ, балки аз рӯи утоқ нишона гузорад.'),
        ('What arrives a day early, causing panic?', 'Что приезжает на день раньше, вызывая панику?', 'Кадом чиз як рӯз пеш омада, изтиробро ба вуҷуд меорад?',
         ['The removal van', 'The new furniture', 'Their relatives'], 'The removal van',
         'The news that the removal van would arrive a day early causes panic.', 'Новость о том, что фургон для переезда приедет на день раньше, вызывает панику.', 'Хабари он ки мошини кӯчонӣ як рӯз пеш меояд, изтиробро ба вуҷуд меорад.'),
    ],
    154: [
        ('What competition do both bakeries have every year?', 'В каком конкурсе участвуют обе пекарни каждый год?', 'Ҳар ду нонвойхона ҳар сол дар кадом мусобиқа иштирок мекунанд?',
         ['Baking the most impressive bread', 'Selling the most bread', 'Making the cheapest bread'], 'Baking the most impressive bread',
         'Both bakeries compete to bake the most impressive bread for the festival.', 'Обе пекарни соревнуются, чтобы испечь самый впечатляющий хлеб для фестиваля.', 'Ҳар ду нонвойхона барои пухтани нони аз ҳама беҳтарин барои идона рақобат мекунанд.'),
        ('What did the grandmothers used to compete over?', 'В чём соревновались бабушки раньше?', 'Бибиҳо пештар дар чӣ рақобат мекарданд?',
         ['Whose plov tasted better', 'Whose garden was bigger', 'Whose children were smarter'], 'Whose plov tasted better',
         "Both grandmothers used to compete fiercely over whose plov tasted better.", 'Обе бабушки яростно соревновались, чей плов вкуснее.', 'Ҳар ду бибӣ сахт рақобат мекарданд, ки палави кӣ бомазатар аст.'),
        ('What happens every year without exception?', 'Что происходит каждый год без исключения?', 'Ҳар сол бидуни истисно чӣ рӯй медиҳад?',
         ['Someone forgets to bring chairs', 'It rains', 'The festival is cancelled'], 'Someone forgets to bring chairs',
         'Every year, without exception, someone forgets to bring chairs.', 'Каждый год, без исключения, кто-то забывает принести стулья.', 'Ҳар сол, бидуни истисно, касе аз овардани курсиҳо фаромӯш мекунад.'),
    ],
    155: [
        ('What did archaeologists announce discovering?', 'О каком открытии объявили археологи?', 'Бостоншиносон дар бораи кадом кашфиёт эълон карданд?',
         ['The oldest tool ever found in the region', 'An ancient city', 'A new species of animal'], 'The oldest tool ever found in the region',
         'Archaeologists announced discovering what may be the oldest tool ever found in the region.', 'Археологи объявили об открытии, возможно, самого древнего орудия, найденного в регионе.', 'Бостоншиносон дар бораи кашфи эҳтимолан қадимтарин асбоби дар минтақа ёфтшуда эълон карданд.'),
        ('How often do scientists travel to the site?', 'Как часто учёные ездят на место раскопок?', 'Олимон ба маҳали кофтуков чанд вақт як маротиба мераванд?',
         ['Twice a year', 'Every month', 'Once'], 'Twice a year',
         'Scientists travel to the site twice a year to document new layers.', 'Учёные приезжают на объект дважды в год, чтобы документировать новые слои.', 'Олимон ду маротиба дар як сол ба маҳал рафта, қабатҳои навро сабт мекунанд.'),
        ('What has the internet also spread about the tool?', 'Что интернет также распространил об орудии?', 'Интернет боз дар бораи асбоб чиро паҳн кардааст?',
         ['Inaccurate theories about its origin', 'Its exact price', 'Photos of the excavation team'], 'Inaccurate theories about its origin',
         'The internet has spread several inaccurate theories about the origin of the tool.', 'Интернет распространил несколько неточных теорий о происхождении орудия.', 'Интернет якчанд назарияи нодурустро дар бораи пайдоиши асбоб паҳн кардааст.'),
    ],
}


async def main():
    async with AsyncSessionLocal() as db:
        created = 0
        for story_id, questions in Q.items():
            for text_en, text_ru, text_tg, options, answer, expl_en, expl_ru, expl_tg in questions:
                db.add(StoryQuestions(
                    story_id=story_id,
                    text_en=text_en,
                    text_ru=text_ru,
                    text_tg=text_tg,
                    options=options,
                    answer=answer,
                    explanation_en=expl_en,
                    explanation_ru=expl_ru,
                    explanation_tg=expl_tg,
                ))
                created += 1
        await db.commit()
        print(f'created {created} story questions for {len(Q)} stories')


asyncio.run(main())
