# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
96: {
    'getting': {'ru': 'выходить (замуж)', 'tg': 'ба шавҳар баромадан', 'lemma': 'get married'},
    'married': {'ru': 'женатый (замужняя)', 'tg': 'оиладор', 'lemma': 'married'},
    'june': {'ru': 'июнь', 'tg': 'июн', 'lemma': 'June'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'planning': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'detail': {'ru': 'деталь', 'tg': 'тафсилот', 'lemma': 'detail'},
    'having': {'ru': 'проводить (иметь)', 'tg': 'баргузор кардан', 'lemma': 'have'},
    'ceremony': {'ru': 'церемония', 'tg': 'маросим', 'lemma': 'ceremony'},
    'grandmother\'s': {'ru': 'бабушкин', 'tg': 'аз они бибӣ', 'lemma': 'grandmother'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'tells': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'friend': {'ru': 'друг (подруга)', 'tg': 'дӯст', 'lemma': 'friend'},
    'showing': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'cousin': {'ru': 'двоюродная сестра', 'tg': 'амакбача', 'lemma': 'cousin'},
    'bringing': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'flowers': {'ru': 'цветы', 'tg': 'гул', 'lemma': 'flower'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'going': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
    'wear': {'ru': 'надевать (носить)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'mother\'s': {'ru': 'мамин', 'tg': 'аз они модар', 'lemma': 'mother'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'wedding': {'ru': 'свадьба (свадебный)', 'tg': 'туй', 'lemma': 'wedding'},
    'dress': {'ru': 'платье', 'tg': 'курта', 'lemma': 'dress'},
    'which': {'ru': 'которое', 'tg': 'ки', 'lemma': 'which'},
    'tailor': {'ru': 'портной', 'tg': 'дӯзанда', 'lemma': 'tailor'},
    'currently': {'ru': 'в настоящее время', 'tg': 'ҳоло', 'lemma': 'currently'},
    'altering': {'ru': 'переделывать', 'tg': 'тағир додан', 'lemma': 'alter'},
    'fiancé': {'ru': 'жених', 'tg': 'домоди оянда', 'lemma': 'fiancé'},
    'worried': {'ru': 'обеспокоенный', 'tg': 'нигарон', 'lemma': 'worried'},
    'simply': {'ru': 'просто', 'tg': 'танҳо', 'lemma': 'simply'},
    'trust': {'ru': 'доверять', 'tg': 'бовар кардан', 'lemma': 'trust'},
    'plans': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'meeting': {'ru': 'встречаться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'photographer': {'ru': 'фотограф', 'tg': 'аксбардор', 'lemma': 'photographer'},
    'thursday': {'ru': 'четверг', 'tg': 'панҷшанбе', 'lemma': 'Thursday'},
    'continues': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'choosing': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'menu': {'ru': 'меню', 'tg': 'меню', 'lemma': 'menu'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'nervous': {'ru': 'нервный', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'little': {'ru': 'немного', 'tg': 'андак', 'lemma': 'little'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'mostly': {'ru': 'в основном', 'tg': 'бештар', 'lemma': 'mostly'},
    'excited': {'ru': 'взволнованная (в предвкушении)', 'tg': 'хурсанду мунтазир', 'lemma': 'excited'},
    'invite': {'ru': 'приглашать', 'tg': 'даъват кардан', 'lemma': 'invite'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'hundred': {'ru': 'сто', 'tg': 'сад', 'lemma': 'hundred'},
    'guests': {'ru': 'гость', 'tg': 'меҳмон', 'lemma': 'guest'},
    'seems': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'weddings': {'ru': 'свадьба', 'tg': 'туй', 'lemma': 'wedding'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'huge': {'ru': 'огромный', 'tg': 'бузург', 'lemma': 'huge'},
    'picking': {'ru': 'забирать', 'tg': 'гирифтан', 'lemma': 'pick up'},
    'rings': {'ru': 'кольцо', 'tg': 'ангуштарин', 'lemma': 'ring'},
    'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'left': {'ru': 'оставшийся', 'tg': 'боқимонда', 'lemma': 'left'},
    'organize': {'ru': 'организовывать', 'tg': 'ташкил кардан', 'lemma': 'organize'},
    'except': {'ru': 'кроме', 'tg': 'ба ғайр аз', 'lemma': 'except'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'arrive': {'ru': 'наступать (прибывать)', 'tg': 'расидан', 'lemma': 'arrive'},
    'is': BE, 'she\'s': BE, 'isn\'t': BE, 'he\'s': BE, 'we\'re': BE, 'there\'s': BE,
},
97: {
    'looking': {'ru': 'искать', 'tg': 'ҷустуҷӯ кардан', 'lemma': 'look for'},
    'flat': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'flat'},
    'close': {'ru': 'близкий', 'tg': 'наздик', 'lemma': 'close'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'cost': {'ru': 'стоить', 'tg': 'арзидан', 'lemma': 'cost'},
    'too': {'ru': 'слишком', 'tg': 'аз ҳад зиёд', 'lemma': 'too'},
    'much': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'much'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'agent': {'ru': 'агент', 'tg': 'агент', 'lemma': 'agent'},
    'shown': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'apartments': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'apartment'},
    'calls': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'more': {'ru': 'ещё', 'tg': 'боз', 'lemma': 'more'},
    'option': {'ru': 'вариант', 'tg': 'варианти', 'lemma': 'option'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'balcony': {'ru': 'балкон', 'tg': 'балкон', 'lemma': 'balcony'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'just': {'ru': 'только что', 'tg': 'ҳозиргина', 'lemma': 'just'},
    'renovated': {'ru': 'отремонтированный', 'tg': 'таъмиршуда', 'lemma': 'renovate'},
    'explains': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'hates': {'ru': 'ненавидеть', 'tg': 'нафрат доштан', 'lemma': 'hate'},
    'wasting': {'ru': 'тратить впустую', 'tg': 'бекор сарф кардан', 'lemma': 'waste'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'agrees': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'see': {'ru': 'увидеть', 'tg': 'дидан', 'lemma': 'see'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'building': {'ru': 'здание', 'tg': 'бино', 'lemma': 'building'},
    'built': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'modern': {'ru': 'современный', 'tg': 'муосир', 'lemma': 'modern'},
    'clean': {'ru': 'чистый', 'tg': 'тоза', 'lemma': 'clean'},
    'inside': {'ru': 'внутри', 'tg': 'дарун', 'lemma': 'inside'},
    'meets': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'owner': {'ru': 'владелец', 'tg': 'соҳиб', 'lemma': 'owner'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'works': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'nearby': {'ru': 'поблизости', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'keep': {'ru': 'хранить', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'books': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'around': {'ru': 'вокруг', 'tg': 'атроф', 'lemma': 'around'},
    'likes': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'overlooks': {'ru': 'выходить (окнами) на', 'tg': 'рӯ ба рӯ будан', 'lemma': 'overlook'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'trees': {'ru': 'дерево', 'tg': 'дарахт', 'lemma': 'tree'},
    'going2': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'tells': {'ru': 'сказать (говорить)', 'tg': 'гуфтан', 'lemma': 'tell'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'answer': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'neighbours': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'briefly': {'ru': 'вкратце (недолго)', 'tg': 'мухтасар', 'lemma': 'briefly'},
    'hallway': {'ru': 'коридор', 'tg': 'долон', 'lemma': 'hallway'},
    'seem': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'friendly': {'ru': 'дружелюбный', 'tg': 'дӯстона', 'lemma': 'friendly'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'sign': {'ru': 'подписывать', 'tg': 'имзо кардан', 'lemma': 'sign'},
    'contract': {'ru': 'договор', 'tg': 'шартнома', 'lemma': 'contract'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'feels': {'ru': 'чувствовать (казаться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'is': BE, 'that\'s': BE, 'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'was': BE, 'doesn\'t': DO,
},
98: {
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'apartment': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'apartment'},
    'boxes': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'everywhere': {'ru': 'везде', 'tg': 'дар ҳама ҷо', 'lemma': 'everywhere'},
    'unpacked': {'ru': 'распаковывать', 'tg': 'кушода гирифтан', 'lemma': 'unpack'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'yet': {'ru': 'ещё (уже)', 'tg': 'ҳанӯз', 'lemma': 'yet'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'haven\'t': DO, 'touched': {'ru': 'трогать', 'tg': 'даст расондан', 'lemma': 'touch'},
    'bedroom': {'ru': 'спальня', 'tg': 'хобгоҳ', 'lemma': 'bedroom'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'hung': {'ru': 'вешать', 'tg': 'овехтан', 'lemma': 'hang'},
    'pictures': {'ru': 'картина', 'tg': 'расм', 'lemma': 'picture'},
    'living': {'ru': 'гостиная', 'tg': 'меҳмонхона', 'lemma': 'living room'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'matches': {'ru': 'сочетаться', 'tg': 'мувофиқат кардан', 'lemma': 'match'},
    'walls': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'machine': {'ru': 'машина (аппарат)', 'tg': 'дастгоҳ', 'lemma': 'machine'},
    'clearly': {'ru': 'явно (ясно)', 'tg': 'равшан', 'lemma': 'clearly'},
    'missing': {'ru': 'скучать (не хватает)', 'tg': 'дилтанг шудан', 'lemma': 'miss'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'one': {'ru': 'одна (из)', 'tg': 'яке', 'lemma': 'one'},
    'met': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'elderly': {'ru': 'пожилой', 'tg': 'солхӯрда', 'lemma': 'elderly'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'brought': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'plate': {'ru': 'тарелка', 'tg': 'табақ', 'lemma': 'plate'},
    'biscuits': {'ru': 'печенье', 'tg': 'бисквит', 'lemma': 'biscuit'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'building': {'ru': 'здание', 'tg': 'бино', 'lemma': 'building'},
    'noticed': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'registered': {'ru': 'регистрировать', 'tg': 'сабт кардан', 'lemma': 'register'},
    'address': {'ru': 'адрес', 'tg': 'суроға', 'lemma': 'address'},
    'confess': {'ru': 'признаваться', 'tg': 'эътироф кардан', 'lemma': 'confess'},
    'we\'ll': BE, 'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'slowly': {'ru': 'медленно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'box': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'empty': {'ru': 'пустой', 'tg': 'холӣ', 'lemma': 'empty'},
    'starting': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'feel': {'ru': 'чувствоваться (казаться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'ours': {'ru': 'наш', 'tg': 'аз они мо', 'lemma': 'ours'},
    'is': BE, 've': {'ru': 'иметь (вспом.)', 'tg': 'доранд', 'lemma': 'have'}, 'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
},
99: {
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'interview': {'ru': 'собеседование', 'tg': 'мусоҳиба', 'lemma': 'interview'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'heard': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'anything': {'ru': 'что-нибудь', 'tg': 'чизе', 'lemma': 'anything'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'yet': {'ru': 'ещё', 'tg': 'ҳанӯз', 'lemma': 'yet'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'flatmate': {'ru': 'сосед по квартире', 'tg': 'ҳамхона', 'lemma': 'flatmate'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'friday': {'ru': 'пятница', 'tg': 'ҷумъа', 'lemma': 'Friday'},
    'replies': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'happened': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'far': {'ru': 'до сих пор', 'tg': 'то ҳол', 'lemma': 'so far'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'checked': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'email': {'ru': 'электронная почта', 'tg': 'почтаи электронӣ', 'lemma': 'email'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'hoping': {'ru': 'надеяться', 'tg': 'умед доштан', 'lemma': 'hope'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'inbox': {'ru': 'входящие', 'tg': 'номаҳои воридотӣ', 'lemma': 'inbox'},
    'except': {'ru': 'кроме', 'tg': 'ба ғайр аз', 'lemma': 'except'},
    'adverts': {'ru': 'реклама', 'tg': 'реклама', 'lemma': 'advert'},
    'applied': {'ru': 'подавать заявку', 'tg': 'дархост додан', 'lemma': 'apply'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'companies': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'case': {'ru': 'случай', 'tg': 'ҳолат', 'lemma': 'case'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'felt': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'detailed': {'ru': 'подробный', 'tg': 'муфассал', 'lemma': 'detailed'},
    'questions': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'experience': {'ru': 'опыт', 'tg': 'таҷриба', 'lemma': 'experience'},
    'sure': {'ru': 'уверенный', 'tg': 'мутмаин', 'lemma': 'sure'},
    'meant': {'ru': 'значить', 'tg': 'маъно доштан', 'lemma': 'mean'},
    'through': {'ru': 'через (пройти через)', 'tg': 'аз сар гузарондан', 'lemma': 'go through'},
    'before': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'before'},
    'advice': {'ru': 'совет', 'tg': 'маслиҳат', 'lemma': 'advice'},
    'once': {'ru': 'однажды', 'tg': 'як бор', 'lemma': 'once'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'answer': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'turned': {'ru': 'оказываться', 'tg': 'баромадан', 'lemma': 'turn out'},
    'fine': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'fine'},
    'nods': {'ru': 'кивать', 'tg': 'сар ҷунбондан', 'lemma': 'nod'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'much2': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'much'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'told': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'decides': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'wait': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'until': {'ru': 'до', 'tg': 'то', 'lemma': 'until'},
    'calling': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'herself': {'ru': 'сама', 'tg': 'худаш', 'lemma': 'herself'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'hasn\'t': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'isn\'t': BE, 'there\'s': BE, 'doesn\'t': DO,
},
100: {
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'cafés': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'opinion': {'ru': 'мнение', 'tg': 'ақида', 'lemma': 'opinion'},
    'café': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'corner': {'ru': 'угол', 'tg': 'гӯшаи', 'lemma': 'corner'},
    'cheaper': {'ru': 'дешевле', 'tg': 'арзонтар', 'lemma': 'cheap'},
    'than': {'ru': 'чем', 'tg': 'нисбат ба', 'lemma': 'than'},
    'opposite': {'ru': 'напротив', 'tg': 'рӯ ба рӯ', 'lemma': 'opposite'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'strong': {'ru': 'крепкий', 'tg': 'сахт', 'lemma': 'strong'},
    'rival\'s': {'ru': 'соперничий (конкурент)', 'tg': 'аз они рақиб', 'lemma': 'rival'},
    'waiters': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    'friendlier': {'ru': 'дружелюбнее', 'tg': 'дӯстонатар', 'lemma': 'friendly'},
    'tables': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'smaller': {'ru': 'меньше', 'tg': 'хурдтар', 'lemma': 'small'},
    'closer': {'ru': 'ближе', 'tg': 'наздиктар', 'lemma': 'close'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'across': {'ru': 'через (напротив)', 'tg': 'дар он тарафи', 'lemma': 'across'},
    'newer': {'ru': 'новее', 'tg': 'навтар', 'lemma': 'new'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'modern': {'ru': 'современный', 'tg': 'муосир', 'lemma': 'modern'},
    'bigger': {'ru': 'больше', 'tg': 'калонтар', 'lemma': 'big'},
    'windows': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'softer': {'ru': 'мягче (тише)', 'tg': 'мулоимтар', 'lemma': 'soft'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'cakes': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'more': {'ru': 'более', 'tg': 'бештар', 'lemma': 'more'},
    'expensive': {'ru': 'дорогой', 'tg': 'қиммат', 'lemma': 'expensive'},
    'customers': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'worth': {'ru': 'стоящий', 'tg': 'арзанда', 'lemma': 'worth'},
    'just': {'ru': 'так же', 'tg': 'ба ҳамин андоза', 'lemma': 'just'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'capital': {'ru': 'столица', 'tg': 'пойтахт', 'lemma': 'capital'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'tapping': {'ru': 'постукивать', 'tg': 'зарба задан', 'lemma': 'tap'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'proudly': {'ru': 'гордо', 'tg': 'бо ифтихор', 'lemma': 'proudly'},
    'busier': {'ru': 'оживлённее', 'tg': 'серодамтар', 'lemma': 'busy'},
    'mornings': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'while': {'ru': 'в то время как', 'tg': 'дар ҳоле ки', 'lemma': 'while'},
    'fills': {'ru': 'заполняться', 'tg': 'пур шудан', 'lemma': 'fill up'},
    'faster': {'ru': 'быстрее', 'tg': 'тезтар', 'lemma': 'fast'},
    'evenings': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'prices': {'ru': 'цена', 'tg': 'нарх', 'lemma': 'price'},
    'higher': {'ru': 'выше', 'tg': 'баландтар', 'lemma': 'high'},
    'service': {'ru': 'обслуживание', 'tg': 'хизматрасонӣ', 'lemma': 'service'},
    'quicker': {'ru': 'быстрее', 'tg': 'тезтар', 'lemma': 'quick'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'loyal': {'ru': 'преданный (лояльный)', 'tg': 'содиқ', 'lemma': 'loyal'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'arguing': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'which': {'ru': 'который (какой)', 'tg': 'кадом', 'lemma': 'which'},
    'truly': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'truly'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'personally': {'ru': 'лично', 'tg': 'шахсан', 'lemma': 'personally'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'clock': {'ru': 'часы (башня)', 'tg': 'соат', 'lemma': 'clock tower'},
    'tower': {'ru': 'башня', 'tg': 'бурҷ', 'lemma': 'tower'},
    'nearby': {'ru': 'поблизости', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'are': BE, 'is': BE, 'isn\'t': BE, 'its': {'ru': 'его (её)', 'tg': 'аз они он', 'lemma': 'its'}, 'they\'re': BE,
},
101: {
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'meal': {'ru': 'приём пищи (еда)', 'tg': 'таом', 'lemma': 'meal'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'eaten': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'putting': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'put'},
    'fork': {'ru': 'вилка', 'tg': 'чангак', 'lemma': 'fork'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'hidden': {'ru': 'скрытый', 'tg': 'пинҳон', 'lemma': 'hidden'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'side': {'ru': 'боковая (сторона)', 'tg': 'паҳлуӣ', 'lemma': 'side'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'quietest': {'ru': 'самый тихий', 'tg': 'оромтарин', 'lemma': 'quiet'},
    'place': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'cheapest': {'ru': 'самый дешёвый', 'tg': 'арзонтарин', 'lemma': 'cheap'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'restaurants': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'tried': {'ru': 'пробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'adds': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'portions': {'ru': 'порция', 'tg': 'ҳисса', 'lemma': 'portion'},
    'generous': {'ru': 'щедрый', 'tg': 'саховатманд', 'lemma': 'generous'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'dishes': {'ru': 'блюдо', 'tg': 'таом', 'lemma': 'dish'},
    'spicy': {'ru': 'острый', 'tg': 'тунд', 'lemma': 'spicy'},
    'daughter': {'ru': 'дочь', 'tg': 'духтар', 'lemma': 'daughter'},
    'prefers': {'ru': 'предпочитать', 'tg': 'афзал донистан', 'lemma': 'prefer'},
    'milder': {'ru': 'мягче (менее острый)', 'tg': 'сустаранг', 'lemma': 'mild'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'sauce': {'ru': 'соус', 'tg': 'сӯс', 'lemma': 'sauce'},
    'rice': {'ru': 'рис', 'tg': 'биринҷ', 'lemma': 'rice'},
    'little': {'ru': 'маленькая', 'tg': 'хурд', 'lemma': 'little'},
    'girl': {'ru': 'девочка', 'tg': 'духтар', 'lemma': 'girl'},
    'complains': {'ru': 'жаловаться', 'tg': 'шикоят кардан', 'lemma': 'complain'},
    'pushing': {'ru': 'отодвигать (толкать)', 'tg': 'тела додан', 'lemma': 'push'},
    'plate': {'ru': 'тарелка', 'tg': 'табақ', 'lemma': 'plate'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'waiter': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    'most': {'ru': 'самый', 'tg': 'аз ҳама', 'lemma': 'most'},
    'patient': {'ru': 'терпеливый', 'tg': 'сабур', 'lemma': 'patient'},
    'met': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'brings': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'extra': {'ru': 'дополнительный', 'tg': 'иловагӣ', 'lemma': 'extra'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'asked': {'ru': 'просить', 'tg': 'пурсидан', 'lemma': 'ask'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'definitely': {'ru': 'определённо', 'tg': 'бешубҳа', 'lemma': 'definitely'},
    'friendliest': {'ru': 'самый дружелюбный', 'tg': 'дӯстонатарин', 'lemma': 'friendly'},
    'visited': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'looking': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'busy': {'ru': 'оживлённый', 'tg': 'серодам', 'lemma': 'busy'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'such': {'ru': 'такой', 'tg': 'чунин', 'lemma': 'such'},
    'fresh': {'ru': 'свежий', 'tg': 'тоза', 'lemma': 'fresh'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'before': {'ru': 'раньше (прежде)', 'tg': 'пештар', 'lemma': 'before'},
    'warm': {'ru': 'тёплый', 'tg': 'гарм', 'lemma': 'warm'},
    'oven': {'ru': 'печь (духовка)', 'tg': 'танӯр', 'lemma': 'oven'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'dessert': {'ru': 'десерт', 'tg': 'десерт', 'lemma': 'dessert'},
    'visit': {'ru': 'визит (посещение)', 'tg': 'ташриф', 'lemma': 'visit'},
    'should': {'ru': 'следует (должны)', 'tg': 'бояд', 'lemma': 'should'},
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'might': {'ru': 'возможно (могли бы)', 'tg': 'мумкин аст', 'lemma': 'might'},
    'discovery': {'ru': 'открытие', 'tg': 'кашфиёт', 'lemma': 'discovery'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'is': BE, 'isn\'t': BE, 'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'she\'s': BE,
},
102: {
    'local': {'ru': 'местный', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'weather': {'ru': 'погода', 'tg': 'обу ҳаво', 'lemma': 'weather'},
    'forecaster': {'ru': 'синоптик', 'tg': 'обуҳавошинос', 'lemma': 'forecaster'},
    'makes': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'bold': {'ru': 'смелый', 'tg': 'ҷасур', 'lemma': 'bold'},
    'prediction': {'ru': 'прогноз', 'tg': 'пешгӯӣ', 'lemma': 'prediction'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'radio': {'ru': 'радио', 'tg': 'радио', 'lemma': 'radio'},
    'won\'t': {'ru': 'не будет', 'tg': 'нахоҳад', 'lemma': 'will'},
    'rain': {'ru': 'дождь (идти дождём)', 'tg': 'борон', 'lemma': 'rain'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'announces': {'ru': 'объявлять', 'tg': 'эълон кардан', 'lemma': 'announce'},
    'confidently': {'ru': 'уверенно', 'tg': 'боэътимод', 'lemma': 'confidently'},
    'sky': {'ru': 'небо', 'tg': 'осмон', 'lemma': 'sky'},
    'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'},
    'stay': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'clear': {'ru': 'ясный', 'tg': 'соф', 'lemma': 'clear'},
    'until': {'ru': 'до', 'tg': 'то', 'lemma': 'until'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'listeners': {'ru': 'слушатель', 'tg': 'шунаванда', 'lemma': 'listener'},
    'learned': {'ru': 'научиться (узнать)', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'trust': {'ru': 'доверять', 'tg': 'бовар кардан', 'lemma': 'trust'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'wrong': {'ru': 'неправый (ошибающийся)', 'tg': 'хато', 'lemma': 'wrong'},
    'within': {'ru': 'в течение', 'tg': 'дар зарфи', 'lemma': 'within'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'dark': {'ru': 'тёмный', 'tg': 'торик', 'lemma': 'dark'},
    'clouds': {'ru': 'облако', 'tg': 'абр', 'lemma': 'cloud'},
    'appear': {'ru': 'появляться', 'tg': 'пайдо шудан', 'lemma': 'appear'},
    'lunchtime': {'ru': 'обеденное время', 'tg': 'вақти нисфирӯзӣ', 'lemma': 'lunchtime'},
    'raining': {'ru': 'идти (о дожде)', 'tg': 'борон боридан', 'lemma': 'rain'},
    'heavily': {'ru': 'сильно', 'tg': 'сахт', 'lemma': 'heavily'},
    'pass': {'ru': 'проходить', 'tg': 'гузаштан', 'lemma': 'pass'},
    'quickly': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'quickly'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'air': {'ru': 'в эфире', 'tg': 'дар эфир', 'lemma': 'on air'},
    'storm': {'ru': 'буря', 'tg': 'тӯфон', 'lemma': 'storm'},
    'continues': {'ru': 'продолжаться', 'tg': 'давом ёфтан', 'lemma': 'continue'},
    'rest': {'ru': 'остаток', 'tg': 'боқимонда', 'lemma': 'rest'},
    'afternoon': {'ru': 'вторая половина дня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'colleagues': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'joke': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'predicts': {'ru': 'предсказывать', 'tg': 'пешгӯӣ кардан', 'lemma': 'predict'},
    'sunshine': {'ru': 'солнечная погода', 'tg': 'офтобӣ', 'lemma': 'sunshine'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'should': {'ru': 'следует', 'tg': 'бояд', 'lemma': 'should'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'umbrella': {'ru': 'зонт', 'tg': 'чатр', 'lemma': 'umbrella'},
    'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'definitely': {'ru': 'определённо', 'tg': 'бешубҳа', 'lemma': 'definitely'},
    'warmer': {'ru': 'теплее', 'tg': 'гармтар', 'lemma': 'warm'},
    'promises': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'once': {'ru': 'однажды', 'tg': 'як бор', 'lemma': 'once'},
    'right': {'ru': 'правый (прав)', 'tg': 'ҳақ', 'lemma': 'right'},
    'football': {'ru': 'футбольный', 'tg': 'футболӣ', 'lemma': 'football'},
    'team': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'half': {'ru': 'наполовину', 'tg': 'ним', 'lemma': 'half'},
    'serious': {'ru': 'серьёзный', 'tg': 'ҷиддӣ', 'lemma': 'serious'},
    'bet': {'ru': 'спорить (на что-то)', 'tg': 'гарав бастан', 'lemma': 'bet'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'forecasts': {'ru': 'прогноз', 'tg': 'пешгӯӣ', 'lemma': 'forecast'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'owes': {'ru': 'быть должным', 'tg': 'қарздор будан', 'lemma': 'owe'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'coffees': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'give': {'ru': 'сдаваться', 'tg': 'даст кашидан', 'lemma': 'give up'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'checking': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'satellite': {'ru': 'спутник', 'tg': 'моҳвора', 'lemma': 'satellite'},
    'images': {'ru': 'изображение', 'tg': 'тасвир', 'lemma': 'image'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'one': {'ru': 'однажды', 'tg': 'як рӯз', 'lemma': 'one day'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'simply': {'ru': 'просто', 'tg': 'танҳо', 'lemma': 'simply'},
    'carry': {'ru': 'носить с собой', 'tg': 'бо худ гирифтан', 'lemma': 'carry'},
    'case': {'ru': 'случай', 'tg': 'ҳолат', 'lemma': 'case'},
    'is': BE, 'it\'s': BE, 'he\'s': BE,
},
103: {
    'shall': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'shall'},
    'organize': {'ru': 'организовать', 'tg': 'ташкил кардан', 'lemma': 'organize'},
    'surprise': {'ru': 'сюрприз', 'tg': 'ғайричашмдошт', 'lemma': 'surprise'},
    'party': {'ru': 'вечеринка', 'tg': 'зиёфат', 'lemma': 'party'},
    'grandma\'s': {'ru': 'бабушкин', 'tg': 'аз они бибӣ', 'lemma': 'grandma'},
    'birthday': {'ru': 'день рождения', 'tg': 'зодрӯз', 'lemma': 'birthday'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'brothers': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'i\'ll': {'ru': 'я (буд. время)', 'tg': 'ман хоҳам', 'lemma': 'I'},
    'book': {'ru': 'бронировать', 'tg': 'фармоиш додан', 'lemma': 'book'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'eldest': {'ru': 'старший', 'tg': 'калонӣ', 'lemma': 'eldest'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'reaching': {'ru': 'тянуться (за)', 'tg': 'даст дароз кардан', 'lemma': 'reach for'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'won\'t': {'ru': 'не буду (не сделаю)', 'tg': 'нахоҳам', 'lemma': 'will'},
    'tell': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'anything': {'ru': 'что-нибудь', 'tg': 'чизе', 'lemma': 'anything'},
    'promise': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'youngest': {'ru': 'младший', 'tg': 'хурдӣ', 'lemma': 'youngest'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'keep': {'ru': 'хранить', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'secret': {'ru': 'секрет', 'tg': 'сир', 'lemma': 'secret'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'celebrated': {'ru': 'праздновать', 'tg': 'ҷашн гирифтан', 'lemma': 'celebrate'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'birthdays': {'ru': 'день рождения', 'tg': 'зодрӯз', 'lemma': 'birthday'},
    'before': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'before'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'coming': {'ru': 'приезжать', 'tg': 'омадан', 'lemma': 'come'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'relatives': {'ru': 'родственники', 'tg': 'хешовандон', 'lemma': 'relative'},
    'abroad': {'ru': 'за границей', 'tg': 'хориҷа', 'lemma': 'abroad'},
    'bake': {'ru': 'печь', 'tg': 'пухтан', 'lemma': 'bake'},
    'cake': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'order': {'ru': 'заказывать', 'tg': 'фармоиш додан', 'lemma': 'order'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'decide': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'she\'ll': {'ru': 'она (буд. время)', 'tg': 'вай хоҳад', 'lemma': 'she'},
    'since': {'ru': 'так как (поскольку)', 'tg': 'зеро', 'lemma': 'since'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'shop': {'ru': 'магазинный', 'tg': 'мағозавӣ', 'lemma': 'shop'},
    'cakes': {'ru': 'торт', 'tg': 'торт', 'lemma': 'cake'},
    'taste': {'ru': 'иметь вкус', 'tg': 'таъм доштан', 'lemma': 'taste'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'homemade': {'ru': 'домашний', 'tg': 'хонагӣ', 'lemma': 'homemade'},
    'ones': {'ru': 'те (штуки)', 'tg': 'онҳо', 'lemma': 'one'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'walked': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'past': {'ru': 'мимо', 'tg': 'аз пеши', 'lemma': 'past'},
    'admired': {'ru': 'восхищаться', 'tg': 'таҳсин кардан', 'lemma': 'admire'},
    'blue': {'ru': 'синий', 'tg': 'кабуд', 'lemma': 'blue'},
    'scarf': {'ru': 'шарф', 'tg': 'рӯймол', 'lemma': 'scarf'},
    'part': {'ru': 'часть', 'tg': 'қисм', 'lemma': 'part'},
    'present': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'present'},
    'itself': {'ru': 'сам', 'tg': 'худаш', 'lemma': 'itself'},
    'hide': {'ru': 'прятаться', 'tg': 'пинҳон шудан', 'lemma': 'hide'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'arrives': {'ru': 'приходить (прибывать)', 'tg': 'расидан', 'lemma': 'arrive'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'walk': {'ru': 'прогулка', 'tg': 'сайр', 'lemma': 'walk'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'surprised': {'ru': 'удивлённый', 'tg': 'ҳайрон', 'lemma': 'surprised'},
    'nervously': {'ru': 'нервно', 'tg': 'бо асабоният', 'lemma': 'nervously'},
    'suspected': {'ru': 'подозревать', 'tg': 'шубҳа кардан', 'lemma': 'suspect'},
    'far': {'ru': 'до сих пор', 'tg': 'то ҳол', 'lemma': 'so far'},
    'reassures': {'ru': 'успокаивать', 'tg': 'ором кардан', 'lemma': 'reassure'},
    'soon': {'ru': 'скоро', 'tg': 'ба зудӣ', 'lemma': 'soon'},
    'shout': {'ru': 'кричать', 'tg': 'фарёд задан', 'lemma': 'shout'},
    'stop': {'ru': 'переставать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'will': {'ru': 'будет', 'tg': 'хоҳад', 'lemma': 'will'},
},
}

for sid, keys in {97: ['going2'], 99: ['much2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
