import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.db.database import AsyncSessionLocal
from app.models.model_content import StoryQuestions

Q = {
    116: [
        ('What does grandmother believe is the best way to show love?', 'Что бабушка считает лучшим способом проявить любовь?', 'Бибӣ бовар дорад, ки беҳтарин роҳи изҳори муҳаббат чист?',
         ['Cooking', 'Giving gifts', 'Telling stories'], 'Cooking',
         'She believes cooking is the best way to show love.', 'Она считает, что готовка — лучший способ показать любовь.', 'Вай бовар дорад, ки пухтупаз беҳтарин роҳи нишон додани муҳаббат аст.'),
        ("Why doesn't grandmother trust the cousin with seasoning?", 'Почему бабушка не доверяет кузену специи?', 'Бибӣ чаро ба ҷиян дар бораи ҳанут бовар намекунад?',
         ['Because of a disastrous rice incident two years ago', 'He is too young', 'He never helps'], 'Because of a disastrous rice incident two years ago',
         'She has not trusted him with seasoning since the disastrous rice incident two years ago.', 'Она не доверяет ему специи с того злополучного случая с рисом два года назад.', 'Вай пас аз ҳодисаи бади биринҷ ду сол пеш ба ӯ дар бораи ҳанут бовар намекунад.'),
        ('Who are they expecting today that nobody has met yet?', "Кого сегодня ждут, с кем ещё никто не знаком?", 'Имрӯз чашми интизори киянд, ки ҳанӯз ҳеҷ кас нашинохтааст?',
         ["The aunt's new husband", 'A new neighbour', "The cousin's girlfriend"], "The aunt's new husband",
         "They're expecting the aunt and her new husband, who nobody has properly met yet.", 'Они ждут тётю и её нового мужа, с которым ещё толком никто не знаком.', 'Онҳо чашми интизори хола ва шавҳари навашанд, ки ҳанӯз ҳеҷ кас хуб нашинохтааст.'),
    ],
    117: [
        ('When are they leaving?', 'Когда они уезжают?', 'Онҳо кай мераванд?',
         ['The first of July', 'The first of June', 'The last of July'], 'The first of July',
         "The father announced 'We're leaving on the first of July.'", 'Отец объявил: «Мы уезжаем первого июля».', 'Падар эълон кард: «Мо якуми июл меравем».'),
        ('How are they travelling?', 'Как они путешествуют?', 'Онҳо чӣ тавр сафар мекунанд?',
         ['Driving', 'Flying', 'By train'], 'Driving',
         "The mother says 'No, we're driving.'", 'Мать говорит: «Нет, мы едем на машине».', 'Модар мегӯяд: «Не, мо бо мошин меравем».'),
        ('Does grandmother join the trip?', 'Едет ли бабушка в поездку?', 'Оё бибӣ ба сафар меравад?',
         ['Yes, despite hating long journeys', 'No, she stays home', "It isn't decided"], 'Yes, despite hating long journeys',
         "Grandmother says 'I won't miss this trip', despite hating long journeys.", 'Бабушка говорит: «Я не пропущу эту поездку», хотя не любит долгие путешествия.', 'Бибӣ мегӯяд: «Ман ин сафарро аз даст намедиҳам», гарчанде ки сафари дурударозро дӯст намедорад.'),
    ],
    118: [
        ('What has Amira finished?', 'Что закончила Амира?', 'Амира чиро тамом кард?',
         ['Her degree', 'A book', 'A course'], 'Her degree',
         "Amira has finished her degree and found a job.", 'Амира закончила учёбу и нашла работу.', 'Амира таҳсилашро тамом кард ва кор ёфт.'),
        ('What did Amira do alone last year that took courage?', 'Что Амира сделала одна в прошлом году, что потребовало смелости?', 'Соли гузашта Амира танҳо чӣ кор кард, ки ҷасорат металабид?',
         ['Moved to a new city', 'Started a business', 'Learned to drive'], 'Moved to a new city',
         'Last year she moved to a new city alone, which took real courage.', 'В прошлом году она одна переехала в новый город, что потребовало настоящей смелости.', 'Соли гузашта вай танҳо ба шаҳри нав кӯчид, ки ҷасорати ҳақиқӣ металабид.'),
        ('When did Amira tell her parents the news?', 'Когда Амира рассказала новость родителям?', 'Амира ин хабарро кай ба волидонаш гуфт?',
         ['Right after the interview', 'A month later', 'She has not told them yet'], 'Right after the interview',
         "Amira says 'I called them right after the interview.'", 'Амира говорит: «Я позвонила им сразу после собеседования».', 'Амира мегӯяд: «Ман фавран пас аз мусоҳиба ба онҳо занг задам».'),
    ],
    119: [
        ('How long have the parents been building the house?', 'Сколько времени родители строят дом?', 'Волидон чанд вақт хонаро сохта истодаанд?',
         ['Almost four years', 'Two years', 'Ten years'], 'Almost four years',
         'They have been building the house for almost four years.', 'Они строят дом почти четыре года.', 'Онҳо хонаро қариб чор сол сохта истодаанд.'),
        ('What has the father been doing himself to save money?', 'Что отец делает сам, чтобы сэкономить деньги?', 'Падар барои сарфаи пул худаш чӣ кор карда истодааст?',
         ['Laying tiles in the kitchen', 'Painting the walls', 'Building the roof'], 'Laying tiles in the kitchen',
         'He has been laying tiles in the kitchen himself to save money.', 'Он сам укладывает плитку на кухне, чтобы сэкономить.', 'Ӯ худаш дар ошхона коширо мегузорад, то пул сарфа кунад.'),
        ('How long has the roof been finished?', 'Сколько времени крыша уже готова?', 'Бом чанд вақт боз тайёр аст?',
         ['Two years', 'Four years', 'Six months'], 'Two years',
         'The roof has actually been finished for two years already.', 'Крыша на самом деле уже готова два года.', 'Бом дар асл аллакай ду сол тайёр аст.'),
    ],
    120: [
        ('Which is usually the most reliable option?', 'Какой вариант обычно самый надёжный?', 'Кадом роҳ одатан мӯътамадтарин аст?',
         ['The metro', 'The bus', 'A taxi'], 'The metro',
         'The metro is usually the most reliable option.', 'Метро обычно самый надёжный вариант.', 'Метро одатан роҳи мӯътамадтарин аст.'),
        ('Which is the most expensive option?', 'Какой вариант самый дорогой?', 'Кадом роҳ гаронтарин аст?',
         ['A taxi', 'The bus', 'The metro'], 'A taxi',
         "Taxis are the most convenient, but also the most expensive by far.", 'Такси самое удобное, но и самое дорогое.', 'Такси мувофиқтарин аст, вале гаронтарин ҳам ҳаст.'),
        ('What does the narrator choose tonight because of the rain?', 'Что рассказчик выбирает сегодня вечером из-за дождя?', 'Ровӣ имшаб бинобар борон чиро интихоб мекунад?',
         ['The metro', 'A taxi', 'Cycling'], 'The metro',
         'With rain pouring, the metro is the clear choice tonight.', 'Из-за дождя сегодня вечером явный выбор — метро.', 'Бо сабаби борон, имшаб интихоби равшан метро аст.'),
    ],
    121: [
        ('What did the museum building use to be?', 'Чем раньше было здание музея?', 'Бинои осорхона пештар чӣ буд?',
         ['A factory', 'A school', 'A train station'], 'A factory',
         'The guide explains the building itself used to be a factory.', 'Гид объясняет, что само здание раньше было фабрикой.', 'Роҳбалад мефаҳмонад, ки худи бино пештар корхона буд.'),
        ('When did the factory close?', 'Когда закрылась фабрика?', 'Корхона кай баста шуд?',
         ['The nineties', 'The eighties', 'Last year'], 'The nineties',
         "The guide says 'The factory closed in the nineties.'", 'Гид говорит: «Фабрика закрылась в девяностых».', 'Роҳбалад мегӯяд: «Корхона дар солҳои навадум баста шуд».'),
        ('What does the narrator generally prefer?', 'Что рассказчик обычно предпочитает?', 'Ровӣ маъмулан чиро авло медонад?',
         ['Modern art', 'Local history', 'Photography'], 'Modern art',
         'The narrator says they generally prefer modern art, though this collection focused on local history.', 'Рассказчик говорит, что обычно предпочитает современное искусство, хотя эта коллекция посвящена местной истории.', 'Ровӣ мегӯяд, ки маъмулан санъати муосирро авло медонад, гарчанде ин маҷмӯа ба таърихи маҳаллӣ бахшида шудааст.'),
    ],
    122: [
        ('How many rings must employees answer client calls within?', 'В течение скольких гудков сотрудники должны ответить на звонок клиента?', 'Корманд бояд бо зангзании чандум ҷавоби мизоҷро диҳад?',
         ['Three', 'Five', 'One'], 'Three',
         'Employees have to answer client calls within three rings.', 'Сотрудники должны отвечать на звонки клиентов в течение трёх гудков.', 'Кормандон бояд то зангзании сеюм ба мизоҷ ҷавоб диҳанд.'),
        ('What must employees never do during a call?', 'Что сотрудники никогда не должны делать во время звонка?', 'Кормандон ҳангоми сӯҳбат бояд чиро ҳаргиз накунанд?',
         ['Eat', 'Take notes', 'Ask questions'], 'Eat',
         'They must never eat while on a call, since a client once complained about it.', 'Им нельзя есть во время звонка, поскольку клиент однажды пожаловался на это.', 'Онҳо ҳангоми сӯҳбат набояд хӯрок хӯранд, зеро як мизоҷ боре шикоят карда буд.'),
        ('Do employees have to switch their phones off completely during meetings?', 'Должны ли сотрудники полностью выключать телефоны на встречах?', 'Оё кормандон бояд дар ҷаласаҳо телефони худро комилан хомӯш кунанд?',
         ["No, they don't have to", 'Yes, always', 'Only in the mornings'], "No, they don't have to",
         "The manager says they mustn't use personal phones in meetings, but don't have to switch them off completely.", 'Менеджер говорит, что личные телефоны нельзя использовать на встречах, но полностью выключать их не обязательно.', 'Менеҷер мегӯяд, ки телефони шахсиро дар ҷаласа истифода бурдан мумкин нест, вале комилан хомӯш кардан ҳатмӣ нест.'),
    ],
    123: [
        ('How did the neighbour learn to fix phones?', 'Как сосед научился чинить телефоны?', 'Ҳамсоя таъмири телефонро чӣ тавр омӯхт?',
         ['He taught himself', 'He went to a special school', 'His father taught him'], 'He taught himself',
         'He taught himself this skill after years of curiosity.', 'Он сам обучился этому навыку после многих лет любопытства.', 'Ӯ ин малакаро пас аз солҳои кунҷковӣ худаш омӯхт.'),
        ("How long did it take him to fix the narrator's screen?", 'Сколько времени у него ушло на ремонт экрана рассказчика?', 'Ба ӯ барои таъмири экрани ровӣ чанд вақт лозим шуд?',
         ['Under an hour', 'A whole day', 'A week'], 'Under an hour',
         'He repaired the cracked screen in under an hour.', 'Он починил треснувший экран менее чем за час.', 'Ӯ экрани тарканеро камтар аз як соат таъмир кард.'),
        ('What tool does he hand the narrator?', 'Какой инструмент он даёт рассказчику?', 'Ӯ ба ровӣ кадом асборо медиҳад?',
         ['A tiny screwdriver', 'A hammer', 'Tweezers'], 'A tiny screwdriver',
         'He hands the narrator a tiny screwdriver to try.', 'Он даёт рассказчику маленькую отвёртку, чтобы попробовать.', 'Ӯ ба ровӣ печгардони хурд медиҳад, то кӯшиш кунад.'),
    ],
    124: [
        ('How many goals had the team scored by half-time?', 'Сколько голов забила команда к перерыву?', 'Дастаи бозӣ то танаффус чанд гол зада буд?',
         ['Twice', 'Once', 'Three times'], 'Twice',
         'Our team had already scored twice by half-time.', 'Наша команда уже дважды забила к перерыву.', 'Дастаи мо то танаффус аллакай ду маротиба гол зада буд.'),
        ("Why was the opposing team's confidence affected?", 'Почему уверенность команды соперника пострадала?', 'Эътимоди дастаи рақиб чаро осеб дид?',
         ['They lost their best player to injury', 'They had a new coach', 'They travelled a long way'], 'They lost their best player to injury',
         'They had lost their best player to injury the previous week.', 'На прошлой неделе они потеряли своего лучшего игрока из-за травмы.', 'Ҳафтаи гузашта беҳтарин бозигари онҳо бинобар осеб аз бозӣ монд.'),
        ('How did the team feel at the final whistle?', 'Что чувствовала команда в конце матча?', 'Даста ҳангоми хатми бозӣ чӣ ҳис кард?',
         ['Emotional, crying with relief', 'Disappointed', 'Indifferent'], 'Emotional, crying with relief',
         'Several teammates were crying with relief when the final whistle went.', 'Несколько игроков плакали от облегчения, когда прозвучал финальный свисток.', 'Чанд бозигар ҳангоми садои ҳуштаки ниҳоӣ аз сабукӣ гиря карданд.'),
    ],
    125: [
        ('What did the brothers used to argue about as teenagers?', 'О чём братья спорили в подростковом возрасте?', 'Бародарон дар наврасӣ дар бораи чӣ баҳс мекарданд?',
         ['Everything', 'Only football', 'Nothing'], 'Everything',
         'They used to argue about absolutely everything — music, chores, TV.', 'Они спорили абсолютно обо всём — музыке, домашних делах, телевизоре.', 'Онҳо дар бораи мутлақо ҳама чиз баҳс мекарданд — мусиқӣ, кори хона, телевизор.'),
        ('What do they still disagree about now?', 'О чём они всё ещё не соглашаются сейчас?', 'Онҳо ҳоло дар бораи чӣ розӣ намешаванд?',
         ['Football teams', 'Music', 'Clothes'], 'Football teams',
         'They still disagree loudly about football teams.', 'Они всё ещё громко спорят о футбольных командах.', 'Онҳо то ҳол дар бораи дастаҳои футбол бо овози баланд баҳс мекунанд.'),
        ('How often do they call each other now?', 'Как часто они теперь созваниваются?', 'Онҳо ҳоло чанд вақт як маротиба занг мезананд?',
         ['Every weekend', 'Every day', 'Once a year'], 'Every weekend',
         'They usually call each other every weekend now.', 'Теперь они обычно созваниваются каждые выходные.', 'Онҳо ҳоло одатан ҳар истироҳат ба ҳам занг мезананд.'),
    ],
    126: [
        ('How long was the film shot over?', 'Сколько времени снимался фильм?', 'Филм чанд вақт бардошта шуд?',
         ['Eighteen months', 'Six months', 'Three years'], 'Eighteen months',
         'The film was shot over eighteen months.', 'Фильм снимался восемнадцать месяцев.', 'Филм ҳаждаҳ моҳ бардошта шуд.'),
        ('What was changed just weeks before shooting ended?', 'Что изменили за несколько недель до конца съёмок?', 'Чанд ҳафта пеш аз хатми наворбардорӣ чӣ иваз шуд?',
         ['The final scene', 'The lead actress', 'The soundtrack'], 'The final scene',
         "The film's final scene was completely rewritten just weeks before shooting ended.", 'Финальную сцену фильма полностью переписали за несколько недель до конца съёмок.', 'Саҳнаи ниҳоии филм чанд ҳафта пеш аз хатми наворбардорӣ комилан аз нав навишта шуд.'),
        ('Who was the lead actress chosen from?', 'Из скольких кандидатов выбрали главную актрису?', 'Актрисаи асосӣ аз миёни чанд номзад интихоб шуд?',
         ['Hundreds of candidates', 'Ten candidates', 'A well-known actress was chosen directly'], 'Hundreds of candidates',
         'The lead actress was chosen from hundreds of candidates after a long audition.', 'Главную актрису выбрали из сотен кандидатов после долгого кастинга.', 'Актрисаи асосиро аз миёни садҳо номзад пас аз кастинги дарозмуддат интихоб карданд.'),
    ],
    127: [
        ('What did colleagues see that confused them?', 'Что коллеги увидели, что их запутало?', 'Ҳамкорон чиро диданд, ки онҳоро гиҷ кард?',
         ['Photos from the mountains', 'A resignation letter', 'A hospital photo'], 'Photos from the mountains',
         'He posted photos from the mountains while supposedly sick.', 'Он выложил фото из гор, хотя, предположительно, был болен.', 'Ӯ ҳангоме ки гӯё бемор буд, аксҳои аз кӯҳҳо гузоштааст.'),
        ("What did the neighbour see Farrukh loading Monday morning?", 'Что сосед увидел, как Фаррух грузит в понедельник утром?', 'Ҳамсоя рӯзи душанбе субҳ дид, ки Фаррух чиро бор мекунад?',
         ['A suitcase into his car', 'Furniture', 'Boxes of books'], 'A suitcase into his car',
         'The neighbour saw him loading a suitcase into his car early Monday morning.', 'Сосед видел, как он рано утром в понедельник грузил чемодан в машину.', 'Ҳамсоя дид, ки ӯ рӯзи душанбе бармаҳал ба мошинаш чамадонро бор мекард.'),
        ("What was the real reason for Farrukh's absence?", 'Какова настоящая причина отсутствия Фарруха?', 'Сабаби ҳақиқии набудани Фаррух чист?',
         ['A sudden family emergency', 'A new job interview', 'A holiday'], 'A sudden family emergency',
         'Farrukh explains a sudden family emergency when he returns.', 'Фаррух объясняет внезапную семейную ситуацию, когда возвращается.', 'Фаррух ҳангоми баргаштан ҳодисаи ногаҳонии оилавиро шарҳ медиҳад.'),
    ],
    128: [
        ('What does the narrator want to study?', 'Что рассказчик хочет изучать?', 'Ровӣ чиро омӯхтан мехоҳад?',
         ['Architecture', 'Medicine', 'Law'], 'Architecture',
         "The narrator will apply to study architecture at university.", 'Рассказчик собирается поступать на архитектуру в университет.', 'Ровӣ ба факултаи меъморӣ дар донишгоҳ дохил шудан мехоҳад.'),
        ('Who will the narrator call first with the results?', 'Кому рассказчик позвонит первым с результатами?', 'Ровӣ бо натиҷаҳо аввал ба кӣ занг мезанад?',
         ['Grandmother', 'A friend', 'A teacher'], 'Grandmother',
         "As soon as the narrator knows the results, they'll call their grandmother first.", 'Как только рассказчик узнает результаты, он сначала позвонит бабушке.', 'Ҳамин ки ровӣ натиҷаҳоро донист, аввал ба бибиаш занг мезанад.'),
        ("What will the narrator do if the grades aren't good enough?", 'Что рассказчик сделает, если оценки будут недостаточно хорошими?', 'Агар бааҳо кофӣ набошад, ровӣ чӣ мекунад?',
         ['Retake one exam in the autumn', 'Give up completely', 'Study something else'], 'Retake one exam in the autumn',
         "If the grades aren't good enough, the narrator will retake one exam in the autumn.", 'Если оценок будет недостаточно, рассказчик пересдаст один экзамен осенью.', 'Агар бааҳо кофӣ набошад, ровӣ як имтиҳонро тирамоҳ такрор месупорад.'),
    ],
    129: [
        ('What does the mother want if they had a bigger house?', 'Что мать хочет, если бы у них был дом побольше?', 'Агар хонаи калонтар медоштанд, модар чиро мехост?',
         ['A proper garden', 'A swimming pool', 'A bigger kitchen'], 'A proper garden',
         'The mother says she would finally have a proper garden.', 'Мать говорит, что у неё наконец был бы настоящий сад.', 'Модар мегӯяд, ки ниҳоят боғи ҳақиқӣ медошт.'),
        ('What would the father keep from the old house?', 'Что отец сохранил бы из старого дома?', 'Падар аз хонаи кӯҳна чиро нигоҳ медошт?',
         ['The old front door', 'The old kitchen table', 'The garden fence'], 'The old front door',
         'He would keep the old front door with the childhood height marks on it.', 'Он бы сохранил старую входную дверь с отметками роста детей.', 'Ӯ дари кӯҳнаи пешро бо нишонаҳои қади кӯдакӣ нигоҳ медошт.'),
        ('What would the sister do differently in a house she designed?', 'Что сестра сделала бы иначе в доме, который спроектировала бы сама?', 'Хоҳар дар хонае, ки худаш тарҳрезӣ мекард, чиро дигар мекард?',
         ['Fewer stairs and more sunlight', 'More stairs', 'A smaller kitchen'], 'Fewer stairs and more sunlight',
         'She would build it with fewer stairs and more sunlight.', 'Она бы построила его с меньшим числом лестниц и большим количеством солнечного света.', 'Вай онро бо зинапояҳои камтар ва рӯшноии офтоби бештар месохт.'),
    ],
    130: [
        ('What did Malika decide to do?', 'Что решила сделать Малика?', 'Малика чӣ кор карданро қарор кард?',
         ['Quit her office job and open a bakery', 'Ask for a promotion', 'Move to another city'], 'Quit her office job and open a bakery',
         'Malika decided to quit and open a small bakery instead.', 'Малика решила уволиться и открыть небольшую пекарню.', 'Малика қарор кард, ки аз кор рафта нонвойхонаи хурд кушояд.'),
        ('What did her brother suggest?', 'Что предложил её брат?', 'Бародараш чӣ пешниҳод кард?',
         ['Start small, selling to neighbours first', 'Borrow money from the bank', 'Hire staff immediately'], 'Start small, selling to neighbours first',
         'Her brother suggested starting small, selling bread only to neighbours first.', 'Её брат предложил начать с малого, продавая хлеб сначала только соседям.', 'Бародараш пешниҳод кард, ки аз хурд сар кунад ва аввал танҳо ба ҳамсояҳо нон фурӯшад.'),
        ('What do customers keep requesting?', 'Что клиенты постоянно просят?', 'Мизоҷон доим чиро талаб мекунанд?',
         ['Her sourdough', 'Cakes', 'Croissants'], 'Her sourdough',
         'A loyal group of customers kept requesting her sourdough specifically.', 'Постоянные клиенты постоянно просили именно её хлеб на закваске.', 'Мизоҷони собитқадам маҳз нони туршмояи ӯро талаб мекарданд.'),
    ],
    131: [
        ("Why couldn't the jacket be returned easily?", 'Почему куртку было не так просто вернуть?', 'Курта чаро ба осонӣ баргардонида намешуд?',
         ['The customer had lost the receipt', 'It was already worn', 'It was on sale'], 'The customer had lost the receipt',
         'The customer had lost the receipt somewhere between the till and the bus stop.', 'Покупатель потерял чек где-то между кассой и автобусной остановкой.', 'Мизоҷ квитансияро дар байни касса ва истгоҳи автобус гум кардааст.'),
        ('How does the manager verify the purchase?', 'Как менеджер проверяет покупку?', 'Менеҷер харидро чӣ тавр тасдиқ мекунад?',
         ['By checking the payment system', 'By calling the bank', 'By asking other staff'], 'By checking the payment system',
         'He checks the payment system instead of relying on a receipt.', 'Он проверяет платёжную систему вместо того, чтобы полагаться на чек.', 'Ӯ ба ҷои такя ба квитансия системаи пардохтро тафтиш мекунад.'),
        ('How did the narrator pay?', 'Как рассказчик расплатился?', 'Ровӣ чӣ тавр пул дод?',
         ['By card', 'In cash', 'By cheque'], 'By card',
         'The narrator confirms they had paid by card.', 'Рассказчик подтверждает, что расплатился картой.', 'Ровӣ тасдиқ мекунад, ки бо корт пул додааст.'),
    ],
    132: [
        ('What happened to the phone?', 'Что случилось с телефоном?', 'Ба телефон чӣ рӯй дод?',
         ['It fell in the river', 'It was stolen', 'It broke at home'], 'It fell in the river',
         'The phone fell in the river.', 'Телефон упал в реку.', 'Телефон ба дарё афтод.'),
        ('How many years of photos were lost?', 'Сколько лет фотографий было потеряно?', 'Аксҳои чанд сол гум шуданд?',
         ['Four years', 'One year', 'Ten years'], 'Four years',
         'Four years of photographs were lost in a single afternoon.', 'Четыре года фотографий были потеряны за один день.', 'Аксҳои чор сол дар як рӯз гум шуданд.'),
        ('What did the narrator do with the phone that may have made things worse?', 'Что рассказчик сделал с телефоном, что могло усугубить ситуацию?', 'Ровӣ бо телефон чӣ кард, ки шояд вазъро бадтар кард?',
         ['Left it in a bag of rice for a week', 'Threw it away', 'Tried to charge it immediately'], 'Left it in a bag of rice for a week',
         'The narrator left it in a bag of rice for a week, which the delay may have worsened.', 'Рассказчик оставил его в пакете с рисом на неделю, что могло ухудшить ситуацию.', 'Ровӣ онро як ҳафта дар халтаи биринҷ монд, ки ин таъхир шояд вазъро бадтар кард.'),
    ],
    133: [
        ('What is the kitchen drawer full of?', 'Чем забит кухонный ящик?', 'Ғаладони ошхона аз чӣ пур аст?',
         ['Phone chargers', 'Old photos', 'Kitchen tools'], 'Phone chargers',
         'The kitchen drawer contains far too many phone chargers.', 'Кухонный ящик содержит слишком много зарядных устройств для телефона.', 'Ғаладони ошхона хеле бисёр заряднокҳои телефон дорад.'),
        ('How many chargers do they eventually keep?', 'Сколько зарядных устройств они в итоге оставляют?', 'Онҳо дар охир чанд заряднок нигоҳ медоранд?',
         ['One', 'Five', 'None'], 'One',
         'They find exactly one charger that works with everything they use.', 'Они находят ровно одно зарядное устройство, которое подходит ко всему, чем они пользуются.', 'Онҳо маҳз як заряднокро меёбанд, ки ба ҳама чизе, ки истифода мебаранд, мувофиқ аст.'),
        ('What happens to the rest of the chargers?', 'Что происходит с остальными зарядными устройствами?', 'Ба боқимондаи заряднокҳо чӣ мешавад?',
         ['They go into a bag for recycling', 'They keep them all', 'They give them to neighbours'], 'They go into a bag for recycling',
         'The rest, several dozen useless cables, go into a bag for recycling.', 'Остальные, несколько десятков бесполезных проводов, отправляются в мешок для переработки.', 'Боқимонда, даҳҳо симҳои бефоида, ба халтаи бозиёфт мераванд.'),
    ],
    134: [
        ('What kind of shop was robbed?', 'Какой магазин ограбили?', 'Кадом мағоза дуздӣ шуд?',
         ['A jewellery shop', 'A bakery', 'A phone shop'], 'A jewellery shop',
         'The jewellery shop had been robbed twice in the same month.', 'Ювелирный магазин был ограблен дважды за один месяц.', 'Мағозаи заргарӣ дар як моҳ ду маротиба дуздӣ шуд.'),
        ('What clue did the young witness mention?', 'Какую улику упомянула молодая свидетельница?', 'Шоҳиди ҷавон кадом далелро зикр кард?',
         ['A delivery van parked outside both times', 'A man in a black coat', 'A broken window'], 'A delivery van parked outside both times',
         'She mentioned a delivery van that had parked outside both times.', 'Она упомянула фургон доставки, который оба раза стоял снаружи.', 'Вай мошини бордории мебошад, ки ҳар ду бор дар берун истода буд, зикр кард.'),
        ('Who turned out to be the thief?', 'Кто оказался вором?', 'Дузд кӣ баромад?',
         ['A former employee with keys', 'The shop owner', 'A random stranger'], 'A former employee with keys',
         'The van led detectives to a former employee who still had a set of keys.', 'Фургон привёл детективов к бывшему сотруднику, у которого всё ещё был комплект ключей.', 'Мошин детективҳоро ба кормандии собиқ бурд, ки ҳанӯз калид дошт.'),
    ],
    135: [
        ('What does the host ask the two strangers?', 'О чём хозяин спрашивает двух незнакомцев?', 'Мизбон аз ду шахси ношинос дар бораи чӣ мепурсад?',
         ['Whether they have met before', 'Where they work', 'What they want to drink'], 'Whether they have met before',
         "The host asks 'You two haven't actually met before, have you?'", 'Хозяин спрашивает: «Вы двое ведь раньше не встречались, да?»', 'Мизбон мепурсад: «Шумо дуто пештар вохӯрда набудед, ҳамин тавр не?»'),
        ('Where does the woman say she saw the narrator before?', 'Где женщина говорит, что видела рассказчика раньше?', 'Зан мегӯяд, ки ровиро пештар дар куҷо дидааст?',
         ['At a lecture he gave', 'At the university cafeteria', 'At a wedding'], 'At a lecture he gave',
         'She says she attended a lecture he once gave.', 'Она говорит, что была на одной из его лекций.', 'Вай мегӯяд, ки дар яке аз лексияҳои ӯ буд.'),
        ('What do they exchange by the end of the evening?', 'Чем они обмениваются к концу вечера?', 'Онҳо то охири шаб бо чӣ мубодила мекунанд?',
         ['Phone numbers', 'Books', 'Addresses'], 'Phone numbers',
         "They'd exchanged numbers, promising to have coffee sometime.", 'Они обменялись номерами, пообещав как-нибудь выпить кофе.', 'Онҳо рақамҳо мубодила карда, ваъда доданд, ки боре қаҳва менӯшанд.'),
    ],
}


async def main():
    async with AsyncSessionLocal() as db:
        created = 0
        for story_id, questions in Q.items():
            for text_en, text_ru, text_tg, options, answer, expl_en, expl_ru, expl_tg in questions:
                db.add(StoryQuestions(
                    story_id=story_id,
                    text_en=text_en,
                    text_ru=text_ru,
                    text_tg=text_tg,
                    options=options,
                    answer=answer,
                    explanation_en=expl_en,
                    explanation_ru=expl_ru,
                    explanation_tg=expl_tg,
                ))
                created += 1
        await db.commit()
        print(f'created {created} story questions for {len(Q)} stories')


asyncio.run(main())
