import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.db.database import AsyncSessionLocal
from app.models.model_content import StoryQuestions

Q = {
    92: [
        ('What does the woman do every Sunday?', 'Что женщина делает каждое воскресенье?', 'Зан ҳар якшанбе чӣ мекунад?',
         ['She runs', 'She paints', 'She cooks'], 'She runs',
         "She says 'I never miss my Sunday run.'", 'Она говорит: «Я никогда не пропускаю свою воскресную пробежку».', 'Вай мегӯяд: «Ман давидани якшанбегиамро ҳеҷ гоҳ намемонам».'),
        ('What does Aziz love doing?', 'Что любит делать Азиз?', 'Азиз чӣ карданро дӯст медорад?',
         ['Cooking for his friends', 'Painting', 'Travelling'], 'Cooking for his friends',
         "Aziz says 'I love cooking for my friends.'", 'Азиз говорит: «Я люблю готовить для друзей».', 'Азиз мегӯяд: «Ман пухтани таом барои дӯстонамро дӯст медорам».'),
        ('Which table matches Aziz?', 'С каким столиком совпадает Азиз?', 'Азиз бо кадом миз мувофиқ меояд?',
         ['Table nine', 'Table four', 'Table one'], 'Table nine',
         'The organizer says table four and table nine chose each other; Aziz was at table four.', 'Организатор говорит, что столики четыре и девять выбрали друг друга; Азиз был за столиком четыре.', 'Ташкилотчӣ мегӯяд, ки мизҳои чор ва нӯҳ якдигарро интихоб карданд; Азиз дар мизи чор буд.'),
    ],
    93: [
        ('What are they renovating?', 'Что они ремонтируют?', 'Онҳо чиро таъмир мекунанд?',
         ['The kitchen and the bathroom', 'The garden', 'The garage'], 'The kitchen and the bathroom',
         "The designer says 'we're renovating the kitchen and the bathroom.'", 'Дизайнер говорит: «мы ремонтируем кухню и ванную».', 'Дизайнер мегӯяд: «мо ошхона ва ҳаммомро таъмир мекунем».'),
        ('Where is the Karimov family currently living?', 'Где сейчас живёт семья Каримовых?', 'Оилаи Каримовҳо ҳоло дар куҷо зиндагӣ мекунад?',
         ['With relatives', 'In a hotel', 'In their garden'], 'With relatives',
         'The Karimovs are currently living with relatives during the renovation.', 'Каримовы сейчас живут у родственников во время ремонта.', 'Каримовҳо ҳангоми таъмир назди хешовандон зиндагӣ мекунанд.'),
        ('What is happening to every room?', 'Что происходит с каждой комнатой?', 'Бо ҳар утоқ чӣ рӯй медиҳад?',
         ['Being painted a different colour', 'Being made bigger', 'Being emptied'], 'Being painted a different colour',
         "The designer says 'we're also painting every room a different colour.'", 'Дизайнер говорит: «мы также красим каждую комнату в другой цвет».', 'Дизайнер мегӯяд: «мо инчунин ҳар утоқро ба ранги дигар мекашем».'),
    ],
    94: [
        ('What time did the power cut happen?', 'Во сколько произошло отключение света?', 'Қатъи барқ соати чанд рӯй дод?',
         ['Eight o\'clock', 'Ten o\'clock', 'Nine o\'clock'], 'Eight o\'clock',
         'The neighbourhood lost electricity at exactly eight o\'clock.', 'Электричество в районе отключилось ровно в восемь.', 'Дар маҳалла барқ маҳз соати ҳашт қатъ шуд.'),
        ('How long did the power stay off?', 'Сколько времени не было света?', 'Барқ чанд вақт набуд?',
         ['Almost three hours', 'One hour', 'All night'], 'Almost three hours',
         'The power stayed off for almost three hours.', 'Электричества не было почти три часа.', 'Барқ қариб се соат набуд.'),
        ('What did the family do while waiting?', 'Что делала семья, пока ждала?', 'Оила дар вақти интизорӣ чӣ кард?',
         ['Played cards by candlelight', 'Watched TV', 'Went to sleep'], 'Played cards by candlelight',
         'The family played cards by candlelight while the power was off.', 'Семья играла в карты при свечах, пока не было света.', 'Оила дар вақти набудани барқ бо шамъ қартабозӣ кард.'),
    ],
    95: [
        ('What problem does the bus have?', 'Какая проблема у автобуса?', 'Автобус кадом мушкилотро дорад?',
         ['A flat tyre', 'A broken window', 'No fuel'], 'A flat tyre',
         'The bus stops with a flat tyre after an hour.', 'Автобус останавливается со спущенным колесом через час.', 'Автобус пас аз як соат бо чархи сӯрохшуда меистад.'),
        ('How much later than planned does the bus arrive?', 'На сколько позже плана прибывает автобус?', 'Автобус аз нақша чанд дертар мерасад?',
         ['Six hours', 'Two hours', 'One hour'], 'Six hours',
         'The bus arrives six hours later than planned.', 'Автобус прибывает на шесть часов позже, чем планировалось.', 'Автобус аз нақша шаш соат дертар мерасад.'),
        ('What does the cousin suggest for next time?', 'Что кузина советует на следующий раз?', 'Ҷиян барои дафъаи оянда чӣ маслиҳат медиҳад?',
         ['Take the train', 'Take a taxi', 'Fly instead'], 'Take the train',
         "The cousin says 'Next time, take the train.'", 'Кузина говорит: «В следующий раз поезжай на поезде».', 'Ҷиян мегӯяд: «Дафъаи дигар бо поезд рав».'),
    ],
    96: [
        ('When is Nigora getting married?', 'Когда Нигора выходит замуж?', 'Нигора кай ба хона медарояд?',
         ['June', 'May', 'July'], 'June',
         "The story says 'Nigora is getting married in June.'", 'В истории сказано: «Нигора выходит замуж в июне».', 'Дар ҳикоя гуфта мешавад: «Нигора моҳи июн хонадор мешавад».'),
        ('Where is the ceremony?', 'Где проходит церемония?', 'Маросим дар куҷо мегузарад?',
         ["Her grandmother's garden", 'A restaurant', 'A park'], "Her grandmother's garden",
         "Nigora says 'We're having the ceremony in my grandmother's garden.'", 'Нигора говорит: «Церемония пройдёт в саду моей бабушки».', 'Нигора мегӯяд: «Маросим дар боғи бибиям мегузарад».'),
        ('About how many guests is she inviting?', 'Сколько примерно гостей она приглашает?', 'Тахминан чанд меҳмон даъват мекунад?',
         ['Almost two hundred', 'About fifty', 'About a hundred'], 'Almost two hundred',
         "Nigora is going to invite almost two hundred guests.", 'Нигора собирается пригласить почти двести гостей.', 'Нигора қариб дусад меҳмон даъват мекунад.'),
    ],
    97: [
        ('What does Jamshed want near his flat?', 'Что Джамшед хочет рядом с квартирой?', 'Ҷамшед чиро дар наздикии хонаи худ мехоҳад?',
         ['His office', 'A park', 'A market'], 'His office',
         'Jamshed wants a flat close to his office.', 'Джамшед хочет квартиру рядом с офисом.', 'Ҷамшед хонаеро дар наздикии идораи худ мехоҳад.'),
        ('How old is the building?', 'Сколько лет зданию?', 'Бино чандсола аст?',
         ['Two years old', 'Ten years old', 'Twenty years old'], 'Two years old',
         'The building was built only two years ago.', 'Здание было построено всего два года назад.', 'Бино танҳо ду сол пеш сохта шудааст.'),
        ("What is the owner's job?", 'Кем работает владелица?', 'Соҳиби хона бо кадом касб кор мекунад?',
         ['A teacher', 'A doctor', 'An agent'], 'A teacher',
         'The owner works as a teacher nearby.', 'Владелица работает учителем неподалёку.', 'Соҳиби хона дар наздикӣ муаллима кор мекунад.'),
    ],
    98: [
        ('What has the narrator already finished unpacking?', 'Что рассказчик уже распаковал?', 'Ровӣ бастабандии чиро аллакай кушодааст?',
         ['The kitchen', 'The bedroom', 'The living room'], 'The kitchen',
         "The narrator says 'I've already finished the kitchen.'", 'Рассказчик говорит: «Я уже закончил с кухней».', 'Ровӣ мегӯяд: «Ман ошхонаро аллакай тамом кардам».'),
        ("What hasn't been touched yet?", 'До чего ещё не дошли руки?', 'Дасти кӣ ба чӣ ҳанӯз нарасидааст?',
         ['The bedroom', 'The kitchen', 'The hallway'], 'The bedroom',
         "The narrator hasn't touched the bedroom yet.", 'Рассказчик ещё не занимался спальней.', 'Ровӣ ба хобгоҳ ҳанӯз даст назадааст.'),
        ('Have they registered their new address?', 'Зарегистрировали ли они новый адрес?', 'Оё онҳо суроғаи навро сабт карданд?',
         ['Not yet', 'Yes, already', "They don't need to"], 'Not yet',
         "The narrator says 'We haven't done that yet.'", 'Рассказчик говорит: «Мы ещё этого не сделали».', 'Ровӣ мегӯяд: «Мо ин корро ҳанӯз накардаем».'),
    ],
    99: [
        ('When did they say they would call?', 'Когда они обещали позвонить?', 'Онҳо кай занг заданро ваъда доданд?',
         ['By Friday', 'By Monday', 'The next day'], 'By Friday',
         "Sitora says 'They said they'd call by Friday.'", 'Ситора говорит: «Они сказали, что позвонят к пятнице».', 'Ситора мегӯяд: «Онҳо гуфтанд, ки то ҷумъа занг мезананд».'),
        ('How many other companies has Sitora applied to?', 'В сколько ещё компаний Ситора подала заявку?', 'Ситора ба чанд ширкати дигар аризаи кор додааст?',
         ['Two', 'Three', 'One'], 'Two',
         'Sitora has already applied to two other companies.', 'Ситора уже подала заявку в две другие компании.', 'Ситора ба ду ширкати дигар аллакай ариза додааст.'),
        ('Has Sitora told her parents about the interview?', 'Рассказала ли Ситора родителям о собеседовании?', 'Оё Ситора ба волидонаш дар бораи мусоҳиба гуфт?',
         ['Not yet', 'Yes', "She doesn't have parents"], 'Not yet',
         "Sitora hasn't told her parents about the interview yet.", 'Ситора пока не рассказала родителям о собеседовании.', 'Ситора то ҳол ба волидонаш дар бораи мусоҳиба нагуфтааст.'),
    ],
    100: [
        ('Which cafe is cheaper?', 'Какое кафе дешевле?', 'Кадом кафе арзонтар аст?',
         ['The one on the corner', 'The modern one', 'Both are the same'], 'The one on the corner',
         'The corner café is cheaper than the one opposite.', 'Кафе на углу дешевле, чем кафе напротив.', 'Кафеи гӯшагӣ аз кафеи рӯ ба рӯ арзонтар аст.'),
        ('Which cafe is busier in the evenings?', 'Какое кафе более людное вечером?', 'Кадом кафе бегоҳирӯзӣ шулуғтар аст?',
         ['The modern one', 'The corner one', 'Neither'], 'The modern one',
         'The modern café fills up faster in the evenings.', 'Современное кафе быстрее заполняется вечером.', 'Кафеи муосир бегоҳирӯзӣ тезтар пур мешавад.'),
        ("How is the corner cafe's coffee compared to its rival?", 'Каков кофе в угловом кафе по сравнению с конкурентом?', 'Қаҳваи кафеи гӯшагӣ нисбат ба рақибаш чӣ гуна аст?',
         ['Not as strong', 'Stronger', 'The same'], 'Not as strong',
         "The corner café's coffee isn't as strong as its rival's.", 'Кофе в угловом кафе не такой крепкий, как у конкурента.', 'Қаҳваи кафеи гӯшагӣ ба монанди рақибаш тунд нест.'),
    ],
    101: [
        ('What does the daughter say is missing?', 'Чего, по словам дочери, не хватает?', 'Духтар мегӯяд, ки чӣ намерасад?',
         ['Enough sauce for the rice', 'More bread', 'A fork'], 'Enough sauce for the rice',
         "The girl complains 'There isn't enough sauce for the rice.'", 'Девочка жалуется: «Соуса для риса недостаточно».', 'Духтарак шикоят мекунад: «Барои биринҷ соус кам аст».'),
        ('Is this restaurant expensive compared to others they tried?', 'Этот ресторан дорогой по сравнению с другими, которые они пробовали?', 'Ин тарабхона нисбат ба дигарҳое, ки санҷиданд, гарон аст?',
         ['No, it is the cheapest of the three', 'Yes, the most expensive', 'About the same'], 'No, it is the cheapest of the three',
         "The husband says it's 'the cheapest of the three restaurants.'", 'Муж говорит, что это «самый дешёвый из трёх ресторанов».', 'Шавҳар мегӯяд, ки ин «арзонтарин аз се тарабхона» аст.'),
        ('What does the waiter bring without being asked twice?', 'Что официант приносит, не переспрашивая?', 'Пешхидмат бе такрор мепурсидан чӣ меорад?',
         ['Extra sauce', 'The bill', 'More bread'], 'Extra sauce',
         'The very patient waiter brings extra sauce right away.', 'Очень терпеливый официант сразу приносит дополнительный соус.', 'Пешхидмати сабрнок фавран соуси иловагӣ меорад.'),
    ],
    102: [
        ('What does Umar predict?', 'Что предсказывает Умар?', 'Умар чиро пешгӯӣ мекунад?',
         ["It won't rain today", 'It will snow', 'It will be very hot'], "It won't rain today",
         "Umar announces 'It won't rain today.'", 'Умар объявляет: «Сегодня дождя не будет».', 'Умар эълон мекунад: «Имрӯз борон намеборад».'),
        ('What actually happens?', 'Что происходит на самом деле?', 'Дар асл чӣ рӯй медиҳад?',
         ['It rains heavily', 'It stays sunny', 'It snows'], 'It rains heavily',
         'Dark clouds appear and it rains heavily by lunchtime.', 'Появляются тёмные тучи, и к обеду идёт сильный дождь.', 'Абрҳои торик пайдо мешаванд ва то нисфирӯзӣ борони сахт меборад.'),
        ('How many coffees does Umar owe by the end?', 'Сколько кофе должен Умар в конце?', 'Умар дар охир чанд қаҳва қарздор аст?',
         ['Three', 'One', 'Five'], 'Three',
         "The story says 'This week, Umar owes three coffees already.'", 'В истории сказано: «На этой неделе Умар уже должен три кофе».', 'Дар ҳикоя гуфта мешавад: «Дар ин ҳафта Умар аллакай се қаҳва қарздор аст».'),
    ],
    103: [
        ("Whose birthday are they planning?", 'Чей день рождения они планируют?', 'Онҳо рӯзи таваллуди киро нақша мегиранд?',
         ["Grandma's", "Malika's", "The youngest brother's"], "Grandma's",
         "Malika asks about organizing 'a surprise party for grandma's birthday.'", 'Малика спрашивает об организации «сюрприза на день рождения бабушки».', 'Малика дар бораи ташкили «ҷашни ногаҳонӣ барои рӯзи таваллуди бибӣ» мепурсад.'),
        ('Who will bake the cake?', 'Кто испечёт торт?', 'Тортро кӣ мепазад?',
         ['Malika', 'Her sister', 'Grandma herself'], 'Malika',
         "They decide 'she'll bake it' - Malika will bake the cake.", 'Они решают: торт испечёт Малика.', 'Онҳо қарор мекунанд, ки тортро Малика мепазад.'),
        ('What present do they plan besides the party?', 'Какой подарок они планируют помимо праздника?', 'Ба ғайр аз ҷашн, онҳо кадом тӯҳфаро нақша мегиранд?',
         ['A blue scarf', 'A photo album', 'A necklace'], 'A blue scarf',
         'Grandma admired a blue scarf, so that will be part of her present.', 'Бабушке понравился синий шарф, поэтому это будет частью подарка.', 'Ба бибӣ рӯймоли кабуд маъқул шуд, аз ин рӯ он қисми тӯҳфа мешавад.'),
    ],
    104: [
        ('What two things does Rustam decide to change?', 'Какие две вещи Рустам решает изменить?', 'Рустам ду чизро дигар кардан мехоҳад — кадомҳо?',
         ['Stop eating sugar and start running', 'Sleep more and eat more', 'Quit his job and travel'], 'Stop eating sugar and start running',
         "Rustam chooses 'to stop eating sugar and to start running every morning.'", 'Рустам решает «отказаться от сахара и начать бегать каждое утро».', 'Рустам қарор мекунад «шакарро тарк кунад ва ҳар субҳ давиданро сар кунад».'),
        ('What was hardest for Rustam?', 'Что было труднее всего для Рустама?', 'Барои Рустам чӣ душвортарин буд?',
         ['Waking up early', 'Cooking dinner', 'Talking to the doctor'], 'Waking up early',
         "Waking up early was the hardest part for him.", 'Просыпаться рано было для него самым трудным.', 'Барвақт бедор шудан барои ӯ душвортарин буд.'),
        ('What does his wife suggest?', 'Что предлагает его жена?', 'Занаш чӣ пешниҳод мекунад?',
         ['Cooking dinner together instead of ordering food', 'Going to the gym together', 'Eating more sugar'], 'Cooking dinner together instead of ordering food',
         'His wife suggested cooking dinner together instead of ordering food.', 'Его жена предложила готовить ужин вместе, а не заказывать еду.', 'Занаш пешниҳод кард, ки якҷоя шом пазанд, на фармоиши хӯрок диҳанд.'),
    ],
    105: [
        ('What must students switch off?', 'Что студенты должны выключить?', 'Донишҷӯён бояд чиро хомӯш кунанд?',
         ['Their phones', 'Their watches', 'Their laptops'], 'Their phones',
         "The supervisor says 'You must switch off your phones completely.'", 'Наблюдатель говорит: «Вы должны полностью выключить телефоны».', 'Нозир мегӯяд: «Шумо бояд телефонҳоятонро комилан хомӯш кунед».'),
        ('What must students bring?', 'Что студенты должны принести?', 'Донишҷӯён бояд чиро бо худ гиранд?',
         ['A valid student card', 'Their own pens', 'A calculator'], 'A valid student card',
         'They have to bring a valid student card.', 'Они должны принести действующий студенческий билет.', 'Онҳо бояд билети донишҷӯии эътиборнок дошта бошанд.'),
        ('Do students have to bring their own pens?', 'Должны ли студенты приносить свои ручки?', 'Оё донишҷӯён бояд қалами худро биёранд?',
         ['No, the school provides them', 'Yes, always', 'Only for the essay part'], 'No, the school provides them',
         'Students do not have to bring their own pens since the school provides them.', 'Студентам не нужно приносить свои ручки, школа их выдаёт.', 'Донишҷӯён набояд қалами худро биёранд, мактаб медиҳад.'),
    ],
    106: [
        ('What does Farida want to decide?', 'Что Фарида хочет решить?', 'Фарида чиро ҳал кардан мехоҳад?',
         ['Whether to change her job', 'Whether to move house', 'Whether to study abroad'], 'Whether to change her job',
         "Farida can't decide whether to change her job.", 'Фарида не может решить, менять ли работу.', 'Фарида ҳал карда наметавонад, ки ҷои корашро иваз кунад ё не.'),
        ('What does the sister suggest Farida do first?', 'Что сестра советует Фариде сделать сначала?', 'Хоҳар ба Фарида чӣ маслиҳат медиҳад, ки аввал кунад?',
         ['Talk to her manager', 'Quit immediately', 'Ask for a raise first'], 'Talk to her manager',
         "The sister says 'You should talk to your manager first.'", 'Сестра говорит: «Сначала поговори со своим руководителем».', 'Хоҳар мегӯяд: «Аввал бо роҳбаратон гап занед».'),
        ('What is Farida afraid of?', 'Чего боится Фарида?', 'Фарида аз чӣ метарсад?',
         ['Starting somewhere new', 'Losing her salary', 'Talking to her sister'], 'Starting somewhere new',
         'Farida is afraid of starting somewhere new.', 'Фарида боится начинать что-то новое.', 'Фарида аз оғози ҷои нав метарсад.'),
    ],
    107: [
        ('What is the picnic plan if it rains?', 'Какой план на пикник, если пойдёт дождь?', 'Агар борон борад, нақшаи пикник чист?',
         ["Move everything to Aziza's place", 'Cancel the picnic', 'Go anyway'], "Move everything to Aziza's place",
         "Aziza says 'If it rains, we'll move everything to my place instead.'", 'Азиза говорит: «Если пойдёт дождь, мы всё перенесём ко мне».', 'Азиза мегӯяд: «Агар борон борад, ҳамаашро ба хонаи ман мебарем».'),
        ('What do the friends argue about?', 'О чём спорят друзья?', 'Дӯстон дар бораи чӣ баҳс мекунанд?',
         ['Whose basket it is', 'What food to bring', 'What time to meet'], 'Whose basket it is',
         'They argue about who owns the heavy basket and who should carry it.', 'Они спорят, чья это тяжёлая корзина и кто должен её нести.', 'Онҳо дар бораи он ки сабади вазнин аз они кист ва кӣ бояд бардорад, баҳс мекунанд.'),
        ('Where do they want the best spot?', 'Где они хотят занять лучшее место?', 'Онҳо ҷои беҳтаринро дар куҷо мехоҳанд?',
         ['Near the lake', 'Under a tree', 'Near the entrance'], 'Near the lake',
         'If everyone arrives on time, they will catch the best spot near the lake.', 'Если все придут вовремя, они займут лучшее место у озера.', 'Агар ҳама бавақт расанд, ҷои беҳтаринро дар назди кӯл мегиранд.'),
    ],
    108: [
        ('What would Aziz buy if he won the lottery?', 'Что бы Азиз купил, если бы выиграл в лотерею?', 'Агар Азиз лотереяро бурд, чӣ мехарид?',
         ['A small house by the sea', 'A sports car', 'A big company'], 'A small house by the sea',
         "Aziz says 'If I won the lottery, I would buy a small house by the sea.'", 'Азиз говорит: «Если бы я выиграл в лотерею, я бы купил небольшой дом у моря».', 'Азиз мегӯяд: «Агар лотереяро бурда бошам, хонаи хурде дар лаби баҳр мехарам».'),
        ('Would Aziz quit his job completely?', 'Азиз бы полностью бросил работу?', 'Оё Азиз корашро тамоман тарк мекард?',
         ["No, he'd work part-time", 'Yes, immediately', "He hasn't decided"], "No, he'd work part-time",
         "Aziz says 'I wouldn't quit my job completely, though — I'd probably work part-time.'", 'Азиз говорит: «Но я бы не бросил работу полностью — вероятно, работал бы неполный день».', 'Азиз мегӯяд: «Вале корамро комилан тарк намекунам — эҳтимол нимрӯза кор мекунам».'),
        ('What does Aziz worry relatives would do?', 'Чего Азиз боится по поводу родственников?', 'Азиз аз хешовандон чиро метарсад?',
         ['Ask for loans', 'Move in with him', 'Stop talking to him'], 'Ask for loans',
         'A friend jokes that relatives would appear from nowhere asking for loans.', 'Друг шутит, что родственники появятся из ниоткуда и попросят денег в долг.', 'Дӯст ба ҳазл мегӯяд, ки хешовандон ногаҳон пайдо шуда қарз металабанд.'),
    ],
    109: [
        ('How long have Malika and Nodira known each other?', 'Сколько лет знакомы Малика и Нодира?', 'Малика ва Нодира чанд сол шуд, ки шинос ҳастанд?',
         ['Almost twenty years', 'Ten years', 'Five years'], 'Almost twenty years',
         'They have known each other since primary school, almost twenty years.', 'Они знакомы с начальной школы, почти двадцать лет.', 'Онҳо аз мактаби ибтидоӣ шиносанд, қариб бист сол.'),
        ('When did they last meet in person before this?', 'Когда они в последний раз встречались лично до этого?', 'Онҳо пеш аз ин бор охирин маротиба кай рӯ ба рӯ вохӯрданд?',
         ['Two years ago', 'Last month', 'Five years ago'], 'Two years ago',
         'They last met in person two years ago at a family event.', 'В последний раз они встречались лично два года назад на семейном мероприятии.', 'Онҳо охирин бор ду сол пеш дар як маросими оилавӣ вохӯрданд.'),
        ("Where did they get lost, according to Malika's memory?", 'Где они заблудились, судя по воспоминанию Малики?', 'Тибқи хотираи Малика, онҳо дар куҷо гум шуда буданд?',
         ['The old town', 'The market', 'The train station'], 'The old town',
         "Malika recalls 'when we got lost in the old town.'", 'Малика вспоминает: «когда мы заблудились в старом городе».', 'Малика ба ёд меорад: «вақте ки мо дар шаҳри кӯҳна гум шудем».'),
    ],
    110: [
        ('What does Jahongir have to carry?', 'Что Джахонгир должен нести?', 'Ҷаҳонгир бояд чиро бардорад?',
         ['A heavy tyre', 'A wooden box', 'A water bottle'], 'A heavy tyre',
         'Jahongir has to carry a heavy tyre from one point to another.', 'Джахонгир должен нести тяжёлую покрышку от одной точки до другой.', 'Ҷаҳонгир бояд шинаи вазнинро аз як нуқта ба нуқтаи дигар бардорад.'),
        ('What cold thing does he cross?', 'Через что холодное он переправляется?', 'Ӯ аз кадом чизи хунук мегузарад?',
         ['A river', 'A lake', 'A stream of ice'], 'A river',
         'Jahongir splashes straight into the cold river crossing.', 'Джахонгир прыгает прямо в холодную реку на переправе.', 'Ҷаҳонгир мустақим ба дарёи хунук ҷаҳида мегузарад.'),
        ('How does Jahongir feel at the finish?', 'Что чувствует Джахонгир на финише?', 'Ҷаҳонгир дар хат-и хотимавӣ чӣ ҳис мекунад?',
         ['Exhausted but proud', 'Angry', 'Bored'], 'Exhausted but proud',
         'He crosses the line exhausted but proud.', 'Он пересекает финиш измождённым, но гордым.', 'Ӯ хаста, вале бо ифтихор аз хат мегузарад.'),
    ],
    111: [
        ('What time does the bakery open?', 'Во сколько открывается пекарня?', 'Нонвойхона соати чанд кушода мешавад?',
         ['Four o\'clock', 'Six o\'clock', 'Seven o\'clock'], 'Four o\'clock',
         'The bakery is opened at four o\'clock every morning.', 'Пекарня открывается каждое утро в четыре часа.', 'Нонвойхона ҳар субҳ соати чор кушода мешавад.'),
        ('How long is the dough kneaded?', 'Сколько времени месят тесто?', 'Хамир чанд вақт вармекунанд?',
         ['Almost twenty minutes', 'Ten minutes', 'One hour'], 'Almost twenty minutes',
         'The dough is kneaded by hand for almost twenty minutes.', 'Тесто месят вручную почти двадцать минут.', 'Хамирро бо даст қариб бист дақиқа вармекунанд.'),
        ('How long is each loaf baked?', 'Сколько времени выпекается каждый батон?', 'Ҳар як нон чанд вақт пухта мешавад?',
         ['Forty minutes', 'Twenty minutes', 'One hour'], 'Forty minutes',
         'Each loaf is baked for exactly forty minutes.', 'Каждый батон выпекается ровно сорок минут.', 'Ҳар нон маҳз чил дақиқа пухта мешавад.'),
    ],
    112: [
        ('What subject did Mr Aliyev teach?', 'Какой предмет преподавал мистер Алиев?', 'Ҷаноби Алиев кадом фанро таълим медод?',
         ['Maths', 'English', 'History'], 'Maths',
         'Mr Aliyev used to teach maths for almost thirty years.', 'Мистер Алиев преподавал математику почти тридцать лет.', 'Ҷаноби Алиев қариб сӣ сол математикаро таълим медод.'),
        ('How long did he use to walk to school?', 'Сколько он раньше шёл пешком до школы?', 'Ӯ пештар то мактаб чанд вақт пиёда мерафт?',
         ['Two hours', 'One hour', 'Thirty minutes'], 'Two hours',
         "He says 'I used to walk two hours to get here every morning.'", 'Он говорит: «Раньше я шёл сюда пешком два часа каждое утро».', 'Ӯ мегӯяд: «Пештар ман ҳар субҳ ду соат пиёда ба ин ҷо мерафтам».'),
        ('What extra classes did he used to give?', 'Какие дополнительные занятия он раньше вёл?', 'Ӯ кадом дарсҳои иловагиро пештар медод?',
         ['Saturday maths classes', 'Sunday sports classes', 'Evening English classes'], 'Saturday maths classes',
         'He used to give extra maths classes on Saturdays.', 'Раньше он вёл дополнительные занятия по математике по субботам.', 'Ӯ пештар рӯзҳои шанбе дарсҳои иловагии математика медод.'),
    ],
    113: [
        ('What does Sabina want to do this weekend?', 'Что Сабина хочет сделать в эти выходные?', 'Сабина ин истироҳат чӣ кардан мехоҳад?',
         ['Go hiking', 'Go swimming', 'Stay home'], 'Go hiking',
         "Sabina says 'I might go hiking this weekend.'", 'Сабина говорит: «Я, возможно, пойду в поход в эти выходные».', 'Сабина мегӯяд: «Ман шояд ин истироҳат ба сайри кӯҳ равам».'),
        ('Do they both dislike crowded places?', 'Оба ли они не любят людные места?', 'Оё ҳарду ҷойҳои шулуғро дӯст намедоранд?',
         ['Yes', 'No, only Sabina', 'No, only her colleague'], 'Yes',
         "Both say they don't enjoy crowded places, agreeing with 'Neither do I.'", 'Оба говорят, что не любят людные места, соглашаясь фразой «Я тоже нет».', 'Ҳарду мегӯянд, ки ҷойҳои шулуғро дӯст намедоранд, бо ибораи «Ман ҳам не» розӣ мешаванд.'),
        ('Where do they agree to meet?', 'Где они договариваются встретиться?', 'Онҳо дар куҷо вохӯрданро розӣ мешаванд?',
         ['The trail entrance', 'The office', 'The bus stop'], 'The trail entrance',
         'They arrange to meet at the trail entrance on Saturday morning.', 'Они договариваются встретиться у входа на тропу в субботу утром.', 'Онҳо субҳи шанбе назди даромадгоҳи роҳи кӯҳ вохӯрданро розӣ мешаванд.'),
    ],
}


async def main():
    async with AsyncSessionLocal() as db:
        created = 0
        for story_id, questions in Q.items():
            for text_en, text_ru, text_tg, options, answer, expl_en, expl_ru, expl_tg in questions:
                db.add(StoryQuestions(
                    story_id=story_id,
                    text_en=text_en,
                    text_ru=text_ru,
                    text_tg=text_tg,
                    options=options,
                    answer=answer,
                    explanation_en=expl_en,
                    explanation_ru=expl_ru,
                    explanation_tg=expl_tg,
                ))
                created += 1
        await db.commit()
        print(f'created {created} story questions for {len(Q)} stories')


asyncio.run(main())
