# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
88: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'learn': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'drive': {'ru': 'водить (машину)', 'tg': 'мошин рондан', 'lemma': 'drive'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'calm': {'ru': 'спокойный', 'tg': 'ором', 'lemma': 'calm'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'thirty': {'ru': 'тридцать', 'tg': 'си', 'lemma': 'thirty'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'experience': {'ru': 'опыт', 'tg': 'таҷриба', 'lemma': 'experience'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'lesson': {'ru': 'урок', 'tg': 'дарс', 'lemma': 'lesson'},
    'spoke': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'slowly': {'ru': 'медленно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'clearly': {'ru': 'ясно (чётко)', 'tg': 'равшан', 'lemma': 'clearly'},
    'rule': {'ru': 'правило', 'tg': 'қоида', 'lemma': 'rule'},
    'number': {'ru': 'номер (число)', 'tg': 'рақам', 'lemma': 'number'},
    'carefully': {'ru': 'осторожно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'quickly': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'quickly'},
    'decide': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'calmly': {'ru': 'спокойно', 'tg': 'ором', 'lemma': 'calmly'},
    'started': {'ru': 'заводить (начинать)', 'tg': 'сар кардан', 'lemma': 'start'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'nervously': {'ru': 'нервно', 'tg': 'бо асабоният', 'lemma': 'nervously'},
    'moved': {'ru': 'двигаться', 'tg': 'ҳаракат кардан', 'lemma': 'move'},
    'backwards': {'ru': 'назад', 'tg': 'ба ақиб', 'lemma': 'backwards'},
    'interesting': {'ru': 'интересный', 'tg': 'ҷолиб', 'lemma': 'interesting'},
    'choice': {'ru': 'выбор', 'tg': 'интихоб', 'lemma': 'choice'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'quietly': {'ru': 'тихо', 'tg': 'ором', 'lemma': 'quietly'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'students': {'ru': 'ученик', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'forwards': {'ru': 'вперёд', 'tg': 'ба пеш', 'lemma': 'forwards'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'learned': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'stopped': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'smoothly': {'ru': 'плавно', 'tg': 'мулоим', 'lemma': 'smoothly'},
    'traffic': {'ru': 'светофор (движение)', 'tg': 'чароғаки роҳ', 'lemma': 'traffic lights'},
    'lights': {'ru': 'светофор (огни)', 'tg': 'чароғак', 'lemma': 'light'},
    'turned': {'ru': 'поворачивать', 'tg': 'гардидан', 'lemma': 'turn'},
    'correctly': {'ru': 'правильно', 'tg': 'дуруст', 'lemma': 'correctly'},
    'parked': {'ru': 'парковаться', 'tg': 'парк кардан', 'lemma': 'park'},
    'well': {'ru': 'ну (хорошо)', 'tg': 'хайр', 'lemma': 'well'},
    'tried': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'park': {'ru': 'парковаться', 'tg': 'парк кардан', 'lemma': 'park'},
    'parking': {'ru': 'парковка', 'tg': 'паркинг', 'lemma': 'parking'},
    'enemy': {'ru': 'враг', 'tg': 'душман', 'lemma': 'enemy'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'feel': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'patiently': {'ru': 'терпеливо', 'tg': 'бо сабр', 'lemma': 'patiently'},
    'don\'t': DO, 'fight': {'ru': 'бороться', 'tg': 'мубориза бурдан', 'lemma': 'fight'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'exam': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'drove': {'ru': 'водить (ехать)', 'tg': 'рондан', 'lemma': 'drive'},
    'inspector': {'ru': 'инспектор', 'tg': 'нозир', 'lemma': 'inspector'},
    'nodded': {'ru': 'кивать', 'tg': 'сар ҷунбондан', 'lemma': 'nod'},
    'wrote': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'came': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'breathed': {'ru': 'дышать', 'tg': 'нафас кашидан', 'lemma': 'breathe'},
    'deeply': {'ru': 'глубоко', 'tg': 'амиқ', 'lemma': 'deeply'},
    'wheel': {'ru': 'руль', 'tg': 'руль', 'lemma': 'wheel'},
    'gently': {'ru': 'мягко (нежно)', 'tg': 'мулоим', 'lemma': 'gently'},
    'entered': {'ru': 'входить (заезжать)', 'tg': 'даромадан', 'lemma': 'enter'},
    'space': {'ru': 'место (пространство)', 'tg': 'ҷой', 'lemma': 'space'},
    'perfectly': {'ru': 'идеально', 'tg': 'комилан', 'lemma': 'perfectly'},
    'congratulations': {'ru': 'поздравляю', 'tg': 'табрик', 'lemma': 'congratulations'},
    'wanted': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'dance': {'ru': 'танцевать', 'tg': 'рақс кардан', 'lemma': 'dance'},
    'happily': {'ru': 'радостно', 'tg': 'бо шодӣ', 'lemma': 'happily'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'shook': {'ru': 'трясти (пожать)', 'tg': 'ларзондан', 'lemma': 'shake'},
    'hand': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'warmly': {'ru': 'тепло', 'tg': 'гарм', 'lemma': 'warmly'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'driver': {'ru': 'водитель', 'tg': 'ронанда', 'lemma': 'driver'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'stops': {'ru': 'переставать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'learning': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'is': BE, 'was': BE,
},
89: {
    'aunt': {'ru': 'тётя', 'tg': 'хола', 'lemma': 'aunt'},
    'lives': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'canada': {'ru': 'Канада', 'tg': 'Канада', 'lemma': 'Canada'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'sends': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'writes': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'idea': {'ru': 'идея', 'tg': 'ғоя', 'lemma': 'idea'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'break': {'ru': 'ломаться', 'tg': 'шикастан', 'lemma': 'break'},
    'get': {'ru': 'становиться (получать)', 'tg': 'шудан', 'lemma': 'get'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'let\'s': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'let'},
    'experience': {'ru': 'впечатление (опыт)', 'tg': 'таассурот', 'lemma': 'experience'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'tickets': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'mountains': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'stayed': {'ru': 'останавливаться', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'guest': {'ru': 'гостевой (гость)', 'tg': 'меҳмонӣ', 'lemma': 'guest house'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'lake': {'ru': 'озеро', 'tg': 'кӯл', 'lemma': 'lake'},
    'mornings': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'walked': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'forest': {'ru': 'лес', 'tg': 'ҷангал', 'lemma': 'forest'},
    'evenings': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'played': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'games': {'ru': 'игра', 'tg': 'бозӣ', 'lemma': 'game'},
    'drank': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'honey': {'ru': 'мёд', 'tg': 'асал', 'lemma': 'honey'},
    'forgot': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'internet': {'ru': 'интернет', 'tg': 'интернет', 'lemma': 'internet'},
    'any': {'ru': 'какой-либо', 'tg': 'ягон', 'lemma': 'any'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'sent': {'ru': 'отправлять', 'tg': 'фиристодан', 'lemma': 'send'},
    'photo': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'faces': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'white': {'ru': 'белый', 'tg': 'сафед', 'lemma': 'white'},
    'golden': {'ru': 'золотой', 'tg': 'тиллоӣ', 'lemma': 'golden'},
    'sun': {'ru': 'солнце', 'tg': 'офтоб', 'lemma': 'sun'},
    'answered': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'quickly': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'quickly'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'present': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'present'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'december': {'ru': 'декабрь', 'tg': 'декабр', 'lemma': 'December'},
    'come': {'ru': 'приезжать', 'tg': 'омадан', 'lemma': 'come'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'works': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'fine': {'ru': 'в порядке', 'tg': 'хуб', 'lemma': 'fine'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'stay': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'forever': {'ru': 'навсегда', 'tg': 'то абад', 'lemma': 'forever'},
    'right': {'ru': 'правый (правая, права)', 'tg': 'ҳақ', 'lemma': 'right'},
    'memories': {'ru': 'воспоминание', 'tg': 'хотира', 'lemma': 'memory'},
    'is': BE, 'was': BE, 'are': BE, 'is going to': BE, 'going': {'ru': 'собираться', 'tg': 'мехоҳад', 'lemma': 'going to'},
},
90: {
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'film': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'expert': {'ru': 'эксперт', 'tg': 'коршинос', 'lemma': 'expert'},
    'least': {'ru': 'по крайней мере', 'tg': 'ҳадди ақал', 'lemma': 'at least'},
    'thinks': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'favourite': {'ru': 'любимый', 'tg': 'дӯстдоштатарин', 'lemma': 'favourite'},
    'question': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'watched': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'all': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'all'},
    'famous': {'ru': 'известный', 'tg': 'машҳур', 'lemma': 'famous'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'proudly': {'ru': 'гордо', 'tg': 'бо ифтихор', 'lemma': 'proudly'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'ones': {'ru': 'те (штуки)', 'tg': 'онҳо', 'lemma': 'one'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'different': {'ru': 'разный', 'tg': 'гуногун', 'lemma': 'different'},
    'countries': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'friday': {'ru': 'пятница', 'tg': 'ҷумъа', 'lemma': 'Friday'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'club': {'ru': 'клуб', 'tg': 'клуб', 'lemma': 'club'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'classic': {'ru': 'классика', 'tg': 'классика', 'lemma': 'classic'},
    'comedy': {'ru': 'комедия', 'tg': 'комедия', 'lemma': 'comedy'},
    'ah': {'ru': 'ах', 'tg': 'оҳ', 'lemma': 'ah'},
    'one': {'ru': 'этот', 'tg': 'ин', 'lemma': 'one'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'brilliant': {'ru': 'блестящий', 'tg': 'аъло', 'lemma': 'brilliant'},
    'started2': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'looked': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'confused': {'ru': 'растерянный', 'tg': 'гаранг', 'lemma': 'confused'},
    'forty': {'ru': 'сорок', 'tg': 'чил', 'lemma': 'forty'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'french': {'ru': 'французский', 'tg': 'фаронсавӣ', 'lemma': 'French'},
    'ending': {'ru': 'финал (окончание)', 'tg': 'анҷом', 'lemma': 'ending'},
    'sad': {'ru': 'грустный', 'tg': 'ғамгин', 'lemma': 'sad'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'funny': {'ru': 'смешной', 'tg': 'хандаовар', 'lemma': 'funny'},
    'whispered': {'ru': 'шептать', 'tg': 'пичиррос задан', 'lemma': 'whisper'},
    'really': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'really'},
    'like': {'ru': 'как (подобно)', 'tg': 'мисли', 'lemma': 'like'},
    'tomato': {'ru': 'помидор', 'tg': 'помидор', 'lemma': 'tomato'},
    'poster': {'ru': 'постер (афиша)', 'tg': 'плакат', 'lemma': 'poster'},
    'many': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'many'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'class': {'ru': 'класс', 'tg': 'синф', 'lemma': 'class'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'rule': {'ru': 'правило', 'tg': 'қоида', 'lemma': 'rule'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    've': BE, 'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'is': BE, 'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'was': BE,
},
91: {
    'grandfather': {'ru': 'дедушка', 'tg': 'бобо', 'lemma': 'grandfather'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'map': {'ru': 'карта', 'tg': 'харита', 'lemma': 'map'},
    'wall': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'red': {'ru': 'красный', 'tg': 'сурх', 'lemma': 'red'},
    'pins': {'ru': 'булавка', 'tg': 'сӯзан', 'lemma': 'pin'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'place': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'visited': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'eleven': {'ru': 'одиннадцать', 'tg': 'ёздаҳ', 'lemma': 'eleven'},
    'countries': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'told': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'india': {'ru': 'Индия', 'tg': 'Ҳиндустон', 'lemma': 'India'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'went': {'ru': 'ехать', 'tg': 'рафтан', 'lemma': 'go'},
    'there': {'ru': 'туда', 'tg': 'ба он ҷо', 'lemma': 'there'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'engineer': {'ru': 'инженер', 'tg': 'муҳандис', 'lemma': 'engineer'},
    'built': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'power': {'ru': 'станция (энергия)', 'tg': 'нерӯгоҳ', 'lemma': 'power station'},
    'station': {'ru': 'станция', 'tg': 'истгоҳ', 'lemma': 'station'},
    'heat': {'ru': 'жара', 'tg': 'гармӣ', 'lemma': 'heat'},
    'unbelievable': {'ru': 'невероятный', 'tg': 'бовариннопазир', 'lemma': 'unbelievable'},
    'china': {'ru': 'Китай', 'tg': 'Чин', 'lemma': 'China'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'time': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'uncle': {'ru': 'дядя', 'tg': 'тағо', 'lemma': 'uncle'},
    'took': {'ru': 'брать (вести)', 'tg': 'бурдан', 'lemma': 'take'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'changed': {'ru': 'меняться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'rode': {'ru': 'ездить (на велосипеде)', 'tg': 'сувор шудан', 'lemma': 'ride'},
    'bicycles': {'ru': 'велосипед', 'tg': 'велосипед', 'lemma': 'bicycle'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'cities': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'electric': {'ru': 'электрический', 'tg': 'электрикӣ', 'lemma': 'electric'},
    'cars': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'looked': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'which': {'ru': 'который (какой)', 'tg': 'кадом', 'lemma': 'which'},
    'country': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'loved': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'most': {'ru': 'больше всего (самое)', 'tg': 'бештар аз ҳама', 'lemma': 'most'},
    'smiled': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'put': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'put'},
    'finger': {'ru': 'палец', 'tg': 'ангушт', 'lemma': 'finger'},
    'tajikistan': {'ru': 'Таджикистан', 'tg': 'Тоҷикистон', 'lemma': 'Tajikistan'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'places': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'better': {'ru': 'лучший (лучше)', 'tg': 'беҳтар', 'lemma': 'better'},
    'than': {'ru': 'чем', 'tg': 'нисбат ба', 'lemma': 'than'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'dear': {'ru': 'дорогой', 'tg': 'азиз', 'lemma': 'dear'},
    'see': {'ru': 'увидеть', 'tg': 'дидан', 'lemma': 'see'},
    'world': {'ru': 'мир', 'tg': 'дунё', 'lemma': 'world'},
    'you\'ll': {'ru': 'ты (буд. время)', 'tg': 'ту хоҳӣ', 'lemma': 'you'},
    'understand': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'far': {'ru': 'пока (до сих пор)', 'tg': 'то ҳол', 'lemma': 'so far'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'made': {'ru': 'делать (составлять)', 'tg': 'тартиб додан', 'lemma': 'make'},
    'list': {'ru': 'список', 'tg': 'рӯйхат', 'lemma': 'list'},
    'journey': {'ru': 'путешествие', 'tg': 'сафар', 'lemma': 'journey'},
    'just': {'ru': 'только что', 'tg': 'ҳозиргина', 'lemma': 'just'},
    'started2': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'is': BE, 'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
},
92: {
    'speed': {'ru': 'скоростной (быстрый)', 'tg': 'тезбозор', 'lemma': 'speed dating'},
    'event': {'ru': 'мероприятие', 'tg': 'ҳодиса', 'lemma': 'event'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'couple': {'ru': 'пара', 'tg': 'ҷуфт', 'lemma': 'couple'},
    'exactly': {'ru': 'ровно (точно)', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'bell': {'ru': 'звонок', 'tg': 'занг', 'lemma': 'bell'},
    'rings': {'ru': 'звонить (о звонке)', 'tg': 'занг задан', 'lemma': 'ring'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'across': {'ru': 'напротив', 'tg': 'дар рӯ ба рӯ', 'lemma': 'across'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'paint': {'ru': 'рисовать', 'tg': 'рассомӣ кардан', 'lemma': 'paint'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'miss': {'ru': 'пропускать', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'run': {'ru': 'бег (пробежка)', 'tg': 'давидан', 'lemma': 'run'},
    'seems': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'confident': {'ru': 'уверенный', 'tg': 'боэътимод', 'lemma': 'confident'},
    'funny': {'ru': 'весёлый', 'tg': 'хушмуомила', 'lemma': 'funny'},
    'likes': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'holiday': {'ru': 'отпуск', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'back': {'ru': 'в ответ', 'tg': 'дар ҷавоб', 'lemma': 'back'},
    'much': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'much'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'cooking': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'talking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'moves': {'ru': 'переходить', 'tg': 'гузаштан', 'lemma': 'move'},
    'next': {'ru': 'следующий', 'tg': 'навбатӣ', 'lemma': 'next'},
    'disappointed': {'ru': 'разочарованный', 'tg': 'ноумед', 'lemma': 'disappointed'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'conversations': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'thinks': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'answers': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'organizer': {'ru': 'организатор', 'tg': 'ташкилкунанда', 'lemma': 'organizer'},
    'reads': {'ru': 'читать (оглашать)', 'tg': 'хондан', 'lemma': 'read out'},
    'matches': {'ru': 'совпадение (пара)', 'tg': 'мутобиқат', 'lemma': 'match'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'nine': {'ru': 'девять', 'tg': 'нӯҳ', 'lemma': 'nine'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'chose': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'relief': {'ru': 'облегчение', 'tg': 'сабукӣ', 'lemma': 'relief'},
    'exactly2': {'ru': 'именно', 'tg': 'маҳз', 'lemma': 'exactly'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'number': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'time': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'there\'s': BE, 'stop': {'ru': 'останавливать', 'tg': 'қатъ кардан', 'lemma': 'stop'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'is': BE, 'don\'t': DO,
},
93: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'friday': {'ru': 'пятница', 'tg': 'ҷумъа', 'lemma': 'Friday'},
    'millions': {'ru': 'миллион', 'tg': 'миллион', 'lemma': 'million'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'television': {'ru': 'телевидение', 'tg': 'телевизион', 'lemma': 'television'},
    'show': {'ru': 'шоу (передача)', 'tg': 'намоиш', 'lemma': 'show'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'follows': {'ru': 'следовать', 'tg': 'пайравӣ кардан', 'lemma': 'follow'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'pattern': {'ru': 'шаблон (модель)', 'tg': 'намуна', 'lemma': 'pattern'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'lives': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'tired': {'ru': 'усталый (изношенный)', 'tg': 'фарсуда', 'lemma': 'tired'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'designers': {'ru': 'дизайнер', 'tg': 'дизайнер', 'lemma': 'designer'},
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'plans': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'standing': {'ru': 'стоять', 'tg': 'истодан', 'lemma': 'stand'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'watching': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'workers': {'ru': 'рабочий', 'tg': 'коргар', 'lemma': 'worker'},
    'carry': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'furniture': {'ru': 'мебель', 'tg': 'мебел', 'lemma': 'furniture'},
    'out': {'ru': 'наружу', 'tg': 'берун', 'lemma': 'out'},
    'renovating': {'ru': 'ремонтировать', 'tg': 'таъмир кардан', 'lemma': 'renovate'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'bathroom': {'ru': 'ванная', 'tg': 'ҳаммомхона', 'lemma': 'bathroom'},
    'explains': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'lead': {'ru': 'ведущий (главный)', 'tg': 'асосӣ', 'lemma': 'lead'},
    'designer': {'ru': 'дизайнер', 'tg': 'дизайнер', 'lemma': 'designer'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'painting': {'ru': 'красить', 'tg': 'ранг кардан', 'lemma': 'paint'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'colour': {'ru': 'цвет', 'tg': 'ранг', 'lemma': 'colour'},
    'spend': {'ru': 'тратить', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'little': {'ru': 'немного', 'tg': 'андак', 'lemma': 'little'},
    'nervous': {'ru': 'нервный', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'right': {'ru': 'прямо', 'tg': 'маҳз', 'lemma': 'right'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'one': {'ru': 'один (некто)', 'tg': 'як нафар', 'lemma': 'one'},
    'worker': {'ru': 'рабочий', 'tg': 'коргар', 'lemma': 'worker'},
    'knocking': {'ru': 'сносить (стучать)', 'tg': 'вайрон кардан', 'lemma': 'knock down'},
    'wall': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'while': {'ru': 'пока (в то время как)', 'tg': 'дар ҳоле ки', 'lemma': 'while'},
    'another': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'another'},
    'measuring': {'ru': 'измерять', 'tg': 'ченидан', 'lemma': 'measure'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'island': {'ru': 'остров (кухонный)', 'tg': 'ҷазира', 'lemma': 'island'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'episode': {'ru': 'эпизод (серия)', 'tg': 'қисм', 'lemma': 'episode'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'currently': {'ru': 'в настоящее время', 'tg': 'ҳоло', 'lemma': 'currently'},
    'relatives': {'ru': 'родственники', 'tg': 'хешовандон', 'lemma': 'relative'},
    'counting': {'ru': 'считать', 'tg': 'шумурдан', 'lemma': 'count'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'until': {'ru': 'до тех пор пока', 'tg': 'то', 'lemma': 'until'},
    'move': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'back': {'ru': 'назад', 'tg': 'бозгашт', 'lemma': 'back'},
    'believe': {'ru': 'верить', 'tg': 'бовар кардан', 'lemma': 'believe'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'camera': {'ru': 'камера', 'tg': 'камера', 'lemma': 'camera'},
    'never2': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'exciting': {'ru': 'захватывающий', 'tg': 'ҳаяҷонбахш', 'lemma': 'exciting'},
    'is': BE, 'are': BE, 'we\'re': BE, 'they\'re': BE, 'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'}, 'doesn\'t': DO,
},
94: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'tuesday': {'ru': 'вторник', 'tg': 'сешанбе', 'lemma': 'Tuesday'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'neighbourhood': {'ru': 'район (округа)', 'tg': 'маҳалла', 'lemma': 'neighbourhood'},
    'lost': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'electricity': {'ru': 'электричество', 'tg': 'барқ', 'lemma': 'electricity'},
    'exactly': {'ru': 'ровно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'eight': {'ru': 'восемь', 'tg': 'ҳашт', 'lemma': 'eight'},
    'cooking': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'lights': {'ru': 'свет', 'tg': 'равшанӣ', 'lemma': 'light'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'went': {'ru': 'гаснуть (уходить)', 'tg': 'хомӯш шудан', 'lemma': 'go out'},
    'lit': {'ru': 'зажигать', 'tg': 'даргирондан', 'lemma': 'light'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'candles': {'ru': 'свеча', 'tg': 'шам', 'lemma': 'candle'},
    'continued': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'chopping': {'ru': 'резать (мелко)', 'tg': 'реза кардан', 'lemma': 'chop'},
    'vegetables': {'ru': 'овощ', 'tg': 'сабзавот', 'lemma': 'vegetable'},
    'dark': {'ru': 'тёмный', 'tg': 'торик', 'lemma': 'dark'},
    'kitchen': {'ru': 'кухня', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'meanwhile': {'ru': 'тем временем', 'tg': 'дар айни ҳол', 'lemma': 'meanwhile'},
    'neighbours': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'sitting': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'talking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'laughing': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'under': {'ru': 'под', 'tg': 'дар зери', 'lemma': 'under'},
    'stars': {'ru': 'звезда', 'tg': 'ситора', 'lemma': 'star'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'studying': {'ru': 'учиться', 'tg': 'таҳсил кардан', 'lemma': 'study'},
    'exam': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'complained': {'ru': 'жаловаться', 'tg': 'шикоят кардан', 'lemma': 'complain'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'laptop': {'ru': 'ноутбук', 'tg': 'лэптоп', 'lemma': 'laptop'},
    'battery': {'ru': 'батарея', 'tg': 'батарея', 'lemma': 'battery'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'homework': {'ru': 'домашнее задание', 'tg': 'вазифаи хонагӣ', 'lemma': 'homework'},
    'just': {'ru': 'как раз', 'tg': 'маҳз', 'lemma': 'just'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'closing': {'ru': 'закрывать', 'tg': 'пӯшидан', 'lemma': 'close'},
    'lid': {'ru': 'крышка', 'tg': 'сарпӯш', 'lemma': 'lid'},
    'power': {'ru': 'электричество', 'tg': 'барқ', 'lemma': 'power'},
    'stayed': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'off': {'ru': 'выключенный', 'tg': 'хомӯш', 'lemma': 'off'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'played': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'cards': {'ru': 'карты', 'tg': 'қартаҳо', 'lemma': 'card'},
    'candlelight': {'ru': 'свет свечи', 'tg': 'равшании шам', 'lemma': 'candlelight'},
    'hadn\'t': DO, 'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'served': {'ru': 'подавать', 'tg': 'пешкаш кардан', 'lemma': 'serve'},
    'half': {'ru': 'половина', 'tg': 'ним', 'lemma': 'half'},
    'past': {'ru': 'после (о времени)', 'tg': 'аз', 'lemma': 'past'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'later': {'ru': 'позже', 'tg': 'дертар', 'lemma': 'later'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'least': {'ru': 'по крайней мере', 'tg': 'ҳадди ақал', 'lemma': 'at least'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'cold': {'ru': 'холодный', 'tg': 'сард', 'lemma': 'cold'},
    'joked': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'stove': {'ru': 'плита', 'tg': 'плита', 'lemma': 'stove'},
    'used': {'ru': 'использовать', 'tg': 'истифода бурдан', 'lemma': 'use'},
    'gas': {'ru': 'газ', 'tg': 'газ', 'lemma': 'gas'},
    'came': {'ru': 'возвращаться', 'tg': 'баргаштан', 'lemma': 'come back'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'rushed': {'ru': 'спешить', 'tg': 'шитоб кардан', 'lemma': 'rush'},
    'turn': {'ru': 'включать', 'tg': 'даргирондан', 'lemma': 'turn on'},
    'television': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'television'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'blinking': {'ru': 'моргать', 'tg': 'чашмак задан', 'lemma': 'blink'},
    'sudden': {'ru': 'внезапный', 'tg': 'ногаҳонӣ', 'lemma': 'sudden'},
    'brightness': {'ru': 'яркость', 'tg': 'равшанӣ', 'lemma': 'brightness'},
    'strangely': {'ru': 'странно', 'tg': 'аҷиб', 'lemma': 'strangely'},
    'sorry': {'ru': 'сожалеющий', 'tg': 'мутаассиф', 'lemma': 'sorry'},
    'over': {'ru': 'законченный', 'tg': 'ба анҷом расида', 'lemma': 'over'},
    'was': BE, 'were': BE,
},
95: {
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'left': {'ru': 'покидать (отправляться)', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'station': {'ru': 'станция (вокзал)', 'tg': 'истгоҳ', 'lemma': 'station'},
    'twenty': {'ru': 'двадцать', 'tg': 'бист', 'lemma': 'twenty'},
    'minutes': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'stopped': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'side': {'ru': 'сторона (обочина)', 'tg': 'канор', 'lemma': 'side'},
    'road': {'ru': 'дорога', 'tg': 'роҳ', 'lemma': 'road'},
    'flat': {'ru': 'спущенный (плоский)', 'tg': 'холӣ', 'lemma': 'flat'},
    'tyre': {'ru': 'шина', 'tg': 'шина', 'lemma': 'tyre'},
    'while': {'ru': 'пока', 'tg': 'дар ҳоле ки', 'lemma': 'while'},
    'driver': {'ru': 'водитель', 'tg': 'ронанда', 'lemma': 'driver'},
    'changed': {'ru': 'менять', 'tg': 'иваз кардан', 'lemma': 'change'},
    'wheel': {'ru': 'колесо', 'tg': 'чарх', 'lemma': 'wheel'},
    'all': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'all'},
    'passengers': {'ru': 'пассажир', 'tg': 'мусофир', 'lemma': 'passenger'},
    'got': {'ru': 'выходить (получать)', 'tg': 'баромадан', 'lemma': 'get out'},
    'stretch': {'ru': 'размять', 'tg': 'дароз кардан', 'lemma': 'stretch'},
    'legs': {'ru': 'нога', 'tg': 'пой', 'lemma': 'leg'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'started': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'raining': {'ru': 'идти (о дожде)', 'tg': 'борон боридан', 'lemma': 'rain'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'ran': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'back': {'ru': 'назад', 'tg': 'бозгашт', 'lemma': 'back'},
    'inside': {'ru': 'внутрь', 'tg': 'дарун', 'lemma': 'inside'},
    'afterwards': {'ru': 'потом (впоследствии)', 'tg': 'баъдтар', 'lemma': 'afterwards'},
    'continued': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'more': {'ru': 'ещё (более)', 'tg': 'боз', 'lemma': 'more'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'until': {'ru': 'пока не', 'tg': 'то', 'lemma': 'until'},
    'reached': {'ru': 'достигать', 'tg': 'расидан', 'lemma': 'reach'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'break': {'ru': 'перерыв', 'tg': 'танаффус', 'lemma': 'break'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'roadside': {'ru': 'придорожный', 'tg': 'канори роҳ', 'lemma': 'roadside'},
    'stall': {'ru': 'ларёк', 'tg': 'дӯкон', 'lemma': 'stall'},
    'called': {'ru': 'звать', 'tg': 'даъват кардан', 'lemma': 'call'},
    'eventually': {'ru': 'в конечном итоге', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'sun': {'ru': 'солнце', 'tg': 'офтоб', 'lemma': 'sun'},
    'began': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'begin'},
    'set': {'ru': 'заходить (о солнце)', 'tg': 'ғуруб кардан', 'lemma': 'set'},
    'climbed': {'ru': 'подниматься', 'tg': 'баромадан', 'lemma': 'climb'},
    'mountains': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'narrow': {'ru': 'узкий', 'tg': 'танг', 'lemma': 'narrow'},
    'winding': {'ru': 'извилистый', 'tg': 'печ-печон', 'lemma': 'winding'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'just': {'ru': 'как раз', 'tg': 'маҳз', 'lemma': 'just'},
    'midnight': {'ru': 'полночь', 'tg': 'нисфи шаб', 'lemma': 'midnight'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'final': {'ru': 'последний (конечный)', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'stop': {'ru': 'остановка', 'tg': 'истгоҳ', 'lemma': 'stop'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'planned': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'delay': {'ru': 'задержка', 'tg': 'таъхир', 'lemma': 'delay'},
    'feel': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'angry': {'ru': 'сердитый', 'tg': 'хашмгин', 'lemma': 'angry'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'strangely': {'ru': 'странно', 'tg': 'аҷиб', 'lemma': 'strangely'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'survived': {'ru': 'пережить', 'tg': 'аз сар гузарондан', 'lemma': 'survive'},
    'adventure': {'ru': 'приключение', 'tg': 'саргузашт', 'lemma': 'adventure'},
    'soon': {'ru': 'как только (скоро)', 'tg': 'ҳамин ки', 'lemma': 'as soon as'},
    'stepped': {'ru': 'выходить', 'tg': 'баромадан', 'lemma': 'step off'},
    'cousin': {'ru': 'двоюродный брат/сестра', 'tg': 'амакбача', 'lemma': 'cousin'},
    'hugged': {'ru': 'обнимать', 'tg': 'оғӯш кардан', 'lemma': 'hug'},
    'made': {'ru': 'справляться (успеть)', 'tg': 'муваффақ шудан', 'lemma': 'make it'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'take': {'ru': 'взять (сесть на)', 'tg': 'савор шудан', 'lemma': 'take'},
    'train': {'ru': 'поезд', 'tg': 'поезд', 'lemma': 'train'},
    'didn\'t': DO,
},
}

DICTS[90].pop('started2', None)
DICTS[91].pop('started2', None)
DICTS[92].pop('exactly2', None)
DICTS[93].pop('never2', None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
