# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
128: {
    'pass': {'ru': 'сдавать (экзамен)', 'tg': 'супоридан', 'lemma': 'pass'},
    'final': {'ru': 'финальный', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'exams': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'apply': {'ru': 'подавать заявку', 'tg': 'дархост додан', 'lemma': 'apply'},
    'study': {'ru': 'изучать', 'tg': 'омӯхтан', 'lemma': 'study'},
    'architecture': {'ru': 'архитектура', 'tg': 'меъморӣ', 'lemma': 'architecture'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'keep': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'asking': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'results': {'ru': 'результат', 'tg': 'натиҷа', 'lemma': 'result'},
    'come': {'ru': 'выходить (появляться)', 'tg': 'баромадан', 'lemma': 'come out'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'fully': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'fully'},
    'yet': {'ru': 'ещё', 'tg': 'ҳанӯз', 'lemma': 'yet'},
    'grades': {'ru': 'оценка', 'tg': 'баҳо', 'lemma': 'grade'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'move': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'capital': {'ru': 'столица', 'tg': 'пойтахт', 'lemma': 'capital'},
    'studies': {'ru': 'учёба', 'tg': 'таҳсил', 'lemma': 'studies'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'miss': {'ru': 'скучать', 'tg': 'дилтанг шудан', 'lemma': 'miss'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'more': {'ru': 'больше', 'tg': 'бештар', 'lemma': 'more'},
    'expect': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'until': {'ru': 'до', 'tg': 'то', 'lemma': 'until'},
    'arrive': {'ru': 'приходить', 'tg': 'расидан', 'lemma': 'arrive'},
    'next': {'ru': 'следующий', 'tg': 'оянда', 'lemma': 'next'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'trying': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'much': {'ru': 'слишком', 'tg': 'зиёд', 'lemma': 'much'},
    'difficult': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'difficult'},
    'soon': {'ru': 'как только', 'tg': 'ҳамин ки', 'lemma': 'as soon as'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'believed': {'ru': 'верить', 'tg': 'бовар доштан', 'lemma': 'believe'},
    'get': {'ru': 'добраться (дойти)', 'tg': 'расидан', 'lemma': 'get'},
    'here': {'ru': 'сюда', 'tg': 'ин ҷо', 'lemma': 'here'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'retake': {'ru': 'пересдавать', 'tg': 'дубора супоридан', 'lemma': 'retake'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'exam': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'autumn': {'ru': 'осень', 'tg': 'тирамоҳ', 'lemma': 'autumn'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'giving': {'ru': 'сдаваться', 'tg': 'даст кашидан', 'lemma': 'give up'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'somewhere': {'ru': 'куда-нибудь', 'tg': 'ҷое', 'lemma': 'somewhere'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'starting': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'allow': {'ru': 'позволять', 'tg': 'иҷозат додан', 'lemma': 'allow'},
    'then': {'ru': 'до тех пор', 'tg': 'то он вақт', 'lemma': 'then'},
    'studying': {'ru': 'учиться', 'tg': 'таҳсил кардан', 'lemma': 'study'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'quizzing': {'ru': 'опрашивать (проверять)', 'tg': 'санҷидан', 'lemma': 'quiz'},
    'each': {'ru': 'каждый (друг друга)', 'tg': 'ҳар', 'lemma': 'each other'},
    'outdated': {'ru': 'устаревший', 'tg': 'кӯҳнашуда', 'lemma': 'outdated'},
    'notes': {'ru': 'записи', 'tg': 'қайдҳо', 'lemma': 'note'},
    'goes': {'ru': 'проходить (идти)', 'tg': 'гузаштан', 'lemma': 'go'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'living': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'student': {'ru': 'студенческий', 'tg': 'донишҷӯӣ', 'lemma': 'student'},
    'flat': {'ru': 'квартира', 'tg': 'манзил', 'lemma': 'flat'},
    'surrounded': {'ru': 'окружённый', 'tg': 'иҳоташуда', 'lemma': 'surrounded'},
    'unfamiliar': {'ru': 'незнакомый', 'tg': 'ношинос', 'lemma': 'unfamiliar'},
    'streets': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'hopefully': {'ru': 'будем надеяться', 'tg': 'умедворона', 'lemma': 'hopefully'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'whatever': {'ru': 'что бы ни', 'tg': 'ҳар чи', 'lemma': 'whatever'},
    'happens': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'last': {'ru': 'последний', 'tg': 'охирин', 'lemma': 'last'},
    'uncertain': {'ru': 'неопределённый', 'tg': 'номуайян', 'lemma': 'uncertain'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'i\'ll': BE, 'don\'t': DO, 'she\'s': BE, 'i\'d': BE, 'we\'re': BE, 'we\'ll': BE,
},
129: {
    'had': HAVE, 'bigger': {'ru': 'больше', 'tg': 'калонтар', 'lemma': 'big'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'proper': {'ru': 'настоящий', 'tg': 'дурустӣ', 'lemma': 'proper'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'instead': {'ru': 'вместо', 'tg': 'ба ҷои', 'lemma': 'instead'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'pots': {'ru': 'горшок', 'tg': 'гулдон', 'lemma': 'pot'},
    'balcony': {'ru': 'балкон', 'tg': 'балкон', 'lemma': 'balcony'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'disagrees': {'ru': 'не соглашаться', 'tg': 'розӣ набудан', 'lemma': 'disagree'},
    'thinks': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'somewhere': {'ru': 'куда-нибудь', 'tg': 'ҷое', 'lemma': 'somewhere'},
    'larger': {'ru': 'больше', 'tg': 'калонтар', 'lemma': 'large'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'fill': {'ru': 'заполнять', 'tg': 'пур кардан', 'lemma': 'fill'},
    'unnecessary': {'ru': 'ненужный', 'tg': 'бефоида', 'lemma': 'unnecessary'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'own': {'ru': 'собственный', 'tg': 'худи', 'lemma': 'own'},
    'place': {'ru': 'место (жильё)', 'tg': 'ҷой', 'lemma': 'place'},
    'paint': {'ru': 'красить', 'tg': 'ранг кардан', 'lemma': 'paint'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'wall': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'different': {'ru': 'разный', 'tg': 'гуногун', 'lemma': 'different'},
    'colour': {'ru': 'цвет', 'tg': 'ранг', 'lemma': 'colour'},
    'allow': {'ru': 'позволять', 'tg': 'иҷозат додан', 'lemma': 'allow'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'practical': {'ru': 'практичный', 'tg': 'амалӣ', 'lemma': 'practical'},
    'either': {'ru': 'любой (из нас двоих)', 'tg': 'ҳар кадоме', 'lemma': 'either'},
    'designed': {'ru': 'проектировать', 'tg': 'тарҳрезӣ кардан', 'lemma': 'design'},
    'scratch': {'ru': 'с нуля', 'tg': 'аз нав', 'lemma': 'from scratch'},
    'build': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'fewer': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'fewer'},
    'stairs': {'ru': 'лестница', 'tg': 'зинапоя', 'lemma': 'stairs'},
    'sunlight': {'ru': 'солнечный свет', 'tg': 'нури офтоб', 'lemma': 'sunlight'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'imagine': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'won': {'ru': 'выигрывать', 'tg': 'бурдан', 'lemma': 'win'},
    'enough2': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'dream': {'ru': 'мечта (мечты)', 'tg': 'орзу', 'lemma': 'dream'},
    'add': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'library': {'ru': 'библиотека', 'tg': 'китобхона', 'lemma': 'library'},
    'space': {'ru': 'место (пространство)', 'tg': 'ҷой', 'lemma': 'space'},
    'issue': {'ru': 'проблема', 'tg': 'мушкилот', 'lemma': 'issue'},
    'filled': {'ru': 'наполнять', 'tg': 'пур кардан', 'lemma': 'fill'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'room': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'room'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'sentimental': {'ru': 'сентиментальный', 'tg': 'ҳиссиётӣ', 'lemma': 'sentimental'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'built': {'ru': 'строить', 'tg': 'сохтан', 'lemma': 'build'},
    'front': {'ru': 'передняя (входная)', 'tg': 'пеш', 'lemma': 'front door'},
    'door': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'childhood': {'ru': 'детство (детский)', 'tg': 'кӯдакӣ', 'lemma': 'childhood'},
    'height': {'ru': 'рост (высота)', 'tg': 'қад', 'lemma': 'height'},
    'marks': {'ru': 'отметка', 'tg': 'аломат', 'lemma': 'mark'},
    'pencilled': {'ru': 'нарисованный карандашом', 'tg': 'бо қалам сабтшуда', 'lemma': 'pencil'},
    'cry': {'ru': 'плакать', 'tg': 'гиря кардан', 'lemma': 'cry'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'survived': {'ru': 'уцелеть (пережить)', 'tg': 'солим мондан', 'lemma': 'survive'},
    'realistically': {'ru': 'реалистично', 'tg': 'воқеъбинона', 'lemma': 'realistically'},
    'none': {'ru': 'ничто', 'tg': 'ҳеҷ чиз', 'lemma': 'none'},
    'happen': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'anytime': {'ru': 'в ближайшее время', 'tg': 'ба зудӣ', 'lemma': 'anytime'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'evenings': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'imagining': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'impossible': {'ru': 'невозможный', 'tg': 'ғайриимкон', 'lemma': 'impossible'},
    'feels': {'ru': 'чувствоваться (казаться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'own2': {'ru': 'своего рода', 'tg': 'навъи худ', 'lemma': 'own'},
    'kind': {'ru': 'вид (тип)', 'tg': 'навъ', 'lemma': 'kind'},
    'comfort': {'ru': 'утешение', 'tg': 'тасаллӣ', 'lemma': 'comfort'},
    'she\'d': BE, 'they\'d': BE, 'i\'d': BE, 'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'}, 'weren\'t': BE, 'i\'ve': HAVE,
},
130: {
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'enjoying': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'stable': {'ru': 'стабильный', 'tg': 'устувор', 'lemma': 'stable'},
    'office': {'ru': 'офис (офисная)', 'tg': 'идора', 'lemma': 'office'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'suddenly': {'ru': 'внезапно', 'tg': 'ногаҳон', 'lemma': 'suddenly'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'quit': {'ru': 'увольняться', 'tg': 'тарк кардан', 'lemma': 'quit'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'bakery': {'ru': 'пекарня', 'tg': 'нонвойхона', 'lemma': 'bakery'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'avoided': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'discussing': {'ru': 'обсуждать', 'tg': 'муҳокима кардан', 'lemma': 'discuss'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'worried': {'ru': 'обеспокоенный', 'tg': 'нигарон', 'lemma': 'worried'},
    'making': {'ru': 'совершать (делать)', 'tg': 'кардан', 'lemma': 'make'},
    'mistake': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'thinking': {'ru': 'думать (обдумывать)', 'tg': 'фикр кардан', 'lemma': 'think over'},
    'told': {'ru': 'говорить (сообщать)', 'tg': 'гуфтан', 'lemma': 'tell'},
    'firmly': {'ru': 'твёрдо', 'tg': 'қатъӣ', 'lemma': 'firmly'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'baking': {'ru': 'выпечка', 'tg': 'пухтупаз', 'lemma': 'baking'},
    'professionally': {'ru': 'профессионально', 'tg': 'касбӣ', 'lemma': 'professionally'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'risking': {'ru': 'рисковать', 'tg': 'хавф кардан', 'lemma': 'risk'},
    'savings': {'ru': 'сбережения', 'tg': 'пасандоз', 'lemma': 'savings'},
    'terrified': {'ru': 'ужасать', 'tg': 'сахт тарсондан', 'lemma': 'terrify'},
    'refused': {'ru': 'отказываться', 'tg': 'рад кардан', 'lemma': 'refuse'},
    'keep': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'postponing': {'ru': 'откладывать', 'tg': 'ба таъхир андохтан', 'lemma': 'postpone'},
    'decision': {'ru': 'решение', 'tg': 'қарор', 'lemma': 'decision'},
    'any': {'ru': 'дальше (какой-либо)', 'tg': 'дигар', 'lemma': 'any longer'},
    'longer': {'ru': 'дольше', 'tg': 'дарозтар', 'lemma': 'long'},
    'manager': {'ru': 'менеджер (начальник)', 'tg': 'менеҷер', 'lemma': 'manager'},
    'offered': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'position': {'ru': 'должность', 'tg': 'вазифа', 'lemma': 'position'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'hoping': {'ru': 'надеяться', 'tg': 'умед доштан', 'lemma': 'hope'},
    'reconsider': {'ru': 'передумать', 'tg': 'дубора фикр кардан', 'lemma': 'reconsider'},
    'chose': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'decline': {'ru': 'отказаться', 'tg': 'рад кардан', 'lemma': 'decline'},
    'politely': {'ru': 'вежливо', 'tg': 'бо эҳтиром', 'lemma': 'politely'},
    'began': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'begin'},
    'learning': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'recipes': {'ru': 'рецепт', 'tg': 'дастур', 'lemma': 'recipe'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'practising': {'ru': 'практиковаться (тренироваться)', 'tg': 'машқ кардан', 'lemma': 'practise'},
    'midnight': {'ru': 'полночь', 'tg': 'нисфи шаб', 'lemma': 'midnight'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'nights': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'suggested': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'starting': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'selling': {'ru': 'продавать', 'tg': 'фурӯхтан', 'lemma': 'sell'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'neighbours': {'ru': 'соседи', 'tg': 'ҳамсоягон', 'lemma': 'neighbour'},
    'actual': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'actual'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'agreed': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'mostly': {'ru': 'в основном', 'tg': 'бештар', 'lemma': 'mostly'},
    'avoid': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'disappointing': {'ru': 'разочаровывать', 'tg': 'ноумед кардан', 'lemma': 'disappoint'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'within': {'ru': 'в течение', 'tg': 'дар зарфи', 'lemma': 'within'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'managed': {'ru': 'удаваться (справляться)', 'tg': 'муваффақ шудан', 'lemma': 'manage'},
    'build': {'ru': 'создавать (строить)', 'tg': 'ба вуҷуд овардан', 'lemma': 'build'},
    'loyal': {'ru': 'преданный (постоянный)', 'tg': 'содиқ', 'lemma': 'loyal'},
    'group': {'ru': 'группа', 'tg': 'гурӯҳ', 'lemma': 'group'},
    'customers': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'requesting': {'ru': 'просить (заказывать)', 'tg': 'дархост кардан', 'lemma': 'request'},
    'sourdough': {'ru': 'закваска', 'tg': 'хамиртуруш', 'lemma': 'sourdough'},
    'specifically': {'ru': 'именно', 'tg': 'мушаххас', 'lemma': 'specifically'},
    'loves': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'waking': {'ru': 'просыпаться', 'tg': 'бедор шудан', 'lemma': 'wake up'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'feel': {'ru': 'казаться (чувствоваться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'looking': {'ru': 'оглядываясь', 'tg': 'бознигарӣ', 'lemma': 'look back'},
    'remembers': {'ru': 'помнить (вспоминать)', 'tg': 'ба ёд овардан', 'lemma': 'remember'},
    'hesitating': {'ru': 'колебаться', 'tg': 'дудила будан', 'lemma': 'hesitate'},
    'take': {'ru': 'сделать (шаг)', 'tg': 'гузоштан', 'lemma': 'take'},
    'step': {'ru': 'шаг', 'tg': 'қадам', 'lemma': 'step'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'kneading': {'ru': 'месить', 'tg': 'варзидан', 'lemma': 'knead'},
    'dough': {'ru': 'тесто', 'tg': 'хамир', 'lemma': 'dough'},
    'dawn': {'ru': 'рассвет', 'tg': 'субҳидам', 'lemma': 'dawn'},
    'imagine': {'ru': 'вообразить', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'going': {'ru': 'возвращаться (идти)', 'tg': 'баргаштан', 'lemma': 'go back'},
    'spending': {'ru': 'проводить (время)', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'sunny': {'ru': 'солнечный', 'tg': 'офтобӣ', 'lemma': 'sunny'},
    'afternoons': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'behind': {'ru': 'за', 'tg': 'дар паси', 'lemma': 'behind'},
    'computer': {'ru': 'компьютер', 'tg': 'компютер', 'lemma': 'computer'},
    'i\'ve': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}, 'she\'d': {'ru': 'она (сослаг.)', 'tg': 'вай мебуд', 'lemma': 'she'}, 'used': {'ru': 'раньше было', 'tg': 'пештар буд', 'lemma': 'used to'}, 'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
},
131: {
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'assistant': {'ru': 'продавец (помощник)', 'tg': 'ёрдамчӣ', 'lemma': 'assistant'},
    'told': {'ru': 'говорить (сообщать)', 'tg': 'гуфтан', 'lemma': 'tell'},
    'jacket': {'ru': 'куртка', 'tg': 'куртка', 'lemma': 'jacket'},
    'returned': {'ru': 'возвращать', 'tg': 'баргардондан', 'lemma': 'return'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'receipt': {'ru': 'чек', 'tg': 'квитансия', 'lemma': 'receipt'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'lost': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'somewhere': {'ru': 'где-то', 'tg': 'ҷое', 'lemma': 'somewhere'},
    'between': {'ru': 'между', 'tg': 'дар байни', 'lemma': 'between'},
    'till': {'ru': 'касса', 'tg': 'касса', 'lemma': 'till'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'stop': {'ru': 'остановка', 'tg': 'истгоҳ', 'lemma': 'stop'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'remembered': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'exact': {'ru': 'точное', 'tg': 'дақиқ', 'lemma': 'exact'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'purchase': {'ru': 'покупка', 'tg': 'харид', 'lemma': 'purchase'},
    'precisely': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'precisely'},
    'insisted': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'tag': {'ru': 'бирка (ярлык)', 'tg': 'нишона', 'lemma': 'tag'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'attached': {'ru': 'прикреплённый', 'tg': 'васлшуда', 'lemma': 'attached'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'would': {'ru': 'нужно бы (буд.)', 'tg': 'бояд мешуд', 'lemma': 'would'},
    'approve': {'ru': 'одобрять', 'tg': 'тасдиқ кардан', 'lemma': 'approve'},
    'any': {'ru': 'какое-либо', 'tg': 'ягон', 'lemma': 'any'},
    'exception': {'ru': 'исключение', 'tg': 'истисно', 'lemma': 'exception'},
    'personally': {'ru': 'лично', 'tg': 'шахсан', 'lemma': 'personally'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'actual': {'ru': 'настоящая (реальная)', 'tg': 'воқеӣ', 'lemma': 'actual'},
    'problem': {'ru': 'проблема', 'tg': 'мушкилот', 'lemma': 'problem'},
    'claimed': {'ru': 'утверждать', 'tg': 'даъво кардан', 'lemma': 'claim'},
    'directly': {'ru': 'прямо', 'tg': 'бевосита', 'lemma': 'directly'},
    'whether': {'ru': 'ли', 'tg': 'оё', 'lemma': 'whether'},
    'paid': {'ru': 'платить', 'tg': 'пул додан', 'lemma': 'pay'},
    'card': {'ru': 'карта', 'tg': 'корт', 'lemma': 'card'},
    'confirmed': {'ru': 'подтверждать', 'tg': 'тасдиқ кардан', 'lemma': 'confirm'},
    'check': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'payment': {'ru': 'платёж (оплата)', 'tg': 'пардохт', 'lemma': 'payment'},
    'system': {'ru': 'система', 'tg': 'система', 'lemma': 'system'},
    'surprised': {'ru': 'удивлять', 'tg': 'ҳайрон кардан', 'lemma': 'surprise'},
    'apparently': {'ru': 'по-видимому', 'tg': 'зоҳиран', 'lemma': 'apparently'},
    'considered': {'ru': 'рассматривать (обдумывать)', 'tg': 'дида баромадан', 'lemma': 'consider'},
    'option': {'ru': 'вариант', 'tg': 'вариант', 'lemma': 'option'},
    'brief': {'ru': 'короткий (краткий)', 'tg': 'кӯтоҳ', 'lemma': 'brief'},
    'search': {'ru': 'поиск', 'tg': 'ҷустуҷӯ', 'lemma': 'search'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'transaction': {'ru': 'транзакция', 'tg': 'амалиёт', 'lemma': 'transaction'},
    'previous': {'ru': 'предыдущий', 'tg': 'гузашта', 'lemma': 'previous'},
    'afternoon': {'ru': 'вторая половина дня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'apologised': {'ru': 'извиняться', 'tg': 'узр хостан', 'lemma': 'apologise'},
    'saying': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'another': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'another'},
    'way': {'ru': 'способ', 'tg': 'роҳ', 'lemma': 'way'},
    'verify': {'ru': 'подтверждать (проверять)', 'tg': 'тасдиқ кардан', 'lemma': 'verify'},
    'reassured': {'ru': 'успокаивать', 'tg': 'ором кардан', 'lemma': 'reassure'},
    'process': {'ru': 'обрабатывать', 'tg': 'коркард кардан', 'lemma': 'process'},
    'refund': {'ru': 'возврат средств', 'tg': 'баргардонидани пул', 'lemma': 'refund'},
    'immediately': {'ru': 'немедленно', 'tg': 'фавран', 'lemma': 'immediately'},
    'walking': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'walk'},
    'wondered': {'ru': 'задаваться вопросом', 'tg': 'фикр кардан', 'lemma': 'wonder'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'taught': {'ru': 'учить', 'tg': 'омӯзондан', 'lemma': 'teach'},
    'proof': {'ru': 'доказательство', 'tg': 'далел', 'lemma': 'proof'},
    'mattered': {'ru': 'иметь значение', 'tg': 'аҳамият доштан', 'lemma': 'matter'},
    'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'}, 'i\'d': HAVE, 'i had': HAVE, 'he\'d': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'}, 'hadn\'t': DO, 'they\'d': {'ru': 'обрабатывать (буд.)', 'tg': 'коркард мекунанд', 'lemma': 'process'}, 'weren\'t': BE,
},
132: {
    'backed': {'ru': 'делать резервную копию', 'tg': 'нусхаи эҳтиётӣ гирифтан', 'lemma': 'back up'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'fell': {'ru': 'падать', 'tg': 'афтодан', 'lemma': 'fall'},
    'river': {'ru': 'река', 'tg': 'дарё', 'lemma': 'river'},
    'wouldn\'t': DO, 'lost': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'four': {'ru': 'четыре', 'tg': 'чор', 'lemma': 'four'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'photographs': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photograph'},
    'single': {'ru': 'единственный (один)', 'tg': 'ягона', 'lemma': 'single'},
    'afternoon': {'ru': 'день (после полудня)', 'tg': 'нимрӯз', 'lemma': 'afternoon'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'warned': {'ru': 'предупреждать', 'tg': 'огоҳ кардан', 'lemma': 'warn'},
    'repeatedly': {'ru': 'неоднократно', 'tg': 'борҳо', 'lemma': 'repeatedly'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'assumed': {'ru': 'предполагать', 'tg': 'гумон кардан', 'lemma': 'assume'},
    'disaster': {'ru': 'катастрофа', 'tg': 'фалокат', 'lemma': 'disaster'},
    'happen': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'else': {'ru': 'ещё (другой)', 'tg': 'дигар', 'lemma': 'else'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'would': {'ru': 'бы', 'tg': 'мебуд', 'lemma': 'would'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'pictures': {'ru': 'фотография (картина)', 'tg': 'расм', 'lemma': 'picture'},
    'sister\'s': {'ru': 'сестрина', 'tg': 'аз они хоҳар', 'lemma': 'sister'},
    'wedding': {'ru': 'свадьба', 'tg': 'туй', 'lemma': 'wedding'},
    'countless': {'ru': 'бесчисленный', 'tg': 'бешумор', 'lemma': 'countless'},
    'ordinary': {'ru': 'обычный', 'tg': 'оддӣ', 'lemma': 'ordinary'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'bothered': {'ru': 'утруждаться', 'tg': 'заҳмат кашидан', 'lemma': 'bother'},
    'appreciate': {'ru': 'ценить', 'tg': 'қадр кардан', 'lemma': 'appreciate'},
    'until': {'ru': 'пока не', 'tg': 'то', 'lemma': 'until'},
    'vanished': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'vanish'},
    'technician': {'ru': 'мастер (техник)', 'tg': 'техник', 'lemma': 'technician'},
    'tried': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'possible': {'ru': 'возможный', 'tg': 'мумкин', 'lemma': 'possible'},
    'spent': {'ru': 'провести (время)', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'less': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'less'},
    'underwater': {'ru': 'под водой', 'tg': 'зери об', 'lemma': 'underwater'},
    'might': {'ru': 'мог бы', 'tg': 'мумкин буд', 'lemma': 'might'},
    'recovered': {'ru': 'восстановить', 'tg': 'барқарор кардан', 'lemma': 'recover'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'panicked': {'ru': 'паниковать', 'tg': 'ба ошуфтагӣ афтодан', 'lemma': 'panic'},
    'left': {'ru': 'оставлять', 'tg': 'мондан', 'lemma': 'leave'},
    'bag': {'ru': 'пакет (сумка)', 'tg': 'халта', 'lemma': 'bag'},
    'rice': {'ru': 'рис', 'tg': 'биринҷ', 'lemma': 'rice'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'perhaps': {'ru': 'возможно', 'tg': 'мумкин аст', 'lemma': 'perhaps'},
    'delay': {'ru': 'задержка', 'tg': 'таъхир', 'lemma': 'delay'},
    'made': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'worse': {'ru': 'хуже', 'tg': 'бадтар', 'lemma': 'worse'},
    'gentler': {'ru': 'мягче (добрее)', 'tg': 'мулоимтар', 'lemma': 'gentle'},
    'deserved': {'ru': 'заслуживать', 'tg': 'сазовор будан', 'lemma': 'deserve'},
    'reminded': {'ru': 'напоминать', 'tg': 'ёдовар шудан', 'lemma': 'remind'},
    'memories': {'ru': 'воспоминание', 'tg': 'хотира', 'lemma': 'memory'},
    'mattered': {'ru': 'иметь значение', 'tg': 'аҳамият доштан', 'lemma': 'matter'},
    'much': {'ru': 'много (так сильно)', 'tg': 'бисёр', 'lemma': 'much'},
    'printed': {'ru': 'печатать', 'tg': 'чоп кардан', 'lemma': 'print'},
    'least': {'ru': 'по крайней мере', 'tg': 'ҳадди ақал', 'lemma': 'at least'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'right': {'ru': 'права (правая)', 'tg': 'ҳақ', 'lemma': 'right'},
    'comfort': {'ru': 'утешать', 'tg': 'тасаллӣ додан', 'lemma': 'comfort'},
    'continued': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'ignoring': {'ru': 'игнорировать', 'tg': 'сарфи назар кардан', 'lemma': 'ignore'},
    'backups': {'ru': 'резервные копии', 'tg': 'нусхаи эҳтиётӣ', 'lemma': 'backup'},
    'indefinitely': {'ru': 'бесконечно', 'tg': 'то бемуҳлат', 'lemma': 'indefinitely'},
    'assuming': {'ru': 'предполагать', 'tg': 'гумон кардан', 'lemma': 'assume'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'painfully': {'ru': 'мучительно (болезненно)', 'tg': 'дардовар', 'lemma': 'painfully'},
    'places': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'habit': {'ru': 'привычка', 'tg': 'одат', 'lemma': 'habit'},
    'developed': {'ru': 'развивать (выработать)', 'tg': 'инкишоф додан', 'lemma': 'develop'},
    'expensive': {'ru': 'дорогой', 'tg': 'қиммат', 'lemma': 'expensive'},
    'lesson': {'ru': 'урок', 'tg': 'дарс', 'lemma': 'lesson'},
    'had': HAVE, 'hadn\'t': HAVE, 'i\'d': HAVE,
},
133: {
    'kitchen': {'ru': 'кухня (кухонный)', 'tg': 'ошхона', 'lemma': 'kitchen'},
    'drawer': {'ru': 'ящик', 'tg': 'ҷевон', 'lemma': 'drawer'},
    'contains': {'ru': 'содержать', 'tg': 'дар бар гирифтан', 'lemma': 'contain'},
    'far': {'ru': 'намного (слишком)', 'tg': 'хеле', 'lemma': 'far too'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'phone': {'ru': 'телефонный', 'tg': 'телефонӣ', 'lemma': 'phone'},
    'chargers': {'ru': 'зарядное устройство', 'tg': 'заряднок', 'lemma': 'charger'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'barely': {'ru': 'едва', 'tg': 'базӯр', 'lemma': 'barely'},
    'any': {'ru': 'какие-либо', 'tg': 'ягон', 'lemma': 'any'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'anymore': {'ru': 'больше (не)', 'tg': 'дигар', 'lemma': 'anymore'},
    'little': {'ru': 'мало', 'tg': 'кам', 'lemma': 'little'},
    'space': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'space'},
    'left': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'left'},
    'else': {'ru': 'ещё', 'tg': 'дигар', 'lemma': 'else'},
    'since': {'ru': 'так как', 'tg': 'зеро', 'lemma': 'since'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'cables': {'ru': 'кабель', 'tg': 'сим', 'lemma': 'cable'},
    'slowly': {'ru': 'постепенно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'taken': {'ru': 'захватывать (занимать)', 'tg': 'ишғол кардан', 'lemma': 'take over'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'how': {'ru': 'сколько (как)', 'tg': 'чанд', 'lemma': 'how'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'holding': {'ru': 'держать', 'tg': 'нигоҳ доштан', 'lemma': 'hold'},
    'tangled': {'ru': 'запутанный', 'tg': 'дарҳамбарҳам', 'lemma': 'tangled'},
    'handful': {'ru': 'горсть', 'tg': 'мушт', 'lemma': 'handful'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'own': {'ru': 'владеть', 'tg': 'соҳиб будан', 'lemma': 'own'},
    'dozens': {'ru': 'десятки', 'tg': 'даҳҳо', 'lemma': 'dozen'},
    'belong': {'ru': 'принадлежать', 'tg': 'тааллуқ доштан', 'lemma': 'belong'},
    'phones': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'replaced': {'ru': 'заменять', 'tg': 'иваз кардан', 'lemma': 'replace'},
    'years2': {'ru': 'годы (лет назад)', 'tg': 'сол пеш', 'lemma': 'years ago'},
    'collected': {'ru': 'собирать', 'tg': 'ҷамъ кардан', 'lemma': 'collect'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'device': {'ru': 'устройство', 'tg': 'дастгоҳ', 'lemma': 'device'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'owned': {'ru': 'владеть', 'tg': 'соҳиб будан', 'lemma': 'own'},
    'unable': {'ru': 'неспособный', 'tg': 'қодир набудан', 'lemma': 'unable'},
    'throw': {'ru': 'выбрасывать', 'tg': 'партофтан', 'lemma': 'throw away'},
    'case': {'ru': 'случай', 'tg': 'ҳолат', 'lemma': 'case'},
    'clutter': {'ru': 'беспорядок (хлам)', 'tg': 'бетартибӣ', 'lemma': 'clutter'},
    'organisation': {'ru': 'организация (порядок)', 'tg': 'тартибот', 'lemma': 'organisation'},
    'complains': {'ru': 'жаловаться', 'tg': 'шикоят кардан', 'lemma': 'complain'},
    'entirely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'entirely'},
    'unfairly': {'ru': 'несправедливо', 'tg': 'ноодилона', 'lemma': 'unfairly'},
    'spend': {'ru': 'проводить (время)', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'meaning': {'ru': 'намереваться', 'tg': 'ният доштан', 'lemma': 'mean to'},
    'sort': {'ru': 'разобраться', 'tg': 'мураттаб кардан', 'lemma': 'sort out'},
    'rarely': {'ru': 'редко', 'tg': 'кам', 'lemma': 'rarely'},
    'make': {'ru': 'делать (совершать)', 'tg': 'кардан', 'lemma': 'make'},
    'progress': {'ru': 'прогресс', 'tg': 'пешрафт', 'lemma': 'progress'},
    'fit': {'ru': 'подходить', 'tg': 'мувофиқат кардан', 'lemma': 'fit'},
    'currently': {'ru': 'в настоящее время', 'tg': 'ҳоло', 'lemma': 'currently'},
    'exist': {'ru': 'существовать', 'tg': 'вуҷуд доштан', 'lemma': 'exist'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'find': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'exactly': {'ru': 'ровно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'charger': {'ru': 'зарядное устройство', 'tg': 'заряднок', 'lemma': 'charger'},
    'use': {'ru': 'использовать', 'tg': 'истифода бурдан', 'lemma': 'use'},
    'rest': {'ru': 'остальное', 'tg': 'боқимонда', 'lemma': 'rest'},
    'several': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'several'},
    'dozen': {'ru': 'дюжина', 'tg': 'даҳҳо', 'lemma': 'dozen'},
    'useless': {'ru': 'бесполезный', 'tg': 'бефоида', 'lemma': 'useless'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'go': {'ru': 'отправляться', 'tg': 'равон шудан', 'lemma': 'go'},
    'recycling': {'ru': 'переработка', 'tg': 'коркарди дуюмдараҷа', 'lemma': 'recycling'},
    'much2': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'much'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'regret': {'ru': 'сожаление', 'tg': 'пушаймонӣ', 'lemma': 'regret'},
    'throwing': {'ru': 'выбрасывать', 'tg': 'партофтан', 'lemma': 'throw away'},
    'accumulated': {'ru': 'накопленный', 'tg': 'ҷамъшуда', 'lemma': 'accumulated'},
    'uncertainty': {'ru': 'неопределённость', 'tg': 'номуайянӣ', 'lemma': 'uncertainty'},
    'there\'s': BE, 'don\'t': DO, 'we\'ve': HAVE, 'we\'d': BE,
},
134: {
    'detective': {'ru': 'детектив', 'tg': 'детектив', 'lemma': 'detective'},
    'assigned': {'ru': 'назначать', 'tg': 'таъин кардан', 'lemma': 'assign'},
    'case': {'ru': 'дело', 'tg': 'парванда', 'lemma': 'case'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'seen': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'anything': {'ru': 'что-либо', 'tg': 'чизе', 'lemma': 'anything'},
    'quite': {'ru': 'вполне (совсем)', 'tg': 'комилан', 'lemma': 'quite'},
    'like': {'ru': 'как (подобно)', 'tg': 'мисли', 'lemma': 'like'},
    'jewellery': {'ru': 'ювелирный', 'tg': 'заргарӣ', 'lemma': 'jewellery'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'robbed': {'ru': 'грабить', 'tg': 'ғорат кардан', 'lemma': 'rob'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'unusually': {'ru': 'необычно', 'tg': 'ғайриоддӣ', 'lemma': 'unusually'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'security': {'ru': 'охрана (безопасность)', 'tg': 'амният', 'lemma': 'security'},
    'cameras': {'ru': 'камера', 'tg': 'камера', 'lemma': 'camera'},
    'recorded': {'ru': 'записывать', 'tg': 'сабт кардан', 'lemma': 'record'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'useful': {'ru': 'полезный', 'tg': 'муфид', 'lemma': 'useful'},
    'either': {'ru': 'ни (тот, ни другой)', 'tg': 'ҳам не', 'lemma': 'either'},
    'time': {'ru': 'раз', 'tg': 'дафъа', 'lemma': 'time'},
    'owner': {'ru': 'владелец', 'tg': 'соҳиб', 'lemma': 'owner'},
    'insurance': {'ru': 'страховой', 'tg': 'суғуртавӣ', 'lemma': 'insurance'},
    'claim': {'ru': 'заявление (иск)', 'tg': 'даъво', 'lemma': 'claim'},
    'seemed': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'suspiciously': {'ru': 'подозрительно', 'tg': 'бо шубҳа', 'lemma': 'suspiciously'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'prepared': {'ru': 'подготовленный', 'tg': 'омодашуда', 'lemma': 'prepared'},
    'became': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'real': {'ru': 'настоящий', 'tg': 'воқеӣ', 'lemma': 'real'},
    'suspect': {'ru': 'подозреваемый', 'tg': 'гумонбар', 'lemma': 'suspect'},
    'neighbours': {'ru': 'соседи', 'tg': 'ҳамсоягон', 'lemma': 'neighbour'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'nearby': {'ru': 'поблизости', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'reported': {'ru': 'сообщать', 'tg': 'хабар додан', 'lemma': 'report'},
    'seeing': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'unusual': {'ru': 'необычный', 'tg': 'ғайриоддӣ', 'lemma': 'unusual'},
    'occasion': {'ru': 'случай', 'tg': 'маврид', 'lemma': 'occasion'},
    'thief': {'ru': 'вор', 'tg': 'дузд', 'lemma': 'thief'},
    'knew': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'blind': {'ru': 'слепой (мёртвая зона)', 'tg': 'кӯр', 'lemma': 'blind spot'},
    'spots': {'ru': 'место (пятно)', 'tg': 'нуқта', 'lemma': 'spot'},
    'evidence': {'ru': 'улика (доказательство)', 'tg': 'далел', 'lemma': 'evidence'},
    'behind': {'ru': 'позади', 'tg': 'дар паси', 'lemma': 'behind'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'witness': {'ru': 'свидетель', 'tg': 'шоҳид', 'lemma': 'witness'},
    'statement': {'ru': 'показания (заявление)', 'tg': 'изҳорот', 'lemma': 'statement'},
    'initially': {'ru': 'изначально', 'tg': 'аввалан', 'lemma': 'initially'},
    'unreliable': {'ru': 'ненадёжный', 'tg': 'боэътимод набуда', 'lemma': 'unreliable'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'provided': {'ru': 'предоставить', 'tg': 'пешниҳод кардан', 'lemma': 'provide'},
    'crucial': {'ru': 'решающий (ключевой)', 'tg': 'ҳалкунанда', 'lemma': 'crucial'},
    'detail': {'ru': 'деталь', 'tg': 'тафсилот', 'lemma': 'detail'},
    'broke': {'ru': 'раскрыть (взломать)', 'tg': 'кушодан', 'lemma': 'break'},
    'mentioned': {'ru': 'упоминать', 'tg': 'ёдовар шудан', 'lemma': 'mention'},
    'delivery': {'ru': 'доставка', 'tg': 'расонидан', 'lemma': 'delivery'},
    'van': {'ru': 'фургон', 'tg': 'фургон', 'lemma': 'van'},
    'parked': {'ru': 'парковаться', 'tg': 'парк кардан', 'lemma': 'park'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'noticed': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'belonged': {'ru': 'принадлежать', 'tg': 'тааллуқ доштан', 'lemma': 'belong'},
    'local': {'ru': 'местный', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'courier': {'ru': 'курьерский', 'tg': 'қосидӣ', 'lemma': 'courier'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'led': {'ru': 'привести', 'tg': 'бурдан', 'lemma': 'lead'},
    'detectives': {'ru': 'детектив', 'tg': 'детектив', 'lemma': 'detective'},
    'straight': {'ru': 'прямо', 'tg': 'рост', 'lemma': 'straight'},
    'former': {'ru': 'бывший', 'tg': 'собиқ', 'lemma': 'former'},
    'employee': {'ru': 'сотрудник', 'tg': 'корманд', 'lemma': 'employee'},
    'set': {'ru': 'набор', 'tg': 'маҷмӯа', 'lemma': 'set'},
    'keys': {'ru': 'ключ', 'tg': 'калид', 'lemma': 'key'},
    'financial': {'ru': 'финансовый', 'tg': 'молиявӣ', 'lemma': 'financial'},
    'troubles': {'ru': 'проблема (трудности)', 'tg': 'мушкилот', 'lemma': 'trouble'},
    'colleagues': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'obvious': {'ru': 'очевидный', 'tg': 'равшан', 'lemma': 'obvious'},
    'frustrated': {'ru': 'раздражать', 'tg': 'ноумед кардан', 'lemma': 'frustrate'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'department': {'ru': 'отдел', 'tg': 'шӯъба', 'lemma': 'department'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'solved': {'ru': 'раскрывать (решать)', 'tg': 'ҳал кардан', 'lemma': 'solve'},
    'overlooked': {'ru': 'упущенный (незамеченный)', 'tg': 'нодида гирифташуда', 'lemma': 'overlooked'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'innocent': {'ru': 'невиновный', 'tg': 'бегуноҳ', 'lemma': 'innocent'},
    'along': {'ru': 'всё время', 'tg': 'ҳамеша', 'lemma': 'all along'},
    'apologised': {'ru': 'извиняться', 'tg': 'узр хостан', 'lemma': 'apologise'},
    'publicly': {'ru': 'публично', 'tg': 'оммавӣ', 'lemma': 'publicly'},
    'unwanted': {'ru': 'нежелательный', 'tg': 'номатлуб', 'lemma': 'unwanted'},
    'suspicion': {'ru': 'подозрение', 'tg': 'шубҳа', 'lemma': 'suspicion'},
    'briefly': {'ru': 'кратковременно', 'tg': 'мухтасар', 'lemma': 'briefly'},
    'faced': {'ru': 'сталкиваться', 'tg': 'рӯ ба рӯ шудан', 'lemma': 'face'},
    'had': HAVE, 'who': {'ru': 'который', 'tg': 'ки', 'lemma': 'who'}, 'whose': {'ru': 'чей', 'tg': 'аз они кӣ', 'lemma': 'whose'}, 'was': BE,
},
135: {
    'two': {'ru': 'двое', 'tg': 'ду нафар', 'lemma': 'two'},
    'haven\'t': HAVE, 'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'met': {'ru': 'встречаться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'before': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'before'},
    'host': {'ru': 'хозяин', 'tg': 'соҳибхона', 'lemma': 'host'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'guiding': {'ru': 'вести (направлять)', 'tg': 'роҳбарӣ кардан', 'lemma': 'guide'},
    'toward': {'ru': 'к', 'tg': 'ба сӯи', 'lemma': 'toward'},
    'stranger': {'ru': 'незнакомец', 'tg': 'бегона', 'lemma': 'stranger'},
    'window': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'shaking': {'ru': 'пожимать (трясти)', 'tg': 'даст додан', 'lemma': 'shake hands'},
    'hands': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'looked': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'vaguely': {'ru': 'смутно', 'tg': 'мубҳам', 'lemma': 'vaguely'},
    'familiar': {'ru': 'знакомый', 'tg': 'шинос', 'lemma': 'familiar'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'catching': {'ru': 'заставать (врасплох)', 'tg': 'ба ҳайрат овардан', 'lemma': 'catch off guard'},
    'guard': {'ru': 'врасплох', 'tg': 'бехабар', 'lemma': 'guard'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'gave': {'ru': 'проводить (давать)', 'tg': 'додан', 'lemma': 'give'},
    'lecture': {'ru': 'лекция', 'tg': 'лексия', 'lemma': 'lecture'},
    'attended': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'attend'},
    'once': {'ru': 'однажды', 'tg': 'як бор', 'lemma': 'once'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'pretended': {'ru': 'притворяться', 'tg': 'вонамуд кардан', 'lemma': 'pretend'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'admitting': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'defeat': {'ru': 'поражение', 'tg': 'шикаст', 'lemma': 'defeat'},
    'memorable': {'ru': 'запоминающийся', 'tg': 'ба ёдмонда', 'lemma': 'memorable'},
    'joked': {'ru': 'шутить', 'tg': 'шӯхӣ кардан', 'lemma': 'joke'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'more': {'ru': 'более', 'tg': 'бештар', 'lemma': 'more'},
    'genuinely': {'ru': 'искренне', 'tg': 'самимона', 'lemma': 'genuinely'},
    'time': {'ru': 'раз (время)', 'tg': 'дафъа', 'lemma': 'time'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'while': {'ru': 'некоторое время', 'tg': 'муддате', 'lemma': 'a while'},
    'mutual': {'ru': 'общий (взаимный)', 'tg': 'муштарак', 'lemma': 'mutual'},
    'acquaintances': {'ru': 'знакомые', 'tg': 'шиносҳо', 'lemma': 'acquaintance'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'replied': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'reply'},
    'impossible': {'ru': 'невозможно', 'tg': 'ғайриимкон', 'lemma': 'impossible'},
    'avoid': {'ru': 'избегать', 'tg': 'канорагирӣ кардан', 'lemma': 'avoid'},
    'parties': {'ru': 'вечеринка', 'tg': 'зиёфат', 'lemma': 'party'},
    'end': {'ru': 'конец', 'tg': 'охир', 'lemma': 'end'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'exchanged': {'ru': 'обмениваться', 'tg': 'мубодила кардан', 'lemma': 'exchange'},
    'numbers': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'promising': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'sometime': {'ru': 'как-нибудь', 'tg': 'вақте', 'lemma': 'sometime'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'left2': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'meant': {'ru': 'иметь в виду (всерьёз)', 'tg': 'дар назар доштан', 'lemma': 'mean'},
    'small': {'ru': 'маленький (небольшой)', 'tg': 'хурд', 'lemma': 'small'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'thing': {'ru': 'дело (вещь)', 'tg': 'чиз', 'lemma': 'thing'},
    'yet': {'ru': 'но всё же', 'tg': 'аммо', 'lemma': 'yet'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'turned': {'ru': 'оказаться', 'tg': 'баромадан', 'lemma': 'turn out'},
    'rather': {'ru': 'довольно', 'tg': 'хеле', 'lemma': 'rather'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'i\'d': BE, 'we\'d': HAVE, 'i\'ll': BE, 'won\'t': BE, 'aren\'t': BE, 'are': BE,
},
}

for sid, keys in {129: ['enough2', 'own2'], 130: [], 133: ['years2', 'much2'], 135: ['left2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
