# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
120: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'face': {'ru': 'сталкиваться (стоять перед)', 'tg': 'рӯ ба рӯ шудан', 'lemma': 'face'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'decision': {'ru': 'решение', 'tg': 'қарор', 'lemma': 'decision'},
    'which': {'ru': 'какой', 'tg': 'кадом', 'lemma': 'which'},
    'quickest': {'ru': 'самый быстрый', 'tg': 'тезтарин', 'lemma': 'quick'},
    'way': {'ru': 'путь', 'tg': 'роҳ', 'lemma': 'way'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'metro': {'ru': 'метро', 'tg': 'метро', 'lemma': 'metro'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'taxi': {'ru': 'такси', 'tg': 'таксӣ', 'lemma': 'taxi'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'most': {'ru': 'самый', 'tg': 'аз ҳама', 'lemma': 'most'},
    'reliable': {'ru': 'надёжный', 'tg': 'боэътимод', 'lemma': 'reliable'},
    'option': {'ru': 'вариант', 'tg': 'вариант', 'lemma': 'option'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'crowded': {'ru': 'многолюдный', 'tg': 'серодам', 'lemma': 'crowded'},
    'rush': {'ru': 'час пик', 'tg': 'соатҳои серodам', 'lemma': 'rush hour'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'cheaper': {'ru': 'дешевле', 'tg': 'арзонтар', 'lemma': 'cheap'},
    'than': {'ru': 'чем', 'tg': 'нисбат ба', 'lemma': 'than'},
    'definitely': {'ru': 'определённо', 'tg': 'бешубҳа', 'lemma': 'definitely'},
    'slowest': {'ru': 'самый медленный', 'tg': 'сусттарин', 'lemma': 'slow'},
    'especially': {'ru': 'особенно', 'tg': 'бахусус', 'lemma': 'especially'},
    'traffic': {'ru': 'движение (пробки)', 'tg': 'ҳаракати нақлиёт', 'lemma': 'traffic'},
    'bad': {'ru': 'плохой', 'tg': 'бад', 'lemma': 'bad'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'try': {'ru': 'попробовать', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'express': {'ru': 'экспресс', 'tg': 'экспресс', 'lemma': 'express'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'claims': {'ru': 'утверждать', 'tg': 'даъво кардан', 'lemma': 'claim'},
    'faster': {'ru': 'быстрее', 'tg': 'тезтар', 'lemma': 'fast'},
    'ordinary': {'ru': 'обычный', 'tg': 'оддӣ', 'lemma': 'ordinary'},
    'route': {'ru': 'маршрут', 'tg': 'масир', 'lemma': 'route'},
    'much': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'much'},
    'quicker': {'ru': 'быстрее', 'tg': 'тезтар', 'lemma': 'quick'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'seats': {'ru': 'сиденье (место)', 'tg': 'ҷой', 'lemma': 'seat'},
    'comfortable': {'ru': 'удобный', 'tg': 'бароҳат', 'lemma': 'comfortable'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'taxis': {'ru': 'такси', 'tg': 'таксӣ', 'lemma': 'taxi'},
    'convenient': {'ru': 'удобный', 'tg': 'мувофиқ', 'lemma': 'convenient'},
    'expensive': {'ru': 'дорогой', 'tg': 'қиммат', 'lemma': 'expensive'},
    'far': {'ru': 'намного (гораздо)', 'tg': 'хеле', 'lemma': 'by far'},
    'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'afford': {'ru': 'позволить себе', 'tg': 'иқтидор доштан', 'lemma': 'afford'},
    'one': {'ru': 'одну (штуку)', 'tg': 'якто', 'lemma': 'one'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'lot': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'a lot'},
    'patient': {'ru': 'терпеливый', 'tg': 'сабур', 'lemma': 'patient'},
    'prefers': {'ru': 'предпочитать', 'tg': 'афзал донистан', 'lemma': 'prefer'},
    'cycling': {'ru': 'езда на велосипеде', 'tg': 'велосипедронӣ', 'lemma': 'cycling'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'healthier': {'ru': 'полезнее (для здоровья)', 'tg': 'солимтар', 'lemma': 'healthy'},
    'any': {'ru': 'любой', 'tg': 'ҳар кадом', 'lemma': 'any'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'personally': {'ru': 'лично', 'tg': 'шахсан', 'lemma': 'personally'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'remains': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'safest': {'ru': 'самый безопасный', 'tg': 'бехатартарин', 'lemma': 'safe'},
    'choice': {'ru': 'выбор', 'tg': 'интихоб', 'lemma': 'choice'},
    'weather': {'ru': 'погода', 'tg': 'обу ҳаво', 'lemma': 'weather'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'pleasant': {'ru': 'приятный', 'tg': 'форам', 'lemma': 'pleasant'},
    'experience': {'ru': 'впечатление (опыт)', 'tg': 'таассурот', 'lemma': 'experience'},
    'summer': {'ru': 'лето', 'tg': 'тобистон', 'lemma': 'summer'},
    'heat': {'ru': 'жара', 'tg': 'гармӣ', 'lemma': 'heat'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'though': {'ru': 'однако', 'tg': 'аммо', 'lemma': 'though'},
    'rain': {'ru': 'дождь', 'tg': 'борон', 'lemma': 'rain'},
    'pouring': {'ru': 'лить (о дожде)', 'tg': 'сахт боридан', 'lemma': 'pour'},
    'outside': {'ru': 'снаружи', 'tg': 'берун', 'lemma': 'outside'},
    'easy': {'ru': 'лёгкий', 'tg': 'осон', 'lemma': 'easy'},
    'however': {'ru': 'как бы ни', 'tg': 'ҳарчанд', 'lemma': 'however'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'compared': {'ru': 'по сравнению', 'tg': 'нисбат ба', 'lemma': 'compared to'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'might': {'ru': 'могло бы', 'tg': 'мумкин аст', 'lemma': 'might'},
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'is': BE, 'it\'s': BE, 'wasn\'t': BE, 'they\'re': BE, 'who\'s': BE,
},
121: {
    'visited': {'ru': 'посещать', 'tg': 'ташриф овардан', 'lemma': 'visit'},
    'museum': {'ru': 'музей', 'tg': 'осорхона', 'lemma': 'museum'},
    'before': {'ru': 'раньше', 'tg': 'пештар', 'lemma': 'before'},
    'tucked': {'ru': 'спрятанный', 'tg': 'пинҳоншуда', 'lemma': 'tucked away'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'downtown': {'ru': 'центр города', 'tg': 'марказ', 'lemma': 'downtown'},
    'smaller': {'ru': 'меньше', 'tg': 'хурдтар', 'lemma': 'small'},
    'expected': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'collection': {'ru': 'коллекция', 'tg': 'маҷмӯа', 'lemma': 'collection'},
    'inside': {'ru': 'внутри', 'tg': 'дарун', 'lemma': 'inside'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'impressive': {'ru': 'впечатляющий', 'tg': 'таассуротбахш', 'lemma': 'impressive'},
    'entrance': {'ru': 'вход', 'tg': 'дарвозаи вуруд', 'lemma': 'entrance'},
    'guide': {'ru': 'гид', 'tg': 'роҳбалад', 'lemma': 'guide'},
    'handed': {'ru': 'вручать', 'tg': 'додан', 'lemma': 'hand'},
    'map': {'ru': 'карта', 'tg': 'харита', 'lemma': 'map'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'building': {'ru': 'здание', 'tg': 'бино', 'lemma': 'building'},
    'itself': {'ru': 'само', 'tg': 'худаш', 'lemma': 'itself'},
    'used': {'ru': 'раньше было (было когда-то)', 'tg': 'пештар буд', 'lemma': 'used to'},
    'factory': {'ru': 'фабрика', 'tg': 'корхона', 'lemma': 'factory'},
    'closed': {'ru': 'закрываться', 'tg': 'баста шудан', 'lemma': 'close'},
    'nineties': {'ru': 'девяностые', 'tg': 'солҳои навадум', 'lemma': 'nineties'},
    'later': {'ru': 'позже', 'tg': 'баъдтар', 'lemma': 'later'},
    'turned': {'ru': 'превращать', 'tg': 'табдил додан', 'lemma': 'turn into'},
    'cultural': {'ru': 'культурный', 'tg': 'фарҳангӣ', 'lemma': 'cultural'},
    'centre': {'ru': 'центр', 'tg': 'марказ', 'lemma': 'centre'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'painting': {'ru': 'картина', 'tg': 'наққошӣ', 'lemma': 'painting'},
    'immediately': {'ru': 'сразу', 'tg': 'фавран', 'lemma': 'immediately'},
    'caught': {'ru': 'привлечь (поймать)', 'tg': 'ҷалб кардан', 'lemma': 'catch'},
    'attention': {'ru': 'внимание', 'tg': 'диққат', 'lemma': 'attention'},
    'showed': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'busy': {'ru': 'оживлённый', 'tg': 'серодам', 'lemma': 'busy'},
    'scene': {'ru': 'сцена (вид)', 'tg': 'манзара', 'lemma': 'scene'},
    'hundred': {'ru': 'сто', 'tg': 'сад', 'lemma': 'hundred'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'ago': {'ru': 'назад', 'tg': 'пеш', 'lemma': 'ago'},
    'nearby': {'ru': 'рядом', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'photograph': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photograph'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'barely': {'ru': 'едва', 'tg': 'базӯр', 'lemma': 'barely'},
    'changed': {'ru': 'меняться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'generally': {'ru': 'в общем', 'tg': 'умуман', 'lemma': 'generally'},
    'prefer': {'ru': 'предпочитать', 'tg': 'афзал донистан', 'lemma': 'prefer'},
    'modern': {'ru': 'современный', 'tg': 'муосир', 'lemma': 'modern'},
    'art': {'ru': 'искусство', 'tg': 'санъат', 'lemma': 'art'},
    'particular': {'ru': 'конкретный (этот)', 'tg': 'мушаххас', 'lemma': 'particular'},
    'focused': {'ru': 'сосредоточиваться', 'tg': 'тамаркуз кардан', 'lemma': 'focus'},
    'mostly': {'ru': 'в основном', 'tg': 'бештар', 'lemma': 'mostly'},
    'local': {'ru': 'местный', 'tg': 'маҳаллӣ', 'lemma': 'local'},
    'history': {'ru': 'история', 'tg': 'таърих', 'lemma': 'history'},
    'surprised': {'ru': 'удивлять', 'tg': 'ҳайрон кардан', 'lemma': 'surprise'},
    'pleasantly': {'ru': 'приятно', 'tg': 'форам', 'lemma': 'pleasantly'},
    'group': {'ru': 'группа', 'tg': 'гурӯҳ', 'lemma': 'group'},
    'schoolchildren': {'ru': 'школьники', 'tg': 'мактаббачагон', 'lemma': 'schoolchildren'},
    'moved': {'ru': 'перемещаться', 'tg': 'ҳаракат кардан', 'lemma': 'move'},
    'noisily': {'ru': 'шумно', 'tg': 'бо ғавғо', 'lemma': 'noisily'},
    'room': {'ru': 'комната (зал)', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'interested': {'ru': 'заинтересованный', 'tg': 'ҳавасманд', 'lemma': 'interested'},
    'gift': {'ru': 'сувенирный', 'tg': 'тӯҳфа', 'lemma': 'gift shop'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'exhibits': {'ru': 'экспонат', 'tg': 'намоишот', 'lemma': 'exhibit'},
    'exit': {'ru': 'выход', 'tg': 'баромад', 'lemma': 'exit'},
    'café': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'leaving': {'ru': 'уходить', 'tg': 'рафтан', 'lemma': 'leave'},
    'especially': {'ru': 'особенно', 'tg': 'бахусус', 'lemma': 'especially'},
    'memorable': {'ru': 'запоминающийся', 'tg': 'ба ёдмонда', 'lemma': 'memorable'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'courtyard': {'ru': 'двор', 'tg': 'ҳавлӣ', 'lemma': 'courtyard'},
    'window': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'deserves': {'ru': 'заслуживать', 'tg': 'сазовор будан', 'lemma': 'deserve'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'quieter': {'ru': 'более тихий', 'tg': 'оромтар', 'lemma': 'quiet'},
    'visit': {'ru': 'посещение', 'tg': 'ташриф', 'lemma': 'visit'},
    'sometime': {'ru': 'когда-нибудь', 'tg': 'вақте', 'lemma': 'sometime'},
    'soon': {'ru': 'скоро', 'tg': 'ба зудӣ', 'lemma': 'soon'},
    'was': BE, 'wasn\'t': BE, 'i\'d': HAVE, 'i\'ve': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
},
122: {
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'rules': {'ru': 'правило', 'tg': 'қоида', 'lemma': 'rule'},
    'carefully': {'ru': 'внимательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'mustn\'t': {'ru': 'нельзя', 'tg': 'набояд', 'lemma': 'must not'},
    'use': {'ru': 'использовать', 'tg': 'истифода бурдан', 'lemma': 'use'},
    'personal': {'ru': 'личный', 'tg': 'шахсӣ', 'lemma': 'personal'},
    'phones': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'meetings': {'ru': 'встреча (совещание)', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'switch': {'ru': 'выключать', 'tg': 'хомӯш кардан', 'lemma': 'switch off'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'employees': {'ru': 'сотрудник', 'tg': 'корманд', 'lemma': 'employee'},
    'answer': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'client': {'ru': 'клиент', 'tg': 'муштарӣ', 'lemma': 'client'},
    'calls': {'ru': 'звонок', 'tg': 'занг', 'lemma': 'call'},
    'within': {'ru': 'в течение', 'tg': 'дар зарфи', 'lemma': 'within'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'rings': {'ru': 'гудок (звонок)', 'tg': 'занг', 'lemma': 'ring'},
    'according': {'ru': 'согласно', 'tg': 'мувофиқи', 'lemma': 'according to'},
    'policy': {'ru': 'политика (правила)', 'tg': 'сиёсат', 'lemma': 'policy'},
    'must': {'ru': 'должен', 'tg': 'бояд', 'lemma': 'must'},
    'admit': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'found': {'ru': 'находить (считать)', 'tg': 'ёфтан', 'lemma': 'find'},
    'rule': {'ru': 'правило', 'tg': 'қоида', 'lemma': 'rule'},
    'stricter': {'ru': 'строже', 'tg': 'сахтгиртар', 'lemma': 'strict'},
    'last': {'ru': 'прошлый (предыдущий)', 'tg': 'гузашта', 'lemma': 'last'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'should': {'ru': 'следует', 'tg': 'бояд', 'lemma': 'should'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'introduce': {'ru': 'представляться', 'tg': 'муаррифӣ кардан', 'lemma': 'introduce'},
    'clearly': {'ru': 'ясно (чётко)', 'tg': 'равшан', 'lemma': 'clearly'},
    'added': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'callers': {'ru': 'звонящий', 'tg': 'зангзананда', 'lemma': 'caller'},
    'frustrated': {'ru': 'раздосадованный', 'tg': 'ноумед', 'lemma': 'frustrated'},
    'understand': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'speaking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'speak'},
    'transfer': {'ru': 'переводить (звонок)', 'tg': 'гузарондан', 'lemma': 'transfer'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'explaining': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'why': {'ru': 'почему', 'tg': 'чаро', 'lemma': 'why'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'learned': {'ru': 'научиться', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'hard': {'ru': 'трудный (тяжёлый)', 'tg': 'сахт', 'lemma': 'hard'},
    'way2': {'ru': 'способ', 'tg': 'тарз', 'lemma': 'way'},
    'confusing': {'ru': 'запутанный', 'tg': 'печида', 'lemma': 'confusing'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'told': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'much': {'ru': 'слишком', 'tg': 'зиёд', 'lemma': 'much'},
    'patient': {'ru': 'терпеливый', 'tg': 'сабур', 'lemma': 'patient'},
    'polite': {'ru': 'вежливый', 'tg': 'муаддаб', 'lemma': 'polite'},
    'still': {'ru': 'всё же', 'tg': 'ба ҳар ҳол', 'lemma': 'still'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'eat': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'call': {'ru': 'звонок', 'tg': 'занг', 'lemma': 'call'},
    'apparently': {'ru': 'по-видимому', 'tg': 'зоҳиран', 'lemma': 'apparently'},
    'once': {'ru': 'однажды', 'tg': 'як бор', 'lemma': 'once'},
    'complained': {'ru': 'жаловаться', 'tg': 'шикоят кардан', 'lemma': 'complain'},
    'hearing': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'chewing': {'ru': 'жевать', 'tg': 'ҷавидан', 'lemma': 'chew'},
    'keep': {'ru': 'держать (делать)', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'brief': {'ru': 'краткий', 'tg': 'мухтасар', 'lemma': 'brief'},
    'enforces': {'ru': 'обеспечивать соблюдение', 'tg': 'риоя кунонидан', 'lemma': 'enforce'},
    'strictly': {'ru': 'строго', 'tg': 'сахтгирона', 'lemma': 'strictly'},
    'memorised': {'ru': 'запоминать', 'tg': 'аз ёд кардан', 'lemma': 'memorise'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'forget': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'put': {'ru': 'ставить', 'tg': 'гузоштан', 'lemma': 'put'},
    'hold': {'ru': 'ожидание (на линии)', 'tg': 'интизорӣ', 'lemma': 'hold'},
    'minute': {'ru': 'минута', 'tg': 'дақиқа', 'lemma': 'minute'},
    'checking': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'don\'t': DO, 'has': {'ru': 'должны', 'tg': 'бояд', 'lemma': 'have to'}, 'who\'s': HAVE, 'you\'re': BE, 'i\'d': BE,
},
123: {
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'fix': {'ru': 'чинить', 'tg': 'таъмир кардан', 'lemma': 'fix'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'broken': {'ru': 'сломанный', 'tg': 'вайроншуда', 'lemma': 'broken'},
    'skill': {'ru': 'навык', 'tg': 'малака', 'lemma': 'skill'},
    'taught': {'ru': 'учить', 'tg': 'омӯзондан', 'lemma': 'teach'},
    'himself': {'ru': 'сам (себя)', 'tg': 'худаш', 'lemma': 'himself'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'curiosity': {'ru': 'любопытство', 'tg': 'кунҷковӣ', 'lemma': 'curiosity'},
    'younger': {'ru': 'моложе', 'tg': 'ҷавонтар', 'lemma': 'young'},
    'could': {'ru': 'мог', 'tg': 'метавонист', 'lemma': 'could'},
    'barely': {'ru': 'едва', 'tg': 'базӯр', 'lemma': 'barely'},
    'change': {'ru': 'менять', 'tg': 'иваз кардан', 'lemma': 'change'},
    'lightbulb': {'ru': 'лампочка', 'tg': 'лампа', 'lemma': 'lightbulb'},
    'help': {'ru': 'помощь', 'tg': 'кӯмак', 'lemma': 'help'},
    'transformation': {'ru': 'преображение', 'tg': 'тағйирот', 'lemma': 'transformation'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'surprises': {'ru': 'удивлять', 'tg': 'ҳайрон кардан', 'lemma': 'surprise'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'anyone': {'ru': 'любой', 'tg': 'ҳар кас', 'lemma': 'anyone'},
    'learn': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'convinced': {'ru': 'убеждённый', 'tg': 'мутмаин', 'lemma': 'convinced'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'able': {'ru': 'способный', 'tg': 'қодир', 'lemma': 'able'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'breaking': {'ru': 'ломать', 'tg': 'шикастан', 'lemma': 'break'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'having': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'proper': {'ru': 'нормальный (подходящий)', 'tg': 'дурустӣ', 'lemma': 'proper'},
    'tools': {'ru': 'инструмент', 'tg': 'асбоб', 'lemma': 'tool'},
    'repair': {'ru': 'ремонтировать', 'tg': 'таъмир кардан', 'lemma': 'repair'},
    'cracked': {'ru': 'треснувший', 'tg': 'даррафта', 'lemma': 'cracked'},
    'screen': {'ru': 'экран', 'tg': 'экран', 'lemma': 'screen'},
    'under': {'ru': 'менее чем', 'tg': 'камтар аз', 'lemma': 'under'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'surprisingly': {'ru': 'удивительно', 'tg': 'бо тааҷҷуб', 'lemma': 'surprisingly'},
    'simple': {'ru': 'простой', 'tg': 'сода', 'lemma': 'simple'},
    'basic': {'ru': 'базовый (основной)', 'tg': 'асосӣ', 'lemma': 'basic'},
    'parts': {'ru': 'деталь (часть)', 'tg': 'қисм', 'lemma': 'part'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'theory': {'ru': 'теория', 'tg': 'назария', 'lemma': 'theory'},
    'thinks': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'hands': {'ru': 'рука', 'tg': 'даст', 'lemma': 'hand'},
    'steady': {'ru': 'твёрдый (устойчивый)', 'tg': 'устувор', 'lemma': 'steady'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'delicate': {'ru': 'тонкий (деликатный)', 'tg': 'нозук', 'lemma': 'delicate'},
    'practice': {'ru': 'практика', 'tg': 'машқ', 'lemma': 'practice'},
    'encourages': {'ru': 'подбадривать', 'tg': 'рӯҳбаланд кардан', 'lemma': 'encourage'},
    'handing': {'ru': 'вручать', 'tg': 'додан', 'lemma': 'hand'},
    'tiny': {'ru': 'крошечный', 'tg': 'хурдакак', 'lemma': 'tiny'},
    'screwdriver': {'ru': 'отвёртка', 'tg': 'бурма', 'lemma': 'screwdriver'},
    'nervously': {'ru': 'нервно', 'tg': 'бо асабоният', 'lemma': 'nervously'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'manage': {'ru': 'справляться', 'tg': 'муваффақ шудан', 'lemma': 'manage'},
    'remove': {'ru': 'снимать (убирать)', 'tg': 'баровардан', 'lemma': 'remove'},
    'screw': {'ru': 'винт', 'tg': 'винт', 'lemma': 'screw'},
    'disaster': {'ru': 'катастрофа', 'tg': 'фалокат', 'lemma': 'disaster'},
    'apparently': {'ru': 'по-видимому', 'tg': 'зоҳиран', 'lemma': 'apparently'},
    'counts': {'ru': 'считаться', 'tg': 'ҳисоб шудан', 'lemma': 'count'},
    'progress': {'ru': 'прогресс', 'tg': 'пешрафт', 'lemma': 'progress'},
    'training': {'ru': 'обучение', 'tg': 'таълим', 'lemma': 'training'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'online': {'ru': 'онлайн', 'tg': 'онлайн', 'lemma': 'online'},
    'videos': {'ru': 'видео', 'tg': 'видео', 'lemma': 'video'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'neighbourhood': {'ru': 'район', 'tg': 'маҳалла', 'lemma': 'neighbourhood'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'less': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'less'},
    'shop': {'ru': 'мастерская (магазин)', 'tg': 'мағоза', 'lemma': 'shop'},
    'charges': {'ru': 'брать плату', 'tg': 'пул гирифтан', 'lemma': 'charge'},
    'become': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'expert': {'ru': 'эксперт', 'tg': 'коршинос', 'lemma': 'expert'},
    'appreciate': {'ru': 'ценить', 'tg': 'қадр кардан', 'lemma': 'appreciate'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'}, 'i\'m': BE, 'i\'d': BE, 'you\'ll': BE, 'couldn\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'}, 'aren\'t': BE,
},
124: {
    'whistle': {'ru': 'свисток', 'tg': 'ҳуштак', 'lemma': 'whistle'},
    'blew': {'ru': 'свистеть (дуть)', 'tg': 'ҳуштак задан', 'lemma': 'blow'},
    'half': {'ru': 'тайм (половина)', 'tg': 'нима', 'lemma': 'half-time'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'team': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'scored': {'ru': 'забивать (гол)', 'tg': 'гол задан', 'lemma': 'score'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'expected': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'such': {'ru': 'такой', 'tg': 'чунин', 'lemma': 'such'},
    'strong': {'ru': 'сильный', 'tg': 'қавӣ', 'lemma': 'strong'},
    'start': {'ru': 'начало', 'tg': 'оғоз', 'lemma': 'start'},
    'training': {'ru': 'тренироваться', 'tg': 'машқ кардан', 'lemma': 'train'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'paying': {'ru': 'окупаться', 'tg': 'самар додан', 'lemma': 'pay off'},
    'coach': {'ru': 'тренер', 'tg': 'мураббӣ', 'lemma': 'coach'},
    'giving': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'instructions': {'ru': 'инструкция (указания)', 'tg': 'дастур', 'lemma': 'instruction'},
    'break': {'ru': 'перерыв', 'tg': 'танаффус', 'lemma': 'break'},
    'noticed': {'ru': 'замечать', 'tg': 'пай бурдан', 'lemma': 'notice'},
    'opposing': {'ru': 'противоположный (соперничающий)', 'tg': 'муқобил', 'lemma': 'opposing'},
    'captain': {'ru': 'капитан', 'tg': 'капитан', 'lemma': 'captain'},
    'watching': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'nervously': {'ru': 'нервно', 'tg': 'бо асабоният', 'lemma': 'nervously'},
    'across': {'ru': 'через', 'tg': 'аз тарафи он', 'lemma': 'across'},
    'pitch': {'ru': 'поле (футбольное)', 'tg': 'майдон', 'lemma': 'pitch'},
    'lost': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'player': {'ru': 'игрок', 'tg': 'бозигар', 'lemma': 'player'},
    'injury': {'ru': 'травма', 'tg': 'осеб', 'lemma': 'injury'},
    'previous': {'ru': 'предыдущий', 'tg': 'гузашта', 'lemma': 'previous'},
    'affected': {'ru': 'влиять', 'tg': 'таъсир расондан', 'lemma': 'affect'},
    'confidence': {'ru': 'уверенность', 'tg': 'боварӣ', 'lemma': 'confidence'},
    'second': {'ru': 'второй', 'tg': 'дуюм', 'lemma': 'second'},
    'began': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'running': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'wing': {'ru': 'фланг', 'tg': 'канор', 'lemma': 'wing'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'passed': {'ru': 'передавать (пас)', 'tg': 'пас додан', 'lemma': 'pass'},
    'ball': {'ru': 'мяч', 'tg': 'тӯб', 'lemma': 'ball'},
    'unexpectedly': {'ru': 'неожиданно', 'tg': 'ногаҳон', 'lemma': 'unexpectedly'},
    'practised': {'ru': 'тренировать (практиковать)', 'tg': 'машқ кардан', 'lemma': 'practise'},
    'particular': {'ru': 'конкретный', 'tg': 'мушаххас', 'lemma': 'particular'},
    'move': {'ru': 'приём (движение)', 'tg': 'ҳаракат', 'lemma': 'move'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'worked': {'ru': 'сработать (работать)', 'tg': 'кор кардан', 'lemma': 'work'},
    'perfectly': {'ru': 'идеально', 'tg': 'комилан', 'lemma': 'perfectly'},
    'crowd': {'ru': 'толпа (зрители)', 'tg': 'издиҳом', 'lemma': 'crowd'},
    'cheering': {'ru': 'подбадривать (кричать)', 'tg': 'рӯҳбаланд кардан', 'lemma': 'cheer'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'else': {'ru': 'остальное', 'tg': 'дигар', 'lemma': 'else'},
    'disappeared': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'disappear'},
    'worked2': {'ru': 'работать (трудиться)', 'tg': 'кор кардан', 'lemma': 'work'},
    'hard2': {'ru': 'усердно', 'tg': 'сахт', 'lemma': 'hard'},
    'final': {'ru': 'финальный', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'went': {'ru': 'звучать (прозвучать)', 'tg': 'садо додан', 'lemma': 'go'},
    'several': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'several'},
    'teammates': {'ru': 'товарищ по команде', 'tg': 'ҳамдаста', 'lemma': 'teammate'},
    'crying': {'ru': 'плакать', 'tg': 'гиря кардан', 'lemma': 'cry'},
    'relief': {'ru': 'облегчение', 'tg': 'сабукӣ', 'lemma': 'relief'},
    'afterwards': {'ru': 'после этого', 'tg': 'баъдтар', 'lemma': 'afterwards'},
    'admitted': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'secretly': {'ru': 'втайне', 'tg': 'пинҳонӣ', 'lemma': 'secretly'},
    'worried': {'ru': 'обеспокоенный', 'tg': 'нигарон', 'lemma': 'worried'},
    'week': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'hidden': {'ru': 'скрывать', 'tg': 'пинҳон кардан', 'lemma': 'hide'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'celebrated': {'ru': 'праздновать', 'tg': 'ҷашн гирифтан', 'lemma': 'celebrate'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'proudest': {'ru': 'самый гордый', 'tg': 'ифтихормандтарин', 'lemma': 'proud'},
    'felt': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'probably': {'ru': 'вероятно', 'tg': 'эҳтимол', 'lemma': 'probably'},
    'long': {'ru': 'долгий', 'tg': 'дароз', 'lemma': 'long'},
    'had': HAVE, 'hadn\'t': HAVE, 'was': BE, 'it\'s': BE, 'she\'d': HAVE,
},
125: {
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'used': {'ru': 'раньше делал (привычка в прошлом)', 'tg': 'пештар мекард', 'lemma': 'used to'},
    'argue': {'ru': 'спорить', 'tg': 'баҳс кардан', 'lemma': 'argue'},
    'absolutely': {'ru': 'абсолютно', 'tg': 'комилан', 'lemma': 'absolutely'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'teenagers': {'ru': 'подростки', 'tg': 'наврасон', 'lemma': 'teenager'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'chores': {'ru': 'домашние обязанности', 'tg': 'корҳои хона', 'lemma': 'chore'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'which': {'ru': 'какой', 'tg': 'кадом', 'lemma': 'which'},
    'channel': {'ru': 'канал', 'tg': 'канал', 'lemma': 'channel'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'days': {'ru': 'сейчас (в наши дни)', 'tg': 'ҳозир', 'lemma': 'these days'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'agree': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'disagree': {'ru': 'не соглашаться', 'tg': 'розӣ набудан', 'lemma': 'disagree'},
    'loudly': {'ru': 'громко', 'tg': 'баланд', 'lemma': 'loudly'},
    'football': {'ru': 'футбольный', 'tg': 'футболӣ', 'lemma': 'football'},
    'teams': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'share': {'ru': 'делить', 'tg': 'муштарак истифода бурдан', 'lemma': 'share'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'honestly': {'ru': 'честно говоря', 'tg': 'самимона', 'lemma': 'honestly'},
    'made': {'ru': 'делать (превращать)', 'tg': 'кардан', 'lemma': 'make'},
    'arguments': {'ru': 'спор', 'tg': 'баҳс', 'lemma': 'argument'},
    'worse': {'ru': 'хуже', 'tg': 'бадтар', 'lemma': 'worse'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'each': {'ru': 'каждый (друг друга)', 'tg': 'ҳар', 'lemma': 'each other'},
    'other': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'other'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'dinners': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'borrow': {'ru': 'брать взаймы (одалживать)', 'tg': 'қарз гирифтан', 'lemma': 'borrow'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'asking': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'furious': {'ru': 'взбешённый', 'tg': 'хеле хашмгин', 'lemma': 'furious'},
    'nowadays': {'ru': 'в наши дни', 'tg': 'дар айни замон', 'lemma': 'nowadays'},
    'first': {'ru': 'сначала', 'tg': 'аввал', 'lemma': 'first'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'forgets': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'relationship': {'ru': 'отношения', 'tg': 'муносибат', 'lemma': 'relationship'},
    'feel': {'ru': 'чувствоваться (казаться)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'competitive': {'ru': 'соперничающий', 'tg': 'рақобатнок', 'lemma': 'competitive'},
    'like': {'ru': 'словно (как)', 'tg': 'мисли', 'lemma': 'like'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'comparing': {'ru': 'сравнивать', 'tg': 'муқоиса кардан', 'lemma': 'compare'},
    'grades': {'ru': 'оценка', 'tg': 'баҳо', 'lemma': 'grade'},
    'achievements': {'ru': 'достижение', 'tg': 'дастовард', 'lemma': 'achievement'},
    'support': {'ru': 'поддерживать', 'tg': 'дастгирӣ кардан', 'lemma': 'support'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'especially': {'ru': 'особенно', 'tg': 'бахусус', 'lemma': 'especially'},
    'since': {'ru': 'с тех пор как', 'tg': 'аз он вақте ки', 'lemma': 'since'},
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'another': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'another'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'work': {'ru': 'работа', 'tg': 'кор', 'lemma': 'work'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'get': {'ru': 'ладить (получать)', 'tg': 'муросо кардан', 'lemma': 'get along'},
    'along': {'ru': 'вместе (ладить)', 'tg': 'бо ҳамдигар', 'lemma': 'along'},
    'properly': {'ru': 'по-настоящему', 'tg': 'дуруст', 'lemma': 'properly'},
    'adults': {'ru': 'взрослый', 'tg': 'калонсол', 'lemma': 'adult'},
    'wrong': {'ru': 'неправый (ошибающийся)', 'tg': 'хато', 'lemma': 'wrong'},
    'call': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'neither': {'ru': 'ни', 'tg': 'ҳеҷ', 'lemma': 'neither'},
    'bother': {'ru': 'утруждаться', 'tg': 'заҳмат кашидан', 'lemma': 'bother'},
    'doing': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'referee': {'ru': 'судить (быть арбитром)', 'tg': 'доварӣ кардан', 'lemma': 'referee'},
    'childhood': {'ru': 'детство (детский)', 'tg': 'кӯдакӣ', 'lemma': 'childhood'},
    'fights': {'ru': 'драка (ссора)', 'tg': 'ҷангу ҷанҷол', 'lemma': 'fight'},
    'constantly': {'ru': 'постоянно', 'tg': 'доимо', 'lemma': 'constantly'},
    'relieved': {'ru': 'испытывающий облегчение', 'tg': 'сабукшуда', 'lemma': 'relieved'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'act': {'ru': 'вести себя', 'tg': 'рафтор кардан', 'lemma': 'act'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'looking': {'ru': 'оглядываясь', 'tg': 'бознигарӣ', 'lemma': 'look back'},
    'fight': {'ru': 'ссориться', 'tg': 'ҷанҷол кардан', 'lemma': 'fight'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'similar': {'ru': 'похожий', 'tg': 'монанд', 'lemma': 'similar'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'clash': {'ru': 'сталкиваться (конфликтовать)', 'tg': 'бархӯрд кардан', 'lemma': 'clash'},
    'eventually': {'ru': 'в конце концов', 'tg': 'дар ниҳоят', 'lemma': 'eventually'},
    'were': BE, 'was': BE, 'we\'d': {'ru': 'мы (буд. время)', 'tg': 'мо хоҳем', 'lemma': 'we'}, 'she\'s': BE,
},
126: {
    'film': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'shot': {'ru': 'снимать (фильм)', 'tg': 'навор гирифтан', 'lemma': 'shoot'},
    'eighteen': {'ru': 'восемнадцать', 'tg': 'ҳаждаҳ', 'lemma': 'eighteen'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'different': {'ru': 'разный', 'tg': 'гуногун', 'lemma': 'different'},
    'countries': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'scenes': {'ru': 'сцена', 'tg': 'саҳна', 'lemma': 'scene'},
    'filmed': {'ru': 'снимать (фильм)', 'tg': 'навор гирифтан', 'lemma': 'film'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'studio': {'ru': 'студия', 'tg': 'студия', 'lemma': 'studio'},
    'outside': {'ru': 'за пределами', 'tg': 'берун аз', 'lemma': 'outside'},
    'city': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'city'},
    'script': {'ru': 'сценарий', 'tg': 'сенария', 'lemma': 'script'},
    'written': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'director': {'ru': 'режиссёр', 'tg': 'коргардон', 'lemma': 'director'},
    'surprised': {'ru': 'удивлять', 'tg': 'ҳайрон кардан', 'lemma': 'surprise'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'critics': {'ru': 'критик', 'tg': 'мунаққид', 'lemma': 'critic'},
    'once': {'ru': 'как только', 'tg': 'ҳамин ки', 'lemma': 'once'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'released': {'ru': 'выходить (в прокат)', 'tg': 'ба намоиш баромадан', 'lemma': 'release'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'costume': {'ru': 'костюм', 'tg': 'либос', 'lemma': 'costume'},
    'designed': {'ru': 'создавать (проектировать)', 'tg': 'тарҳрезӣ кардан', 'lemma': 'design'},
    'hand': {'ru': 'рука (вручную)', 'tg': 'дастӣ', 'lemma': 'by hand'},
    'main': {'ru': 'главный', 'tg': 'асосӣ', 'lemma': 'main'},
    'character\'s': {'ru': 'персонажа', 'tg': 'аз они қаҳрамон', 'lemma': 'character'},
    'coat': {'ru': 'пальто', 'tg': 'палто', 'lemma': 'coat'},
    'particular': {'ru': 'в частности', 'tg': 'алалхусус', 'lemma': 'in particular'},
    'praised': {'ru': 'хвалить', 'tg': 'таъриф кардан', 'lemma': 'praise'},
    'widely': {'ru': 'широко', 'tg': 'васеъ', 'lemma': 'widely'},
    'fashion': {'ru': 'мода', 'tg': 'мод', 'lemma': 'fashion'},
    'magazines': {'ru': 'журнал', 'tg': 'маҷалла', 'lemma': 'magazine'},
    'soundtrack': {'ru': 'саундтрек', 'tg': 'мусиқии филм', 'lemma': 'soundtrack'},
    'composed': {'ru': 'сочинять (музыку)', 'tg': 'офаридан', 'lemma': 'compose'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'musician': {'ru': 'музыкант', 'tg': 'мусиқинавоз', 'lemma': 'musician'},
    'discovered': {'ru': 'открывать (обнаруживать)', 'tg': 'ошкор кардан', 'lemma': 'discover'},
    'accident': {'ru': 'случайность (авария)', 'tg': 'тасодуф', 'lemma': 'accident'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'concert': {'ru': 'концерт', 'tg': 'консерт', 'lemma': 'concert'},
    'several': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'several'},
    'difficult': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'difficult'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'capture': {'ru': 'запечатлеть (поймать)', 'tg': 'сабт кардан', 'lemma': 'capture'},
    'right': {'ru': 'правильный (нужный)', 'tg': 'дуруст', 'lemma': 'right'},
    'lighting': {'ru': 'освещение', 'tg': 'равшанӣ', 'lemma': 'lighting'},
    'meant': {'ru': 'значить', 'tg': 'маъно доштан', 'lemma': 'mean'},
    'crew': {'ru': 'съёмочная группа', 'tg': 'гурӯҳи наворбардорӣ', 'lemma': 'crew'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'lead': {'ru': 'главная (ведущая)', 'tg': 'асосӣ', 'lemma': 'lead'},
    'actress': {'ru': 'актриса', 'tg': 'актриса', 'lemma': 'actress'},
    'chosen': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'hundreds': {'ru': 'сотни', 'tg': 'садҳо', 'lemma': 'hundred'},
    'candidates': {'ru': 'кандидат', 'tg': 'номзад', 'lemma': 'candidate'},
    'long': {'ru': 'долгий', 'tg': 'дароз', 'lemma': 'long'},
    'audition': {'ru': 'прослушивание (кастинг)', 'tg': 'озмоиш', 'lemma': 'audition'},
    'process': {'ru': 'процесс', 'tg': 'раванд', 'lemma': 'process'},
    'interestingly': {'ru': 'интересно (примечательно)', 'tg': 'ҷолиб', 'lemma': 'interestingly'},
    'final': {'ru': 'финальная (последняя)', 'tg': 'ниҳоӣ', 'lemma': 'final'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'rewritten': {'ru': 'переписывать', 'tg': 'дубора навиштан', 'lemma': 'rewrite'},
    'just': {'ru': 'всего лишь', 'tg': 'танҳо', 'lemma': 'just'},
    'weeks': {'ru': 'неделя', 'tg': 'ҳафта', 'lemma': 'week'},
    'before': {'ru': 'до', 'tg': 'пеш аз', 'lemma': 'before'},
    'shooting': {'ru': 'съёмки', 'tg': 'наворбардорӣ', 'lemma': 'shoot'},
    'ended': {'ru': 'заканчиваться', 'tg': 'тамом шудан', 'lemma': 'end'},
    'completed': {'ru': 'завершать', 'tg': 'ба анҷом расондан', 'lemma': 'complete'},
    'shown': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'festivals': {'ru': 'фестиваль', 'tg': 'фестивал', 'lemma': 'festival'},
    'officially': {'ru': 'официально', 'tg': 'расман', 'lemma': 'officially'},
    'worldwide': {'ru': 'по всему миру', 'tg': 'дар саросари ҷаҳон', 'lemma': 'worldwide'},
    'reviews': {'ru': 'рецензия (отзывы)', 'tg': 'баррасӣ', 'lemma': 'review'},
    'generally': {'ru': 'в целом', 'tg': 'умуман', 'lemma': 'generally'},
    'positive': {'ru': 'положительный', 'tg': 'мусбат', 'lemma': 'positive'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'felt': {'ru': 'считать (чувствовать)', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'ending': {'ru': 'концовка', 'tg': 'анҷом', 'lemma': 'ending'},
    'left': {'ru': 'оставлять', 'tg': 'мондан', 'lemma': 'leave'},
    'open': {'ru': 'открытый', 'tg': 'кушода', 'lemma': 'open'},
    'millions': {'ru': 'миллион', 'tg': 'миллион', 'lemma': 'million'},
    'tickets': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'since': {'ru': 'с тех пор', 'tg': 'аз он вақт', 'lemma': 'since'},
    'sold': {'ru': 'продавать', 'tg': 'фурӯхтан', 'lemma': 'sell'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'studied': {'ru': 'изучать', 'tg': 'омӯхтан', 'lemma': 'study'},
    'schools': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'example': {'ru': 'пример', 'tg': 'намуна', 'lemma': 'example'},
    'unusual': {'ru': 'необычный', 'tg': 'ғайриоддӣ', 'lemma': 'unusual'},
    'effective': {'ru': 'эффективный', 'tg': 'самарабахш', 'lemma': 'effective'},
    'storytelling': {'ru': 'повествование', 'tg': 'ҳикоягӯӣ', 'lemma': 'storytelling'},
    'was': BE, 'is': BE, 'has': HAVE,
},
127: {
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'work': {'ru': 'работа', 'tg': 'кор', 'lemma': 'work'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'seems': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'know': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'exactly': {'ru': 'точно', 'tg': 'дақиқ', 'lemma': 'exactly'},
    'why': {'ru': 'почему', 'tg': 'чаро', 'lemma': 'why'},
    'must': {'ru': 'должно быть', 'tg': 'бояд', 'lemma': 'must'},
    'sick': {'ru': 'больной', 'tg': 'бемор', 'lemma': 'sick'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'colleague': {'ru': 'коллега', 'tg': 'ҳамкор', 'lemma': 'colleague'},
    'looked': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'pale': {'ru': 'бледный', 'tg': 'рангпарида', 'lemma': 'pale'},
    'friday': {'ru': 'пятница', 'tg': 'ҷумъа', 'lemma': 'Friday'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'disagrees': {'ru': 'не соглашаться', 'tg': 'розӣ набудан', 'lemma': 'disagree'},
    'can\'t': {'ru': 'не может', 'tg': 'наметавонад', 'lemma': 'can'},
    'posted': {'ru': 'публиковать (пост)', 'tg': 'нашр кардан', 'lemma': 'post'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'mountains': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'broken': {'ru': 'сломанный', 'tg': 'вайроншуда', 'lemma': 'broken'},
    'another': {'ru': 'другой (некто ещё)', 'tg': 'дигаре', 'lemma': 'another'},
    'suggests': {'ru': 'предполагать', 'tg': 'пешниҳод кардан', 'lemma': 'suggest'},
    'calls': {'ru': 'звонки', 'tg': 'занг', 'lemma': 'call'},
    'going': {'ru': 'проходить (идти)', 'tg': 'гузаштан', 'lemma': 'go through'},
    'desk': {'ru': 'стол (парта)', 'tg': 'миз', 'lemma': 'desk'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'cup': {'ru': 'чашка', 'tg': 'пиёла', 'lemma': 'cup'},
    'untouched': {'ru': 'нетронутый', 'tg': 'дастнорас', 'lemma': 'untouched'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'planned': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'away': {'ru': 'уехавший (в отъезде)', 'tg': 'дар сафар', 'lemma': 'away'},
    'told': {'ru': 'говорить (сообщать)', 'tg': 'гуфтан', 'lemma': 'tell'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'privately': {'ru': 'лично (в частном порядке)', 'tg': 'шахсан', 'lemma': 'privately'},
    'offers': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'equally': {'ru': 'одинаково', 'tg': 'ба таври баробар', 'lemma': 'equally'},
    'confused': {'ru': 'растерянный', 'tg': 'гаранг', 'lemma': 'confused'},
    'asked': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'mentioned': {'ru': 'упоминать', 'tg': 'ёдовар шудан', 'lemma': 'mention'},
    'seeing': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'loading': {'ru': 'загружать', 'tg': 'бор кардан', 'lemma': 'load'},
    'suitcase': {'ru': 'чемодан', 'tg': 'чамадон', 'lemma': 'suitcase'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'monday': {'ru': 'понедельник', 'tg': 'душанбе', 'lemma': 'Monday'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'left2': {'ru': 'уезжать', 'tg': 'рафтан', 'lemma': 'leave'},
    'hurry': {'ru': 'спешка', 'tg': 'шитоб', 'lemma': 'hurry'},
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'where': {'ru': 'куда', 'tg': 'куҷо', 'lemma': 'where'},
    'quit': {'ru': 'увольняться', 'tg': 'тарк кардан', 'lemma': 'quit'},
    'telling': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'anyone': {'ru': 'кому-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'closest': {'ru': 'самый близкий', 'tg': 'наздиктарин', 'lemma': 'close'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'insists': {'ru': 'настаивать', 'tg': 'исрор кардан', 'lemma': 'insist'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'uncertain': {'ru': 'неуверенный', 'tg': 'номуайян', 'lemma': 'uncertain'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'automatically': {'ru': 'автоматически', 'tg': 'ба таври худкор', 'lemma': 'automatically'},
    'points': {'ru': 'указывать', 'tg': 'ишора кардан', 'lemma': 'point out'},
    'scheduled': {'ru': 'запланированный', 'tg': 'ба нақша гирифташуда', 'lemma': 'scheduled'},
    'post': {'ru': 'публикация (пост)', 'tg': 'нашр', 'lemma': 'post'},
    'thursday': {'ru': 'четверг', 'tg': 'панҷшанбе', 'lemma': 'Thursday'},
    'afternoon': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'theory': {'ru': 'теория (версия)', 'tg': 'фарзия', 'lemma': 'theory'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'equally2': {'ru': 'одинаково', 'tg': 'ба таври баробар', 'lemma': 'equally'},
    'walks': {'ru': 'входить (заходить)', 'tg': 'даромадан', 'lemma': 'walk in'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'explaining': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'sudden': {'ru': 'внезапный', 'tg': 'ногаҳонӣ', 'lemma': 'sudden'},
    'family': {'ru': 'семья (семейный)', 'tg': 'оилавӣ', 'lemma': 'family'},
    'emergency': {'ru': 'чрезвычайная ситуация', 'tg': 'ҳолати фавқулодда', 'lemma': 'emergency'},
    'admits': {'ru': 'признавать', 'tg': 'эътироф кардан', 'lemma': 'admit'},
    'already': {'ru': 'уже', 'tg': 'аллакай', 'lemma': 'already'},
    'imagined': {'ru': 'воображать', 'tg': 'тасаввур кардан', 'lemma': 'imagine'},
    'stranger': {'ru': 'более странный', 'tg': 'аҷибтар', 'lemma': 'strange'},
    'explanations': {'ru': 'объяснение', 'tg': 'шарҳ', 'lemma': 'explanation'},
    'hasn\'t': HAVE, 'has': HAVE, 'he\'d': HAVE,
    'she': {'ru': 'она', 'tg': 'вай', 'lemma': 'she'},
},
}

for sid, keys in {122: ['way2'], 124: ['worked2', 'hard2'], 127: ['left2', 'equally2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
