import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}

DICTS = {
46: {
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'doing': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    "don't": {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'likes': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'camping': {'ru': 'кемпинг (отдых в палатке)', 'tg': 'чодирнишинӣ', 'lemma': 'camping'},
    'cycling': {'ru': 'езда на велосипеде', 'tg': 'велосипедронӣ', 'lemma': 'cycling'},
    'enjoy': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'going': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'walk': {'ru': 'гулять', 'tg': 'сайр кардан', 'lemma': 'walk'},
    'park': {'ru': 'парк', 'tg': 'боғ', 'lemma': 'park'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'books': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'hate': {'ru': 'ненавидеть', 'tg': 'нафрат доштан', 'lemma': 'hate'},
    'shopping': {'ru': 'делать покупки', 'tg': 'харид кардан', 'lemma': 'shopping'},
    'watching': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'series': {'ru': 'сериал', 'tg': 'силсила', 'lemma': 'series'},
    'prefer': {'ru': 'предпочитать', 'tg': 'афзал донистан', 'lemma': 'prefer'},
    'cinema': {'ru': 'кинотеатр', 'tg': 'кинотеатр', 'lemma': 'cinema'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
    "can't": {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'swim': {'ru': 'плавать', 'tg': 'шино кардан', 'lemma': 'swim'},
    'run': {'ru': 'бегать', 'tg': 'давидан', 'lemma': 'run'},
    'sing': {'ru': 'петь', 'tg': 'суруд хондан', 'lemma': 'sing'},
    'painting': {'ru': 'рисовать', 'tg': 'рассомӣ кардан', 'lemma': 'paint'},
    'relaxes': {'ru': 'расслаблять', 'tg': 'ором кардан', 'lemma': 'relax'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'sleeping': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'yoga': {'ru': 'йога', 'tg': 'йога', 'lemma': 'yoga'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'health': {'ru': 'здоровье', 'tg': 'саломатӣ', 'lemma': 'health'},
    'travelling': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'places': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'holiday': {'ru': 'отпуск', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'favourite': {'ru': 'любимый', 'tg': 'дӯстдоштатарин', 'lemma': 'favourite'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'am': BE,
},
47: {
    'learn': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'learning': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'play': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'piano': {'ru': 'фортепиано', 'tg': 'пианино', 'lemma': 'piano'},
    'playing': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'music': {'ru': 'музыка', 'tg': 'мусиқӣ', 'lemma': 'music'},
    'swim': {'ru': 'плавать', 'tg': 'шино кардан', 'lemma': 'swim'},
    "can't": {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'sea': {'ru': 'море', 'tg': 'баҳр', 'lemma': 'sea'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'run': {'ru': 'бегать', 'tg': 'давидан', 'lemma': 'run'},
    'marathon': {'ru': 'марафон', 'tg': 'марафон', 'lemma': 'marathon'},
    'running': {'ru': 'бег', 'tg': 'давидан', 'lemma': 'run'},
    'kilometres': {'ru': 'километр', 'tg': 'километр', 'lemma': 'kilometre'},
    'hate': {'ru': 'ненавидеть', 'tg': 'нафрат доштан', 'lemma': 'hate'},
    'giving': {'ru': 'сдаваться', 'tg': 'аз ният гаштан', 'lemma': 'give up'},
    'more': {'ru': 'больше', 'tg': 'бештар', 'lemma': 'more'},
    'gym': {'ru': 'спортзал', 'tg': 'толори варзишӣ', 'lemma': 'gym'},
    'doing': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'exercise': {'ru': 'упражнение', 'tg': 'машқ', 'lemma': 'exercise'},
    'cook': {'ru': 'готовить', 'tg': 'пухтан', 'lemma': 'cook'},
    'too': {'ru': 'тоже', 'tg': 'низ', 'lemma': 'too'},
    'making': {'ru': 'делать (готовить)', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'pasta': {'ru': 'паста', 'tg': 'макарон', 'lemma': 'pasta'},
    'salad': {'ru': 'салат', 'tg': 'салат', 'lemma': 'salad'},
    'bake': {'ru': 'печь', 'tg': 'пухтан', 'lemma': 'bake'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'read': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'history': {'ru': 'история', 'tg': 'таърих', 'lemma': 'history'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'plan': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'save': {'ru': 'копить (тж. спасать)', 'tg': 'пасандоз кардан', 'lemma': 'save'},
    'money': {'ru': 'деньги', 'tg': 'пул', 'lemma': 'money'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'September': {'ru': 'сентябрь', 'tg': 'сентябр', 'lemma': 'September'},
    'achieve': {'ru': 'достигать', 'tg': 'ноил шудан', 'lemma': 'achieve'},
    'dreams': {'ru': 'мечта', 'tg': 'орзу', 'lemma': 'dream'},
    'believe': {'ru': 'верить', 'tg': 'бовар кардан', 'lemma': 'believe'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
},
48: {
    'sitting': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'cafe': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'hat': {'ru': 'шляпа', 'tg': 'кулоҳ', 'lemma': 'hat'},
    'sunglasses': {'ru': 'солнечные очки', 'tg': 'айнаки офтобӣ', 'lemma': 'sunglasses'},
    'tourist': {'ru': 'турист', 'tg': 'турист', 'lemma': 'tourist'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'undercover': {'ru': 'под прикрытием', 'tg': 'пинҳонӣ', 'lemma': 'undercover'},
    'watching': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'waiters': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    'waiter': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    'white': {'ru': 'белый', 'tg': 'сафед', 'lemma': 'white'},
    'shirt': {'ru': 'рубашка', 'tg': 'куртаи мардона', 'lemma': 'shirt'},
    'black': {'ru': 'чёрный', 'tg': 'сиёҳ', 'lemma': 'black'},
    'trousers': {'ru': 'брюки', 'tg': 'шим', 'lemma': 'trousers'},
    'serving': {'ru': 'обслуживать', 'tg': 'пешкаш кардан', 'lemma': 'serve'},
    'talking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'customer': {'ru': 'покупатель (клиент)', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'eating': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'toast': {'ru': 'тост', 'tg': 'нони бирёншуда', 'lemma': 'toast'},
    'drinking': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'writing': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'notes': {'ru': 'заметка', 'tg': 'қайд', 'lemma': 'note'},
    'boss': {'ru': 'начальник', 'tg': 'сардор', 'lemma': 'boss'},
    'phoning': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'phone'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'looking': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'staff': {'ru': 'персонал', 'tg': 'кормандон', 'lemma': 'staff'},
    'doing': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'cleaning': {'ru': 'убирать (чистить)', 'tg': 'тоза кардан', 'lemma': 'clean'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'cook': {'ru': 'повар', 'tg': 'ошпаз', 'lemma': 'cook'},
    'making': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'eggs': {'ru': 'яйцо', 'tg': 'тухм', 'lemma': 'egg'},
    'manager': {'ru': 'менеджер', 'tg': 'менеҷер', 'lemma': 'manager'},
    'newspaper': {'ru': 'газета', 'tg': 'рӯзнома', 'lemma': 'newspaper'},
    'suit': {'ru': 'костюм', 'tg': 'костюм', 'lemma': 'suit'},
    'jeans': {'ru': 'джинсы', 'tg': 'ҷинс', 'lemma': 'jeans'},
    'great': {'ru': 'отлично', 'tg': 'олӣ', 'lemma': 'great'},
    'keep': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep'},
    'smile': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'am': BE, 'is': BE, 'are': BE,
},
49: {
    'airport': {'ru': 'аэропорт', 'tg': 'фурудгоҳ', 'lemma': 'airport'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'flight': {'ru': 'рейс', 'tg': 'парвоз', 'lemma': 'flight'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'coat': {'ru': 'пальто', 'tg': 'палто', 'lemma': 'coat'},
    'carrying': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'suitcase': {'ru': 'чемодан', 'tg': 'чамадон', 'lemma': 'suitcase'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'ticket': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'looking': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'board': {'ru': 'табло', 'tg': 'тахтаи эълон', 'lemma': 'board'},
    'says': {'ru': 'написано (гласит)', 'tg': 'навишта шудааст', 'lemma': 'say'},
    'gate': {'ru': 'выход (на посадку)', 'tg': 'дарвоза', 'lemma': 'gate'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'sit': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'this': {'ru': 'это', 'tg': 'ин', 'lemma': 'this'},
    'oh': {'ru': 'ох', 'tg': 'оҳ', 'lemma': 'oh'},
    'wrong': {'ru': 'неправильный (не тот)', 'tg': 'нодуруст', 'lemma': 'wrong'},
    'place': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'stand': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'stand'},
    'run': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'out': {'ru': 'запыхавшийся (вне дыхания)', 'tg': 'нафастанг', 'lemma': 'out of breath'},
    'breath': {'ru': 'дыхание', 'tg': 'нафас', 'lemma': 'breath'},
    'still': {'ru': 'ещё (по-прежнему)', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'there': {'ru': 'там', 'tg': 'дар он ҷо', 'lemma': 'there'},
    'get': {'ru': 'садиться (на транспорт)', 'tg': 'савор шудан', 'lemma': 'get on'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'learn': {'ru': 'учиться (понимать)', 'tg': 'ёд гирифтан', 'lemma': 'learn'},
    'check': {'ru': 'проверять', 'tg': 'тафтиш кардан', 'lemma': 'check'},
    'number': {'ru': 'номер', 'tg': 'рақам', 'lemma': 'number'},
    'carefully': {'ru': 'внимательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'am': BE, 'is': BE,
},
50: {
    'staying': {'ru': 'останавливаться (проживать)', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'jacket': {'ru': 'куртка', 'tg': 'куртка', 'lemma': 'jacket'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'arriving': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'carrying': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'suitcase': {'ru': 'чемодан', 'tg': 'чамадон', 'lemma': 'suitcase'},
    'cap': {'ru': 'кепка', 'tg': 'кулоҳча', 'lemma': 'cap'},
    'wave': {'ru': 'махать (рукой)', 'tg': 'даст афшондан', 'lemma': 'wave'},
    'doesn\'t': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'see': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'talking': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'phone': {'ru': 'телефон (тж. звонить)', 'tg': 'телефон', 'lemma': 'phone'},
    'saying': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'right': {'ru': 'прямо (правильно)', 'tg': 'маҳз', 'lemma': 'right'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    "can't": {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'surprised': {'ru': 'удивлённый', 'tg': 'ҳайрон', 'lemma': 'surprised'},
    'different': {'ru': 'другой (разный)', 'tg': 'дигар', 'lemma': 'different'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'didn\'t': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'recognise': {'ru': 'узнавать', 'tg': 'шинохтан', 'lemma': 'recognise'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'buying': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'presents': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'present'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'jeans': {'ru': 'джинсы', 'tg': 'ҷинс', 'lemma': 'jeans'},
    'look': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'great': {'ru': 'отлично', 'tg': 'олӣ', 'lemma': 'great'},
    'room': {'ru': 'комната (номер)', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'unpack': {'ru': 'распаковывать', 'tg': 'кушода гирифтан', 'lemma': 'unpack'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'am': BE, 'is': BE, 'are': BE,
},
51: {
    'holiday': {'ru': 'отпуск', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'beach': {'ru': 'пляж', 'tg': 'соҳил', 'lemma': 'beach'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'shorts': {'ru': 'шорты', 'tg': 'шорт', 'lemma': 'shorts'},
    'sunglasses': {'ru': 'солнечные очки', 'tg': 'айнаки офтобӣ', 'lemma': 'sunglasses'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'coat': {'ru': 'пальто', 'tg': 'палто', 'lemma': 'coat'},
    'swimming': {'ru': 'плавать', 'tg': 'шино кардан', 'lemma': 'swim'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'book': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'wearing2': {'ru': 'носить', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'hat': {'ru': 'шляпа', 'tg': 'кулоҳ', 'lemma': 'hat'},
    'relaxing': {'ru': 'отдыхать', 'tg': 'истироҳат кардан', 'lemma': 'relax'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'thinking': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'work': {'ru': 'работа', 'tg': 'кор', 'lemma': 'work'},
    'enjoying': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'sun': {'ru': 'солнце', 'tg': 'офтоб', 'lemma': 'sun'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'having': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'fun': {'ru': 'веселье', 'tg': 'шодӣ', 'lemma': 'fun'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'walk': {'ru': 'гулять (прогулка)', 'tg': 'сайр кардан', 'lemma': 'walk'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'let\'s': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'let'},
    'along': {'ru': 'вдоль', 'tg': 'дар паҳлӯи', 'lemma': 'along'},
    'talk': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'ice': {'ru': 'лёд', 'tg': 'ях', 'lemma': 'ice'},
    'cream': {'ru': 'крем (мороженое)', 'tg': 'қаймоқ', 'lemma': 'cream'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'sunset': {'ru': 'закат', 'tg': 'ғуруб', 'lemma': 'sunset'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'am': BE, 'is': BE,
},
52: {
    'preparing': {'ru': 'готовиться', 'tg': 'тайёрӣ дидан', 'lemma': 'prepare'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'packing': {'ru': 'упаковывать', 'tg': 'бор кардан', 'lemma': 'pack'},
    'suitcase': {'ru': 'чемодан', 'tg': 'чамадон', 'lemma': 'suitcase'},
    'putting': {'ru': 'класть', 'tg': 'гузоштан', 'lemma': 'put'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'taking': {'ru': 'брать', 'tg': 'гирифтан', 'lemma': 'take'},
    'shirt': {'ru': 'рубашка', 'tg': 'куртаи мардона', 'lemma': 'shirt'},
    'jeans': {'ru': 'джинсы', 'tg': 'ҷинс', 'lemma': 'jeans'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'jacket': {'ru': 'куртка', 'tg': 'куртка', 'lemma': 'jacket'},
    'coat': {'ru': 'пальто', 'tg': 'палто', 'lemma': 'coat'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'shorts': {'ru': 'шорты', 'tg': 'шорт', 'lemma': 'shorts'},
    'cold': {'ru': 'холодный', 'tg': 'сард', 'lemma': 'cold'},
    'wearing': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'sweater': {'ru': 'свитер', 'tg': 'свитер', 'lemma': 'sweater'},
    'hat': {'ru': 'шляпа', 'tg': 'кулоҳ', 'lemma': 'hat'},
    'cap': {'ru': 'кепка', 'tg': 'кулоҳча', 'lemma': 'cap'},
    'carrying': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'leaving': {'ru': 'покидать (уходить)', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'getting': {'ru': 'брать (заказывать)', 'tg': 'гирифтан', 'lemma': 'get'},
    'taxi': {'ru': 'такси', 'tg': 'таксӣ', 'lemma': 'taxi'},
    'going': {'ru': 'идти (ехать)', 'tg': 'рафтан', 'lemma': 'go'},
    'airport': {'ru': 'аэропорт', 'tg': 'фурудгоҳ', 'lemma': 'airport'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'flight': {'ru': 'рейс', 'tg': 'парвоз', 'lemma': 'flight'},
    'nervous': {'ru': 'нервный', 'tg': 'асабӣ', 'lemma': 'nervous'},
    'excited': {'ru': 'взволнованный (в предвкушении)', 'tg': 'хурсанду мунтазир', 'lemma': 'excited'},
    'meet': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'buying': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'presents': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'present'},
    'staying': {'ru': 'останавливаться (проживать)', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'near': {'ru': 'рядом (близко)', 'tg': 'наздик', 'lemma': 'near'},
    'beach': {'ru': 'пляж', 'tg': 'соҳил', 'lemma': 'beach'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'am': BE, 'is': BE,
},
53: {
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'near': {'ru': 'рядом (близко)', 'tg': 'наздик', 'lemma': 'near'},
    'lake': {'ru': 'озеро', 'tg': 'кӯл', 'lemma': 'lake'},
    'some': {'ru': 'несколько (немного)', 'tg': 'баъзе', 'lemma': 'some'},
    'rooms': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'staying': {'ru': 'останавливаться (проживать)', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'lamp': {'ru': 'лампа', 'tg': 'чароғ', 'lemma': 'lamp'},
    'remote': {'ru': 'пульт (дистанционный)', 'tg': 'пулти дурдаст', 'lemma': 'remote control'},
    'control': {'ru': 'пульт', 'tg': 'идоракунӣ', 'lemma': 'control'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'any': {'ru': 'какой-либо (никакой)', 'tg': 'ягон', 'lemma': 'any'},
    'towels': {'ru': 'полотенце', 'tg': 'сачоқ', 'lemma': 'towel'},
    'bathroom': {'ru': 'ванная', 'tg': 'ҳаммомхона', 'lemma': 'bathroom'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'bath': {'ru': 'ванна', 'tg': 'ваннаи оббозӣ', 'lemma': 'bath'},
    'ask': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'reception': {'ru': 'ресепшн', 'tg': 'қабулгоҳ', 'lemma': 'reception'},
    'gift': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'gift'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'receptionist': {'ru': 'администратор', 'tg': 'қабулкунанда', 'lemma': 'receptionist'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'ground': {'ru': 'земля (первый этаж)', 'tg': 'ошёнаи якум', 'lemma': 'ground floor'},
    'floor': {'ru': 'этаж (пол)', 'tg': 'ошёна', 'lemma': 'floor'},
    'down': {'ru': 'вниз', 'tg': 'поён', 'lemma': 'down'},
    'bar': {'ru': 'бар', 'tg': 'бар', 'lemma': 'bar'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'see': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'woman': {'ru': 'женщина', 'tg': 'зан', 'lemma': 'woman'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'last': {'ru': 'последний (прошлый)', 'tg': 'гузашта', 'lemma': 'last'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'says2': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'spa': {'ru': 'спа', 'tg': 'спа', 'lemma': 'spa'},
    'fantastic': {'ru': 'потрясающий', 'tg': 'аҷоиб', 'lemma': 'fantastic'},
    'swimming': {'ru': 'плавательный', 'tg': 'шиноварӣ', 'lemma': 'swimming'},
    'pool': {'ru': 'бассейн', 'tg': 'ҳавз', 'lemma': 'pool'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'is': BE, 'are': BE, 'was': BE, 'were': BE, 'were2': BE,
},
}

# clean up placeholder duplicate keys used only to avoid python dict literal collisions
DICTS[51].pop('wearing2', None)
DICTS[53].pop('says2', None)
DICTS[53].pop('were2', None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
