import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.db.database import AsyncSessionLocal
from app.models.model_content import StoryQuestions

Q = {
    38: [
        ('What films does the narrator love?', 'Какие фильмы любит рассказчик?', 'Ровӣ кадом филмҳоро дӯст медорад?',
         ['Action films', 'Comedies', 'Horror films'], 'Action films',
         "The narrator says 'I love action films.'", 'Рассказчик говорит: «Я люблю боевики».', 'Ровӣ мегӯяд: «Ман филмҳои ҷангиро дӯст медорам».'),
        ('What does the friend prefer?', 'Что предпочитает друг?', 'Дӯст чиро авло медонад?',
         ['Comedies', 'Action films', 'Westerns'], 'Comedies',
         "The friend hates action films and prefers comedies.", 'Друг не любит боевики и предпочитает комедии.', 'Дӯст филмҳои ҷангиро дӯст намедорад ва комедияро авло медонад.'),
        ('Where do they decide to go?', 'Куда они решают пойти?', 'Онҳо ба куҷо рафтанро қарор мекунанд?',
         ['The theatre', 'The cinema', 'A restaurant'], 'The theatre',
         "The friend suggests 'Let's go to the theatre.'", 'Друг предлагает: «Давай пойдём в театр».', 'Дӯст пешниҳод мекунад: «Биёед ба театр равем».'),
    ],
    39: [
        ('What film do they want to see?', 'Какой фильм они хотят посмотреть?', 'Онҳо кадом филмро дидан мехоҳанд?',
         ['An action film', 'A western', 'A comedy'], 'An action film',
         'They go to the cinema wanting to see an action film.', 'Они идут в кино посмотреть боевик.', 'Онҳо ба кинотеатр филми ҷангӣ дидан мераванд.'),
        ('What film do they actually see?', 'Какой фильм они смотрят на самом деле?', 'Онҳо дар асл кадом филмро мебинанд?',
         ['A western', 'An action film', 'A comedy'], 'A western',
         'The film turns out to be a western, not an action film.', 'Фильм оказывается вестерном, а не боевиком.', 'Филм вестерн баромад, на филми ҷангӣ.'),
        ('What time does the film start?', 'Во сколько начинается фильм?', 'Филм соати чанд оғоз мешавад?',
         ['7.30', '7.00', '8.00'], '7.30',
         'The friend says the film starts at 7.30.', 'Друг говорит, что фильм начинается в 7.30.', 'Дӯст мегӯяд, ки филм соати 7.30 оғоз мешавад.'),
    ],
    40: [
        ('What kind of film is being made?', 'Какой фильм снимают?', 'Кадом филм гирифта истодааст?',
         ['A horror film', 'A comedy', 'A western'], 'A horror film',
         "The actor says 'I'm making a horror film.'", 'Актёр говорит: «Я снимаю фильм ужасов».', 'Актёр мегӯяд: «Ман филми даҳшатнок гирифта истодаам».'),
        ('What does the narrator do in the scene?', 'Что делает рассказчик в сцене?', 'Ровӣ дар саҳна чӣ мекунад?',
         ['Run and scream', 'Sing', 'Dance'], 'Run and scream',
         "The actor tells the narrator to 'just run and scream.'", 'Актёр говорит рассказчику «просто беги и кричи».', 'Актёр ба ровӣ мегӯяд: «танҳо давиду фарёд зан».'),
        ('What does the director say after the take?', 'Что говорит режиссёр после дубля?', 'Коргардон пас аз наворбардорӣ чӣ мегӯяд?',
         ['"Cut! That was great."', '"Try again."', '"Stop the camera."'], '"Cut! That was great."',
         "The director says 'Cut! That was great.'", 'Режиссёр говорит: «Снято! Это было отлично».', 'Коргардон мегӯяд: «Бас! Хеле хуб буд».'),
    ],
    41: [
        ('What do they do on Saturday?', 'Что они делают в субботу?', 'Онҳо рӯзи шанбе чӣ мекунанд?',
         ['Go to the cinema', 'Go to a restaurant', 'Stay at home'], 'Go to the cinema',
         'On Saturday they go to the cinema and watch a comedy.', 'В субботу они идут в кино смотреть комедию.', 'Рӯзи шанбе онҳо ба кинотеатр рафта комедия тамошо мекунанд.'),
        ('What instrument does the friend play?', 'На каком инструменте играет друг?', 'Дӯст кадом асбоби мусиқиро менавозад?',
         ['The piano', 'The guitar', 'The drums'], 'The piano',
         'The friend plays the piano very well.', 'Друг очень хорошо играет на пианино.', 'Дӯст пианинои хуб менавозад.'),
        ('What genre is the film they watch at home?', 'Какой жанр у фильма, который они смотрят дома?', 'Филме, ки дар хона тамошо мекунанд, аз кадом жанр аст?',
         ['Science fiction', 'Comedy', 'Western'], 'Science fiction',
         'They watch a science fiction film at home.', 'Дома они смотрят научно-фантастический фильм.', 'Дар хона онҳо филми илмию тахайюлӣ тамошо мекунанд.'),
    ],
    42: [
        ('What does the narrator want to become?', 'Кем хочет стать рассказчик?', 'Ровӣ кӣ шудан мехоҳад?',
         ['An actor', 'A director', 'A teacher'], 'An actor',
         "The narrator says 'I want to be an actor.'", 'Рассказчик говорит: «Я хочу стать актёром».', 'Ровӣ мегӯяд: «Ман актёр шудан мехоҳам».'),
        ('What does the narrator forget during practice?', 'Что рассказчик забывает во время практики?', 'Ровӣ ҳангоми машқ чиро фаромӯш мекунад?',
         ['The words', 'The teacher\'s name', 'The scene'], 'The words',
         "The narrator says 'I don't remember the words' and later forgets lines.", 'Рассказчик говорит: «Я не помню слова» и позже забывает реплики.', 'Ровӣ мегӯяд: «Ман калимаҳоро дар ёд надорам» ва баъдтар суханонро фаромӯш мекунад.'),
        ('What does the teacher say when he makes a mistake?', 'Что говорит учитель, когда он ошибается?', 'Муаллим ҳангоми хатогии ӯ чӣ мегӯяд?',
         ["Don't worry, continue", 'Start again', 'Leave the class'], "Don't worry, continue",
         "The teacher says 'Don't worry. You are learning.'", 'Учитель говорит: «Не переживай. Ты учишься».', 'Муаллим мегӯяд: «Ташвиш накаш. Ту меомӯзӣ».'),
    ],
    43: [
        ("What can't the narrator do well?", 'Что рассказчик не умеет хорошо делать?', 'Ровӣ чиро хуб карда наметавонад?',
         ['Park', 'Drive', 'Swim'], 'Park',
         "The narrator says 'I can drive a car, but I can't park!'", 'Рассказчик говорит: «Я умею водить машину, но не умею парковаться!»', 'Ровӣ мегӯяд: «Ман мошинро ронда метавонам, вале парк карда наметавонам!»'),
        ('What does the narrator love making?', 'Что рассказчик любит готовить?', 'Ровӣ пухтани чиро дӯст медорад?',
         ['Pasta', 'Salad', 'Soup'], 'Pasta',
         "The narrator says 'I like making pasta.'", 'Рассказчик говорит: «Мне нравится готовить пасту».', 'Ровӣ мегӯяд: «Ба ман пухтани макарон маъқул аст».'),
        ("What can the narrator do that the friend can't?", 'Что умеет рассказчик, но не умеет друг?', 'Ровӣ чиро карда метавонад, ки дӯсташ наметавонад?',
         ['Swim', 'Cook', 'Drive'], 'Swim',
         "The narrator can swim, but the friend can't swim.", 'Рассказчик умеет плавать, а друг не умеет.', 'Ровӣ шино карда метавонад, дӯсташ бошад не.'),
    ],
    44: [
        ('What mistake does the narrator make with the pasta?', 'Какую ошибку рассказчик делает с пастой?', 'Ровӣ дар макарон кадом хатогиро содир мекунад?',
         ['Puts too much salt', 'Burns it', 'Forgets the water'], 'Puts too much salt',
         'The narrator puts too much salt in the pasta.', 'Рассказчик кладёт слишком много соли в пасту.', 'Ровӣ ба макарон намаки зиёд мепартояд.'),
        ('What does the narrator like peeling?', 'Что рассказчик любит чистить?', 'Ровӣ тоза карданани чиро дӯст медорад?',
         ['Potatoes', 'Onions', 'Carrots'], 'Potatoes',
         "The narrator likes peeling potatoes.", 'Рассказчику нравится чистить картошку.', 'Ба ровӣ тоза кардани картошка маъқул аст.'),
        ('What does the narrator hate chopping?', 'Что рассказчик ненавидит резать?', 'Ровӣ буридани чиро нафрат дорад?',
         ['Onions', 'Potatoes', 'Tomatoes'], 'Onions',
         'The narrator hates chopping onions because they make him cry.', 'Рассказчик ненавидит резать лук, потому что от него плачет.', 'Ровӣ буридани пиёзро нафрат дорад, зеро аз он гиря мекунад.'),
    ],
    45: [
        ('What can the friend do?', 'Что умеет друг?', 'Дӯст чӣ карда метавонад?',
         ['Fly a plane', 'Drive a bus', 'Sail a boat'], 'Fly a plane',
         "The friend can fly a plane and loves flying.", 'Друг умеет управлять самолётом и любит летать.', 'Дӯст ҳавопаймо ронда метавонад ва парвозро дӯст медорад.'),
        ('How does the narrator feel about flying?', 'Как рассказчик относится к полётам?', 'Ровӣ дар бораи парвоз чӣ ҳис мекунад?',
         ['Afraid', 'Excited', 'Bored'], 'Afraid',
         "The narrator says 'I am afraid of flying.'", 'Рассказчик говорит: «Я боюсь летать».', 'Ровӣ мегӯяд: «Ман аз парвоз метарсам».'),
        ('What does the narrator like despite hating flying?', 'Что рассказчику нравится, несмотря на нелюбовь к полётам?', 'Бо вуҷуди нафрат аз парвоз, ба ровӣ чӣ маъқул аст?',
         ['The view', 'The speed', 'The food'], 'The view',
         "The narrator says 'I still hate flying, but I love the view.'", 'Рассказчик говорит: «Я всё ещё не люблю летать, но люблю вид».', 'Ровӣ мегӯяд: «Ман то ҳол парвозро нафрат дорам, вале манзараро дӯст медорам».'),
    ],
    46: [
        ("What can't the narrator do?", 'Что рассказчик не умеет делать?', 'Ровӣ чӣ карда наметавонад?',
         ['Sing', 'Swim', 'Run'], 'Sing',
         "The narrator says 'I can't sing.'", 'Рассказчик говорит: «Я не умею петь».', 'Ровӣ мегӯяд: «Ман суруд хонда наметавонам».'),
        ("What are the narrator's favourite months?", 'Какие месяцы любимые у рассказчика?', 'Моҳҳои дилхоҳи ровӣ кадомҳоянд?',
         ['July and August', 'June and July', 'August and September'], 'July and August',
         'The narrator says those (July and August) are the favourite months.', 'Рассказчик говорит, что это (июль и август) — любимые месяцы.', 'Ровӣ мегӯяд, ки ин (июл ва август) моҳҳои дилхоҳ ҳастанд.'),
        ('What does the narrator hate?', 'Что рассказчик ненавидит?', 'Ровӣ чиро нафрат дорад?',
         ['Shopping', 'Reading', 'Painting'], 'Shopping',
         "The narrator says 'I hate shopping.'", 'Рассказчик говорит: «Я ненавижу шопинг».', 'Ровӣ мегӯяд: «Ман харидро нафрат дорам».'),
    ],
    47: [
        ('What instrument can the narrator play?', 'На каком инструменте умеет играть рассказчик?', 'Ровӣ кадом асбоби мусиқиро навохта метавонад?',
         ['The piano', 'The guitar', 'The violin'], 'The piano',
         "The narrator says 'I can play the piano.'", 'Рассказчик говорит: «Я умею играть на пианино».', 'Ровӣ мегӯяд: «Ман пианино навохта метавонам».'),
        ('How far can the narrator run?', 'На какое расстояние может пробежать рассказчик?', 'Ровӣ то кадом масофа давида метавонад?',
         ['5 kilometres', '10 kilometres', '1 kilometre'], '5 kilometres',
         "The narrator says 'I can run 5 kilometres.'", 'Рассказчик говорит: «Я могу пробежать 5 километров».', 'Ровӣ мегӯяд: «Ман 5 километр давида метавонам».'),
        ('When does the narrator plan a trip?', 'Когда рассказчик планирует поездку?', 'Ровӣ сафарро ба кай нақша мегирад?',
         ['September', 'July', 'December'], 'September',
         "The narrator says 'I can go on a trip in September.'", 'Рассказчик говорит: «Я могу поехать в путешествие в сентябре».', 'Ровӣ мегӯяд: «Ман дар моҳи сентябр ба сафар рафта метавонам».'),
    ],
    48: [
        ("What is the narrator's real job?", 'Какая настоящая работа у рассказчика?', 'Кори ҳақиқии ровӣ чист?',
         ['Working undercover', 'A waiter', 'A cook'], 'Working undercover',
         "The narrator says 'I am working undercover!'", 'Рассказчик говорит: «Я работаю под прикрытием!»', 'Ровӣ мегӯяд: «Ман пинҳонӣ кор мекунам!»'),
        ('What is the waiter wearing?', 'Что надето на официанте?', 'Пешхидмат чӣ пӯшидааст?',
         ['A white shirt and black trousers', 'A suit', 'A cap'], 'A white shirt and black trousers',
         'The waiter is wearing a white shirt and black trousers.', 'На официанте белая рубашка и чёрные брюки.', 'Пешхидмат куртаи сафед ва шалвори сиёҳ пӯшидааст.'),
        ('What is the narrator wearing?', 'Что надето на рассказчике?', 'Ровӣ чӣ пӯшидааст?',
         ['Jeans and a T-shirt', 'A suit', 'A hat and sunglasses'], 'Jeans and a T-shirt',
         "The narrator tells the boss 'I'm wearing jeans and a T-shirt.'", 'Рассказчик говорит боссу: «На мне джинсы и футболка».', 'Ровӣ ба саркор мегӯяд: «Ман ҷинс ва футболка пӯшидаам».'),
    ],
    49: [
        ('What gate is for the Paris flight?', 'Какой выход у рейса в Париж?', 'Дари барои парвоз ба Париж кадом аст?',
         ['Gate 5', 'Gate 10', 'Gate 3'], 'Gate 5',
         'The woman says gate 5 is for the Paris flight.', 'Женщина говорит, что выход 5 — для рейса в Париж.', 'Зан мегӯяд, ки дари 5 барои парвоз ба Париж аст.'),
        ('What gate is for the London flight?', 'Какой выход у рейса в Лондон?', 'Дари барои парвоз ба Лондон кадом аст?',
         ['Gate 10', 'Gate 5', 'Gate 3'], 'Gate 10',
         "She says 'London is gate 10.'", 'Она говорит: «Лондон — выход 10».', 'Вай мегӯяд: «Лондон дари 10 аст».'),
        ('What does the narrator learn from this?', 'Чему учится рассказчик из этого случая?', 'Ровӣ аз ин ҳодиса чиро меомӯзад?',
         ['To check the gate number carefully', 'To arrive earlier', 'To ask for help'], 'To check the gate number carefully',
         'The narrator learns to check the gate number carefully.', 'Рассказчик учится внимательно проверять номер выхода.', 'Ровӣ рақами дарро бодиққат тафтиш карданро меомӯзад.'),
    ],
    50: [
        ('Why does the friend not see the narrator at first?', 'Почему друг сначала не видит рассказчика?', 'Чаро дӯст дар аввал ровиро намебинад?',
         ["He's talking on the phone", "He's asleep", "He's reading"], "He's talking on the phone",
         'The friend is talking on the phone and does not see the narrator waving.', 'Друг разговаривает по телефону и не видит, как рассказчик машет.', 'Дӯст бо телефон гап зада истодааст ва намебинад, ки ровӣ даст меҷунбонад.'),
        ('Why does the friend not recognise the narrator?', 'Почему друг не узнаёт рассказчика?', 'Чаро дӯст ровиро намешиносад?',
         ['Different clothes', 'A new haircut', 'Sunglasses'], 'Different clothes',
         'The friend says the narrator is wearing different clothes.', 'Друг говорит, что на рассказчике другая одежда.', 'Дӯст мегӯяд, ки ровӣ либоси дигар пӯшидааст.'),
        ('What is the narrator buying?', 'Что покупает рассказчик?', 'Ровӣ чӣ мехарад?',
         ['Presents for family', 'A new suitcase', 'A ticket'], 'Presents for family',
         "The narrator says 'I am buying presents for my family.'", 'Рассказчик говорит: «Я покупаю подарки для своей семьи».', 'Ровӣ мегӯяд: «Ман барои оилаам тӯҳфа мехарам».'),
    ],
    51: [
        ('What does the narrator do at the beach?', 'Что делает рассказчик на пляже?', 'Ровӣ дар соҳил чӣ мекунад?',
         ['Swim', 'Read a book', 'Sleep'], 'Swim',
         'The narrator is swimming at the beach.', 'Рассказчик плавает на пляже.', 'Ровӣ дар соҳил шино мекунад.'),
        ('What does the friend do instead?', 'Что вместо этого делает друг?', 'Дӯст ба ҷои он чӣ мекунад?',
         ['Reads a book', 'Swims', 'Sleeps'], 'Reads a book',
         'The friend is not swimming, he is reading a book.', 'Друг не плавает, он читает книгу.', 'Дӯст шино намекунад, ӯ китоб мехонад.'),
        ('What do they buy at the end?', 'Что они покупают в конце?', 'Онҳо дар охир чӣ мехаранд?',
         ['Ice cream', 'Sunglasses', 'A hat'], 'Ice cream',
         'They buy ice cream and watch the sunset.', 'Они покупают мороженое и смотрят закат.', 'Онҳо яхмос мехаранду ғуруби офтобро тамошо мекунанд.'),
    ],
    52: [
        ("What does the narrator NOT pack?", 'Что рассказчик НЕ берёт с собой?', 'Ровӣ чиро НАМЕГИРАД?',
         ['Shorts', 'A jacket', 'A sweater'], 'Shorts',
         "The narrator says 'I am not taking shorts.'", 'Рассказчик говорит: «Я не беру шорты».', 'Ровӣ мегӯяд: «Ман шим-и кӯтоҳ намегирам».'),
        ('Why not shorts?', 'Почему не шорты?', 'Чаро шим-и кӯтоҳ не?',
         ['It is cold', 'They are dirty', 'No space in the bag'], 'It is cold',
         "The narrator says 'It is cold' as the reason.", 'Причина, которую называет рассказчик: «Холодно».', 'Сабабе, ки ровӣ мегӯяд: «Хунук аст».'),
        ('Where is the narrator going to stay?', 'Где рассказчик собирается остановиться?', 'Ровӣ дар куҷо истиқомат мекунад?',
         ['A hotel near the beach', 'A friend\'s house', 'A campsite'], 'A hotel near the beach',
         "The narrator says 'I am staying in a hotel near the beach.'", 'Рассказчик говорит: «Я остановлюсь в отеле у пляжа».', 'Ровӣ мегӯяд: «Ман дар меҳмонхонаи наздики соҳил мемонам».'),
    ],
    53: [
        ('What room is the narrator staying in?', 'В каком номере остановился рассказчик?', 'Ровӣ дар кадом утоқ истиқомат дорад?',
         ['Room 10', 'Room 5', 'Room 1'], 'Room 10',
         "The narrator says 'I am staying in room 10.'", 'Рассказчик говорит: «Я остановился в номере 10».', 'Ровӣ мегӯяд: «Ман дар утоқи 10 истиқомат дорам».'),
        ('Where was the woman last night?', 'Где была женщина прошлой ночью?', 'Зан дишаб дар куҷо буд?',
         ['At the spa', 'In the swimming pool', 'In the gym'], 'At the spa',
         "The woman says 'I was at the spa.'", 'Женщина говорит: «Я была в спа».', 'Зан мегӯяд: «Ман дар спа будам».'),
        ("What is missing from the bathroom?", 'Чего не хватает в ванной?', 'Дар ҳаммомхона чӣ намерасад?',
         ['Towels', 'A shower', 'Soap'], 'Towels',
         "The narrator says 'There aren't any towels in the bathroom.'", 'Рассказчик говорит: «В ванной нет полотенец».', 'Ровӣ мегӯяд: «Дар ҳаммомхона сачоқ нест».'),
    ],
    54: [
        ('What does the narrator find under the bed?', 'Что рассказчик находит под кроватью?', 'Ровӣ дар зери кат чиро меёбад?',
         ['A car key', 'A remote control', 'A phone'], 'A car key',
         'The narrator finds a car key under the bed, not the remote control.', 'Рассказчик находит под кроватью автомобильный ключ, а не пульт.', 'Ровӣ дар зери кат калиди мошинро меёбад, на пулт.'),
        ('Where was the previous guest from?', 'Откуда был предыдущий гость?', 'Меҳмони пешина аз куҷо буд?',
         ['Germany', 'France', 'Spain'], 'Germany',
         'The receptionist says the previous guest was from Germany.', 'Администратор говорит, что предыдущий гость был из Германии.', 'Ресепшенист мегӯяд, ки меҳмони пешина аз Олмон буд.'),
        ('What room was the narrator in?', 'В каком номере был рассказчик?', 'Ровӣ дар кадом утоқ буд?',
         ['Room 10', 'Room 5', 'Room 1'], 'Room 10',
         "The narrator says 'I was in room 10.'", 'Рассказчик говорит: «Я был в номере 10».', 'Ровӣ мегӯяд: «Ман дар утоқи 10 будам».'),
    ],
    55: [
        ('What floor is the first room on?', 'На каком этаже первый номер?', 'Утоқи аввал дар кадом ошёна аст?',
         ['The fifth floor', 'The ground floor', 'The tenth floor'], 'The fifth floor',
         'The receptionist offers a room on the fifth floor.', 'Администратор предлагает номер на пятом этаже.', 'Ресепшенист утоқро дар ошёнаи панҷум пешниҳод мекунад.'),
        ("What is missing from the first room's lamp?", 'Чего не хватает у лампы в первом номере?', 'Дар чароғи утоқи аввал чӣ намерасад?',
         ['A light bulb', 'A switch', 'A shade'], 'A light bulb',
         "The narrator says 'there isn't a light bulb.'", 'Рассказчик говорит: «нет лампочки».', 'Ровӣ мегӯяд: «лампа нест».'),
        ('What floor is the good room on?', 'На каком этаже хороший номер?', 'Утоқи хуб дар кадом ошёна аст?',
         ['The 10th floor', 'The 5th floor', 'The ground floor'], 'The 10th floor',
         'The receptionist offers a room with a view on the 10th floor.', 'Администратор предлагает номер с видом на 10 этаже.', 'Ресепшенист утоқи бо манзараро дар ошёнаи 10-ум пешниҳод мекунад.'),
    ],
    56: [
        ('Where was the narrator yesterday?', 'Где рассказчик был вчера?', 'Ровӣ дирӯз дар куҷо буд?',
         ['At the beach', 'At the spa', 'In the gym'], 'At the beach',
         "The narrator says 'Yesterday, I was at the beach.'", 'Рассказчик говорит: «Вчера я был на пляже».', 'Ровӣ мегӯяд: «Дирӯз ман дар соҳил будам».'),
        ('What is the narrator doing today?', 'Что рассказчик делает сегодня?', 'Ровӣ имрӯз чӣ мекунад?',
         ['Relaxing and reading', 'Working', 'Travelling'], 'Relaxing and reading',
         'Today the narrator is relaxing, reading and watching TV.', 'Сегодня рассказчик отдыхает, читает и смотрит телевизор.', 'Имрӯз ровӣ дам мегираду мехонад ва телевизор тамошо мекунад.'),
        ('Which facility does the hotel have?', 'Какое удобство есть в отеле?', 'Меҳмонхона кадом хизматрасониро дорад?',
         ['A swimming pool', 'A library', 'A cinema'], 'A swimming pool',
         'The hotel has a swimming pool and a gym.', 'В отеле есть бассейн и спортзал.', 'Меҳмонхона ҳавзи шиноварӣ ва варзишгоҳ дорад.'),
    ],
    57: [
        ('Where were they on holiday last year?', 'Где они были в отпуске в прошлом году?', 'Соли гузашта онҳо дар куҷо истироҳат карданд?',
         ['Scotland', 'England', 'France'], 'Scotland',
         "The story says 'Last year, we were on holiday in Scotland.'", 'В истории сказано: «В прошлом году мы отдыхали в Шотландии».', 'Дар ҳикоя гуфта мешавад: «Соли гузашта мо дар Шотландия истироҳат кардем».'),
        ("What is new at the hotel this year?", 'Что нового в отеле в этом году?', 'Имсол дар меҳмонхона чӣ нав аст?',
         ['A new spa', 'A new pool', 'A new restaurant'], 'A new spa',
         'This year there is a new spa and a new gift shop.', 'В этом году появились новое спа и новый сувенирный магазин.', 'Имсол спаи нав ва мағозаи тӯҳфаи нав пайдо шуданд.'),
        ('What did they do last year?', 'Что они делали в прошлом году?', 'Онҳо соли гузашта чӣ карданд?',
         ['Went for walks and took photos', 'Went shopping', 'Stayed in the room'], 'Went for walks and took photos',
         'They went for walks and took photos last year.', 'В прошлом году они гуляли и фотографировали.', 'Соли гузашта онҳо сайругашт карданд ва акс гирифтанд.'),
    ],
    58: [
        ('What time did the narrator start work?', 'Во сколько рассказчик начал работу?', 'Ровӣ соати чанд кор сар кард?',
         ['9.00', '7.00', '6.00'], '9.00',
         'The narrator started work at 9.00 and finished at 5.00.', 'Рассказчик начал работу в 9.00 и закончил в 5.00.', 'Ровӣ соати 9.00 кор сар кард ва соати 5.00 тамом кард.'),
        ('What did the friend buy?', 'Что купила подруга?', 'Дугона чӣ харид?',
         ['A new dress', 'A new car', 'A new phone'], 'A new dress',
         'The friend went shopping and bought a new dress.', 'Подруга ходила по магазинам и купила новое платье.', 'Дугона ба харид рафт ва куртаи нав харид.'),
        ('What did the friend do in the evening?', 'Что подруга делала вечером?', 'Дугона бегоҳ чӣ кард?',
         ['Went to the cinema', 'Went to work', 'Did housework'], 'Went to the cinema',
         'The friend went to the cinema and saw a funny film.', 'Подруга пошла в кино и посмотрела смешной фильм.', 'Дугона ба кинотеатр рафту филми хандаовар тамошо кард.'),
    ],
    59: [
        ('What time did the narrator get up?', 'Во сколько встал рассказчик?', 'Ровӣ соати чанд бархост?',
         ['11.00', '9.00', '7.00'], '11.00',
         "The story says 'Last Sunday, I got up at 11.00.'", 'В истории сказано: «В прошлое воскресенье я встал в 11.00».', 'Дар ҳикоя гуфта мешавад: «Якшанбеи гузашта ман соати 11.00 бархостам».'),
        ('Did the narrator go to the gym?', 'Ходил ли рассказчик в спортзал?', 'Оё ровӣ ба варзишгоҳ рафт?',
         ['No', 'Yes', 'Not mentioned'], 'No',
         "The narrator says 'No, I didn't. I stayed at home.'", 'Рассказчик говорит: «Нет, не ходил. Остался дома».', 'Ровӣ мегӯяд: «Не, нарафтам. Дар хона мондам».'),
        ('How did the friend travel that day?', 'Как подруга передвигалась в тот день?', 'Дугона дар он рӯз чӣ тавр рафтуомад кард?',
         ['She walked', 'She drove', 'She took a taxi'], 'She walked',
         "The friend says 'No, I didn't (rent a car). I walked.'", 'Подруга говорит: «Нет (машину не арендовала). Я шла пешком».', 'Дугона мегӯяд: «Не (мошин иҷора накардам). Ман пиёда рафтам».'),
    ],
    60: [
        ('Where was the narrator flying to?', 'Куда летел рассказчик?', 'Ровӣ ба куҷо парвоз мекард?',
         ['Paris', 'London', 'Madrid'], 'Paris',
         "The story says 'I booked a flight to Paris.'", 'В истории сказано: «Я забронировал рейс в Париж».', 'Дар ҳикоя гуфта мешавад: «Ман ба Париж чипта харидам».'),
        ('What gate was the flight actually at?', 'У какого выхода на самом деле был рейс?', 'Парвоз дар асл дар кадом дар буд?',
         ['Gate 3', 'Gate 5', 'Gate 10'], 'Gate 3',
         'The announcement says the flight to Paris is at gate 3, but the narrator was at gate 5.', 'Объявление гласит, что рейс в Париж у выхода 3, а рассказчик был у выхода 5.', 'Эълон мегӯяд, ки парвоз ба Париж дар дари 3 аст, вале ровӣ дар дари 5 буд.'),
        ('Did the narrator miss the flight?', 'Опоздал ли рассказчик на рейс?', 'Оё ровӣ ба парвоз дер монд?',
         ['No', 'Yes', 'It is not clear'], 'No',
         "The attendant says 'No, you didn't. But you are late.'", 'Стюард говорит: «Нет, не опоздали. Но вы задержались».', 'Хизматрасон мегӯяд: «Не, дер намондед. Вале шумо дер кардед».'),
    ],
}


async def main():
    async with AsyncSessionLocal() as db:
        created = 0
        for story_id, questions in Q.items():
            for text_en, text_ru, text_tg, options, answer, expl_en, expl_ru, expl_tg in questions:
                db.add(StoryQuestions(
                    story_id=story_id,
                    text_en=text_en,
                    text_ru=text_ru,
                    text_tg=text_tg,
                    options=options,
                    answer=answer,
                    explanation_en=expl_en,
                    explanation_ru=expl_ru,
                    explanation_tg=expl_tg,
                ))
                created += 1
        await db.commit()
        print(f'created {created} story questions for {len(Q)} stories')


asyncio.run(main())
