# -*- coding: utf-8 -*-
import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}
HAVE = {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'}

DICTS = {
152: {
    'despite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'despite'},
    'losing': {'ru': 'терять', 'tg': 'гум кардан', 'lemma': 'lose'},
    'half': {'ru': 'половина', 'tg': 'ним', 'lemma': 'half'},
    'regular': {'ru': 'постоянный', 'tg': 'доимӣ', 'lemma': 'regular'},
    'customers': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'renovation': {'ru': 'ремонт', 'tg': 'таъмир', 'lemma': 'renovation'},
    'next': {'ru': 'по соседству', 'tg': 'дар паҳлӯ', 'lemma': 'next door'},
    'little': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'little'},
    'bookshop': {'ru': 'книжный магазин', 'tg': 'мағозаи китоб', 'lemma': 'bookshop'},
    'somehow': {'ru': 'как-то', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'managed': {'ru': 'удаваться (справляться)', 'tg': 'муваффақ шудан', 'lemma': 'manage'},
    'survive': {'ru': 'выживать', 'tg': 'зинда мондан', 'lemma': 'survive'},
    'difficult': {'ru': 'трудный', 'tg': 'душвор', 'lemma': 'difficult'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'although': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'although'},
    'owner': {'ru': 'владелец', 'tg': 'соҳиб', 'lemma': 'owner'},
    'considered': {'ru': 'рассматривать', 'tg': 'дида баромадан', 'lemma': 'consider'},
    'closing': {'ru': 'закрывать', 'tg': 'баста кардан', 'lemma': 'close'},
    'permanently': {'ru': 'навсегда', 'tg': 'доимӣ', 'lemma': 'permanently'},
    'decided': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'instead': {'ru': 'вместо этого', 'tg': 'ба ҷои он', 'lemma': 'instead'},
    'reorganise': {'ru': 'реорганизовать', 'tg': 'аз нав ташкил кардан', 'lemma': 'reorganise'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'business': {'ru': 'бизнес', 'tg': 'тиҷорат', 'lemma': 'business'},
    'order': {'ru': 'для того чтобы', 'tg': 'барои', 'lemma': 'in order to'},
    'attract': {'ru': 'привлекать', 'tg': 'ҷалб кардан', 'lemma': 'attract'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'kind': {'ru': 'вид (тип)', 'tg': 'навъ', 'lemma': 'kind'},
    'customer': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'spite': {'ru': 'несмотря на', 'tg': 'сарфи назар аз', 'lemma': 'in spite of'},
    'having': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'almost': {'ru': 'почти', 'tg': 'қариб', 'lemma': 'almost'},
    'marketing': {'ru': 'маркетинговый', 'tg': 'маркетингӣ', 'lemma': 'marketing'},
    'budget': {'ru': 'бюджет', 'tg': 'буҷа', 'lemma': 'budget'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'reading': {'ru': 'читательский', 'tg': 'хониш', 'lemma': 'reading club'},
    'club': {'ru': 'клуб', 'tg': 'клуб', 'lemma': 'club'},
    'purely': {'ru': 'исключительно', 'tg': 'танҳо', 'lemma': 'purely'},
    'reason': {'ru': 'причина (повод)', 'tg': 'сабаб', 'lemma': 'reason'},
    'return': {'ru': 'возвращаться', 'tg': 'баргаштан', 'lemma': 'return'},
    'weekly': {'ru': 'еженедельно', 'tg': 'ҳарҳафта', 'lemma': 'weekly'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'online': {'ru': 'онлайн', 'tg': 'онлайн', 'lemma': 'online'},
    'retailers': {'ru': 'ритейлер (продавец)', 'tg': 'фурӯшанда', 'lemma': 'retailer'},
    'offered': {'ru': 'предлагать', 'tg': 'пешниҳод кардан', 'lemma': 'offer'},
    'lower': {'ru': 'более низкие', 'tg': 'пасттар', 'lemma': 'low'},
    'prices': {'ru': 'цена', 'tg': 'нарх', 'lemma': 'price'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'locals': {'ru': 'местные жители', 'tg': 'сокинони маҳаллӣ', 'lemma': 'local'},
    'continued': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'continue'},
    'choosing': {'ru': 'выбирать', 'tg': 'интихоб кардан', 'lemma': 'choose'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'largely': {'ru': 'в основном', 'tg': 'асосан', 'lemma': 'largely'},
    'because': {'ru': 'потому что', 'tg': 'зеро', 'lemma': 'because'},
    'valued': {'ru': 'ценить', 'tg': 'қадр кардан', 'lemma': 'value'},
    'personal': {'ru': 'личная', 'tg': 'шахсӣ', 'lemma': 'personal'},
    'recommendations': {'ru': 'рекомендация', 'tg': 'тавсия', 'lemma': 'recommendation'},
    'gave': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'generously': {'ru': 'щедро', 'tg': 'саховатмандона', 'lemma': 'generously'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'exhausting': {'ru': 'изнурительный', 'tg': 'хастакунанда', 'lemma': 'exhausting'},
    'hours': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'alone': {'ru': 'одна', 'tg': 'танҳо', 'lemma': 'alone'},
    'refused': {'ru': 'отказываться', 'tg': 'рад кардан', 'lemma': 'refuse'},
    'hire': {'ru': 'нанимать', 'tg': 'киро кардан', 'lemma': 'hire'},
    'extra': {'ru': 'дополнительная', 'tg': 'иловагӣ', 'lemma': 'extra'},
    'help': {'ru': 'помощь', 'tg': 'кӯмак', 'lemma': 'help'},
    'worried': {'ru': 'обеспокоенная', 'tg': 'нигарон', 'lemma': 'worried'},
    'added': {'ru': 'дополнительный', 'tg': 'иловагӣ', 'lemma': 'added'},
    'financial': {'ru': 'финансовый', 'tg': 'молиявӣ', 'lemma': 'financial'},
    'risk': {'ru': 'риск', 'tg': 'хавф', 'lemma': 'risk'},
    'profits': {'ru': 'прибыль', 'tg': 'фоида', 'lemma': 'profit'},
    'remained': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'remain'},
    'modest': {'ru': 'скромный', 'tg': 'мӯътадил', 'lemma': 'modest'},
    'throughout': {'ru': 'на протяжении', 'tg': 'дар давоми', 'lemma': 'throughout'},
    'keep': {'ru': 'сохранять (держать)', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'single': {'ru': 'каждый (единственный)', 'tg': 'ҳар як', 'lemma': 'single'},
    'employee': {'ru': 'сотрудник', 'tg': 'корманд', 'lemma': 'employee'},
    'quietest': {'ru': 'самые тихие', 'tg': 'оромтарин', 'lemma': 'quiet'},
    'winter': {'ru': 'зимние', 'tg': 'зимистонӣ', 'lemma': 'winter'},
    'months': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'coming': {'ru': 'наступающий', 'tg': 'оянда', 'lemma': 'coming'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'planning': {'ru': 'планировать', 'tg': 'нақша кашидан', 'lemma': 'plan'},
    'café': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'corner': {'ru': 'уголок', 'tg': 'кунҷ', 'lemma': 'corner'},
    'linger': {'ru': 'задерживаться', 'tg': 'дер мондан', 'lemma': 'linger'},
    'longer': {'ru': 'дольше', 'tg': 'дарозтар', 'lemma': 'long'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'conversation': {'ru': 'разговор', 'tg': 'сӯҳбат', 'lemma': 'conversation'},
    'future': {'ru': 'будущее', 'tg': 'оянда', 'lemma': 'future'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'uncertain': {'ru': 'неопределённое', 'tg': 'номуайян', 'lemma': 'uncertain'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'regretted': {'ru': 'сожалеть', 'tg': 'пушаймон шудан', 'lemma': 'regret'},
    'keep2': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'keep going'},
    'going': {'ru': 'продолжать', 'tg': 'давом додан', 'lemma': 'going'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'advising': {'ru': 'советовать', 'tg': 'маслиҳат додан', 'lemma': 'advise'},
    'otherwise': {'ru': 'иначе (обратное)', 'tg': 'баръакс', 'lemma': 'otherwise'},
    'obstacle': {'ru': 'препятствие', 'tg': 'монеа', 'lemma': 'obstacle'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'tells': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'tell'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'survives': {'ru': 'выживать', 'tg': 'зинда мондан', 'lemma': 'survive'},
    'mainly': {'ru': 'в основном', 'tg': 'асосан', 'lemma': 'mainly'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'however': {'ru': 'как бы ни', 'tg': 'ҳарчанд', 'lemma': 'however'},
    'busy': {'ru': 'занятые', 'tg': 'серкор', 'lemma': 'busy'},
    'still': {'ru': 'всё же', 'tg': 'ба ҳар ҳол', 'lemma': 'still'},
    'occasionally': {'ru': 'иногда', 'tg': 'гоҳ-гоҳ', 'lemma': 'occasionally'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'somewhere': {'ru': 'куда-нибудь', 'tg': 'ҷое', 'lemma': 'somewhere'},
    'quiet': {'ru': 'тихое', 'tg': 'ором', 'lemma': 'quiet'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'browse': {'ru': 'листать (просматривать)', 'tg': 'варақ задан', 'lemma': 'browse'},
    'had': HAVE, 'she\'s': BE,
},
153: {
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'packing': {'ru': 'упаковывать', 'tg': 'бор кардан', 'lemma': 'pack'},
    'move': {'ru': 'переезд', 'tg': 'кӯчиш', 'lemma': 'move'},
    'underestimated': {'ru': 'недооценивать', 'tg': 'кам баҳо додан', 'lemma': 'underestimate'},
    'much': {'ru': 'сколько', 'tg': 'чанд', 'lemma': 'much'},
    'furniture': {'ru': 'мебель', 'tg': 'мебел', 'lemma': 'furniture'},
    'actually': {'ru': 'на самом деле', 'tg': 'дар ҳақиқат', 'lemma': 'actually'},
    'accumulated': {'ru': 'накапливать', 'tg': 'ҷамъ кардан', 'lemma': 'accumulate'},
    'years': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'information': {'ru': 'информация', 'tg': 'маълумот', 'lemma': 'information'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'flat\'s': {'ru': 'квартирный', 'tg': 'аз они манзил', 'lemma': 'flat'},
    'dimensions': {'ru': 'размеры', 'tg': 'андозаҳо', 'lemma': 'dimension'},
    'seemed': {'ru': 'казаться', 'tg': 'намудор шудан', 'lemma': 'seem'},
    'clear': {'ru': 'ясный', 'tg': 'равшан', 'lemma': 'clear'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'belongings': {'ru': 'вещи (имущество)', 'tg': 'мулк', 'lemma': 'belongings'},
    'clearly': {'ru': 'явно', 'tg': 'равшан', 'lemma': 'clearly'},
    'disagreed': {'ru': 'не соглашаться (противоречить)', 'tg': 'мувофиқат накардан', 'lemma': 'disagree'},
    'scissors': {'ru': 'ножницы', 'tg': 'қайчӣ', 'lemma': 'scissors'},
    'glasses': {'ru': 'очки', 'tg': 'айнак', 'lemma': 'glasses'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'favourite': {'ru': 'любимые', 'tg': 'дӯстдоштатарин', 'lemma': 'favourite'},
    'trousers': {'ru': 'брюки', 'tg': 'шим', 'lemma': 'trousers'},
    'vanished': {'ru': 'исчезать', 'tg': 'нопадид шудан', 'lemma': 'vanish'},
    'mysteriously': {'ru': 'таинственно', 'tg': 'сирри', 'lemma': 'mysteriously'},
    'unlabelled': {'ru': 'без ярлыка (не подписанный)', 'tg': 'бе нишона', 'lemma': 'unlabelled'},
    'boxes': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'impossible': {'ru': 'невозможно', 'tg': 'ғайриимкон', 'lemma': 'impossible'},
    'find': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'needed': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'advice': {'ru': 'совет', 'tg': 'маслиҳат', 'lemma': 'advice'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'experienced': {'ru': 'опытный', 'tg': 'таҷрибадор', 'lemma': 'experienced'},
    'called': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'aunt': {'ru': 'тётя', 'tg': 'хола', 'lemma': 'aunt'},
    'moved': {'ru': 'переезжать', 'tg': 'кӯч бастан', 'lemma': 'move'},
    'houses': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'more': {'ru': 'больше', 'tg': 'бештар', 'lemma': 'more'},
    'times': {'ru': 'раз', 'tg': 'маротиба', 'lemma': 'time'},
    'anyone': {'ru': 'кто-либо', 'tg': 'касе', 'lemma': 'anyone'},
    'else': {'ru': 'ещё (другой)', 'tg': 'дигар', 'lemma': 'else'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'far': {'ru': 'намного', 'tg': 'хеле', 'lemma': 'far'},
    'less': {'ru': 'меньше', 'tg': 'камтар', 'lemma': 'less'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'advised': {'ru': 'советовать', 'tg': 'маслиҳат додан', 'lemma': 'advise'},
    'confidently': {'ru': 'уверенно', 'tg': 'боэътимод', 'lemma': 'confidently'},
    'growing': {'ru': 'растущая', 'tg': 'афзоянда', 'lemma': 'grow'},
    'pile': {'ru': 'куча (стопка)', 'tg': 'тӯда', 'lemma': 'pile'},
    'suggested': {'ru': 'наводить на мысль (предполагать)', 'tg': 'нишон додан', 'lemma': 'suggest'},
    'otherwise': {'ru': 'обратное', 'tg': 'баръакс', 'lemma': 'otherwise'},
    'news': {'ru': 'новость', 'tg': 'хабар', 'lemma': 'news'},
    'removal': {'ru': 'перевозочный (грузовой)', 'tg': 'кӯчонидан', 'lemma': 'removal van'},
    'van': {'ru': 'фургон', 'tg': 'фургон', 'lemma': 'van'},
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'caused': {'ru': 'вызывать', 'tg': 'ба вуҷуд овардан', 'lemma': 'cause'},
    'genuine': {'ru': 'настоящую', 'tg': 'воқеӣ', 'lemma': 'genuine'},
    'panic': {'ru': 'паника', 'tg': 'ошуфтагӣ', 'lemma': 'panic'},
    'household': {'ru': 'домохозяйство (семья)', 'tg': 'хонавода', 'lemma': 'household'},
    'luggage': {'ru': 'багаж', 'tg': 'бор', 'lemma': 'luggage'},
    'filled': {'ru': 'заполнять', 'tg': 'пур кардан', 'lemma': 'fill'},
    'entire': {'ru': 'целая', 'tg': 'тамоми', 'lemma': 'entire'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'quite': {'ru': 'совсем', 'tg': 'комилан', 'lemma': 'quite'},
    'apart': {'ru': 'не считая', 'tg': 'ба ғайр аз', 'lemma': 'apart from'},
    'still': {'ru': 'ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'waiting': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'wrapped': {'ru': 'заворачивать', 'tg': 'печондан', 'lemma': 'wrap'},
    'labelled': {'ru': 'подписывать (ярлыком)', 'tg': 'нишона гузоштан', 'lemma': 'label'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'piece': {'ru': 'часть (кусок)', 'tg': 'пора', 'lemma': 'piece'},
    'useful': {'ru': 'полезный', 'tg': 'муфид', 'lemma': 'useful'},
    'online2': {'ru': 'онлайн', 'tg': 'онлайн', 'lemma': 'online'},
    'label': {'ru': 'подписывать (ярлыком)', 'tg': 'нишона гузоштан', 'lemma': 'label'},
    'category': {'ru': 'категория', 'tg': 'категория', 'lemma': 'category'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'completely': {'ru': 'полностью', 'tg': 'комилан', 'lemma': 'completely'},
    'ignored': {'ru': 'игнорировать', 'tg': 'сарфи назар кардан', 'lemma': 'ignore'},
    'until': {'ru': 'до', 'tg': 'то', 'lemma': 'until'},
    'point': {'ru': 'момент (точка)', 'tg': 'лаҳза', 'lemma': 'point'},
    'final': {'ru': 'последний', 'tg': 'охирин', 'lemma': 'final'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'exhausted': {'ru': 'измученный', 'tg': 'хаставу монда', 'lemma': 'exhausted'},
    'surrounded': {'ru': 'окружённый', 'tg': 'иҳоташуда', 'lemma': 'surrounded'},
    'scattered': {'ru': 'разбросанная', 'tg': 'пароканда', 'lemma': 'scattered'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'realised': {'ru': 'понимать (осознавать)', 'tg': 'дарк кардан', 'lemma': 'realise'},
    'however': {'ru': 'сколько бы ни', 'tg': 'ҳарчанд', 'lemma': 'however'},
    'owned': {'ru': 'владеть', 'tg': 'соҳиб будан', 'lemma': 'own'},
    'mattered': {'ru': 'иметь значение', 'tg': 'аҳамият доштан', 'lemma': 'matter'},
    'simply2': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'getting': {'ru': 'получить (высыпаться)', 'tg': 'ба даст овардан', 'lemma': 'get'},
    'some': {'ru': 'немного', 'tg': 'андак', 'lemma': 'some'},
    'proper': {'ru': 'нормальный', 'tg': 'дурустӣ', 'lemma': 'proper'},
    'sleep': {'ru': 'сон', 'tg': 'хоб', 'lemma': 'sleep'},
    'began': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'we\'d': {'ru': 'мы (буд. время)', 'tg': 'мо хоҳем', 'lemma': 'we'}, 'who\'s': HAVE, 'you\'ll': {'ru': 'нуждаться (буд.)', 'tg': 'ниёз хоҳед дошт', 'lemma': 'need'},
},
154: {
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'autumn': {'ru': 'осень', 'tg': 'тирамоҳ', 'lemma': 'autumn'},
    'village': {'ru': 'деревня', 'tg': 'деҳа', 'lemma': 'village'},
    'holds': {'ru': 'проводить', 'tg': 'баргузор кардан', 'lemma': 'hold'},
    'harvest': {'ru': 'урожайный (сбор урожая)', 'tg': 'ҳосил', 'lemma': 'harvest'},
    'festival': {'ru': 'фестиваль', 'tg': 'фестивал', 'lemma': 'festival'},
    'families': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'genuinely': {'ru': 'действительно', 'tg': 'дар ҳақиқат', 'lemma': 'genuinely'},
    'look': {'ru': 'ждать с нетерпением', 'tg': 'интизорӣ кашидан', 'lemma': 'look forward to'},
    'forward': {'ru': 'вперёд', 'tg': 'ба пеш', 'lemma': 'forward'},
    'both': {'ru': 'обе', 'tg': 'ҳар ду', 'lemma': 'both'},
    'bakeries': {'ru': 'пекарня', 'tg': 'нонвойхона', 'lemma': 'bakery'},
    'compete': {'ru': 'соревноваться', 'tg': 'мусобиқа кардан', 'lemma': 'compete'},
    'good': {'ru': 'добродушно', 'tg': 'хайрхоҳона', 'lemma': 'good-naturedly'},
    'bake': {'ru': 'печь', 'tg': 'пухтан', 'lemma': 'bake'},
    'impressive': {'ru': 'впечатляющий', 'tg': 'таассуротбахш', 'lemma': 'impressive'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'occasion': {'ru': 'событие (повод)', 'tg': 'маврид', 'lemma': 'occasion'},
    'household': {'ru': 'семья (домохозяйство)', 'tg': 'хонавода', 'lemma': 'household'},
    'expected': {'ru': 'ожидать', 'tg': 'интизор доштан', 'lemma': 'expect'},
    'contribute': {'ru': 'вносить вклад', 'tg': 'саҳм гузоштан', 'lemma': 'contribute'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'whether': {'ru': 'будь то', 'tg': 'хоҳ', 'lemma': 'whether'},
    'homemade': {'ru': 'домашняя', 'tg': 'хонагӣ', 'lemma': 'homemade'},
    'food': {'ru': 'еда', 'tg': 'хӯрок', 'lemma': 'food'},
    'handmade': {'ru': 'ручной работы', 'tg': 'дастӣ', 'lemma': 'handmade'},
    'decorations': {'ru': 'украшение', 'tg': 'ороиш', 'lemma': 'decoration'},
    'simply': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'simply'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'helping': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'set': {'ru': 'накрывать', 'tg': 'чидан', 'lemma': 'set up'},
    'tables': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'children': {'ru': 'дети', 'tg': 'кӯдакон', 'lemma': 'child'},
    'participate': {'ru': 'участвовать', 'tg': 'иштирок кардан', 'lemma': 'participate'},
    'competition': {'ru': 'соревнование', 'tg': 'мусобиқа', 'lemma': 'competition'},
    'judged': {'ru': 'судить (оценивать)', 'tg': 'доварӣ кардан', 'lemma': 'judge'},
    'mayor': {'ru': 'мэр', 'tg': 'мэр', 'lemma': 'mayor'},
    'oldest': {'ru': 'самый старый', 'tg': 'калонсолтарин', 'lemma': 'old'},
    'resident': {'ru': 'житель', 'tg': 'сокин', 'lemma': 'resident'},
    'tradition': {'ru': 'традиция', 'tg': 'анъана', 'lemma': 'tradition'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'quite': {'ru': 'толком', 'tg': 'комилан', 'lemma': 'quite'},
    'remembers': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'starting': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'without': {'ru': 'без', 'tg': 'бе', 'lemma': 'without'},
    'exception': {'ru': 'исключение', 'tg': 'истисно', 'lemma': 'exception'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'forgets': {'ru': 'забывать', 'tg': 'фаромӯш кардан', 'lemma': 'forget'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'chairs': {'ru': 'стул', 'tg': 'курсӣ', 'lemma': 'chair'},
    'complaint': {'ru': 'жалоба', 'tg': 'шикоят', 'lemma': 'complaint'},
    'family2': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'generously': {'ru': 'щедро', 'tg': 'саховатмандона', 'lemma': 'generously'},
    'shares': {'ru': 'делиться', 'tg': 'муштарак истифода бурдан', 'lemma': 'share'},
    'theirs': {'ru': 'их (свои)', 'tg': 'аз они онҳо', 'lemma': 'theirs'},
    'grandmothers': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'used': {'ru': 'раньше делал', 'tg': 'пештар мекард', 'lemma': 'used to'},
    'fiercely': {'ru': 'ожесточённо', 'tg': 'сахт', 'lemma': 'fiercely'},
    'whose': {'ru': 'чей', 'tg': 'аз они кӣ', 'lemma': 'whose'},
    'plov': {'ru': 'плов', 'tg': 'палов', 'lemma': 'plov'},
    'tasted': {'ru': 'иметь вкус', 'tg': 'таъм доштан', 'lemma': 'taste'},
    'better': {'ru': 'лучше', 'tg': 'беҳтар', 'lemma': 'better'},
    'rivalry': {'ru': 'соперничество', 'tg': 'рақобат', 'lemma': 'rivalry'},
    'delightfully': {'ru': 'восхитительно (к всеобщей радости)', 'tg': 'бо шодӣ', 'lemma': 'delightfully'},
    'continues': {'ru': 'продолжаться', 'tg': 'давом ёфтан', 'lemma': 'continue'},
    'even': {'ru': 'даже', 'tg': 'ҳатто', 'lemma': 'even'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'grandchildren': {'ru': 'внуки', 'tg': 'наберагон', 'lemma': 'grandchild'},
    'none': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'none'},
    'began': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'begin'},
    'though': {'ru': 'хотя', 'tg': 'гарчанде', 'lemma': 'though'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'agrees': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'existed': {'ru': 'существовать', 'tg': 'вуҷуд доштан', 'lemma': 'exist'},
    'long': {'ru': 'так долго', 'tg': 'дароз', 'lemma': 'long'},
    'itself': {'ru': 'сама', 'tg': 'худаш', 'lemma': 'itself'},
    'generation': {'ru': 'поколение', 'tg': 'насл', 'lemma': 'generation'},
    'adds': {'ru': 'добавлять', 'tg': 'илова кардан', 'lemma': 'add'},
    'new': {'ru': 'новое', 'tg': 'нав', 'lemma': 'new'},
    'dish': {'ru': 'блюдо', 'tg': 'таом', 'lemma': 'dish'},
    'game': {'ru': 'игра', 'tg': 'бозӣ', 'lemma': 'game'},
    'slightly': {'ru': 'слегка', 'tg': 'андак', 'lemma': 'slightly'},
    'updated': {'ru': 'обновлённая', 'tg': 'навсозишуда', 'lemma': 'updated'},
    'somehow': {'ru': 'каким-то образом', 'tg': 'бо ягон роҳ', 'lemma': 'somehow'},
    'keeping': {'ru': 'сохранять', 'tg': 'нигоҳ доштан', 'lemma': 'keep'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'event': {'ru': 'мероприятие', 'tg': 'ҳодиса', 'lemma': 'event'},
    'recognisably': {'ru': 'узнаваемо', 'tg': 'шиносоӣ', 'lemma': 'recognisably'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'daughters': {'ru': 'дочь', 'tg': 'духтар', 'lemma': 'daughter'},
    'old': {'ru': 'достаточно взрослые', 'tg': 'калонсол', 'lemma': 'old enough'},
    'enough': {'ru': 'достаточно', 'tg': 'кофӣ', 'lemma': 'enough'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'properly': {'ru': 'как следует', 'tg': 'дуруст', 'lemma': 'properly'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'carrying': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'dishes': {'ru': 'блюдо (посуда)', 'tg': 'зарфҳо', 'lemma': 'dish'},
    'careful': {'ru': 'осторожный', 'tg': 'бодиққат', 'lemma': 'careful'},
    'serious': {'ru': 'серьёзная', 'tg': 'ҷиддӣ', 'lemma': 'serious'},
    'concentration': {'ru': 'сосредоточенность', 'tg': 'тамаркуз', 'lemma': 'concentration'},
    'particular': {'ru': 'особый', 'tg': 'махсус', 'lemma': 'particular'},
    'way': {'ru': 'способ', 'tg': 'тарз', 'lemma': 'way'},
    'predictable': {'ru': 'предсказуемый', 'tg': 'пешбинишаванда', 'lemma': 'predictable'},
    'comforting': {'ru': 'утешительный (уютный)', 'tg': 'тасаллидиҳанда', 'lemma': 'comforting'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'is': BE, 'used2': BE, 'are': BE, 'can\'t': {'ru': 'не мочь', 'tg': 'наметавонанд', 'lemma': 'can'},
},
155: {
    'internet': {'ru': 'интернет', 'tg': 'интернет', 'lemma': 'internet'},
    'exploded': {'ru': 'взрываться', 'tg': 'таркидан', 'lemma': 'explode'},
    'excitement': {'ru': 'волнение (восторг)', 'tg': 'ҳаяҷон', 'lemma': 'excitement'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'archaeologists': {'ru': 'археолог', 'tg': 'бостоншинос', 'lemma': 'archaeologist'},
    'announced': {'ru': 'объявлять', 'tg': 'эълон кардан', 'lemma': 'announce'},
    'discovery': {'ru': 'открытие', 'tg': 'кашфиёт', 'lemma': 'discovery'},
    'may': {'ru': 'может быть', 'tg': 'мумкин аст', 'lemma': 'may'},
    'oldest': {'ru': 'самый старый (древний)', 'tg': 'қадимтарин', 'lemma': 'old'},
    'tool': {'ru': 'орудие (инструмент)', 'tg': 'асбоб', 'lemma': 'tool'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'found': {'ru': 'находить', 'tg': 'ёфтан', 'lemma': 'find'},
    'region': {'ru': 'регион', 'tg': 'минтақа', 'lemma': 'region'},
    'government': {'ru': 'правительство', 'tg': 'ҳукумат', 'lemma': 'government'},
    'quickly': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'quickly'},
    'allocated': {'ru': 'выделять', 'tg': 'ҷудо кардан', 'lemma': 'allocate'},
    'funding': {'ru': 'финансирование', 'tg': 'маблағгузорӣ', 'lemma': 'funding'},
    'further': {'ru': 'дальнейших', 'tg': 'минбаъда', 'lemma': 'further'},
    'excavation': {'ru': 'раскопки', 'tg': 'ҳафриёт', 'lemma': 'excavation'},
    'recognising': {'ru': 'признавая', 'tg': 'эътироф намуда', 'lemma': 'recognise'},
    'historical': {'ru': 'историческое', 'tg': 'таърихӣ', 'lemma': 'historical'},
    'importance': {'ru': 'важность', 'tg': 'аҳамият', 'lemma': 'importance'},
    'find': {'ru': 'находка', 'tg': 'кашф', 'lemma': 'find'},
    'scientists': {'ru': 'учёный', 'tg': 'олим', 'lemma': 'scientist'},
    'travel': {'ru': 'ездить', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'site': {'ru': 'место (раскопок)', 'tg': 'ҷои ҳафриёт', 'lemma': 'site'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'carefully': {'ru': 'тщательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'documenting': {'ru': 'документировать', 'tg': 'ҳуҷҷатгузорӣ кардан', 'lemma': 'document'},
    'each': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'each'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'layer': {'ru': 'слой', 'tg': 'қабат', 'lemma': 'layer'},
    'uncovered': {'ru': 'раскрывать (обнаруживать)', 'tg': 'кашф кардан', 'lemma': 'uncover'},
    'made': {'ru': 'сделан (из)', 'tg': 'сохта шуда', 'lemma': 'make'},
    'material': {'ru': 'материал', 'tg': 'мавод', 'lemma': 'material'},
    'rarely': {'ru': 'редко', 'tg': 'кам', 'lemma': 'rarely'},
    'used': {'ru': 'использовать', 'tg': 'истифода бурдан', 'lemma': 'use'},
    'elsewhere': {'ru': 'в другом месте', 'tg': 'дар ҷои дигар', 'lemma': 'elsewhere'},
    'ancient': {'ru': 'древняя', 'tg': 'қадим', 'lemma': 'ancient'},
    'history': {'ru': 'история', 'tg': 'таърих', 'lemma': 'history'},
    'puzzled': {'ru': 'озадачивать', 'tg': 'гаранг кардан', 'lemma': 'puzzle'},
    'researchers': {'ru': 'исследователь', 'tg': 'муҳаққиқ', 'lemma': 'researcher'},
    'since': {'ru': 'с', 'tg': 'аз', 'lemma': 'since'},
    'museum': {'ru': 'музей', 'tg': 'осорхона', 'lemma': 'museum'},
    'downtown': {'ru': 'в центре города', 'tg': 'марказ', 'lemma': 'downtown'},
    'exhibit': {'ru': 'выставка (экспонат)', 'tg': 'намоишгоҳ', 'lemma': 'exhibit'},
    'attracts': {'ru': 'привлекать', 'tg': 'ҷалб кардан', 'lemma': 'attract'},
    'visitors': {'ru': 'посетители', 'tg': 'меҳмонон', 'lemma': 'visitor'},
    'across': {'ru': 'со всей', 'tg': 'аз саросари', 'lemma': 'across'},
    'country': {'ru': 'страна', 'tg': 'кишвар', 'lemma': 'country'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'travelling': {'ru': 'ездить (путешествовать)', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'train': {'ru': 'поезд', 'tg': 'поезд', 'lemma': 'train'},
    'specifically': {'ru': 'специально', 'tg': 'махсус', 'lemma': 'specifically'},
    'single': {'ru': 'единственный', 'tg': 'ягона', 'lemma': 'single'},
    'display': {'ru': 'экспозиция (демонстрация)', 'tg': 'намоиш', 'lemma': 'display'},
    'curator': {'ru': 'куратор', 'tg': 'куратор', 'lemma': 'curator'},
    'explained': {'ru': 'объяснять', 'tg': 'фаҳмонидан', 'lemma': 'explain'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'dinner': {'ru': 'ужин', 'tg': 'хӯроки шом', 'lemma': 'dinner'},
    'nearby': {'ru': 'поблизости', 'tg': 'дар наздикӣ', 'lemma': 'nearby'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'spend': {'ru': 'проводить', 'tg': 'сарф кардан', 'lemma': 'spend'},
    'whole': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'whole'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'exploring': {'ru': 'исследовать', 'tg': 'тадқиқ кардан', 'lemma': 'explore'},
    'collection': {'ru': 'коллекция', 'tg': 'маҷмӯа', 'lemma': 'collection'},
    'significant': {'ru': 'значительное', 'tg': 'муҳим', 'lemma': 'significant'},
    'hosted': {'ru': 'принимать (проводить)', 'tg': 'мизбонӣ кардан', 'lemma': 'host'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'proudly': {'ru': 'гордо', 'tg': 'бо ифтихор', 'lemma': 'proudly'},
    'opening': {'ru': 'открытие', 'tg': 'кушоиш', 'lemma': 'opening'},
    'ceremony': {'ru': 'церемония', 'tg': 'маросим', 'lemma': 'ceremony'},
    'interestingly': {'ru': 'интересно', 'tg': 'ҷолиб', 'lemma': 'interestingly'},
    'spread': {'ru': 'распространять', 'tg': 'паҳн кардан', 'lemma': 'spread'},
    'several': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'several'},
    'inaccurate': {'ru': 'неточные', 'tg': 'нодуруст', 'lemma': 'inaccurate'},
    'theories': {'ru': 'теория', 'tg': 'назария', 'lemma': 'theory'},
    'origin': {'ru': 'происхождение', 'tg': 'пайдоиш', 'lemma': 'origin'},
    'historians': {'ru': 'историк', 'tg': 'муаррих', 'lemma': 'historian'},
    'considerable': {'ru': 'значительное', 'tg': 'назаррас', 'lemma': 'considerable'},
    'correcting': {'ru': 'исправлять', 'tg': 'ислоҳ кардан', 'lemma': 'correct'},
    'promised': {'ru': 'обещать', 'tg': 'ваъда додан', 'lemma': 'promise'},
    'additional': {'ru': 'дополнительные', 'tg': 'иловагӣ', 'lemma': 'additional'},
    'resources': {'ru': 'ресурсы', 'tg': 'захираҳо', 'lemma': 'resource'},
    'research': {'ru': 'исследование', 'tg': 'таҳқиқот', 'lemma': 'research'},
    'current': {'ru': 'текущий', 'tg': 'ҳозира', 'lemma': 'current'},
    'annual': {'ru': 'годовой', 'tg': 'солона', 'lemma': 'annual'},
    'growing': {'ru': 'растущая', 'tg': 'афзоянда', 'lemma': 'growing'},
    'now2': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'sits': {'ru': 'находиться (лежать)', 'tg': 'ҷойгир будан', 'lemma': 'sit'},
    'protected': {'ru': 'защищённый', 'tg': 'ҳифзшуда', 'lemma': 'protected'},
    'behind': {'ru': 'за', 'tg': 'дар паси', 'lemma': 'behind'},
    'glass': {'ru': 'стекло', 'tg': 'шиша', 'lemma': 'glass'},
    'object': {'ru': 'предмет (объект)', 'tg': 'объект', 'lemma': 'object'},
    'few': {'ru': 'несколько', 'tg': 'якчанд', 'lemma': 'few'},
    'short': {'ru': 'короткие', 'tg': 'кӯтоҳ', 'lemma': 'short'},
    'reshaped': {'ru': 'изменять (переформировывать)', 'tg': 'тағир додан', 'lemma': 'reshape'},
    'entire2': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'entire'},
    'understanding': {'ru': 'понимание', 'tg': 'фаҳмиш', 'lemma': 'understanding'},
    'own': {'ru': 'своё', 'tg': 'худи', 'lemma': 'own'},
    'distant': {'ru': 'далёкое', 'tg': 'дур', 'lemma': 'distant'},
    'past': {'ru': 'прошлое', 'tg': 'гузашта', 'lemma': 'past'},
    'has': HAVE, 'tool\'s': {'ru': 'орудийный', 'tg': 'аз они асбоб', 'lemma': 'tool'},
},
}

for sid, keys in {152: ['keep2'], 153: ['online2', 'simply2'], 154: ['family2', 'used2'], 155: ['now2', 'entire2']}.items():
    for k in keys:
        DICTS[sid].pop(k, None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
