import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
70: {
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'share': {'ru': 'делить (совместно использовать)', 'tg': 'муштарак истифода бурдан', 'lemma': 'share'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'different': {'ru': 'разный (другой)', 'tg': 'гуногун', 'lemma': 'different'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'tidy': {'ru': 'аккуратный', 'tg': 'озода', 'lemma': 'tidy'},
    'books': {'ru': 'книга', 'tg': 'китоб', 'lemma': 'book'},
    'shelves': {'ru': 'полка', 'tg': 'раф', 'lemma': 'shelf'},
    'pens': {'ru': 'ручка', 'tg': 'қалам', 'lemma': 'pen'},
    'box': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'cupboard': {'ru': 'шкаф', 'tg': 'ҷевон', 'lemma': 'cupboard'},
    'untidy': {'ru': 'неаккуратный', 'tg': 'бетартиб', 'lemma': 'untidy'},
    'things': {'ru': 'вещь', 'tg': 'чиз', 'lemma': 'thing'},
    'everywhere': {'ru': 'везде', 'tg': 'дар ҳама ҷо', 'lemma': 'everywhere'},
    'keys': {'ru': 'ключ', 'tg': 'калид', 'lemma': 'key'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'papers': {'ru': 'бумага', 'tg': 'коғаз', 'lemma': 'paper'},
    'under': {'ru': 'под', 'tg': 'дар зери', 'lemma': 'under'},
    'chair': {'ru': 'стул', 'tg': 'курсӣ', 'lemma': 'chair'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'cups': {'ru': 'чашка', 'tg': 'пиёла', 'lemma': 'cup'},
    'desk': {'ru': 'письменный стол', 'tg': 'мизи корӣ', 'lemma': 'desk'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'glasses': {'ru': 'очки', 'tg': 'айнак', 'lemma': 'glasses'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'look': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'those': {'ru': 'те', 'tg': 'он', 'lemma': 'those'},
    'magazines': {'ru': 'журнал', 'tg': 'маҷалла', 'lemma': 'magazine'},
    'answers': {'ru': 'отвечать', 'tg': 'ҷавоб додан', 'lemma': 'answer'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'idea': {'ru': 'идея', 'tg': 'ғоя', 'lemma': 'idea'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'needs': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'two': {'ru': 'два', 'tg': 'ду', 'lemma': 'two'},
    'zones': {'ru': 'зона', 'tg': 'минтақа', 'lemma': 'zone'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'side': {'ru': 'сторона', 'tg': 'тараф', 'lemma': 'side'},
    'yours': {'ru': 'твой (ваш)', 'tg': 'аз они шумо', 'lemma': 'yours'},
    'that': {'ru': 'тот', 'tg': 'он', 'lemma': 'that'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'half': {'ru': 'половина', 'tg': 'ним', 'lemma': 'half'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'our': {'ru': 'наш', 'tg': 'аз они мо', 'lemma': 'our'},
    'like': {'ru': 'похожий (тж. нравиться)', 'tg': 'монанд', 'lemma': 'like'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'is': BE, 'are': BE,
},
71: {
    'does': DO, 'don\'t': DO,
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'fast': {'ru': 'быстрый (быстро)', 'tg': 'тез', 'lemma': 'fast'},
    'walks': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'talks': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'eats': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'mountains': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'near': {'ru': 'рядом (близко)', 'tg': 'наздик', 'lemma': 'near'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'come': {'ru': 'давай (пошли)', 'tg': 'биё', 'lemma': 'come on'},
    'walk': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'faster': {'ru': 'быстрее', 'tg': 'тезтар', 'lemma': 'fast'},
    'stop': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'shouts': {'ru': 'кричать', 'tg': 'фарёд задан', 'lemma': 'shout'},
    'front': {'ru': 'впереди', 'tg': 'дар пеш', 'lemma': 'front'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'path': {'ru': 'тропа', 'tg': 'роҳ', 'lemma': 'path'},
    'narrow': {'ru': 'узкий', 'tg': 'танг', 'lemma': 'narrow'},
    'hot': {'ru': 'жаркий', 'tg': 'гарм', 'lemma': 'hot'},
    'slow': {'ru': 'замедлить', 'tg': 'суст кардан', 'lemma': 'slow down'},
    'down': {'ru': 'вниз', 'tg': 'поён', 'lemma': 'down'},
    'around': {'ru': 'вокруг', 'tg': 'атроф', 'lemma': 'around'},
    'just': {'ru': 'просто (только)', 'tg': 'фақат', 'lemma': 'just'},
    'run': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'enjoy': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'place': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'stops': {'ru': 'останавливаться', 'tg': 'истодан', 'lemma': 'stop'},
    'looks': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'green': {'ru': 'зелёный', 'tg': 'сабз', 'lemma': 'green'},
    'valley': {'ru': 'долина', 'tg': 'водӣ', 'lemma': 'valley'},
    'white': {'ru': 'белый', 'tg': 'сафед', 'lemma': 'white'},
    'peaks': {'ru': 'пик (вершина)', 'tg': 'қулла', 'lemma': 'peak'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'river': {'ru': 'река', 'tg': 'дарё', 'lemma': 'river'},
    'below': {'ru': 'внизу', 'tg': 'поён', 'lemma': 'below'},
    'air': {'ru': 'воздух', 'tg': 'ҳаво', 'lemma': 'air'},
    'fresh': {'ru': 'свежий', 'tg': 'тоза', 'lemma': 'fresh'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'wow': {'ru': 'ого (вау)', 'tg': 'ваҳ', 'lemma': 'wow'},
    'feel': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'calm': {'ru': 'спокойный', 'tg': 'ором', 'lemma': 'calm'},
    'little': {'ru': 'немного', 'tg': 'андак', 'lemma': 'little'},
    'hungry': {'ru': 'голодный', 'tg': 'гурусна', 'lemma': 'hungry'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'great': {'ru': 'отлично', 'tg': 'олӣ', 'lemma': 'great'},
    'let\'s': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'let'},
    'sit': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'please': {'ru': 'пожалуйста', 'tg': 'лутфан', 'lemma': 'please'},
    'eat': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'slowly': {'ru': 'медленно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'time': {'ru': 'раз (время)', 'tg': 'дафъа', 'lemma': 'time'},
    'warm': {'ru': 'тёплый', 'tg': 'гарм', 'lemma': 'warm'},
    'rocks': {'ru': 'камень', 'tg': 'сангҳо', 'lemma': 'rock'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'bags': {'ru': 'сумка', 'tg': 'сумка', 'lemma': 'bag'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'moment': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'is': BE, 'are': BE,
},
72: {
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'work': {'ru': 'работать (работа)', 'tg': 'кор кардан', 'lemma': 'work'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'baker': {'ru': 'пекарь', 'tg': 'нонво', 'lemma': 'baker'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'bakery': {'ru': 'пекарня', 'tg': 'нонвойхона', 'lemma': 'bakery'},
    'town': {'ru': 'город', 'tg': 'шаҳр', 'lemma': 'town'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'starts': {'ru': 'начинаться', 'tg': 'сар шудан', 'lemma': 'start'},
    'eleven': {'ru': 'одиннадцать', 'tg': 'ёздаҳ', 'lemma': 'eleven'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'most': {'ru': 'большинство', 'tg': 'бештари', 'lemma': 'most'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'don\'t': DO,
    'drink': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'smell': {'ru': 'запах', 'tg': 'бӯй', 'lemma': 'smell'},
    'fresh': {'ru': 'свежий', 'tg': 'тоза', 'lemma': 'fresh'},
    'bread': {'ru': 'хлеб', 'tg': 'нон', 'lemma': 'bread'},
    'wakes': {'ru': 'будить', 'tg': 'бедор кардан', 'lemma': 'wake up'},
    'first': {'ru': 'сначала (первый)', 'tg': 'аввал', 'lemma': 'first'},
    'make': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'dough': {'ru': 'тесто', 'tg': 'хамир', 'lemma': 'dough'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'bake': {'ru': 'печь', 'tg': 'пухтан', 'lemma': 'bake'},
    'sweet': {'ru': 'сладкий', 'tg': 'ширин', 'lemma': 'sweet'},
    'rolls': {'ru': 'булочка', 'tg': 'кулча', 'lemma': 'roll'},
    'favourite': {'ru': 'любимый', 'tg': 'дӯстдоштатарин', 'lemma': 'favourite'},
    'apple': {'ru': 'яблоко', 'tg': 'себ', 'lemma': 'apple'},
    'pies': {'ru': 'пирог', 'tg': 'пирог', 'lemma': 'pie'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'customers': {'ru': 'покупатель', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'warm': {'ru': 'тёплый', 'tg': 'гарм', 'lemma': 'warm'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'seven': {'ru': 'семь', 'tg': 'ҳафт', 'lemma': 'seven'},
    'walk': {'ru': 'идти пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'streets': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'sun': {'ru': 'солнце', 'tg': 'офтоб', 'lemma': 'sun'},
    'soft': {'ru': 'мягкий', 'tg': 'мулоим', 'lemma': 'soft'},
    'wife': {'ru': 'жена', 'tg': 'ҳамсар', 'lemma': 'wife'},
    'makes': {'ru': 'делать', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'much': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'much'},
    'too': {'ru': 'слишком', 'tg': 'аз ҳад зиёд', 'lemma': 'too'},
    'sleep': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'live': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'am': BE, 'is': BE,
},
73: {
    'knows': {'ru': 'знать', 'tg': 'донистан', 'lemma': 'know'},
    'everything': {'ru': 'всё', 'tg': 'ҳама чиз', 'lemma': 'everything'},
    'street': {'ru': 'улица', 'tg': 'кӯча', 'lemma': 'street'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'sits': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'window': {'ru': 'окно', 'tg': 'тиреза', 'lemma': 'window'},
    'watches': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'meet': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'hundred': {'ru': 'сто', 'tg': 'сад', 'lemma': 'hundred'},
    'questions': {'ru': 'вопрос', 'tg': 'савол', 'lemma': 'question'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'much': {'ru': 'сколько (много)', 'tg': 'чанд', 'lemma': 'much'},
    'pay': {'ru': 'платить', 'tg': 'пул додан', 'lemma': 'pay'},
    'smile': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'give': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'short': {'ru': 'короткий', 'tg': 'кӯтоҳ', 'lemma': 'short'},
    'answers': {'ru': 'ответ', 'tg': 'ҷавоб', 'lemma': 'answer'},
    'what': {'ru': 'какое (что)', 'tg': 'чӣ', 'lemma': 'what'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'get': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'get up'},
    'why': {'ru': 'почему', 'tg': 'чаро', 'lemma': 'why'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'drive': {'ru': 'водить (машину)', 'tg': 'мошин рондан', 'lemma': 'drive'},
    'fast': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'fast'},
    'when': {'ru': 'когда', 'tg': 'кай', 'lemma': 'when'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'come': {'ru': 'возвращаться (приходить)', 'tg': 'баргаштан', 'lemma': 'come back'},
    'back': {'ru': 'назад', 'tg': 'бозгашт', 'lemma': 'back'},
    'one': {'ru': 'однажды', 'tg': 'як рӯз', 'lemma': 'one day'},
    'decide': {'ru': 'решать', 'tg': 'қарор кардан', 'lemma': 'decide'},
    'play': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'game': {'ru': 'игра', 'tg': 'бозӣ', 'lemma': 'game'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'all': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'all'},
    'day2': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'don\'t': DO,
    'get2': {'ru': 'скучать', 'tg': 'дилгир шудан', 'lemma': 'get bored'},
    'bored': {'ru': 'скучающий', 'tg': 'дилгир', 'lemma': 'bored'},
    'laughs': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'young': {'ru': 'молодой', 'tg': 'ҷавон', 'lemma': 'young'},
    'man': {'ru': 'мужчина', 'tg': 'мард', 'lemma': 'man'},
    'watch': {'ru': 'наблюдать', 'tg': 'назорат кардан', 'lemma': 'watch'},
    'take': {'ru': 'заботиться', 'tg': 'ғамхорӣ кардан', 'lemma': 'take care'},
    'care': {'ru': 'забота', 'tg': 'ғамхорӣ', 'lemma': 'care'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'winter': {'ru': 'зима', 'tg': 'зимистон', 'lemma': 'winter'},
    'who': {'ru': 'кто', 'tg': 'кӣ', 'lemma': 'who'},
    'calls': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'call'},
    'doctor': {'ru': 'врач', 'tg': 'духтур', 'lemma': 'doctor'},
    'old': {'ru': 'старый', 'tg': 'пир', 'lemma': 'old'},
    'falls': {'ru': 'падать', 'tg': 'афтодан', 'lemma': 'fall'},
    'feeds': {'ru': 'кормить', 'tg': 'хӯрок додан', 'lemma': 'feed'},
    'cats': {'ru': 'кошка', 'tg': 'гурба', 'lemma': 'cat'},
    'travel': {'ru': 'путешествовать', 'tg': 'сафар кардан', 'lemma': 'travel'},
    'understand': {'ru': 'понимать', 'tg': 'фаҳмидан', 'lemma': 'understand'},
    'curious': {'ru': 'любопытный', 'tg': 'кунҷков', 'lemma': 'curious'},
    'guard': {'ru': 'страж (охранник)', 'tg': 'посбон', 'lemma': 'guard'},
    'is': BE, 'isn\'t': BE, 'she\'s': BE, 'do': DO,
},
74: {
    'sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'afternoons': {'ru': 'после полудня', 'tg': 'баъд аз пешин', 'lemma': 'afternoon'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'drinks': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'opens': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'old': {'ru': 'старый', 'tg': 'кӯҳна', 'lemma': 'old'},
    'photo': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'album': {'ru': 'альбом', 'tg': 'албом', 'lemma': 'album'},
    'look': {'ru': 'смотри(те)', 'tg': 'нигоҳ кунед', 'lemma': 'look'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'this': {'ru': 'это', 'tg': 'ин', 'lemma': 'this'},
    'grandfather\'s': {'ru': 'дедушкин', 'tg': 'аз они бобо', 'lemma': 'grandfather'},
    'first': {'ru': 'первый', 'tg': 'аввалин', 'lemma': 'first'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'and': {'ru': 'и', 'tg': 'ва', 'lemma': 'and'},
    'mother\'s': {'ru': 'мамин', 'tg': 'аз они модар', 'lemma': 'mother'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'spring': {'ru': 'весна', 'tg': 'баҳор', 'lemma': 'spring'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'black': {'ru': 'чёрный', 'tg': 'сиёҳ', 'lemma': 'black'},
    'white': {'ru': 'белый', 'tg': 'сафед', 'lemma': 'white'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'stories': {'ru': 'история (рассказ)', 'tg': 'ҳикоя', 'lemma': 'story'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'colour': {'ru': 'цвет', 'tg': 'ранг', 'lemma': 'colour'},
    'whose': {'ru': 'чья (чей)', 'tg': 'аз они кӣ', 'lemma': 'whose'},
    'wedding': {'ru': 'свадьба', 'tg': 'туй', 'lemma': 'wedding'},
    'asks': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'little': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'little'},
    'cousin': {'ru': 'двоюродный брат/сестра', 'tg': 'амакбача', 'lemma': 'cousin'},
    'uncle\'s': {'ru': 'дядин', 'tg': 'аз они тағо', 'lemma': 'uncle'},
    'baby': {'ru': 'младенец', 'tg': 'кӯдак', 'lemma': 'baby'},
    'that\'s': {'ru': 'это', 'tg': 'ин', 'lemma': 'that'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'face': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'red': {'ru': 'красный', 'tg': 'сурх', 'lemma': 'red'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'closes': {'ru': 'закрывать', 'tg': 'пӯшидан', 'lemma': 'close'},
    'only': {'ru': 'только', 'tg': 'танҳо', 'lemma': 'only'},
    'people': {'ru': 'люди', 'tg': 'одамон', 'lemma': 'people'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'again': {'ru': 'снова', 'tg': 'боз', 'lemma': 'again'},
    'friday': {'ru': 'пятница', 'tg': 'ҷумъа', 'lemma': 'Friday'},
    'make': {'ru': 'делать (готовить)', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'plov': {'ru': 'плов', 'tg': 'палов', 'lemma': 'plov'},
    'kiss': {'ru': 'целовать', 'tg': 'бӯса кардан', 'lemma': 'kiss'},
    'goodbye': {'ru': 'прощай', 'tg': 'хайр', 'lemma': 'goodbye'},
    'small': {'ru': 'маленький', 'tg': 'хурд', 'lemma': 'small'},
    'heart': {'ru': 'сердце', 'tg': 'дил', 'lemma': 'heart'},
    'biggest': {'ru': 'самый большой', 'tg': 'бузургтарин', 'lemma': 'biggest'},
    'place': {'ru': 'место', 'tg': 'ҷой', 'lemma': 'place'},
    'world': {'ru': 'мир', 'tg': 'дунё', 'lemma': 'world'},
    'is': BE, 'are': BE, 'isn\'t': BE,
},
75: {
    'grandfather': {'ru': 'дедушка', 'tg': 'бобо', 'lemma': 'grandfather'},
    'live': {'ru': 'жить', 'tg': 'зиндагӣ кардан', 'lemma': 'live'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'days': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'different': {'ru': 'разный', 'tg': 'гуногун', 'lemma': 'different'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'gets': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'get up'},
    'ten': {'ru': 'десять', 'tg': 'даҳ', 'lemma': 'ten'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'five': {'ru': 'пять', 'tg': 'панҷ', 'lemma': 'five'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'best': {'ru': 'лучший', 'tg': 'беҳтарин', 'lemma': 'best'},
    'part': {'ru': 'часть', 'tg': 'қисм', 'lemma': 'part'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'agrees': {'ru': 'соглашаться', 'tg': 'розӣ шудан', 'lemma': 'agree'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'six': {'ru': 'шесть', 'tg': 'шаш', 'lemma': 'six'},
    'works': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'reads': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'newspaper': {'ru': 'газета', 'tg': 'рӯзнома', 'lemma': 'newspaper'},
    'twice': {'ru': 'дважды', 'tg': 'ду бор', 'lemma': 'twice'},
    'studies': {'ru': 'учиться', 'tg': 'таҳсил кардан', 'lemma': 'study'},
    'online': {'ru': 'онлайн', 'tg': 'онлайн', 'lemma': 'online'},
    'chats': {'ru': 'болтать (переписываться)', 'tg': 'сӯҳбат кардан', 'lemma': 'chat'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'hardly': {'ru': 'едва (почти не)', 'tg': 'қариб', 'lemma': 'hardly'},
    'ever': {'ru': 'когда-либо', 'tg': 'ҳаргиз', 'lemma': 'ever'},
    'goes': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'before': {'ru': 'до (перед)', 'tg': 'пеш аз', 'lemma': 'before'},
    'midnight': {'ru': 'полночь', 'tg': 'нисфи шаб', 'lemma': 'midnight'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'eight': {'ru': 'восемь', 'tg': 'ҳашт', 'lemma': 'eight'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'special': {'ru': 'особенный', 'tg': 'махсус', 'lemma': 'special'},
    'happens': {'ru': 'случаться', 'tg': 'рӯй додан', 'lemma': 'happen'},
    'makes': {'ru': 'делать (готовить)', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'green': {'ru': 'зелёный', 'tg': 'сабз', 'lemma': 'green'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'brings': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'sweets': {'ru': 'сладости', 'tg': 'ширинӣ', 'lemma': 'sweets'},
    'sit': {'ru': 'сидеть', 'tg': 'нишастан', 'lemma': 'sit'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'veranda': {'ru': 'веранда', 'tg': 'айвон', 'lemma': 'veranda'},
    'talk': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'tells': {'ru': 'рассказывать', 'tg': 'нақл кардан', 'lemma': 'tell'},
    'past': {'ru': 'прошлое', 'tg': 'гузашта', 'lemma': 'past'},
    'shows': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'videos': {'ru': 'видео', 'tg': 'видео', 'lemma': 'video'},
    'future': {'ru': 'будущее', 'tg': 'оянда', 'lemma': 'future'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'team': {'ru': 'команда', 'tg': 'даста', 'lemma': 'team'},
    'favourite': {'ru': 'любимый', 'tg': 'дӯстдоштатарин', 'lemma': 'favourite'},
    'hour': {'ru': 'час', 'tg': 'соат', 'lemma': 'hour'},
    'miss': {'ru': 'пропускать', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'is': BE, 'are': BE,
},
76: {
    'class': {'ru': 'класс', 'tg': 'синф', 'lemma': 'class'},
    'needs': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'president': {'ru': 'президент', 'tg': 'президент', 'lemma': 'president'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'election': {'ru': 'выборы', 'tg': 'интихобот', 'lemma': 'election'},
    'three': {'ru': 'три', 'tg': 'се', 'lemma': 'three'},
    'students': {'ru': 'ученик', 'tg': 'хонанда', 'lemma': 'student'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'job': {'ru': 'должность (работа)', 'tg': 'вазифа', 'lemma': 'job'},
    'speaks': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'first': {'ru': 'первый (сначала)', 'tg': 'аввал', 'lemma': 'first'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
    'play': {'ru': 'играть', 'tg': 'бозидан', 'lemma': 'play'},
    'football': {'ru': 'футбол', 'tg': 'футбол', 'lemma': 'football'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'vote': {'ru': 'голосовать', 'tg': 'овоз додан', 'lemma': 'vote'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'nice': {'ru': 'приятно (хорошо)', 'tg': 'хуш', 'lemma': 'nice'},
    'how': {'ru': 'как', 'tg': 'чӣ тавр', 'lemma': 'how'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'stands': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'stand'},
    'sing': {'ru': 'петь', 'tg': 'суруд хондан', 'lemma': 'sing'},
    'dance': {'ru': 'танцевать', 'tg': 'рақс кардан', 'lemma': 'dance'},
    'parties': {'ru': 'вечеринка', 'tg': 'зиёфат', 'lemma': 'party'},
    'fantastic': {'ru': 'потрясающий', 'tg': 'аҷоиб', 'lemma': 'fantastic'},
    'some': {'ru': 'некоторые', 'tg': 'баъзе', 'lemma': 'some'},
    'clap': {'ru': 'хлопать', 'tg': 'чапак задан', 'lemma': 'clap'},
    'finally': {'ru': 'наконец', 'tg': 'ниҳоят', 'lemma': 'finally'},
    'goes': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'board': {'ru': 'доска', 'tg': 'тахта', 'lemma': 'board'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'listen': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'come': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'any': {'ru': 'любой', 'tg': 'ягон', 'lemma': 'any'},
    'problem': {'ru': 'проблема', 'tg': 'мушкилот', 'lemma': 'problem'},
    'talk': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'teachers': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'also': {'ru': 'также', 'tg': 'инчунин', 'lemma': 'also'},
    'make': {'ru': 'делать (составлять)', 'tg': 'тартиб додан', 'lemma': 'make'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'plans': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'notebook': {'ru': 'тетрадь', 'tg': 'дафтар', 'lemma': 'notebook'},
    'shows': {'ru': 'показывать', 'tg': 'нишон додан', 'lemma': 'show'},
    'plan': {'ru': 'план', 'tg': 'нақша', 'lemma': 'plan'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'may': {'ru': 'май', 'tg': 'май', 'lemma': 'May'},
    'groups': {'ru': 'группа', 'tg': 'гурӯҳ', 'lemma': 'group'},
    'exams': {'ru': 'экзамен', 'tg': 'имтиҳон', 'lemma': 'exam'},
    'film': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'month': {'ru': 'месяц', 'tg': 'моҳ', 'lemma': 'month'},
    'nobody': {'ru': 'никто', 'tg': 'ҳеҷ кас', 'lemma': 'nobody'},
    'everybody': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everybody'},
    'claps': {'ru': 'хлопать', 'tg': 'чапак задан', 'lemma': 'clap'},
    'most': {'ru': 'самый', 'tg': 'аз ҳама', 'lemma': 'most'},
    'important': {'ru': 'важный', 'tg': 'муҳим', 'lemma': 'important'},
    'skill': {'ru': 'навык', 'tg': 'малака', 'lemma': 'skill'},
    'is': BE, 'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'}, 'that\'s': BE,
},
77: {
    'eleven': {'ru': 'одиннадцать', 'tg': 'ёздаҳ', 'lemma': 'eleven'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'trying': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'sleep': {'ru': 'спать', 'tg': 'хоб рафтан', 'lemma': 'sleep'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'someone': {'ru': 'кто-то', 'tg': 'касе', 'lemma': 'someone'},
    'making': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'noise': {'ru': 'шум', 'tg': 'садо', 'lemma': 'noise'},
    'upstairs': {'ru': 'наверху', 'tg': 'дар болохона', 'lemma': 'upstairs'},
    'bang': {'ru': 'бах', 'tg': 'тарақ', 'lemma': 'bang'},
    'neighbour': {'ru': 'сосед', 'tg': 'ҳамсоя', 'lemma': 'neighbour'},
    'doing': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'goes': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'makes': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'make'},
    'listen': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'carefully': {'ru': 'внимательно', 'tg': 'бодиққат', 'lemma': 'carefully'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'moving': {'ru': 'двигать', 'tg': 'ҳаракат додан', 'lemma': 'move'},
    'furniture': {'ru': 'мебель', 'tg': 'мебел', 'lemma': 'furniture'},
    'walking': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'fast': {'ru': 'быстро', 'tg': 'тез', 'lemma': 'fast'},
    'something': {'ru': 'что-то', 'tg': 'чизе', 'lemma': 'something'},
    'falling': {'ru': 'падать', 'tg': 'афтодан', 'lemma': 'fall'},
    'can\'t': {'ru': 'не мочь', 'tg': 'натавонистан', 'lemma': 'can'},
    'like': {'ru': 'так (подобно)', 'tg': 'мисли', 'lemma': 'like'},
    'this': {'ru': 'это', 'tg': 'ин', 'lemma': 'this'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'knock': {'ru': 'стучать', 'tg': 'тақ-тақ кардан', 'lemma': 'knock'},
    'door': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'opens': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'slowly': {'ru': 'медленно', 'tg': 'оҳиста', 'lemma': 'slowly'},
    'standing': {'ru': 'стоять', 'tg': 'истодан', 'lemma': 'stand'},
    'there': {'ru': 'там', 'tg': 'он ҷо', 'lemma': 'there'},
    'sports': {'ru': 'спортивный', 'tg': 'варзишӣ', 'lemma': 'sports'},
    'clothes': {'ru': 'одежда', 'tg': 'либос', 'lemma': 'clothes'},
    'face': {'ru': 'лицо', 'tg': 'рӯй', 'lemma': 'face'},
    'red': {'ru': 'красный', 'tg': 'сурх', 'lemma': 'red'},
    'wet': {'ru': 'мокрый', 'tg': 'тар', 'lemma': 'wet'},
    'oh': {'ru': 'ох', 'tg': 'оҳ', 'lemma': 'oh'},
    'sorry': {'ru': 'извини(те)', 'tg': 'бубахшед', 'lemma': 'sorry'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'training': {'ru': 'тренироваться', 'tg': 'машқ кардан', 'lemma': 'train'},
    'look': {'ru': 'смотри(те)', 'tg': 'нигоҳ кунед', 'lemma': 'look'},
    'middle': {'ru': 'середина', 'tg': 'миён', 'lemma': 'middle'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'box': {'ru': 'коробка', 'tg': 'қуттӣ', 'lemma': 'box'},
    'picture': {'ru': 'картина', 'tg': 'расм', 'lemma': 'picture'},
    'sea': {'ru': 'море', 'tg': 'баҳр', 'lemma': 'sea'},
    'learning': {'ru': 'учиться', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'surf': {'ru': 'сёрфинг', 'tg': 'сёрфинг', 'lemma': 'surf'},
    'championship': {'ru': 'чемпионат', 'tg': 'чемпионат', 'lemma': 'championship'},
    'Turkey': {'ru': 'Турция', 'tg': 'Туркия', 'lemma': 'Turkey'},
    'june': {'ru': 'июнь', 'tg': 'июн', 'lemma': 'June'},
    'practising': {'ru': 'практиковать (тренировать)', 'tg': 'машқ кардан', 'lemma': 'practise'},
    'balance': {'ru': 'равновесие', 'tg': 'мувозинат', 'lemma': 'balance'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'surfboard': {'ru': 'доска для сёрфинга', 'tg': 'тахтаи сёрфинг', 'lemma': 'surfboard'},
    'living': {'ru': 'гостиная', 'tg': 'меҳмонхона', 'lemma': 'living room'},
    'thousand': {'ru': 'тысяча', 'tg': 'ҳазор', 'lemma': 'thousand'},
    'kilometres': {'ru': 'километр', 'tg': 'километр', 'lemma': 'kilometre'},
    'from': {'ru': 'от', 'tg': 'аз', 'lemma': 'from'},
    'hear': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'angry': {'ru': 'сердитый', 'tg': 'хашмгин', 'lemma': 'angry'},
    'just': {'ru': 'просто', 'tg': 'фақат', 'lemma': 'just'},
    'smile': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'think': {'ru': 'думать', 'tg': 'фикр кардан', 'lemma': 'think'},
    'riding': {'ru': 'ехать (кататься)', 'tg': 'савор шудан', 'lemma': 'ride'},
    'waves': {'ru': 'волна', 'tg': 'мавҷ', 'lemma': 'wave'},
    'dreams': {'ru': 'мечта (сон)', 'tg': 'орзу', 'lemma': 'dream'},
    'is': BE, 'am': BE,
},
}

for sid in (73,):
    d = DICTS[sid]
    d.pop('day2', None)
    d.pop('get2', None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
