import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from app.db.database import AsyncSessionLocal
from app.models.model_content import StoryQuestions

Q = {
    68: [
        ('Where is Zarina from?', 'Откуда Зарина?', 'Зарина аз куҷост?',
         ['Khujand', 'Dushanbe', 'Moscow'], 'Khujand',
         "Zarina says 'I'm from Khujand.'", 'Зарина говорит: «Я из Худжанда».', 'Зарина мегӯяд: «Ман аз Хуҷанд ҳастам».'),
        ('Where is Mr Adams from?', 'Откуда мистер Адамс?', 'Ҷаноби Адамс аз куҷост?',
         ['Manchester', 'London', 'Istanbul'], 'Manchester',
         'The teacher, Mr Adams, is from Manchester.', 'Учитель, мистер Адамс, из Манчестера.', 'Муаллим ҷаноби Адамс аз Манчестер аст.'),
        ('How many students are in the class?', 'Сколько студентов в классе?', 'Дар синф чанд донишҷӯ ҳаст?',
         ['Twelve', 'Ten', 'Fifteen'], 'Twelve',
         'The story says there are twelve students in the class.', 'В истории сказано, что в классе двенадцать студентов.', 'Дар ҳикоя гуфта мешавад, ки дар синф дувоздаҳ донишҷӯ ҳаст.'),
    ],
    69: [
        ('What bus number should Karim be on?', 'На каком автобусе должен ехать Карим?', 'Карим бояд бо кадом автобус равад?',
         ['Number 8', 'Number 18', 'Number 10'], 'Number 8',
         'Karim wanted the bus to the city centre, which was number 8.', 'Карим хотел автобус в центр города, это был номер 8.', 'Карим автобуси ба маркази шаҳрро мехост, ки рақами 8 буд.'),
        ('What bus is he actually on?', 'На каком автобусе он на самом деле едет?', 'Ӯ дар асл дар кадом автобус аст?',
         ['Number 18', 'Number 8', 'Number 10'], 'Number 18',
         'The woman tells him it is bus number 18.', 'Женщина говорит ему, что это автобус номер 18.', 'Зан ба ӯ мегӯяд, ки ин автобуси рақами 18 аст.'),
        ('How does Karim feel when he realizes his mistake?', 'Что чувствует Карим, поняв свою ошибку?', 'Карим пас аз фаҳмидани хатогиаш чӣ ҳис мекунад?',
         ['Embarrassed', 'Angry', 'Bored'], 'Embarrassed',
         "The story says 'Karim's face is red', showing embarrassment.", 'В истории сказано «лицо Карима покраснело», это смущение.', 'Дар ҳикоя гуфта мешавад «рӯи Карим сурх шуд», ки шармандагиро нишон медиҳад.'),
    ],
    70: [
        ('Which sister is tidy?', 'Какая из сестёр аккуратная?', 'Кадом хоҳар озода аст?',
         ['Madina', 'Shahlo', 'Both'], 'Madina',
         'Madina keeps her books, pens and clothes organized.', 'Мадина держит книги, ручки и одежду в порядке.', 'Мадина китобҳо, қалам ва либосҳояшро тартибдода нигоҳ медорад.'),
        ('What does the mother do to solve the problem?', 'Что делает мать, чтобы решить проблему?', 'Модар барои ҳалли мушкилот чӣ мекунад?',
         ['Divides the room into two zones', 'Buys a new room', 'Punishes Shahlo'], 'Divides the room into two zones',
         'The mother gives each sister her own side of the room.', 'Мать даёт каждой сестре свою половину комнаты.', 'Модар ба ҳар хоҳар қисми худро дар утоқ медиҳад.'),
        ('What does Shahlo ask about every morning?', 'О чём Шахло спрашивает каждое утро?', 'Шаҳло ҳар субҳ дар бораи чӣ мепурсад?',
         ['Her glasses', 'Her books', 'Her phone'], 'Her glasses',
         "Shahlo asks 'Where are my glasses?' every morning.", 'Шахло каждое утро спрашивает: «Где мои очки?»', 'Шаҳло ҳар субҳ мепурсад: «Айнакам дар куҷост?»'),
    ],
    71: [
        ('Who tells Aziz to slow down?', 'Кто говорит Азизу замедлиться?', 'Ба Азиз кӣ мегӯяд, ки суст равад?',
         ['Nilufar', 'His mother', 'His teacher'], 'Nilufar',
         "Nilufar says 'Aziz, slow down!'", 'Нилуфар говорит: «Азиз, помедленнее!»', 'Нилуфар мегӯяд: «Азиз, суст рав!»'),
        ('Where do the friends go?', 'Куда идут друзья?', 'Дӯстон ба куҷо мераванд?',
         ['To the mountains', 'To the river', 'To the market'], 'To the mountains',
         'The friends are on a trip to the mountains near their town.', 'Друзья отправились в горы недалеко от города.', 'Дӯстон ба сафари кӯҳҳои наздики шаҳрашон мераванд.'),
        ('How does Aziz feel after he stops?', 'Что чувствует Азиз после того, как остановился?', 'Азиз пас аз истодан чӣ ҳис мекунад?',
         ['Calm', 'Bored', 'Angry'], 'Calm',
         "Aziz says 'I feel calm.'", 'Азиз говорит: «Я чувствую спокойствие».', 'Азиз мегӯяд: «Ман ором ҳис мекунам».'),
    ],
    72: [
        ("What is Suhrob's job?", 'Кем работает Сухроб?', 'Сӯҳроб бо кадом касб кор мекунад?',
         ['A baker', 'A driver', 'A teacher'], 'A baker',
         "Suhrob says 'I'm a baker in a small bakery.'", 'Сухроб говорит: «Я пекарь в маленькой пекарне».', 'Сӯҳроб мегӯяд: «Ман дар нонвойхонаи хурд наввой ҳастам».'),
        ('What time does his work day start?', 'Во сколько начинается его рабочий день?', 'Рӯзи кории ӯ соати чанд сар мешавад?',
         ['Eleven in the evening', 'Six in the morning', 'Seven in the evening'], 'Eleven in the evening',
         'His work day starts at eleven in the evening.', 'Его рабочий день начинается в одиннадцать вечера.', 'Рӯзи кории ӯ соати понздаҳи шаб сар мешавад.'),
        ('What is his favourite thing to bake?', 'Что он больше всего любит печь?', 'Ӯ пухтани чиро бештар дӯст медорад?',
         ['Apple pies', 'Sweet rolls', 'Plain bread'], 'Apple pies',
         'He says apple pies are his favourite.', 'Он говорит, что яблочные пироги — его любимое.', 'Ӯ мегӯяд, ки пирогҳои себ дилхоҳи ӯ ҳастанд.'),
    ],
    73: [
        ('What does Mrs Rahimova do every day?', 'Что миссис Рахимова делает каждый день?', 'Хонум Раҳимова ҳар рӯз чӣ мекунад?',
         ['Sits by her window and watches the street', 'Cooks for the neighbours', 'Goes shopping'], 'Sits by her window and watches the street',
         'She sits by her window and watches everything on the street.', 'Она сидит у окна и наблюдает за всем на улице.', 'Вай назди тиреза нишаста ба кӯча нигоҳ мекунад.'),
        ('What does she do when someone is ill?', 'Что она делает, когда кто-то болеет?', 'Вай ҳангоми беморшавии касе чӣ мекунад?',
         ['Calls the doctor', 'Ignores it', 'Tells everyone'], 'Calls the doctor',
         'She calls the doctor when old Mr Karimov falls.', 'Она вызывает врача, когда старый мистер Каримов падает.', 'Вай ҳангоми афтидани ҷаноби Каримов духтурро даъват мекунад.'),
        ('Why does the narrator now understand her?', 'Почему рассказчик теперь понимает её?', 'Чаро ровӣ ҳоло вайро мефаҳмад?',
         ["She isn't curious, she's the guard of the street", 'She is bored', 'She likes gossip'], "She isn't curious, she's the guard of the street",
         'The narrator realizes she takes care of the street, she does not just watch.', 'Рассказчик понимает, что она заботится об улице, а не просто наблюдает.', 'Ровӣ мефаҳмад, ки вай ба кӯча ғамхорӣ мекунад, на танҳо тамошо.'),
    ],
    74: [
        ('What is grandmother showing the family?', 'Что бабушка показывает семье?', 'Бибӣ ба оила чӣ нишон медиҳад?',
         ['An old photo album', 'A letter', 'A video'], 'An old photo album',
         'Grandmother opens an old photo album.', 'Бабушка открывает старый фотоальбом.', 'Бибӣ албоми кӯҳнаи аксҳоро мекушояд.'),
        ("When was the uncle's wedding?", 'Когда была свадьба дяди?', 'Тӯи тағо кай буд?',
         ['1995', '1985', '2005'], '1995',
         "Grandmother says 'It's your uncle's wedding, in 1995.'", 'Бабушка говорит: «Это свадьба твоего дяди, в 1995 году».', 'Бибӣ мегӯяд: «Ин тӯи тағоят, дар соли 1995».'),
        ('What does grandmother cook on Fridays?', 'Что бабушка готовит по пятницам?', 'Бибӣ рӯзҳои ҷумъа чӣ мепазад?',
         ['Plov', 'Osh', 'Soup'], 'Plov',
         "She says 'I make plov on Fridays.'", 'Она говорит: «По пятницам я готовлю плов».', 'Вай мегӯяд: «Рӯзҳои ҷумъа ман палав мепазам».'),
    ],
    75: [
        ('What time does grandfather get up?', 'Во сколько встаёт дедушка?', 'Бобо соати чанд бармехезад?',
         ['Five', 'Six', 'Ten'], 'Five',
         'Grandfather always gets up at five.', 'Дедушка всегда встаёт в пять.', 'Бобо ҳамеша соати панҷ бармехезад.'),
        ('What time does Dilnoza get up?', 'Во сколько встаёт Дильноза?', 'Дилноза соати чанд бармехезад?',
         ['Ten', 'Five', 'Six'], 'Ten',
         'Dilnoza usually gets up at ten.', 'Дильноза обычно встаёт в десять.', 'Дилноза одатан соати даҳ бармехезад.'),
        ('What do they do together every evening at eight?', 'Что они делают вместе каждый вечер в восемь?', 'Онҳо ҳар бегоҳ соати ҳашт якҷоя чӣ мекунанд?',
         ['Have tea and talk on the veranda', 'Watch TV', 'Go for a walk'], 'Have tea and talk on the veranda',
         'They sit on the veranda, drink green tea and talk about their days.', 'Они сидят на веранде, пьют зелёный чай и разговаривают о своём дне.', 'Онҳо дар айвон нишаста чойи сабз менӯшанд ва дар бораи рӯзашон гап мезананд.'),
    ],
    76: [
        ('Who wins the class president election?', 'Кто выигрывает выборы старосты класса?', 'Дар интихоботи раиси синф кӣ ғолиб мешавад?',
         ['Farida', 'Rustam', 'Malika'], 'Farida',
         'Farida wins because she has real plans to help the class.', 'Фарида побеждает, потому что у неё есть реальные планы помочь классу.', 'Фарида ғолиб мешавад, зеро ӯ нақшаҳои воқеӣ барои кӯмак ба синф дорад.'),
        ('What skill does Farida say is important?', 'Какой навык, по словам Фариды, важен?', 'Фарида мегӯяд, ки кадом малака муҳим аст?',
         ['Listening', 'Singing', 'Playing football'], 'Listening',
         'Farida says she can listen and think, which helps the class.', 'Фарида говорит, что умеет слушать и думать, это помогает классу.', 'Фарида мегӯяд, ки ӯ гӯш кардан ва фикр карданро медонад, ки ба синф кӯмак мекунад.'),
        ('What does Rustam say he is good at?', 'В чём, по словам Рустама, он хорош?', 'Рустам мегӯяд, ки дар кадом кор моҳир аст?',
         ['Playing football', 'Singing', 'Planning'], 'Playing football',
         'Rustam says he can play football very well.', 'Рустам говорит, что очень хорошо играет в футбол.', 'Рустам мегӯяд, ки футболро хеле хуб бозӣ мекунад.'),
    ],
    77: [
        ('What is the neighbour practising?', 'Что тренирует сосед?', 'Ҳамсоя чиро машқ мекунад?',
         ['Surfing', 'Boxing', 'Dancing'], 'Surfing',
         "The neighbour says 'I'm learning to surf!'", 'Сосед говорит: «Я учусь сёрфингу!»', 'Ҳамсоя мегӯяд: «Ман сёрфингро меомӯзам!»'),
        ('Where is the championship?', 'Где проходит чемпионат?', 'Мусобиқа дар куҷо мегузарад?',
         ['Turkey', 'Spain', 'Tajikistan'], 'Turkey',
         'The surfing championship is in Turkey.', 'Чемпионат по сёрфингу проходит в Турции.', 'Мусобиқаи сёрфинг дар Туркия мегузарад.'),
        ('When is the championship?', 'Когда чемпионат?', 'Мусобиқа кай аст?',
         ['June', 'August', 'December'], 'June',
         'The championship is in June.', 'Чемпионат состоится в июне.', 'Мусобиқа дар моҳи июн аст.'),
    ],
    78: [
        ('What does Layla like doing?', 'Что любит делать Лейла?', 'Лайло чӣ карданро дӯст медорад?',
         ['Taking photos', 'Painting', 'Cooking'], 'Taking photos',
         'Layla likes taking photos everywhere.', 'Лейла любит фотографировать везде.', 'Лайло аз ҳама ҷо акс гирифтанро дӯст медорад.'),
        ('What does the old man sell?', 'Что продаёт старик?', 'Пирамард чиро мефурӯшад?',
         ['Carpets', 'Fruit', 'Books'], 'Carpets',
         'The old man sells colourful carpets at the market.', 'Старик продаёт на рынке разноцветные ковры.', 'Пирамард дар бозор гилемҳои рангоранг мефурӯшад.'),
        ("Where does the old man's granddaughter live?", 'Где живёт внучка старика?', 'Набераи пирамард дар куҷо зиндагӣ мекунад?',
         ['Canada', 'Russia', 'Turkey'], 'Canada',
         'His granddaughter is in Canada and misses the market.', 'Его внучка живёт в Канаде и скучает по рынку.', 'Набераи ӯ дар Канада зиндагӣ мекунаду бозорро пазмон мешавад.'),
    ],
    79: [
        ("Whose birthday is it actually?", 'Чей на самом деле день рождения?', 'Дар асл рӯзи таваллуди кист?',
         ["The father's", "The mother's", "The brother's"], "The father's",
         "The mother says 'Today is your father's birthday.'", 'Мать говорит: «Сегодня день рождения твоего отца».', 'Модар мегӯяд: «Имрӯз рӯзи таваллуди падаратон аст».'),
        ("When is the mother's birthday?", 'Когда день рождения матери?', 'Рӯзи таваллуди модар кай аст?',
         ['The twenty-first of June', 'The twelfth of June', 'The first of June'], 'The twenty-first of June',
         "She says 'my birthday is on the twenty-first of June.'", 'Она говорит: «мой день рождения 21 июня».', 'Вай мегӯяд: «рӯзи таваллуди ман 21-уми июн аст».'),
        ('How many cakes do the brothers bring?', 'Сколько тортов приносят братья?', 'Бародарон чанд торт меоранд?',
         ['Three', 'One', 'Two'], 'Three',
         'Each brother brings a cake, so there are three cakes.', 'Каждый брат приносит торт, поэтому тортов три.', 'Ҳар бародар торт меорад, аз ин рӯ се торт мешавад.'),
    ],
    80: [
        ('What year was the photo from?', 'Какого года это фото?', 'Ин акс аз кадом сол аст?',
         ['1985', '1979', '1995'], '1985',
         'The year on the back of the photo is 1985.', 'Год на обратной стороне фото — 1985.', 'Соли дар паси акс навишташуда 1985 аст.'),
        ("What was the other man's name?", 'Как звали второго мужчину?', 'Номи марди дигар чист буд?',
         ['Anvar', 'Rustam', 'Karim'], 'Anvar',
         'The neighbour identifies him as Anvar.', 'Соседка узнаёт его — это Анвар.', 'Ҳамсоя ӯро мешиносад — ин Анвар аст.'),
        ("Where was Anvar's family from?", 'Откуда была семья Анвара?', 'Оилаи Анвар аз куҷо буд?',
         ['Khorog', 'Khujand', 'Dushanbe'], 'Khorog',
         "Anvar's family was from Khorog.", 'Семья Анвара была из Хорога.', 'Оилаи Анвар аз Хоруғ буд.'),
    ],
    81: [
        ('What mistake does Behruz make?', 'Какую ошибку делает Бехруз?', 'Беҳрӯз кадом хатогиро содир мекунад?',
         ['He goes to the wrong wedding hall', 'He forgets the present', 'He arrives late'], 'He goes to the wrong wedding hall',
         'Behruz celebrates at the wrong wedding, in the wrong hall.', 'Бехруз празднует не ту свадьбу, в другом зале.', 'Беҳрӯз тӯи дигарро дар толори дигар ҷашн мегирад.'),
        ('How many halls does the restaurant have?', 'Сколько залов в ресторане?', 'Тарабхона чанд толор дорад?',
         ['Two', 'Three', 'One'], 'Two',
         'The restaurant Gulistan has two halls.', 'В ресторане Гулистон два зала.', 'Тарабхонаи Гулистон ду толор дорад.'),
        ('What does Behruz do when he realizes the mistake?', 'Что делает Бехруз, поняв ошибку?', 'Беҳрӯз пас аз фаҳмидани хатогӣ чӣ мекунад?',
         ['Moves to the right hall', 'Leaves immediately', 'Calls Firdavs'], 'Moves to the right hall',
         'He laughs, apologizes and moves to the correct hall.', 'Он смеётся, извиняется и переходит в нужный зал.', 'Ӯ механдад, узр мехоҳаду ба толори дуруст мегузарад.'),
    ],
    82: [
        ('Who ate the cake?', 'Кто съел торт?', 'Тортро кӣ хӯрд?',
         ['The cat, Barsik', 'The sister', 'The father'], 'The cat, Barsik',
         'The cat Barsik ate the cream from the cake.', 'Кот Барсик съел крем с торта.', 'Гурба Барсик кремии тортро хӯрд.'),
        ("What is on the cat's nose?", 'Что на носу у кота?', 'Дар бинии гурба чист?',
         ['Chocolate cream', 'Flour', 'Sugar'], 'Chocolate cream',
         "There is chocolate cream on Barsik's white nose.", 'На белом носу Барсика шоколадный крем.', 'Дар бинии сафеди Барсик кремии шоколадӣ ҳаст.'),
        ('Is chocolate dangerous for cats?', 'Опасен ли шоколад для кошек?', 'Оё шоколад барои гурбаҳо хатарнок аст?',
         ['Yes', 'No', 'Only dark chocolate'], 'Yes',
         "The narrator says 'Cats can't eat chocolate — it's dangerous!'", 'Рассказчик говорит: «Кошкам нельзя есть шоколад — это опасно!»', 'Ровӣ мегӯяд: «Гурбаҳо шоколад хӯрда наметавонанд — ин хатарнок аст!»'),
    ],
    83: [
        ('What do children say is in the house?', 'Что, по словам детей, есть в доме?', 'Кӯдакон мегӯянд, ки дар хона чӣ ҳаст?',
         ['Ghosts', 'Treasure', 'A museum'], 'Ghosts',
         'Children tell scary stories that there are ghosts in the house.', 'Дети рассказывают страшные истории, что в доме живут призраки.', 'Кӯдакон қиссаҳои даҳшатнок нақл мекунанд, ки дар хона арвоҳ ҳастанд.'),
        ('What was the house actually used for?', 'Для чего на самом деле использовался дом?', 'Хона дар асл барои чӣ истифода мешуд?',
         ['A free hospital for poor children', 'A school', 'A prison'], 'A free hospital for poor children',
         'The man in the house ran a free hospital for poor children.', 'Мужчина в доме содержал бесплатную больницу для бедных детей.', 'Марди дар хона беморхонаи ройгон барои кӯдакони камбизоат дошт.'),
        ('What does the town plan to make in the house?', 'Что город планирует сделать из дома?', 'Шаҳр аз хона чӣ сохтан мехоҳад?',
         ['A museum', 'A hospital', 'A school'], 'A museum',
         'The town plans to turn the house into a museum.', 'Город планирует превратить дом в музей.', 'Шаҳр мехоҳад хонаро ба осорхона табдил диҳад.'),
    ],
    84: [
        ('How many kilos of rice do they need?', 'Сколько килограммов риса им нужно?', 'Ба онҳо чанд килограмм биринҷ лозим аст?',
         ['Three', 'Two', 'Five'], 'Three',
         "The uncle says 'Three kilos.'", 'Дядя говорит: «Три килограмма».', 'Тағо мегӯяд: «Се килограмм».'),
        ('What does the uncle add to the pot first?', 'Что дядя кладёт в казан первым?', 'Тағо аввал ба дег чӣ мепартояд?',
         ['Oil', 'Rice', 'Water'], 'Oil',
         'The uncle starts with oil, then meat, onions and carrots.', 'Дядя начинает с масла, затем мясо, лук и морковь.', 'Тағо аз равған сар мекунад, баъд гӯшт, пиёз ва сабзӣ.'),
        ('How much osh is left after lunch?', 'Сколько плова остаётся после обеда?', 'Пас аз хӯроки нисфирӯзӣ чӣ қадар ош мемонад?',
         ['Only a little, for breakfast', 'A lot', 'None'], 'Only a little, for breakfast',
         "The uncle says 'Not much. Only a little — for breakfast!'", 'Дядя говорит: «Немного. Совсем чуть-чуть — на завтрак!»', 'Тағо мегӯяд: «Кам. Танҳо каме — барои наҳорӣ!»'),
    ],
    85: [
        ('Who wins the melon championship?', 'Кто побеждает в конкурсе дынь?', 'Дар мусобиқаи харбуза кӣ ғолиб мешавад?',
         ['Grandmother Zulfiya', 'The father', 'Rustam'], 'Grandmother Zulfiya',
         "Grandmother Zulfiya's melon wins first prize.", 'Дыня бабушки Зульфии выигрывает первый приз.', 'Харбузаи биби Зулфия ҷои якумро мегирад.'),
        ('What does the judge say is more important than size?', 'Что судья считает важнее размера?', 'Довар мегӯяд, ки аз андоза чӣ муҳимтар аст?',
         ['Taste', 'Colour', 'Weight'], 'Taste',
         "The judge says 'taste is more important' than size.", 'Судья говорит: «вкус важнее» размера.', 'Довар мегӯяд, ки «маза муҳимтар аст» аз андоза.'),
        ('Who comes second?', 'Кто занимает второе место?', 'Ҷои дуюмро кӣ мегирад?',
         ["The narrator's father", 'Rustam', 'The neighbour'], "The narrator's father",
         'The father takes second prize.', 'Отец получает второй приз.', 'Падар ҷои дуюмро мегирад.'),
    ],
    86: [
        ("What is Daler's job?", 'Кем работает Далер?', 'Далер бо кадом касб кор мекунад?',
         ['A driver', 'A doctor', 'A teacher'], 'A driver',
         'Daler is a driver on the Pamir Highway.', 'Далер — водитель на Памирском тракте.', 'Далер дар шоҳроҳи Помир ронанда аст.'),
        ('What road does he drive?', 'По какой дороге он ездит?', 'Ӯ бо кадом роҳ ронандагӣ мекунад?',
         ['The Pamir Highway', 'The Silk Road', 'The coastal road'], 'The Pamir Highway',
         'His route is one of the highest roads in the world, the Pamir Highway.', 'Его маршрут — одна из самых высоких дорог в мире, Памирский тракт.', 'Роҳи ӯ яке аз баландтарин роҳҳои ҷаҳон, шоҳроҳи Помир аст.'),
        ('What does Daler say helps with the thin air?', 'Что, по словам Далера, помогает от разреженного воздуха?', 'Далер мегӯяд, ки барои ҳавои тунук чӣ кӯмак мекунад?',
         ['Drinking more water', 'Sleeping more', 'Eating more'], 'Drinking more water',
         "Daler says 'Drink more water. It's the best medicine here.'", 'Далер говорит: «Пей больше воды. Это лучшее лекарство здесь».', 'Далер мегӯяд: «Оби бештар нӯш. Ин беҳтарин дору дар ин ҷост».'),
    ],
    87: [
        ('What does Nigora want to study?', 'Что хочет изучать Нигора?', 'Нигора чиро омӯхтан мехоҳад?',
         ['Medicine', 'Music', 'Computer science'], 'Medicine',
         "Nigora says 'I'm going to study medicine in Dushanbe.'", 'Нигора говорит: «Я собираюсь изучать медицину в Душанбе».', 'Нигора мегӯяд: «Ман дар Душанбе тибро меомӯзам».'),
        ('What does Aziz want to become?', 'Кем хочет стать Азиз?', 'Азиз кӣ шудан мехоҳад?',
         ['A chef', 'A doctor', 'A driver'], 'A chef',
         "Aziz says 'I'm going to be a chef.'", 'Азиз говорит: «Я собираюсь стать поваром».', 'Азиз мегӯяд: «Ман ошпаз мешавам».'),
        ('What does Jamshed want to open?', 'Что хочет открыть Джамшед?', 'Ҷамшед чиро кушодан мехоҳад?',
         ['A computer club', 'A restaurant', 'A shop'], 'A computer club',
         "Jamshed says 'I'm going to open a small computer club.'", 'Джамшед говорит: «Я собираюсь открыть маленький компьютерный клуб».', 'Ҷамшед мегӯяд: «Ман клуби хурди компютериро мекушоям».'),
    ],
    88: [
        ("What is the driving teacher's name?", 'Как зовут инструктора по вождению?', 'Номи муаллими рондан чист?',
         ['Mr Nazarov', 'Mr Adams', 'Mr Aliyev'], 'Mr Nazarov',
         'The driving teacher is Mr Nazarov.', 'Инструктор по вождению — мистер Назаров.', 'Муаллими рондан ҷаноби Назаров аст.'),
        ("What is the narrator's biggest problem?", 'Какая самая большая проблема у рассказчика?', 'Мушкилоти калонтарини ровӣ чист?',
         ['Parking', 'Starting the car', 'Turning'], 'Parking',
         "The narrator says 'Parking was my enemy.'", 'Рассказчик говорит: «Парковка была моим врагом».', 'Ровӣ мегӯяд: «Парк кардан душмани ман буд».'),
        ('Does the narrator pass the exam?', 'Сдаёт ли рассказчик экзамен?', 'Оё ровӣ имтиҳонро месупорад?',
         ['Yes', 'No', "It doesn't say"], 'Yes',
         "The inspector says 'Congratulations' after the parking.", 'Инспектор говорит «Поздравляю» после парковки.', 'Мушрифи имтиҳон пас аз парк кардан мегӯяд «Табрик мекунам».'),
    ],
    89: [
        ('What does the family buy instead of things?', 'Что семья покупает вместо вещей?', 'Оила ба ҷои чизҳо чӣ мехарад?',
         ['Tickets to the mountains', 'A new phone', 'Clothes'], 'Tickets to the mountains',
         'They buy four tickets to the mountains for the whole family.', 'Они покупают четыре билета в горы для всей семьи.', 'Онҳо барои тамоми оила чор чипта ба кӯҳҳо мехаранд.'),
        ('Where do they stay?', 'Где они останавливаются?', 'Онҳо дар куҷо мемонанд?',
         ['A guest house near a lake', 'A hotel in the city', "The aunt's house"], 'A guest house near a lake',
         'They stay in a small guest house near a lake.', 'Они останавливаются в маленьком гостевом доме у озера.', 'Онҳо дар меҳмонхонаи хурди наздики кӯл мемонанд.'),
        ('What does the mother say lasts forever?', 'Что, по словам матери, остаётся навсегда?', 'Модар мегӯяд, ки чӣ то абад мемонад?',
         ['Memories', 'Phones', 'Clothes'], 'Memories',
         "The mother's idea: 'things get old, memories don't.'", 'Мысль матери: «вещи стареют, воспоминания — нет».', 'Фикри модар: «чизҳо кӯҳна мешаванд, хотираҳо не».'),
    ],
    90: [
        ('Has Sino really seen the classic film?', 'Сино правда смотрел этот классический фильм?', 'Оё Сино дар ҳақиқат ин филми классикиро дидааст?',
         ['No, only the poster', 'Yes, ten times', 'Yes, once'], 'No, only the poster',
         "Sino admits 'I've... seen the poster. Many times.'", 'Сино признаётся: «Я видел... постер. Много раз».', 'Сино эътироф мекунад: «Ман... плакатро дидаам. Бисёр вақт».'),
        ('What language is the film in?', 'На каком языке этот фильм?', 'Филм ба кадом забон аст?',
         ['French', 'English', 'Russian'], 'French',
         'The film turns out to be in French.', 'Оказывается, фильм на французском языке.', 'Маълум мешавад, ки филм ба забони фаронсавӣ аст.'),
        ("What is Sino's new rule?", 'Какое новое правило у Сино?', 'Қоидаи нави Сино чист?',
         ["Never say you've seen a film before you've watched it", 'Always watch films twice', 'Only watch comedies'], "Never say you've seen a film before you've watched it",
         'Sino learns not to claim he has seen a film he has not actually watched.', 'Сино учится не утверждать, что видел фильм, который на самом деле не смотрел.', 'Сино меомӯзад, ки филмеро, ки надидааст, дидаам нагӯяд.'),
    ],
    91: [
        ('How many countries has grandfather visited?', 'Сколько стран посетил дедушка?', 'Бобо чанд кишварро дидааст?',
         ['Eleven', 'Ten', 'Twelve'], 'Eleven',
         "Grandfather says 'I've been to eleven countries.'", 'Дедушка говорит: «Я побывал в одиннадцати странах».', 'Бобо мегӯяд: «Ман дар ёздаҳ кишвар будаам».'),
        ('When did he first go to India?', 'Когда он впервые поехал в Индию?', 'Ӯ бори аввал кай ба Ҳиндустон рафт?',
         ['1979', '1985', '1995'], '1979',
         "Grandfather says 'I went there in 1979.'", 'Дедушка говорит: «Я поехал туда в 1979 году».', 'Бобо мегӯяд: «Ман соли 1979 ба он ҷо рафтам».'),
        ('Which country does he love the most?', 'Какую страну он любит больше всего?', 'Ӯ кадом кишварро бештар дӯст медорад?',
         ['Tajikistan', 'India', 'China'], 'Tajikistan',
         'Grandfather points to Tajikistan on the map, meaning home.', 'Дедушка указывает на Таджикистан на карте, имея в виду дом.', 'Бобо ба харита ба Тоҷикистон ишора мекунад, яъне хона.'),
    ],
}


async def main():
    async with AsyncSessionLocal() as db:
        created = 0
        for story_id, questions in Q.items():
            for text_en, text_ru, text_tg, options, answer, expl_en, expl_ru, expl_tg in questions:
                db.add(StoryQuestions(
                    story_id=story_id,
                    text_en=text_en,
                    text_ru=text_ru,
                    text_tg=text_tg,
                    options=options,
                    answer=answer,
                    explanation_en=expl_en,
                    explanation_ru=expl_ru,
                    explanation_tg=expl_tg,
                ))
                created += 1
        await db.commit()
        print(f'created {created} story questions for {len(Q)} stories')


asyncio.run(main())
