import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}
DO = {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'}

DICTS = {
54: {
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'park': {'ru': 'парковать (тж. парк)', 'tg': 'парк кардан', 'lemma': 'park'},
    'near': {'ru': 'рядом (близко)', 'tg': 'наздик', 'lemma': 'near'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'cars': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'lamp': {'ru': 'лампа', 'tg': 'чароғ', 'lemma': 'lamp'},
    'remote': {'ru': 'пульт (дистанционный)', 'tg': 'пулти дурдаст', 'lemma': 'remote control'},
    'control': {'ru': 'управление', 'tg': 'идоракунӣ', 'lemma': 'control'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'look': {'ru': 'искать (тж. смотреть)', 'tg': 'ҷустуҷӯ кардан', 'lemma': 'look'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'under': {'ru': 'под', 'tg': 'дар зери', 'lemma': 'under'},
    'pillow': {'ru': 'подушка', 'tg': 'болишт', 'lemma': 'pillow'},
    'nothing': {'ru': 'ничего', 'tg': 'ҳеҷ чиз', 'lemma': 'nothing'},
    'key': {'ru': 'ключ', 'tg': 'калид', 'lemma': 'key'},
    'reception': {'ru': 'ресепшн', 'tg': 'қабулгоҳ', 'lemma': 'reception'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    'receptionist': {'ru': 'администратор', 'tg': 'қабулкунанда', 'lemma': 'receptionist'},
    'any': {'ru': 'какой-либо', 'tg': 'ягон', 'lemma': 'any'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'that\'s': {'ru': 'это', 'tg': 'ин', 'lemma': 'that'},
    'strange': {'ru': 'странный', 'tg': 'аҷиб', 'lemma': 'strange'},
    'guest': {'ru': 'гость', 'tg': 'меҳмон', 'lemma': 'guest'},
    'before': {'ru': 'до (перед)', 'tg': 'пеш аз', 'lemma': 'before'},
    'from': {'ru': 'из', 'tg': 'аз', 'lemma': 'from'},
    'Germany': {'ru': 'Германия', 'tg': 'Олмон', 'lemma': 'Germany'},
    'call': {'ru': 'звонить (тж. звать)', 'tg': 'занг задан', 'lemma': 'call'},
    'comes': {'ru': 'приходить', 'tg': 'омадан', 'lemma': 'come'},
    'gets': {'ru': 'получать (брать)', 'tg': 'гирифтан', 'lemma': 'get'},
    'thank': {'ru': 'благодарить', 'tg': 'ташаккур гуфтан', 'lemma': 'thank'},
    'is': BE, 'are': BE, 'were': BE, 'was': BE, 'will': {'ru': 'буду (вспом. буд. вр.)', 'tg': 'хоҳам', 'lemma': 'will'},
},
55: {
    'arrive': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'ask': {'ru': 'спрашивать', 'tg': 'пурсидан', 'lemma': 'ask'},
    'room': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'tonight': {'ru': 'сегодня вечером', 'tg': 'имшаб', 'lemma': 'tonight'},
    'receptionist': {'ru': 'администратор', 'tg': 'қабулкунанда', 'lemma': 'receptionist'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'ground': {'ru': 'первый (наземный) этаж', 'tg': 'ошёнаи якум', 'lemma': 'ground floor'},
    'floor': {'ru': 'этаж', 'tg': 'ошёна', 'lemma': 'floor'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'fifth': {'ru': 'пятый', 'tg': 'панҷум', 'lemma': 'fifth'},
    'lift': {'ru': 'лифт', 'tg': 'лифт', 'lemma': 'lift'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'stairs': {'ru': 'лестница', 'tg': 'зинапоя', 'lemma': 'stairs'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'up': {'ru': 'вверх', 'tg': 'боло', 'lemma': 'up'},
    'open': {'ru': 'открывать', 'tg': 'кушодан', 'lemma': 'open'},
    'door': {'ru': 'дверь', 'tg': 'дар', 'lemma': 'door'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'pillow': {'ru': 'подушка', 'tg': 'болишт', 'lemma': 'pillow'},
    'lamp': {'ru': 'лампа', 'tg': 'чароғ', 'lemma': 'lamp'},
    'light': {'ru': 'свет (лампочка)', 'tg': 'равшанӣ', 'lemma': 'light bulb'},
    'bulb': {'ru': 'лампочка', 'tg': 'лампа', 'lemma': 'bulb'},
    'remote': {'ru': 'пульт', 'tg': 'пулти дурдаст', 'lemma': 'remote control'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'reception': {'ru': 'ресепшн', 'tg': 'қабулгоҳ', 'lemma': 'reception'},
    'any': {'ru': 'какой-либо', 'tg': 'ягон', 'lemma': 'any'},
    'towels': {'ru': 'полотенце', 'tg': 'сачоқ', 'lemma': 'towel'},
    'bath': {'ru': 'ванна', 'tg': 'ваннаи оббозӣ', 'lemma': 'bath'},
    'sorry': {'ru': 'извини(те)', 'tg': 'бубахшед', 'lemma': 'sorry'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'busy': {'ru': 'занятый', 'tg': 'серкор', 'lemma': 'busy'},
    'where': {'ru': 'где', 'tg': 'куҷо', 'lemma': 'where'},
    'phone': {'ru': 'телефон', 'tg': 'телефон', 'lemma': 'phone'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'is': BE, 'isn\'t': BE, 'are': BE, 'aren\'t': BE, 'were': BE, 'was': BE, 'it': {'ru': 'это', 'tg': 'он', 'lemma': 'it'},
},
56: {
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'sea': {'ru': 'море', 'tg': 'баҳр', 'lemma': 'sea'},
    'many': {'ru': 'многие', 'tg': 'бисёр', 'lemma': 'many'},
    'rooms': {'ru': 'комната', 'tg': 'ҳуҷра', 'lemma': 'room'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'staying': {'ru': 'останавливаться (проживать)', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'lamp': {'ru': 'лампа', 'tg': 'чароғ', 'lemma': 'lamp'},
    'remote': {'ru': 'пульт', 'tg': 'пулти дурдаст', 'lemma': 'remote control'},
    'bathroom': {'ru': 'ванная', 'tg': 'ҳаммомхона', 'lemma': 'bathroom'},
    'bath': {'ru': 'ванна', 'tg': 'ваннаи оббозӣ', 'lemma': 'bath'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'towels': {'ru': 'полотенце', 'tg': 'сачоқ', 'lemma': 'towel'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'bar': {'ru': 'бар', 'tg': 'бар', 'lemma': 'bar'},
    'swimming': {'ru': 'плавательный', 'tg': 'шиноварӣ', 'lemma': 'swimming'},
    'pool': {'ru': 'бассейн', 'tg': 'ҳавз', 'lemma': 'pool'},
    'gym': {'ru': 'спортзал', 'tg': 'толори варзишӣ', 'lemma': 'gym'},
    'spa': {'ru': 'спа', 'tg': 'спа', 'lemma': 'spa'},
    'gift': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'gift'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'park': {'ru': 'парковка', 'tg': 'истгоҳи мошин', 'lemma': 'car park'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'beach': {'ru': 'пляж', 'tg': 'соҳил', 'lemma': 'beach'},
    'sun': {'ru': 'солнце', 'tg': 'офтоб', 'lemma': 'sun'},
    'swimming2': {'ru': 'плавать', 'tg': 'шино кардан', 'lemma': 'swim'},
    'not': {'ru': 'не', 'tg': 'на', 'lemma': 'not'},
    'working': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'relaxing': {'ru': 'отдыхать', 'tg': 'истироҳат кардан', 'lemma': 'relax'},
    'reading': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'watching': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'enjoying': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'perfect': {'ru': 'идеальный', 'tg': 'комил', 'lemma': 'perfect'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'stay': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'here': {'ru': 'здесь', 'tg': 'ин ҷо', 'lemma': 'here'},
    'forever': {'ru': 'навсегда', 'tg': 'то абад', 'lemma': 'forever'},
    'am': BE, 'is': BE, 'was': BE,
},
57: {
    'last': {'ru': 'прошлый (последний)', 'tg': 'гузашта', 'lemma': 'last'},
    'year': {'ru': 'год', 'tg': 'сол', 'lemma': 'year'},
    'holiday': {'ru': 'отпуск', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'Scotland': {'ru': 'Шотландия', 'tg': 'Шотландия', 'lemma': 'Scotland'},
    'stayed': {'ru': 'останавливаться (проживать)', 'tg': 'истиқомат кардан', 'lemma': 'stay'},
    'hotel': {'ru': 'гостиница', 'tg': 'меҳмонхона', 'lemma': 'hotel'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'view': {'ru': 'вид', 'tg': 'манзара', 'lemma': 'view'},
    'lake': {'ru': 'озеро', 'tg': 'кӯл', 'lemma': 'lake'},
    'mountains': {'ru': 'гора', 'tg': 'кӯҳ', 'lemma': 'mountain'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'bar': {'ru': 'бар', 'tg': 'бар', 'lemma': 'bar'},
    'garden': {'ru': 'сад', 'tg': 'боғ', 'lemma': 'garden'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'walks': {'ru': 'прогулка', 'tg': 'сайр', 'lemma': 'walk'},
    'took': {'ru': 'брать (снимать)', 'tg': 'гирифтан', 'lemma': 'take'},
    'photos': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'together': {'ru': 'вместе', 'tg': 'якҷоя', 'lemma': 'together'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'this': {'ru': 'этот', 'tg': 'ин', 'lemma': 'this'},
    'same': {'ru': 'тот же', 'tg': 'ҳамон', 'lemma': 'same'},
    'still': {'ru': 'всё ещё', 'tg': 'ҳанӯз', 'lemma': 'still'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'paintings': {'ru': 'картина', 'tg': 'наққошӣ', 'lemma': 'painting'},
    'walls': {'ru': 'стена', 'tg': 'девор', 'lemma': 'wall'},
    'spa': {'ru': 'спа', 'tg': 'спа', 'lemma': 'spa'},
    'gift': {'ru': 'подарок', 'tg': 'тӯҳфа', 'lemma': 'gift'},
    'shop': {'ru': 'магазин', 'tg': 'мағоза', 'lemma': 'shop'},
    'enjoying': {'ru': 'наслаждаться', 'tg': 'лаззат бурдан', 'lemma': 'enjoy'},
    'making': {'ru': 'делать (создавать)', 'tg': 'сохтан', 'lemma': 'make'},
    'memories': {'ru': 'воспоминание', 'tg': 'хотира', 'lemma': 'memory'},
    'grateful': {'ru': 'благодарный', 'tg': 'миннатдор', 'lemma': 'grateful'},
    'these': {'ru': 'эти', 'tg': 'ин', 'lemma': 'these'},
    'moments': {'ru': 'момент', 'tg': 'лаҳза', 'lemma': 'moment'},
    'then': {'ru': 'тогда', 'tg': 'он вақт', 'lemma': 'then'},
    'now': {'ru': 'сейчас', 'tg': 'ҳозир', 'lemma': 'now'},
    'were': BE, 'was': BE, 'there was': BE, 'there were': BE, 'is': BE, 'are': BE,
},
58: {
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'got': {'ru': 'вставать (получать)', 'tg': 'хестан', 'lemma': 'get up'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'work': {'ru': 'работа (работать)', 'tg': 'кор', 'lemma': 'work'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'started': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'finished': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'didn\'t': DO, 'did': DO, 'do': DO,
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'sandwich': {'ru': 'сэндвич', 'tg': 'сандвич', 'lemma': 'sandwich'},
    'cafe': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'radio': {'ru': 'радио', 'tg': 'радио', 'lemma': 'radio'},
    'arrived': {'ru': 'приходить (прибывать)', 'tg': 'расидан', 'lemma': 'arrive'},
    'housework': {'ru': 'домашняя работа', 'tg': 'кори хона', 'lemma': 'housework'},
    'watched': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'normal': {'ru': 'обычный', 'tg': 'оддӣ', 'lemma': 'normal'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'friend': {'ru': 'друг (подруга)', 'tg': 'дӯст', 'lemma': 'friend'},
    'different': {'ru': 'другой', 'tg': 'дигар', 'lemma': 'different'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'shopping': {'ru': 'делать покупки', 'tg': 'харид кардан', 'lemma': 'shopping'},
    'bought': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'dress': {'ru': 'платье', 'tg': 'курта', 'lemma': 'dress'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'talked': {'ru': 'разговаривать', 'tg': 'гап задан', 'lemma': 'talk'},
    'holidays': {'ru': 'отпуск (каникулы)', 'tg': 'рухсатӣ', 'lemma': 'holiday'},
    'cinema': {'ru': 'кинотеатр', 'tg': 'кинотеатр', 'lemma': 'cinema'},
    'saw': {'ru': 'видеть', 'tg': 'дидан', 'lemma': 'see'},
    'funny': {'ru': 'смешной', 'tg': 'хандаовар', 'lemma': 'funny'},
    'film': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'feel': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'was': BE, 'her': {'ru': 'её', 'tg': 'ӯ', 'lemma': 'her'},
},
59: {
    'last': {'ru': 'прошлый', 'tg': 'гузашта', 'lemma': 'last'},
    'Sunday': {'ru': 'воскресенье', 'tg': 'якшанбе', 'lemma': 'Sunday'},
    'got': {'ru': 'вставать', 'tg': 'хестан', 'lemma': 'get up'},
    'didn\'t': DO, 'did': DO, 'do': DO,
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'pasta': {'ru': 'паста', 'tg': 'макарон', 'lemma': 'pasta'},
    'then': {'ru': 'потом', 'tg': 'баъд', 'lemma': 'then'},
    'watched': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'housework': {'ru': 'домашняя работа', 'tg': 'кори хона', 'lemma': 'housework'},
    'homework': {'ru': 'домашнее задание', 'tg': 'вазифаи хонагӣ', 'lemma': 'homework'},
    'listened': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'radio': {'ru': 'радио', 'tg': 'радио', 'lemma': 'radio'},
    'read': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'newspaper': {'ru': 'газета', 'tg': 'рӯзнома', 'lemma': 'newspaper'},
    'phoned': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'phone'},
    'friend': {'ru': 'друг (подруга)', 'tg': 'дӯст', 'lemma': 'friend'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'gym': {'ru': 'спортзал', 'tg': 'толори варзишӣ', 'lemma': 'gym'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'stayed': {'ru': 'оставаться', 'tg': 'мондан', 'lemma': 'stay'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'lazy': {'ru': 'ленивый', 'tg': 'танбал', 'lemma': 'lazy'},
    'laughed': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'exercise': {'ru': 'упражнение', 'tg': 'машқ', 'lemma': 'exercise'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'need': {'ru': 'нуждаться', 'tg': 'ниёз доштан', 'lemma': 'need'},
    'new': {'ru': 'новый', 'tg': 'нав', 'lemma': 'new'},
    'car': {'ru': 'автомобиль', 'tg': 'мошин', 'lemma': 'car'},
    'rent': {'ru': 'арендовать', 'tg': 'ба иҷора гирифтан', 'lemma': 'rent'},
    'walked': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'walk': {'ru': 'ходить пешком', 'tg': 'пиёда рафтан', 'lemma': 'walk'},
    'bed': {'ru': 'кровать', 'tg': 'бистар', 'lemma': 'bed'},
    'both': {'ru': 'оба', 'tg': 'ҳар ду', 'lemma': 'both'},
    'funny': {'ru': 'смешной', 'tg': 'хандаовар', 'lemma': 'funny'},
    'was': BE,
},
60: {
    'booked': {'ru': 'бронировать', 'tg': 'фармоиш додан', 'lemma': 'book'},
    'flight': {'ru': 'рейс', 'tg': 'парвоз', 'lemma': 'flight'},
    'packed': {'ru': 'упаковывать', 'tg': 'бор кардан', 'lemma': 'pack'},
    'suitcase': {'ru': 'чемодан', 'tg': 'чамадон', 'lemma': 'suitcase'},
    'left': {'ru': 'покидать (уходить)', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'got': {'ru': 'брать (заказывать)', 'tg': 'гирифтан', 'lemma': 'get'},
    'taxi': {'ru': 'такси', 'tg': 'таксӣ', 'lemma': 'taxi'},
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'airport': {'ru': 'аэропорт', 'tg': 'фурудгоҳ', 'lemma': 'airport'},
    'waited': {'ru': 'ждать', 'tg': 'интизор шудан', 'lemma': 'wait'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'passport': {'ru': 'паспорт', 'tg': 'шиноснома', 'lemma': 'passport'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'gate': {'ru': 'выход на посадку', 'tg': 'дарвоза', 'lemma': 'gate'},
    'sat': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'heard': {'ru': 'слышать', 'tg': 'шунидан', 'lemma': 'hear'},
    'announcement': {'ru': 'объявление', 'tg': 'эълон', 'lemma': 'announcement'},
    'said': {'ru': 'говорить (гласить)', 'tg': 'гуфтан', 'lemma': 'say'},
    'ran': {'ru': 'бежать', 'tg': 'давидан', 'lemma': 'run'},
    'carried': {'ru': 'нести', 'tg': 'бардоштан', 'lemma': 'carry'},
    'full': {'ru': 'полный', 'tg': 'пур', 'lemma': 'full'},
    'miss': {'ru': 'пропускать (опоздать)', 'tg': 'аз даст додан', 'lemma': 'miss'},
    'attendant': {'ru': 'бортпроводник (служащий)', 'tg': 'хизматгор', 'lemma': 'attendant'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'got2': {'ru': 'садиться (на транспорт)', 'tg': 'савор шудан', 'lemma': 'get on'},
    'plane': {'ru': 'самолёт', 'tg': 'ҳавопаймо', 'lemma': 'plane'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'didn\'t': DO, 'did': DO,
    'wear': {'ru': 'носить (одежду)', 'tg': 'пӯшидан', 'lemma': 'wear'},
    'sunglasses': {'ru': 'солнечные очки', 'tg': 'айнаки офтобӣ', 'lemma': 'sunglasses'},
    'phone': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'phone'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'trip': {'ru': 'поездка', 'tg': 'сафар', 'lemma': 'trip'},
    'was': BE, 'were': BE, 'are': BE,
},
61: {
    'went': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'meeting': {'ru': 'встреча', 'tg': 'ҷаласа', 'lemma': 'meeting'},
    'got': {'ru': 'вставать (получать)', 'tg': 'хестан', 'lemma': 'get up'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'had': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'left': {'ru': 'покидать (уходить)', 'tg': 'тарк кардан', 'lemma': 'leave'},
    'house': {'ru': 'дом', 'tg': 'хона', 'lemma': 'house'},
    'taxi': {'ru': 'такси', 'tg': 'таксӣ', 'lemma': 'taxi'},
    'arrived': {'ru': 'прибывать', 'tg': 'расидан', 'lemma': 'arrive'},
    'office': {'ru': 'офис', 'tg': 'идора', 'lemma': 'office'},
    'met': {'ru': 'встречать', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'boss': {'ru': 'начальник', 'tg': 'сардор', 'lemma': 'boss'},
    'said': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'didn\'t': DO, 'did': DO,
    'finish': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'report': {'ru': 'отчёт', 'tg': 'ҳисобот', 'lemma': 'report'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'worked': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'yesterday': {'ru': 'вчера', 'tg': 'дирӯз', 'lemma': 'yesterday'},
    'good': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'good'},
    'bring': {'ru': 'приносить', 'tg': 'овардан', 'lemma': 'bring'},
    'documents': {'ru': 'документ', 'tg': 'ҳуҷҷат', 'lemma': 'document'},
    'oh': {'ru': 'ох', 'tg': 'оҳ', 'lemma': 'oh'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'them': {'ru': 'их', 'tg': 'онҳоро', 'lemma': 'they'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'phoned': {'ru': 'звонить', 'tg': 'занг задан', 'lemma': 'phone'},
    'wife': {'ru': 'жена', 'tg': 'занак (ҳамсар)', 'lemma': 'wife'},
    'leave': {'ru': 'оставлять', 'tg': 'мондан', 'lemma': 'leave'},
    'table': {'ru': 'стол', 'tg': 'миз', 'lemma': 'table'},
    'yes2': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'will': {'ru': 'буду (вспом. буд. вр.)', 'tg': 'хоҳам', 'lemma': 'will'},
    'gave': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'sandwich': {'ru': 'сэндвич', 'tg': 'сандвич', 'lemma': 'sandwich'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'was': BE,
},
}

DICTS[56].pop('swimming2', None)
DICTS[60].pop('got2', None)
DICTS[61].pop('yes2', None)


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: filled with {len(DICTS[story.id])} entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
