import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select

from app.db.database import AsyncSessionLocal
from app.models.model_content import VocabEntries

# source_key -> example_en. Covers every A1 vocab_entries row that still had
# example_en = NULL after fill_a1_vocab_translations.py (407 of 523; the other
# 116 are full classroom-instruction phrases whose example_en already equals
# the phrase itself in the source data, e.g. "Sit down." - nothing to add there).
EXAMPLES = {
    'seed:A1:vocab:0': "My phone number starts with zero.",
    'seed:A1:vocab:1': "I have one brother.",
    'seed:A1:vocab:2': "She has two children.",
    'seed:A1:vocab:3': "There are three books on the table.",
    'seed:A1:vocab:4': "We need four chairs.",
    'seed:A1:vocab:5': "It's five o'clock.",
    'seed:A1:vocab:6': "The shop closes at six.",
    'seed:A1:vocab:7': "I have seven classes this week.",
    'seed:A1:vocab:8': "There are eight people in my family.",
    'seed:A1:vocab:9': "The bus leaves at nine.",
    'seed:A1:vocab:10': "Count from one to ten.",
    'seed:A1:vocab:11': "My sister is eleven years old.",
    'seed:A1:vocab:12': "There are twelve months in a year.",
    'seed:A1:vocab:13': "I am thirteen years old.",
    'seed:A1:vocab:14': "The lesson is fourteen pages long.",
    'seed:A1:vocab:15': "We have fifteen minutes left.",
    'seed:A1:vocab:16': "My father is sixteen years older than me.",
    'seed:A1:vocab:17': "There are seventeen students in the class.",
    'seed:A1:vocab:18': "She turns eighteen next month.",
    'seed:A1:vocab:19': "The film starts at nineteen hundred.",
    'seed:A1:vocab:20': "I am twenty years old.",
    'seed:A1:vocab:21': "There are twenty-one days left.",
    'seed:A1:vocab:22': "He is twenty-two years old.",
    'seed:A1:vocab:23': "My mother is thirty years old.",
    'seed:A1:vocab:24': "The room number is thirty-three.",
    'seed:A1:vocab:25': "There are forty students in the school.",
    'seed:A1:vocab:26': "The bus number is forty-four.",
    'seed:A1:vocab:27': "My grandfather is fifty years old.",
    'seed:A1:vocab:28': "The price is fifty-five dollars.",
    'seed:A1:vocab:29': "The speed limit is sixty.",
    'seed:A1:vocab:30': "The room is sixty-six square metres.",
    'seed:A1:vocab:31': "My grandmother is seventy years old.",
    'seed:A1:vocab:32': "The building has seventy-seven floors.",
    'seed:A1:vocab:33': "He is eighty years old.",
    'seed:A1:vocab:34': "The score was eighty-eight points.",
    'seed:A1:vocab:35': "The old man is ninety years old.",
    'seed:A1:vocab:36': "There are ninety-nine problems on the list.",
    'seed:A1:vocab:37': "There are a hundred students in the hall.",
    'seed:A1:vocab:38': "My friend is from Brazil.",
    'seed:A1:vocab:39': "She is a tourist from China.",
    'seed:A1:vocab:40': "The pyramids are in Egypt.",
    'seed:A1:vocab:41': "London is the capital of England.",
    'seed:A1:vocab:42': "I live in the UK.",
    'seed:A1:vocab:43': "Paris is the capital of France.",
    'seed:A1:vocab:44': "He works in Germany.",
    'seed:A1:vocab:45': "We are on holiday in Italy.",
    'seed:A1:vocab:46': "She studies in Japan.",
    'seed:A1:vocab:47': "My cousin lives in Mexico.",
    'seed:A1:vocab:48': "They are from Poland.",
    'seed:A1:vocab:49': "Moscow is the capital of Russia.",
    'seed:A1:vocab:50': "We are travelling to Spain.",
    'seed:A1:vocab:51': "The mountains in Switzerland are beautiful.",
    'seed:A1:vocab:52': "Istanbul is a big city in Turkey.",
    'seed:A1:vocab:53': "I want to visit the United States.",
    'seed:A1:vocab:54': "My colleague is Brazilian.",
    'seed:A1:vocab:55': "This restaurant serves Chinese food.",
    'seed:A1:vocab:56': "The Egyptian museum is famous.",
    'seed:A1:vocab:57': "I am learning English.",
    'seed:A1:vocab:58': "She speaks French very well.",
    'seed:A1:vocab:59': "He is a German teacher.",
    'seed:A1:vocab:60': "We love Italian food.",
    'seed:A1:vocab:61': "This is a Japanese car.",
    'seed:A1:vocab:62': "I like Mexican music.",
    'seed:A1:vocab:63': "She is reading a Polish book.",
    'seed:A1:vocab:64': "He is studying Russian history.",
    'seed:A1:vocab:65': "We are learning Spanish songs.",
    'seed:A1:vocab:66': "The Swiss mountains are amazing.",
    'seed:A1:vocab:67': "This is a Turkish restaurant.",
    'seed:A1:vocab:68': "My teacher is American.",
    'seed:A1:vocab:69': "He has a British passport.",
    'seed:A1:vocab:70': "Look at the board, please.",
    'seed:A1:vocab:71': "Please close the door.",
    'seed:A1:vocab:72': "Open the window, please.",
    'seed:A1:vocab:73': "Sit on this chair.",
    'seed:A1:vocab:74': "She is wearing a warm coat.",
    'seed:A1:vocab:75': "Put your bag on the table.",
    'seed:A1:vocab:76': "I write my homework on my laptop.",
    'seed:A1:vocab:77': "Look up the word in a dictionary.",
    'seed:A1:vocab:78': "Write your name on a piece of paper.",
    'seed:A1:vocab:79': "Can I borrow a pen?",
    'seed:A1:vocab:80': "I keep my books in my bag.",
    'seed:A1:vocab:93': "I always have my phone with me.",
    'seed:A1:vocab:94': "He is wearing a nice watch.",
    'seed:A1:vocab:95': "I read books on my tablet.",
    'seed:A1:vocab:96': "My wallet has my money and cards.",
    'seed:A1:vocab:97': "She keeps her keys in her purse.",
    'seed:A1:vocab:98': "Can I borrow your pencil?",
    'seed:A1:vocab:99': "I write ideas in my notebook.",
    'seed:A1:vocab:100': "He wears glasses to read.",
    'seed:A1:vocab:101': "This is a photo of my family.",
    'seed:A1:vocab:102': "I forgot my phone charger at home.",
    'seed:A1:vocab:103': "Please show your ID card.",
    'seed:A1:vocab:104': "I need my passport for the flight.",
    'seed:A1:vocab:105': "Take an umbrella, it's raining.",
    'seed:A1:vocab:106': "She took a photo with her camera.",
    'seed:A1:vocab:107': "I paid with my credit card.",
    'seed:A1:vocab:108': "He pays with a debit card.",
    'seed:A1:vocab:109': "I lost the key to my flat.",
    'seed:A1:vocab:110': "My father reads the newspaper every morning.",
    'seed:A1:vocab:111': "The boy is playing football.",
    'seed:A1:vocab:112': "The girl is reading a book.",
    'seed:A1:vocab:113': "That man is my teacher.",
    'seed:A1:vocab:114': "The woman is a doctor.",
    'seed:A1:vocab:115': "The children are in the garden.",
    'seed:A1:vocab:116': "I met my friends at the cafe.",
    'seed:A1:vocab:117': "Her husband works in a bank.",
    'seed:A1:vocab:118': "His wife is a nurse.",
    'seed:A1:vocab:119': "My mother cooks dinner every day.",
    'seed:A1:vocab:120': "My father drives to work.",
    'seed:A1:vocab:121': "Their son is a student.",
    'seed:A1:vocab:122': "Their daughter is ten years old.",
    'seed:A1:vocab:123': "My brother lives in London.",
    'seed:A1:vocab:124': "My sister studies medicine.",
    'seed:A1:vocab:125': "My grandmother makes delicious soup.",
    'seed:A1:vocab:126': "My grandfather tells great stories.",
    'seed:A1:vocab:127': "She introduced me to her boyfriend.",
    'seed:A1:vocab:128': "He is meeting his girlfriend tonight.",
    'seed:A1:vocab:129': "I have a black bag.",
    'seed:A1:vocab:130': "She is wearing a blue dress.",
    'seed:A1:vocab:131': "He has brown eyes.",
    'seed:A1:vocab:132': "The grass is green.",
    'seed:A1:vocab:133': "My cat is grey.",
    'seed:A1:vocab:134': "I like the orange sunset.",
    'seed:A1:vocab:135': "She bought a pink T-shirt.",
    'seed:A1:vocab:136': "The car is red.",
    'seed:A1:vocab:137': "He wore a white shirt.",
    'seed:A1:vocab:138': "This is a big house.",
    'seed:A1:vocab:139': "That is a small flat.",
    'seed:A1:vocab:140': "This is an old building.",
    'seed:A1:vocab:141': "I bought a new phone.",
    'seed:A1:vocab:143': "The train was very slow.",
    'seed:A1:vocab:144': "The view is beautiful.",
    'seed:A1:vocab:145': "The old sofa is ugly.",
    'seed:A1:vocab:146': "This restaurant is cheap.",
    'seed:A1:vocab:148': "She has long hair.",
    'seed:A1:vocab:149': "He has short hair.",
    'seed:A1:vocab:150': "My room is clean.",
    'seed:A1:vocab:151': "His shoes are dirty.",
    'seed:A1:vocab:152': "This exercise is easy.",
    'seed:A1:vocab:153': "The exam was difficult.",
    'seed:A1:vocab:154': "We had fish for dinner.",
    'seed:A1:vocab:155': "I don't eat meat.",
    'seed:A1:vocab:156': "She cooked pasta for lunch.",
    'seed:A1:vocab:157': "We usually eat rice with dinner.",
    'seed:A1:vocab:158': "I have eggs for breakfast.",
    'seed:A1:vocab:159': "I like yogurt with fruit.",
    'seed:A1:vocab:160': "Eat more vegetables every day.",
    'seed:A1:vocab:161': "She made a fresh salad.",
    'seed:A1:vocab:162': "I eat fruit every morning.",
    'seed:A1:vocab:163': "We buy fresh bread every day.",
    'seed:A1:vocab:164': "Put some butter on the toast.",
    'seed:A1:vocab:165': "I like cheese on my sandwich.",
    'seed:A1:vocab:166': "I don't take sugar in my tea.",
    'seed:A1:vocab:167': "I made a sandwich for lunch.",
    'seed:A1:vocab:168': "I have cereal for breakfast.",
    'seed:A1:vocab:169': "She loves chocolate cake.",
    'seed:A1:vocab:170': "I drink coffee every morning.",
    'seed:A1:vocab:171': "Would you like a cup of tea?",
    'seed:A1:vocab:172': "I drink milk with my cereal.",
    'seed:A1:vocab:173': "She had a glass of orange juice.",
    'seed:A1:vocab:174': "They drank wine at dinner.",
    'seed:A1:vocab:175': "He ordered a beer at the bar.",
    'seed:A1:vocab:177': "We have lunch at one o'clock.",
    'seed:A1:vocab:178': "Dinner is ready at seven.",
    'seed:A1:vocab:179': "My cousin likes to live in a flat.",
    'seed:A1:vocab:180': "I always have breakfast at eight.",
    'seed:A1:vocab:181': "We watch TV in the evening.",
    'seed:A1:vocab:182': "He likes to listen to the radio.",
    'seed:A1:vocab:183': "My father reads the newspaper at breakfast.",
    'seed:A1:vocab:184': "We sometimes eat fast food on Fridays.",
    'seed:A1:vocab:186': "She wants to speak English fluently.",
    'seed:A1:vocab:187': "I want a coffee, please.",
    'seed:A1:vocab:188': "My neighbour likes to have a dog.",
    'seed:A1:vocab:189': "My sister loves to like cats.",
    'seed:A1:vocab:190': "My uncle likes to work in a bank.",
    'seed:A1:vocab:191': "She decided to study Spanish this year.",
    'seed:A1:vocab:192': "He likes to go to English classes.",
    'seed:A1:vocab:193': "They need a new car for the family.",
    'seed:A1:vocab:194': "My aunt is a teacher.",
    'seed:A1:vocab:195': "He wants to be a doctor.",
    'seed:A1:vocab:196': "She works as a nurse.",
    'seed:A1:vocab:197': "He is a journalist for a newspaper.",
    'seed:A1:vocab:198': "The waiter brought our food.",
    'seed:A1:vocab:199': "The waitress took our order.",
    'seed:A1:vocab:200': "The shop assistant helped me find a shirt.",
    'seed:A1:vocab:201': "The receptionist gave me the room key.",
    'seed:A1:vocab:202': "The policeman helped us find the street.",
    'seed:A1:vocab:203': "The policewoman stopped the traffic.",
    'seed:A1:vocab:204': "He works as a factory worker.",
    'seed:A1:vocab:205': "The taxi driver knew the way.",
    'seed:A1:vocab:206': "She works in a hospital.",
    'seed:A1:vocab:207': "I bought bread in a shop.",
    'seed:A1:vocab:208': "We had dinner in a restaurant.",
    'seed:A1:vocab:209': "He works in an office.",
    'seed:A1:vocab:210': "My daughter studies in a school.",
    'seed:A1:vocab:211': "He works in a factory.",
    'seed:A1:vocab:212': "I stayed at home yesterday.",
    'seed:A1:vocab:213': "There were many people in the street.",
    'seed:A1:vocab:222': "I get up at seven every day.",
    'seed:A1:vocab:223': "We have breakfast together.",
    'seed:A1:vocab:224': "I have a shower every morning.",
    'seed:A1:vocab:225': "He goes to work by bus.",
    'seed:A1:vocab:226': "I usually have a coffee first.",
    'seed:A1:vocab:227': "We have lunch at noon.",
    'seed:A1:vocab:228': "She finishes work at five.",
    'seed:A1:vocab:229': "I go home after work.",
    'seed:A1:vocab:230': "We go shopping on Saturdays.",
    'seed:A1:vocab:231': "He goes to the gym every evening.",
    'seed:A1:vocab:232': "I make dinner for my family.",
    'seed:A1:vocab:233': "We have dinner at eight.",
    'seed:A1:vocab:234': "I do housework on Sundays.",
    'seed:A1:vocab:235': "We watch TV after dinner.",
    'seed:A1:vocab:236': "I have a bath before bed.",
    'seed:A1:vocab:237': "I go to bed at eleven.",
    'seed:A1:vocab:238': "We go out at night with friends.",
    'seed:A1:vocab:239': "My brother likes to play computer games.",
    'seed:A1:vocab:240': "I do sport twice a week.",
    'seed:A1:vocab:242': "We stay at home when it rains.",
    'seed:A1:vocab:243': "We play tennis on Sundays.",
    'seed:A1:vocab:244': "We like to walk in the mountains.",
    'seed:A1:vocab:245': "She loves to play the piano.",
    'seed:A1:vocab:246': "I like to swim in the sea.",
    'seed:A1:vocab:247': "I meet friends every weekend.",
    'seed:A1:vocab:248': "I like to relax on Sundays.",
    'seed:A1:vocab:249': "We love to travel in summer.",
    'seed:A1:vocab:250': "We need to book tickets for the concert.",
    'seed:A1:vocab:251': "I need to pack a suitcase for my trip.",
    'seed:A1:vocab:252': "We leave the house at eight.",
    'seed:A1:vocab:253': "He had to carry a suitcase up the stairs.",
    'seed:A1:vocab:254': "She likes to wear sunglasses in summer.",
    'seed:A1:vocab:255': "I need to get a taxi to the airport.",
    'seed:A1:vocab:256': "We had to wait for a flight for two hours.",
    'seed:A1:vocab:257': "We decided to rent a car for the trip.",
    'seed:A1:vocab:258': "We will arrive at a hotel this evening.",
    'seed:A1:vocab:259': "We are going to stay in a hotel.",
    'seed:A1:vocab:260': "I always phone home when I travel.",
    'seed:A1:vocab:261': "I like to buy presents for my family.",
    'seed:A1:vocab:262': "My birthday is in January.",
    'seed:A1:vocab:263': "It often snows in February.",
    'seed:A1:vocab:264': "Spring starts in March.",
    'seed:A1:vocab:265': "We go on holiday in April.",
    'seed:A1:vocab:266': "The weather is warm in May.",
    'seed:A1:vocab:267': "School finishes in June.",
    'seed:A1:vocab:268': "It's very hot in July.",
    'seed:A1:vocab:269': "We usually travel in August.",
    'seed:A1:vocab:270': "School starts again in September.",
    'seed:A1:vocab:271': "The leaves fall in October.",
    'seed:A1:vocab:272': "It gets cold in November.",
    'seed:A1:vocab:273': "We celebrate the new year in December.",
    'seed:A1:vocab:274': "This is the first day of school.",
    'seed:A1:vocab:275': "She came in second place.",
    'seed:A1:vocab:276': "It's the third time I've asked.",
    'seed:A1:vocab:277': "Today is my fourth day here.",
    'seed:A1:vocab:278': "This is the fifth chapter.",
    'seed:A1:vocab:279': "We are on the sixth floor.",
    'seed:A1:vocab:280': "This is my seventh visit.",
    'seed:A1:vocab:281': "It's the eighth of May.",
    'seed:A1:vocab:282': "This is the ninth question.",
    'seed:A1:vocab:283': "Today is the tenth of June.",
    'seed:A1:vocab:284': "It's the eleventh of July.",
    'seed:A1:vocab:285': "Her birthday is the twelfth of March.",
    'seed:A1:vocab:286': "The meeting is on the thirteenth.",
    'seed:A1:vocab:287': "The flight is on the fourteenth.",
    'seed:A1:vocab:288': "The party is on the fifteenth.",
    'seed:A1:vocab:289': "We arrive on the sixteenth.",
    'seed:A1:vocab:290': "The exam is on the seventeenth.",
    'seed:A1:vocab:291': "He was born on the eighteenth of April.",
    'seed:A1:vocab:292': "The wedding is on the nineteenth.",
    'seed:A1:vocab:293': "Today is the twentieth of August.",
    'seed:A1:vocab:294': "Her birthday is the twenty-first of June.",
    'seed:A1:vocab:295': "We leave on the twenty-second.",
    'seed:A1:vocab:296': "The concert is on the twenty-third.",
    'seed:A1:vocab:297': "The holiday starts on the twenty-fourth.",
    'seed:A1:vocab:298': "We return on the twenty-fifth.",
    'seed:A1:vocab:299': "The meeting is on the twenty-sixth.",
    'seed:A1:vocab:300': "His birthday is the twenty-seventh of May.",
    'seed:A1:vocab:301': "The exam is on the twenty-eighth.",
    'seed:A1:vocab:302': "We finish on the twenty-ninth.",
    'seed:A1:vocab:303': "The month ends on the thirtieth.",
    'seed:A1:vocab:304': "The trip starts on the thirty-first.",
    'seed:A1:vocab:305': "She spent the afternoon buying clothes.",
    'seed:A1:vocab:306': "We went camping in the mountains.",
    'seed:A1:vocab:307': "I enjoy cooking for my friends.",
    'seed:A1:vocab:308': "Cycling is good exercise.",
    'seed:A1:vocab:309': "I do yoga every morning.",
    'seed:A1:vocab:310': "We love eating out on weekends.",
    'seed:A1:vocab:311': "Flying makes her nervous.",
    'seed:A1:vocab:312': "We enjoy going for a walk in the park.",
    'seed:A1:vocab:313': "Going to the cinema is our favourite activity.",
    'seed:A1:vocab:314': "She spends hours painting.",
    'seed:A1:vocab:315': "Reading is my favourite hobby.",
    'seed:A1:vocab:316': "Running keeps me fit.",
    'seed:A1:vocab:317': "Shopping takes a lot of time.",
    'seed:A1:vocab:318': "Singing makes her happy.",
    'seed:A1:vocab:319': "Sleeping late is my weekend habit.",
    'seed:A1:vocab:320': "Swimming is great exercise.",
    'seed:A1:vocab:321': "Travelling opens your mind.",
    'seed:A1:vocab:322': "Watching TV series is fun after work.",
    'seed:A1:vocab:323': "I need a warm sweater for winter.",
    'seed:A1:vocab:324': "He is wearing a blue T-shirt.",
    'seed:A1:vocab:325': "She bought a white shirt.",
    'seed:A1:vocab:326': "He is wearing black trousers.",
    'seed:A1:vocab:327': "I like these blue jeans.",
    'seed:A1:vocab:328': "He wore shorts to the beach.",
    'seed:A1:vocab:329': "He wore a suit to the interview.",
    'seed:A1:vocab:330': "She is wearing a red dress.",
    'seed:A1:vocab:331': "She bought a black skirt.",
    'seed:A1:vocab:332': "It's cold, wear your coat.",
    'seed:A1:vocab:333': "He put on his jacket.",
    'seed:A1:vocab:334': "I need new socks.",
    'seed:A1:vocab:335': "She runs in her trainers.",
    'seed:A1:vocab:336': "He bought new shoes.",
    'seed:A1:vocab:337': "She wore a hat in the sun.",
    'seed:A1:vocab:338': "He always wears a cap.",
    'seed:A1:vocab:339': "The bed is very comfortable.",
    'seed:A1:vocab:340': "I sleep with two pillows.",
    'seed:A1:vocab:341': "Put the lamp on the table.",
    'seed:A1:vocab:342': "Turn on the lamp, please.",
    'seed:A1:vocab:343': "Turn off the light, please.",
    'seed:A1:vocab:344': "Where is the remote control?",
    'seed:A1:vocab:345': "There are shoes on the floor.",
    'seed:A1:vocab:346': "The bathroom is upstairs.",
    'seed:A1:vocab:347': "She had a long bath.",
    'seed:A1:vocab:348': "I prefer a shower to a bath.",
    'seed:A1:vocab:349': "Give me a clean towel, please.",
    'seed:A1:vocab:350': "Put the plates in the cupboard.",
    'seed:A1:vocab:352': "We relaxed at the hotel spa.",
    'seed:A1:vocab:353': "The toilets are on the ground floor.",
    'seed:A1:vocab:354': "We had dinner at a restaurant.",
    'seed:A1:vocab:355': "We had a drink at the bar.",
    'seed:A1:vocab:356': "He goes to the gym every day.",
    'seed:A1:vocab:357': "We took the lift to the tenth floor.",
    'seed:A1:vocab:358': "I bought a mug in the gift shop.",
    'seed:A1:vocab:359': "Please leave your key at reception.",
    'seed:A1:vocab:360': "They have a beautiful garden.",
    'seed:A1:vocab:361': "The hotel has a large car park.",
    'seed:A1:vocab:386': "Many tourists visit this city.",
    'seed:A1:vocab:387': "I love dogs.",
    'seed:A1:vocab:388': "The bus stop is over there.",
    'seed:A1:vocab:407': "My bedroom is upstairs.",
    'seed:A1:vocab:408': "We cook in the kitchen.",
    'seed:A1:vocab:409': "There is a garden behind the house.",
    'seed:A1:vocab:410': "This is a big house.",
    'seed:A1:vocab:411': "That is a small flat.",
    'seed:A1:vocab:412': "They live in the south of England.",
    'seed:A1:vocab:429': "I bought some souvenirs for my family.",
    'seed:A1:vocab:430': "Please wait here.",
    'seed:A1:vocab:431': "Put the bag over there.",
    'seed:A1:vocab:438': "The keys are on the table.",
    'seed:A1:vocab:439': "I saved your number in my phone.",
    'seed:A1:vocab:440': "Mum is cooking dinner.",
    'seed:A1:vocab:441': "Dad is watching the football.",
    'seed:A1:vocab:442': "We hired a babysitter for the evening.",
    'seed:A1:vocab:443': "Perhaps we should leave earlier.",
    'seed:A1:vocab:444': "Excuse me, Sir, is this seat free?",
    'seed:A1:vocab:445': "Can I help you, madam?",
    'seed:A1:vocab:446': "We bought an electric car.",
    'seed:A1:vocab:447': "He drives a sports car.",
    'seed:A1:vocab:448': "This small car is easy to park.",
    'seed:A1:vocab:449': "This is a perfect day.",
    'seed:A1:vocab:450': "In her opinion, the film was great.",
    'seed:A1:vocab:455': "We visited a museum yesterday.",
    'seed:A1:vocab:456': "They live in a small village.",
    'seed:A1:vocab:457': "He rides a motorbike to work.",
    'seed:A1:vocab:458': "She is a famous singer.",
    'seed:A1:vocab:459': "He works as a scientist.",
    'seed:A1:vocab:460': "She is training to be a doctor.",
    'seed:A1:vocab:461': "I sometimes go running in the morning.",
    'seed:A1:vocab:462': "I usually walk to work.",
    'seed:A1:vocab:464': "I wake up early every day.",
    'seed:A1:vocab:465': "She eats a healthy diet.",
    'seed:A1:vocab:466': "This is a traditional dish from my country.",
    'seed:A1:vocab:467': "It's important to sleep well.",
    'seed:A1:vocab:468': "We have different opinions about it.",
    'seed:A1:vocab:469': "Pizza is my favourite food.",
    'seed:A1:vocab:470': "We met in a cafe.",
    'seed:A1:vocab:471': "I stayed at home all day.",
    'seed:A1:vocab:472': "She is busy at work today.",
    'seed:A1:vocab:473': "I had soup for lunch.",
    'seed:A1:vocab:474': "I prefer green tea in the morning.",
    'seed:A1:vocab:475': "I had toast for breakfast.",
    'seed:A1:vocab:476': "There is a lot of fruit on the table.",
    'seed:A1:vocab:477': "She is a famous writer.",
    'seed:A1:vocab:478': "The taxi driver took us to the airport.",
    'seed:A1:vocab:479': "He works for a British company.",
    'seed:A1:vocab:480': "Our flight leaves at nine.",
    'seed:A1:vocab:481': "There was a lot of traffic this morning.",
    'seed:A1:vocab:482': "The gate for our flight is number five.",
    'seed:A1:vocab:483': "She studies economics at university.",
    'seed:A1:vocab:484': "My son is at school today.",
    'seed:A1:vocab:501': "She is a very intelligent student.",
    'seed:A1:vocab:502': "The barman made us two drinks.",
    'seed:A1:vocab:503': "He works as a banker in the city.",
    'seed:A1:vocab:504': "The shop had many customers today.",
    'seed:A1:vocab:505': "She washed all the dishes.",
    'seed:A1:vocab:506': "He works for a multinational company.",
    'seed:A1:vocab:507': "We have meetings every Monday.",
    'seed:A1:vocab:508': "Why are you late? Because the bus was slow.",
    'seed:A1:vocab:514': "I feel tired after work.",
    'seed:A1:vocab:515': "I listen to music on the way to work.",
    'seed:A1:vocab:516': "We go to the gym after work.",
    'seed:A1:vocab:517': "I drink coffee every morning.",
    'seed:A1:vocab:518': "I had breakfast, then I went to work.",
    'seed:A1:vocab:519': "The tour guide showed us the city.",
    'seed:A1:vocab:520': "They live in a small apartment.",
    'seed:A1:vocab:521': "We took the subway to the museum.",
    'seed:A1:vocab:522': "I had an omelette for breakfast.",
}


async def main():
    async with AsyncSessionLocal() as db:
        entries = (
            await db.execute(select(VocabEntries).where(VocabEntries.cefr_level == 'A1'))
        ).scalars().all()
        by_source_key = {e.source_key: e for e in entries}

        updated = 0
        missing = []
        for key, example in EXAMPLES.items():
            entry = by_source_key.get(key)
            if entry is None:
                missing.append(key)
                continue
            entry.example_en = example
            updated += 1

        await db.commit()
        print(f'updated {updated} A1 vocab entries with example_en')
        if missing:
            print('missing source_keys:', missing)

        remaining = (
            await db.execute(select(VocabEntries).where(VocabEntries.cefr_level == 'A1', VocabEntries.example_en.is_(None)))
        ).scalars().all()
        print(f'still without example_en: {len(remaining)}')
        for r in remaining:
            print('  ', r.source_key, r.word)


asyncio.run(main())
