import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.orm.attributes import flag_modified

from app.db.database import AsyncSessionLocal
from app.models.model_content import Stories

BE = {'ru': 'быть', 'tg': 'будан', 'lemma': 'be'}

DICTS = {
27: {
    'photo': {'ru': 'фотография', 'tg': 'акс', 'lemma': 'photo'},
    'family': {'ru': 'семья', 'tg': 'оила', 'lemma': 'family'},
    'parents': {'ru': 'родители', 'tg': 'падару модар', 'lemma': 'parent'},
    'middle': {'ru': 'середина', 'tg': 'миён', 'lemma': 'middle'},
    'father': {'ru': 'отец', 'tg': 'падар', 'lemma': 'father'},
    'tall': {'ru': 'высокий', 'tg': 'баланд', 'lemma': 'tall'},
    'strong': {'ru': 'сильный', 'tg': 'қавӣ', 'lemma': 'strong'},
    'mother': {'ru': 'мать', 'tg': 'модар', 'lemma': 'mother'},
    'beautiful': {'ru': 'красивый', 'tg': 'зебо', 'lemma': 'beautiful'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'long': {'ru': 'длинный', 'tg': 'дароз', 'lemma': 'long'},
    'brown': {'ru': 'коричневый', 'tg': 'қаҳваранг', 'lemma': 'brown'},
    'hair': {'ru': 'волосы', 'tg': 'мӯй', 'lemma': 'hair'},
    'brother': {'ru': 'брат', 'tg': 'бародар', 'lemma': 'brother'},
    'next': {'ru': 'рядом (с)', 'tg': 'дар паҳлӯи', 'lemma': 'next'},
    'student': {'ru': 'ученик', 'tg': 'хонанда', 'lemma': 'student'},
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'girl': {'ru': 'девочка', 'tg': 'духтар', 'lemma': 'girl'},
    'front': {'ru': 'впереди', 'tg': 'дар пеш', 'lemma': 'front'},
    'dog': {'ru': 'собака', 'tg': 'саг', 'lemma': 'dog'},
    'its': {'ru': 'её (его — о предмете/животном)', 'tg': 'аз они он', 'lemma': 'its'},
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'grandparents': {'ru': 'дедушка и бабушка', 'tg': 'бобову бибӣ', 'lemma': 'grandparent'},
    'left': {'ru': 'левый', 'tg': 'чап', 'lemma': 'left'},
    'grandmother': {'ru': 'бабушка', 'tg': 'бибӣ', 'lemma': 'grandmother'},
    'old': {'ru': 'старый', 'tg': 'пир', 'lemma': 'old'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'grandfather': {'ru': 'дедушка', 'tg': 'бобо', 'lemma': 'grandfather'},
    'bit': {'ru': 'немного', 'tg': 'як андоза', 'lemma': 'bit'},
    'short': {'ru': 'низкий (тж. короткий)', 'tg': 'паст (тж. кӯтоҳ)', 'lemma': 'short'},
    'retired': {'ru': 'на пенсии', 'tg': 'нафақарафта', 'lemma': 'retired'},
    'doctor': {'ru': 'врач', 'tg': 'духтур', 'lemma': 'doctor'},
    'aunt': {'ru': 'тётя', 'tg': 'хола (амма)', 'lemma': 'aunt'},
    'uncle': {'ru': 'дядя', 'tg': 'тағо (амак)', 'lemma': 'uncle'},
    'right': {'ru': 'правый', 'tg': 'рост', 'lemma': 'right'},
    'nice': {'ru': 'приятный', 'tg': 'хуш', 'lemma': 'nice'},
    'couple': {'ru': 'пара', 'tg': 'ҷуфт', 'lemma': 'couple'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'policeman': {'ru': 'полицейский', 'tg': 'милиса', 'lemma': 'policeman'},
    'everyone': {'ru': 'все', 'tg': 'ҳама', 'lemma': 'everyone'},
    'smiling': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'lucky': {'ru': 'удачливый', 'tg': 'хушбахт (шонсдор)', 'lemma': 'lucky'},
    'am': BE, 'is': BE, 'are': BE,
},
29: {
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'cafe': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'serve': {'ru': 'подавать (обслуживать)', 'tg': 'пешкаш кардан', 'lemma': 'serve'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'make': {'ru': 'делать (готовить)', 'tg': 'тайёр кардан', 'lemma': 'make'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    "don't": {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'drink': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'customers': {'ru': 'покупатель (клиент)', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'cappuccino': {'ru': 'капучино', 'tg': 'капучино', 'lemma': 'cappuccino'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'sugar': {'ru': 'сахар', 'tg': 'шакар', 'lemma': 'sugar'},
    'but': {'ru': 'но', 'tg': 'аммо', 'lemma': 'but'},
    'milk': {'ru': 'молоко', 'tg': 'шир', 'lemma': 'milk'},
    'oh': {'ru': 'ох', 'tg': 'оҳ', 'lemma': 'oh'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'orange': {'ru': 'апельсиновый (тж. апельсин)', 'tg': 'афлесунӣ (тж. афлесун)', 'lemma': 'orange'},
    'juice': {'ru': 'сок', 'tg': 'афшура', 'lemma': 'juice'},
    'laugh': {'ru': 'смеяться', 'tg': 'хандидан', 'lemma': 'laugh'},
    'one': {'ru': 'один', 'tg': 'як', 'lemma': 'one'},
    'wine': {'ru': 'вино', 'tg': 'шароб', 'lemma': 'wine'},
    'beer': {'ru': 'пиво', 'tg': 'пиво', 'lemma': 'beer'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'all': {'ru': 'весь', 'tg': 'тамоми', 'lemma': 'all'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'stop': {'ru': 'прекращать', 'tg': 'бас кардан', 'lemma': 'stop'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'have': {'ru': 'иметь (взять)', 'tg': 'гирифтан', 'lemma': 'have'},
    'cereal': {'ru': 'каша (хлопья)', 'tg': 'ярмаи ғалладона', 'lemma': 'cereal'},
    'fine': {'ru': 'хорошо (ладно)', 'tg': 'хуб (майлаш)', 'lemma': 'fine'},
    'eggs': {'ru': 'яйцо', 'tg': 'тухм', 'lemma': 'egg'},
    'toast': {'ru': 'тост', 'tg': 'нони бирёншуда', 'lemma': 'toast'},
    'customer': {'ru': 'покупатель (клиент)', 'tg': 'муштарӣ', 'lemma': 'customer'},
    'am': BE, 'is': BE, 'are': BE, 'do': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
},
32: {
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'cafe': {'ru': 'кафе', 'tg': 'қаҳвахона', 'lemma': 'cafe'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'study': {'ru': 'изучать', 'tg': 'омӯхтан', 'lemma': 'study'},
    'English': {'ru': 'английский', 'tg': 'англисӣ', 'lemma': 'English'},
    'english': {'ru': 'английский', 'tg': 'англисӣ', 'lemma': 'English'},
    'there': {'ru': 'там', 'tg': 'он ҷо', 'lemma': 'there'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'read': {'ru': 'читать', 'tg': 'хондан', 'lemma': 'read'},
    'newspaper': {'ru': 'газета', 'tg': 'рӯзнома', 'lemma': 'newspaper'},
    'listen': {'ru': 'слушать', 'tg': 'гӯш кардан', 'lemma': 'listen'},
    'radio': {'ru': 'радио', 'tg': 'радио', 'lemma': 'radio'},
    'speak': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'waiters': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    "don't": {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'Spanish': {'ru': 'испанский', 'tg': 'испанӣ', 'lemma': 'Spanish'},
    'say': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'yes': {'ru': 'да', 'tg': 'ҳа', 'lemma': 'yes'},
    'tea': {'ru': 'чай', 'tg': 'чой', 'lemma': 'tea'},
    'green': {'ru': 'зелёный', 'tg': 'сабз', 'lemma': 'green'},
    'black': {'ru': 'чёрный', 'tg': 'сиёҳ', 'lemma': 'black'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'sandwiches': {'ru': 'сэндвич', 'tg': 'сандвич', 'lemma': 'sandwich'},
    'fruit': {'ru': 'фрукт', 'tg': 'мева', 'lemma': 'fruit'},
    'yogurt': {'ru': 'йогурт', 'tg': 'йогурт', 'lemma': 'yogurt'},
    'cereal': {'ru': 'каша (хлопья)', 'tg': 'ярмаи ғалладона', 'lemma': 'cereal'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'give': {'ru': 'давать', 'tg': 'додан', 'lemma': 'give'},
    'eat': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'hard': {'ru': 'усердно (тж. трудный)', 'tg': 'сахт', 'lemma': 'hard'},
    'well': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'well'},
    'improving': {'ru': 'улучшаться', 'tg': 'беҳтар шудан', 'lemma': 'improve'},
    'am': BE, 'do': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
},
33: {
    'sister': {'ru': 'сестра', 'tg': 'хоҳар', 'lemma': 'sister'},
    'nurse': {'ru': 'медсестра', 'tg': 'ҳамшираи тиббӣ', 'lemma': 'nurse'},
    'works': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'work': {'ru': 'работать', 'tg': 'кор кардан', 'lemma': 'work'},
    'hospital': {'ru': 'больница', 'tg': 'беморхона', 'lemma': 'hospital'},
    'gets': {'ru': 'вставать', 'tg': 'аз хоб хестан', 'lemma': 'get up'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'morning': {'ru': 'утро', 'tg': 'субҳ', 'lemma': 'morning'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'has': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'goes': {'ru': 'идти (ехать)', 'tg': 'рафтан', 'lemma': 'go'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'finishes': {'ru': 'заканчивать', 'tg': 'тамом кардан', 'lemma': 'finish'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'watches': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'helps': {'ru': 'помогать', 'tg': 'ёрӣ додан', 'lemma': 'help'},
    'patients': {'ru': 'пациент (больной)', 'tg': 'бемор', 'lemma': 'patient'},
    'speaks': {'ru': 'говорить', 'tg': 'гап задан', 'lemma': 'speak'},
    'loves': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'job': {'ru': 'работа', 'tg': 'кор', 'lemma': 'job'},
    'her': {'ru': 'её', 'tg': 'ӯ', 'lemma': 'her'},
    'husband': {'ru': 'муж', 'tg': 'шавҳар', 'lemma': 'husband'},
    'teacher': {'ru': 'учитель', 'tg': 'муаллим', 'lemma': 'teacher'},
    'teaches': {'ru': 'преподавать', 'tg': 'таълим додан', 'lemma': 'teach'},
    'french': {'ru': 'французский', 'tg': 'фаронсавӣ', 'lemma': 'French'},
    'school': {'ru': 'школа', 'tg': 'мактаб', 'lemma': 'school'},
    'coffee': {'ru': 'кофе', 'tg': 'қаҳва', 'lemma': 'coffee'},
    'gym': {'ru': 'спортзал', 'tg': 'толори варзишӣ', 'lemma': 'gym'},
    'after': {'ru': 'после', 'tg': 'баъд аз', 'lemma': 'after'},
    'does': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'housework': {'ru': 'домашняя работа', 'tg': 'кори хона', 'lemma': 'housework'},
    'daughter': {'ru': 'дочь', 'tg': 'духтар', 'lemma': 'daughter'},
    'journalist': {'ru': 'журналист', 'tg': 'рӯзноманигор', 'lemma': 'journalist'},
    'writes': {'ru': 'писать', 'tg': 'навиштан', 'lemma': 'write'},
    'newspaper': {'ru': 'газета', 'tg': 'рӯзнома', 'lemma': 'newspaper'},
    'company': {'ru': 'компания', 'tg': 'ширкат', 'lemma': 'company'},
    'big': {'ru': 'большой', 'tg': 'калон', 'lemma': 'big'},
    'home': {'ru': 'дом', 'tg': 'хона', 'lemma': 'home'},
    'feels': {'ru': 'чувствовать', 'tg': 'ҳис кардан', 'lemma': 'feel'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'proud': {'ru': 'гордый', 'tg': 'ифтихорманд', 'lemma': 'proud'},
    'am': BE, 'is': BE, 'are': BE,
},
34: {
    'waiter': {'ru': 'официант', 'tg': 'пешхизмат', 'lemma': 'waiter'},
    'restaurant': {'ru': 'ресторан', 'tg': 'тарабхона', 'lemma': 'restaurant'},
    'very': {'ru': 'очень', 'tg': 'хеле', 'lemma': 'very'},
    'lazy': {'ru': 'ленивый', 'tg': 'танбал', 'lemma': 'lazy'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'gets': {'ru': 'вставать', 'tg': 'аз хоб хестан', 'lemma': 'get up'},
    'early': {'ru': 'рано', 'tg': 'барвақт', 'lemma': 'early'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    "doesn": {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'does': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'do': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'goes': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'work': {'ru': 'работа (работать)', 'tg': 'кор', 'lemma': 'work'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'arrives': {'ru': 'приходить (прибывать)', 'tg': 'омадан', 'lemma': 'arrive'},
    'late': {'ru': 'поздно', 'tg': 'дер', 'lemma': 'late'},
    'shower': {'ru': 'душ', 'tg': 'душ', 'lemma': 'shower'},
    'housework': {'ru': 'домашняя работа', 'tg': 'кори хона', 'lemma': 'housework'},
    'boss': {'ru': 'начальник', 'tg': 'сардор', 'lemma': 'boss'},
    'angry': {'ru': 'сердитый', 'tg': 'хашмгин', 'lemma': 'angry'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    'hard': {'ru': 'усердно', 'tg': 'сахт', 'lemma': 'hard'},
    'makes': {'ru': 'делать (совершать)', 'tg': 'кардан', 'lemma': 'make'},
    'mistakes': {'ru': 'ошибка', 'tg': 'хато', 'lemma': 'mistake'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'smiles': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'smile': {'ru': 'улыбаться', 'tg': 'лабханд задан', 'lemma': 'smile'},
    'look': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'looks': {'ru': 'выглядеть', 'tg': 'намудор шудан', 'lemma': 'look'},
    'tired': {'ru': 'усталый', 'tg': 'хаста', 'lemma': 'tired'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'night': {'ru': 'ночь', 'tg': 'шаб', 'lemma': 'night'},
    'need': {'ru': 'нуждаться (быть должным)', 'tg': 'лозим будан', 'lemma': 'need'},
    'change': {'ru': 'изменяться', 'tg': 'тағир ёфтан', 'lemma': 'change'},
    'try': {'ru': 'пытаться', 'tg': 'кӯшиш кардан', 'lemma': 'try'},
    'starts': {'ru': 'начинать', 'tg': 'сар кардан', 'lemma': 'start'},
    'becomes': {'ru': 'становиться', 'tg': 'шудан', 'lemma': 'become'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'am': BE, 'is': BE, 'get': {'ru': 'получать', 'tg': 'гирифтан', 'lemma': 'get'},
},
37: {
    'student': {'ru': 'студент', 'tg': 'донишҷӯ', 'lemma': 'student'},
    'study': {'ru': 'изучать', 'tg': 'омӯхтан', 'lemma': 'study'},
    'economics': {'ru': 'экономика', 'tg': 'иқтисод', 'lemma': 'economics'},
    'university': {'ru': 'университет', 'tg': 'донишгоҳ', 'lemma': 'university'},
    'gets': {'ru': 'вставать', 'tg': 'аз хоб хестан', 'lemma': 'get up'},
    'every': {'ru': 'каждый', 'tg': 'ҳар', 'lemma': 'every'},
    'day': {'ru': 'день', 'tg': 'рӯз', 'lemma': 'day'},
    'always': {'ru': 'всегда', 'tg': 'ҳамеша', 'lemma': 'always'},
    'have': {'ru': 'иметь', 'tg': 'доштан', 'lemma': 'have'},
    'breakfast': {'ru': 'завтрак', 'tg': 'нонушта', 'lemma': 'breakfast'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'cereal': {'ru': 'каша (хлопья)', 'tg': 'ярмаи ғалладона', 'lemma': 'cereal'},
    'usal': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'usally': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'usual': {'ru': 'обычный', 'tg': 'одатӣ', 'lemma': 'usual'},
    'milk': {'ru': 'молоко', 'tg': 'шир', 'lemma': 'milk'},
    'sometimes': {'ru': 'иногда', 'tg': 'баъзан', 'lemma': 'sometimes'},
    'eggs': {'ru': 'яйцо', 'tg': 'тухм', 'lemma': 'egg'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'never': {'ru': 'никогда', 'tg': 'ҳеҷ гоҳ', 'lemma': 'never'},
    'drive': {'ru': 'водить (машину)', 'tg': 'мошин рондан', 'lemma': 'drive'},
    'classes': {'ru': 'занятия', 'tg': 'дарсҳо', 'lemma': 'class'},
    'lunch': {'ru': 'обед', 'tg': 'хӯроки нисфирӯзӣ', 'lemma': 'lunch'},
    'canteen': {'ru': 'столовая', 'tg': 'ошхона', 'lemma': 'canteen'},
    'eat': {'ru': 'есть', 'tg': 'хӯрдан', 'lemma': 'eat'},
    'salad': {'ru': 'салат', 'tg': 'салат', 'lemma': 'salad'},
    'fruit': {'ru': 'фрукт', 'tg': 'мева', 'lemma': 'fruit'},
    'drink': {'ru': 'пить', 'tg': 'нӯшидан', 'lemma': 'drink'},
    'water': {'ru': 'вода', 'tg': 'об', 'lemma': 'water'},
    'library': {'ru': 'библиотека', 'tg': 'китобхона', 'lemma': 'library'},
    'gym': {'ru': 'спортзал', 'tg': 'толори варзишӣ', 'lemma': 'gym'},
    'homework': {'ru': 'домашнее задание', 'tg': 'вазифаи хонагӣ', 'lemma': 'homework'},
    'evening': {'ru': 'вечер', 'tg': 'бегоҳ', 'lemma': 'evening'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'tv': {'ru': 'телевизор', 'tg': 'телевизор', 'lemma': 'TV'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'life': {'ru': 'жизнь', 'tg': 'ҳаёт', 'lemma': 'life'},
    'busy': {'ru': 'занятый', 'tg': 'серкор', 'lemma': 'busy'},
    'happy': {'ru': 'счастливый', 'tg': 'хушбахт', 'lemma': 'happy'},
    'learning': {'ru': 'учиться (узнавать)', 'tg': 'омӯхтан', 'lemma': 'learn'},
    'lot': {'ru': 'много', 'tg': 'бисёр', 'lemma': 'lot'},
    'good': {'ru': 'хороший', 'tg': 'хуб', 'lemma': 'good'},
    'am': BE, 'is': BE, 'was': BE, 'were': BE,
},
38: {
    'weekend': {'ru': 'выходные', 'tg': 'рӯзи истироҳат', 'lemma': 'weekend'},
    'usually': {'ru': 'обычно', 'tg': 'одатан', 'lemma': 'usually'},
    'go': {'ru': 'идти', 'tg': 'рафтан', 'lemma': 'go'},
    'friends': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'friend': {'ru': 'друг', 'tg': 'дӯст', 'lemma': 'friend'},
    'often': {'ru': 'часто', 'tg': 'аксар вақт', 'lemma': 'often'},
    'cinema': {'ru': 'кинотеатр', 'tg': 'кинотеатр', 'lemma': 'cinema'},
    'love': {'ru': 'любить', 'tg': 'дӯст доштан', 'lemma': 'love'},
    'action': {'ru': 'боевик (тж. действие)', 'tg': 'филми ҷангӣ', 'lemma': 'action'},
    'films': {'ru': 'фильм', 'tg': 'филм', 'lemma': 'film'},
    'hates': {'ru': 'ненавидеть', 'tg': 'нафрат доштан', 'lemma': 'hate'},
    'says': {'ru': 'говорить', 'tg': 'гуфтан', 'lemma': 'say'},
    "don't": {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'don': {'ru': 'делать', 'tg': 'кардан', 'lemma': 'do'},
    'watch': {'ru': 'смотреть', 'tg': 'тамошо кардан', 'lemma': 'watch'},
    'awful': {'ru': 'ужасный', 'tg': 'даҳшатнок', 'lemma': 'awful'},
    'quiet': {'ru': 'тихий', 'tg': 'ором', 'lemma': 'quiet'},
    'like': {'ru': 'нравиться', 'tg': 'писанд омадан', 'lemma': 'like'},
    'horror': {'ru': 'ужас', 'tg': 'даҳшат', 'lemma': 'horror'},
    'no': {'ru': 'нет', 'tg': 'не', 'lemma': 'no'},
    'prefer': {'ru': 'предпочитать', 'tg': 'афзал донистан', 'lemma': 'prefer'},
    'comedies': {'ru': 'комедия', 'tg': 'комедия', 'lemma': 'comedy'},
    'lets': {'ru': 'давай(те)', 'tg': 'биёед', 'lemma': 'let'},
    'theatre': {'ru': 'театр', 'tg': 'театр', 'lemma': 'theatre'},
    'ok': {'ru': 'хорошо', 'tg': 'хуб', 'lemma': 'okay'},
    'late': {'ru': 'поздний (опоздавший)', 'tg': 'дер', 'lemma': 'late'},
    'Saturday': {'ru': 'суббота', 'tg': 'шанбе', 'lemma': 'Saturday'},
    'meet': {'ru': 'встречаться', 'tg': 'вохӯрдан', 'lemma': 'meet'},
    'bus': {'ru': 'автобус', 'tg': 'автобус', 'lemma': 'bus'},
    'worry': {'ru': 'беспокоиться', 'tg': 'ташвиш кашидан', 'lemma': 'worry'},
    'sit': {'ru': 'садиться', 'tg': 'нишастан', 'lemma': 'sit'},
    'can': {'ru': 'мочь', 'tg': 'тавонистан', 'lemma': 'can'},
    'tomorrow': {'ru': 'завтра', 'tg': 'фардо', 'lemma': 'tomorrow'},
    'want': {'ru': 'хотеть', 'tg': 'хостан', 'lemma': 'want'},
    'today': {'ru': 'сегодня', 'tg': 'имрӯз', 'lemma': 'today'},
    'please': {'ru': 'пожалуйста', 'tg': 'лутфан', 'lemma': 'please'},
    'cry': {'ru': 'плакать', 'tg': 'гиря кардан', 'lemma': 'cry'},
    'buy': {'ru': 'покупать', 'tg': 'харидан', 'lemma': 'buy'},
    'ticket': {'ru': 'билет', 'tg': 'билет', 'lemma': 'ticket'},
    'remember': {'ru': 'помнить', 'tg': 'дар ёд доштан', 'lemma': 'remember'},
    'actor': {'ru': 'актёр', 'tg': 'актёр', 'lemma': 'actor'},
    'name': {'ru': 'имя', 'tg': 'ном', 'lemma': 'name'},
    'help': {'ru': 'помогать', 'tg': 'кӯмак кардан', 'lemma': 'help'},
    'look': {'ru': 'смотреть', 'tg': 'нигоҳ кардан', 'lemma': 'look'},
    'famous': {'ru': 'известный', 'tg': 'машҳур', 'lemma': 'famous'},
    'great': {'ru': 'отличный', 'tg': 'олӣ', 'lemma': 'great'},
    'wonderful': {'ru': 'чудесный', 'tg': 'аҷиб', 'lemma': 'wonderful'},
    'time': {'ru': 'время', 'tg': 'вақт', 'lemma': 'time'},
    'be': BE, 'is': BE, 'he': {'ru': 'он', 'tg': 'ӯ', 'lemma': 'he'},
    'my': {'ru': 'мой', 'tg': 'аз они ман', 'lemma': 'my'},
    'we': {'ru': 'мы', 'tg': 'мо', 'lemma': 'we'},
    'them': {'ru': 'их', 'tg': 'онҳоро', 'lemma': 'they'},
},
}


async def main():
    async with AsyncSessionLocal() as db:
        rows = (await db.execute(select(Stories).where(Stories.id.in_(DICTS.keys())))).scalars().all()
        for story in rows:
            story.word_dictionary = DICTS[story.id]
            flag_modified(story, 'word_dictionary')
            db.add(story)
            print(f'story {story.id}: replaced with {len(DICTS[story.id])} hand-written entries')
        await db.commit()
        print('done')


if __name__ == '__main__':
    asyncio.run(main())
