# Generated by Django 5.2.16 on 2026-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_backup_codes_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
    ]
