# Generated by Django 5.2.16 on 2026-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_totp_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_username_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
