"""add story exercise models

Revision ID: 0347c6bf9b67
Revises: 67c51516ffa5
Create Date: 2026-07-29 19:44:02.546151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0347c6bf9b67'
down_revision: Union[str, Sequence[str], None] = '67c51516ffa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_exercises_story_id'), 'story_exercises', ['story_id'], unique=False)
    op.create_table('story_exercise_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['story_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_exercise_attempts_exercise_id'), 'story_exercise_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_story_exercise_attempts_user_id'), 'story_exercise_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_exercise_attempts_user_id'), table_name='story_exercise_attempts')
    op.drop_index(op.f('ix_story_exercise_attempts_exercise_id'), table_name='story_exercise_attempts')
    op.drop_table('story_exercise_attempts')
    op.drop_index(op.f('ix_story_exercises_story_id'), table_name='story_exercises')
    op.drop_table('story_exercises')
    # ### end Alembic commands ###
