"""add word_dictionary to user_stories

Revision ID: 1069b9d80247
Revises: f8402419288e
Create Date: 2026-08-07 15:38:07.134193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1069b9d80247'
down_revision: Union[str, Sequence[str], None] = 'f8402419288e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stories', sa.Column('word_dictionary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stories', 'word_dictionary')
    # ### end Alembic commands ###
