"""add source key to content

Revision ID: 1eaf75015e96
Revises: dc071e6cdb6a
Create Date: 2026-07-31 05:33:54.631798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf75015e96'
down_revision: Union[str, Sequence[str], None] = 'dc071e6cdb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grammar_lessons', sa.Column('source_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_grammar_lessons_source_key'), 'grammar_lessons', ['source_key'], unique=True)
    op.add_column('stories', sa.Column('source_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_stories_source_key'), 'stories', ['source_key'], unique=True)
    op.add_column('vocab_entries', sa.Column('source_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_vocab_entries_source_key'), 'vocab_entries', ['source_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_entries_source_key'), table_name='vocab_entries')
    op.drop_column('vocab_entries', 'source_key')
    op.drop_index(op.f('ix_stories_source_key'), table_name='stories')
    op.drop_column('stories', 'source_key')
    op.drop_index(op.f('ix_grammar_lessons_source_key'), table_name='grammar_lessons')
    op.drop_column('grammar_lessons', 'source_key')
    # ### end Alembic commands ###
