"""add adaptive course models

Revision ID: 26d814e01d11
Revises: 1069b9d80247
Create Date: 2026-08-07 18:54:09.078310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26d814e01d11'
down_revision: Union[str, Sequence[str], None] = '1069b9d80247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cefr_level', 'test_type', name='uq_level_test')
    )
    op.create_table('course_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_code', sa.String(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('source_unit_number', sa.Integer(), nullable=False),
    sa.Column('theme_title', sa.String(), nullable=False),
    sa.Column('grammar_topic_label', sa.String(), nullable=True),
    sa.Column('grammar_lesson_id', sa.Integer(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('is_level_midpoint', sa.Boolean(), nullable=False),
    sa.Column('is_level_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_lesson_id'], ['grammar_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_units_cefr_level'), 'course_units', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_course_units_sequence_index'), 'course_units', ['sequence_index'], unique=True)
    op.create_table('level_test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_test_id', sa.Integer(), nullable=False),
    sa.Column('questions_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['level_test_id'], ['level_tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_test_attempts_level_test_id'), 'level_test_attempts', ['level_test_id'], unique=False)
    op.create_index(op.f('ix_level_test_attempts_user_id'), 'level_test_attempts', ['user_id'], unique=False)
    op.create_table('atom_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_unit_id', sa.Integer(), nullable=False),
    sa.Column('atom_type', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_unit_id', 'atom_type', name='uq_atom_completion')
    )
    op.create_index(op.f('ix_atom_completions_course_unit_id'), 'atom_completions', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_atom_completions_user_id'), 'atom_completions', ['user_id'], unique=False)
    op.create_table('course_unit_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_unit_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_unit_id', 'story_id', name='uq_course_unit_story')
    )
    op.create_index(op.f('ix_course_unit_stories_course_unit_id'), 'course_unit_stories', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_course_unit_stories_story_id'), 'course_unit_stories', ['story_id'], unique=False)
    op.create_table('course_unit_vocab',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_unit_id', sa.Integer(), nullable=False),
    sa.Column('vocab_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_unit_id'], ['course_units.id'], ),
    sa.ForeignKeyConstraint(['vocab_entry_id'], ['vocab_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_unit_id', 'vocab_entry_id', name='uq_course_unit_vocab')
    )
    op.create_index(op.f('ix_course_unit_vocab_course_unit_id'), 'course_unit_vocab', ['course_unit_id'], unique=False)
    op.create_index(op.f('ix_course_unit_vocab_vocab_entry_id'), 'course_unit_vocab', ['vocab_entry_id'], unique=False)
    op.create_table('user_course_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('daily_minutes_budget', sa.Integer(), nullable=True),
    sa.Column('days_per_week_target', sa.Integer(), nullable=True),
    sa.Column('current_unit_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pace_recalc_suggested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_unit_id'], ['course_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_course_progress_user_id'), 'user_course_progress', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_course_progress_user_id'), table_name='user_course_progress')
    op.drop_table('user_course_progress')
    op.drop_index(op.f('ix_course_unit_vocab_vocab_entry_id'), table_name='course_unit_vocab')
    op.drop_index(op.f('ix_course_unit_vocab_course_unit_id'), table_name='course_unit_vocab')
    op.drop_table('course_unit_vocab')
    op.drop_index(op.f('ix_course_unit_stories_story_id'), table_name='course_unit_stories')
    op.drop_index(op.f('ix_course_unit_stories_course_unit_id'), table_name='course_unit_stories')
    op.drop_table('course_unit_stories')
    op.drop_index(op.f('ix_atom_completions_user_id'), table_name='atom_completions')
    op.drop_index(op.f('ix_atom_completions_course_unit_id'), table_name='atom_completions')
    op.drop_table('atom_completions')
    op.drop_index(op.f('ix_level_test_attempts_user_id'), table_name='level_test_attempts')
    op.drop_index(op.f('ix_level_test_attempts_level_test_id'), table_name='level_test_attempts')
    op.drop_table('level_test_attempts')
    op.drop_index(op.f('ix_course_units_sequence_index'), table_name='course_units')
    op.drop_index(op.f('ix_course_units_cefr_level'), table_name='course_units')
    op.drop_table('course_units')
    op.drop_table('level_tests')
    # ### end Alembic commands ###
