"""add services books and subscription privacy

Revision ID: 3411391742ef
Revises: bbcb2db23bff
Create Date: 2026-08-14 22:09:36.760115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3411391742ef'
down_revision: Union[str, Sequence[str], None] = 'bbcb2db23bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_privacy', sa.Column('show_services', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('profile_privacy', sa.Column('show_books', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('profile_privacy', sa.Column('show_subscription', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_privacy', 'show_subscription')
    op.drop_column('profile_privacy', 'show_books')
    op.drop_column('profile_privacy', 'show_services')
    # ### end Alembic commands ###
