"""add telegram account linking

Revision ID: 4a4a254f2b2c
Revises: 693f2f124566
Create Date: 2026-07-30 12:48:30.977626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4a254f2b2c'
down_revision: Union[str, Sequence[str], None] = '693f2f124566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'telegram_chat_id')
    # ### end Alembic commands ###
