"""add encouragement to chat_messages

Revision ID: 54191a318345
Revises: 5dda06a07dc8
Create Date: 2026-08-05 16:05:25.744358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54191a318345'
down_revision: Union[str, Sequence[str], None] = '5dda06a07dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('encouragement', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'encouragement')
    # ### end Alembic commands ###
