"""add dc card payment gateway orders and payment logs

Revision ID: 570e3c87eb60
Revises: 72ac22f958a1
Create Date: 2026-08-15 14:38:49.568834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570e3c87eb60'
down_revision: Union[str, Sequence[str], None] = '72ac22f958a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dc_orders_expected_amount'), 'dc_orders', ['expected_amount'], unique=False)
    op.create_index(op.f('ix_dc_orders_expires_at'), 'dc_orders', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dc_orders_user_id'), 'dc_orders', ['user_id'], unique=False)
    op.create_table('dc_payment_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('parsed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_incoming', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['dc_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dc_payment_logs')
    op.drop_index(op.f('ix_dc_orders_user_id'), table_name='dc_orders')
    op.drop_index(op.f('ix_dc_orders_expires_at'), table_name='dc_orders')
    op.drop_index(op.f('ix_dc_orders_expected_amount'), table_name='dc_orders')
    op.drop_table('dc_orders')
    # ### end Alembic commands ###
