"""create content tables

Revision ID: 5b55682f0883
Revises: 5d59f9cf8c02
Create Date: 2026-07-29 13:57:35.501679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b55682f0883'
down_revision: Union[str, Sequence[str], None] = '5d59f9cf8c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('lesson', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('rule_en', sa.String(), nullable=True),
    sa.Column('rule_ru', sa.String(), nullable=True),
    sa.Column('rule_tg', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('tip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_lessons_cefr_level'), 'grammar_lessons', ['cefr_level'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_tg', sa.String(), nullable=True),
    sa.Column('body_en', sa.String(), nullable=False),
    sa.Column('body_ru', sa.String(), nullable=True),
    sa.Column('body_tg', sa.String(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('grammar_topic', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_cefr_level'), 'stories', ['cefr_level'], unique=False)
    op.create_table('vocab_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('example_en', sa.String(), nullable=True),
    sa.Column('translation_ru', sa.String(), nullable=True),
    sa.Column('translation_tg', sa.String(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_entries_cefr_level'), 'vocab_entries', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_vocab_entries_word'), 'vocab_entries', ['word'], unique=False)
    op.create_table('grammar_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['grammar_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_examples_lesson_id'), 'grammar_examples', ['lesson_id'], unique=False)
    op.create_table('grammar_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text_en', sa.String(), nullable=True),
    sa.Column('text_ru', sa.String(), nullable=True),
    sa.Column('text_tg', sa.String(), nullable=True),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('explanation_en', sa.String(), nullable=True),
    sa.Column('explanation_ru', sa.String(), nullable=True),
    sa.Column('explanation_tg', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['grammar_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_questions_lesson_id'), 'grammar_questions', ['lesson_id'], unique=False)
    op.create_table('story_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_questions_story_id'), 'story_questions', ['story_id'], unique=False)
    op.create_table('story_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation_ru', sa.String(), nullable=True),
    sa.Column('translation_tg', sa.String(), nullable=True),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_words_story_id'), 'story_words', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_words_story_id'), table_name='story_words')
    op.drop_table('story_words')
    op.drop_index(op.f('ix_story_questions_story_id'), table_name='story_questions')
    op.drop_table('story_questions')
    op.drop_index(op.f('ix_grammar_questions_lesson_id'), table_name='grammar_questions')
    op.drop_table('grammar_questions')
    op.drop_index(op.f('ix_grammar_examples_lesson_id'), table_name='grammar_examples')
    op.drop_table('grammar_examples')
    op.drop_index(op.f('ix_vocab_entries_word'), table_name='vocab_entries')
    op.drop_index(op.f('ix_vocab_entries_cefr_level'), table_name='vocab_entries')
    op.drop_table('vocab_entries')
    op.drop_index(op.f('ix_stories_cefr_level'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_grammar_lessons_cefr_level'), table_name='grammar_lessons')
    op.drop_table('grammar_lessons')
    # ### end Alembic commands ###
