"""add level and native_language to chat_sessions

Revision ID: 5dda06a07dc8
Revises: 6f29520e2ffb
Create Date: 2026-08-05 16:04:36.650781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dda06a07dc8'
down_revision: Union[str, Sequence[str], None] = '6f29520e2ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('level', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('native_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'native_language')
    op.drop_column('chat_sessions', 'level')
    # ### end Alembic commands ###
