"""add granular profile privacy settings

Revision ID: 5ff1cd938342
Revises: 25fbdf417bc9
Create Date: 2026-07-29 13:33:59.912557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff1cd938342'
down_revision: Union[str, Sequence[str], None] = '25fbdf417bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_privacy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('show_stories_count', sa.Boolean(), nullable=False),
    sa.Column('show_achievements', sa.Boolean(), nullable=False),
    sa.Column('show_current_streak', sa.Boolean(), nullable=False),
    sa.Column('show_best_streak', sa.Boolean(), nullable=False),
    sa.Column('show_languages', sa.Boolean(), nullable=False),
    sa.Column('show_language_levels', sa.Boolean(), nullable=False),
    sa.Column('show_followers', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_privacy_user_id'), 'profile_privacy', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_privacy_user_id'), table_name='profile_privacy')
    op.drop_table('profile_privacy')
    # ### end Alembic commands ###
