"""add user story models

Revision ID: 67c51516ffa5
Revises: 99c151ebb66d
Create Date: 2026-07-29 19:40:16.948678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c51516ffa5'
down_revision: Union[str, Sequence[str], None] = '99c151ebb66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cefr_level', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stories_author_id'), 'user_stories', ['author_id'], unique=False)
    op.create_table('story_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'buyer_id', name='uq_story_purchases_pair')
    )
    op.create_index(op.f('ix_story_purchases_buyer_id'), 'story_purchases', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_story_purchases_story_id'), 'story_purchases', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_purchases_story_id'), table_name='story_purchases')
    op.drop_index(op.f('ix_story_purchases_buyer_id'), table_name='story_purchases')
    op.drop_table('story_purchases')
    op.drop_index(op.f('ix_user_stories_author_id'), table_name='user_stories')
    op.drop_table('user_stories')
    # ### end Alembic commands ###
