"""add long-form grammar lesson explanations

Revision ID: 72ac22f958a1
Revises: d77df0cb56c8
Create Date: 2026-08-15 11:15:50.902655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ac22f958a1'
down_revision: Union[str, Sequence[str], None] = 'd77df0cb56c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grammar_lessons', sa.Column('explanation_long_en', sa.String(), nullable=True))
    op.add_column('grammar_lessons', sa.Column('explanation_long_ru', sa.String(), nullable=True))
    op.add_column('grammar_lessons', sa.Column('explanation_long_tg', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grammar_lessons', 'explanation_long_tg')
    op.drop_column('grammar_lessons', 'explanation_long_ru')
    op.drop_column('grammar_lessons', 'explanation_long_en')
    # ### end Alembic commands ###
