"""add stripe event id to purchases

Revision ID: 72bbed931665
Revises: 1eaf75015e96
Create Date: 2026-07-31 21:43:44.253483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72bbed931665'
down_revision: Union[str, Sequence[str], None] = '1eaf75015e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('stripe_event_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_purchases_stripe_event_id', 'purchases', ['stripe_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_purchases_stripe_event_id', 'purchases', type_='unique')
    op.drop_column('purchases', 'stripe_event_id')
    # ### end Alembic commands ###
