"""add lingo marketplace tables

Revision ID: 7706aa499df4
Revises: 54191a318345
Create Date: 2026-08-07 12:02:38.282682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7706aa499df4'
down_revision: Union[str, Sequence[str], None] = '54191a318345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lingo_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pricing_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lingo_services_provider_id'), 'lingo_services', ['provider_id'], unique=False)
    op.create_table('lingo_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['lingo_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lingo_proposals_client_id'), 'lingo_proposals', ['client_id'], unique=False)
    op.create_index(op.f('ix_lingo_proposals_provider_id'), 'lingo_proposals', ['provider_id'], unique=False)
    op.create_index(op.f('ix_lingo_proposals_service_id'), 'lingo_proposals', ['service_id'], unique=False)
    op.create_table('lingo_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['lingo_proposals.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lingo_messages_proposal_id'), 'lingo_messages', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_lingo_messages_sender_id'), 'lingo_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lingo_messages_sender_id'), table_name='lingo_messages')
    op.drop_index(op.f('ix_lingo_messages_proposal_id'), table_name='lingo_messages')
    op.drop_table('lingo_messages')
    op.drop_index(op.f('ix_lingo_proposals_service_id'), table_name='lingo_proposals')
    op.drop_index(op.f('ix_lingo_proposals_provider_id'), table_name='lingo_proposals')
    op.drop_index(op.f('ix_lingo_proposals_client_id'), table_name='lingo_proposals')
    op.drop_table('lingo_proposals')
    op.drop_index(op.f('ix_lingo_services_provider_id'), table_name='lingo_services')
    op.drop_table('lingo_services')
    # ### end Alembic commands ###
