"""add streak restore columns

Revision ID: 99d440b6eb95
Revises: 3f9d0a1b7c4e
Create Date: 2026-08-17 16:30:22.576662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d440b6eb95'
down_revision: Union[str, Sequence[str], None] = '3f9d0a1b7c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_streaks', sa.Column('restores_used_this_month', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_streaks', sa.Column('last_restore_month', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_streaks', 'last_restore_month')
    op.drop_column('user_streaks', 'restores_used_this_month')
    # ### end Alembic commands ###
