"""add telegram columns to settings

Revision ID: bbcb2db23bff
Revises: 1d75ba237819
Create Date: 2026-08-14 21:08:21.447375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcb2db23bff'
down_revision: Union[str, Sequence[str], None] = '1d75ba237819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('telegram_language', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('telegram_sm2_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'telegram_sm2_enabled')
    op.drop_column('user_settings', 'telegram_language')
    # ### end Alembic commands ###
