"""add grammar attempts table

Revision ID: c59b7aee38a3
Revises: 5b55682f0883
Create Date: 2026-07-29 14:03:05.479658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59b7aee38a3'
down_revision: Union[str, Sequence[str], None] = '5b55682f0883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['grammar_questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_attempts_question_id'), 'grammar_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_grammar_attempts_user_id'), 'grammar_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_attempts_user_id'), table_name='grammar_attempts')
    op.drop_index(op.f('ix_grammar_attempts_question_id'), table_name='grammar_attempts')
    op.drop_table('grammar_attempts')
    # ### end Alembic commands ###
