"""add prev_streak_before_reset column

Revision ID: cd31aa04dbe8
Revises: 99d440b6eb95
Create Date: 2026-08-17 16:57:24.599471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd31aa04dbe8'
down_revision: Union[str, Sequence[str], None] = '99d440b6eb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_streaks', sa.Column('prev_streak_before_reset', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_streaks', 'prev_streak_before_reset')
    # ### end Alembic commands ###
