"""add generated_stories_per_day

Revision ID: d77df0cb56c8
Revises: 3411391742ef
Create Date: 2026-08-15 00:19:14.037809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77df0cb56c8'
down_revision: Union[str, Sequence[str], None] = '3411391742ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('word_dictionary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cefr_levels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('approx_word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_stories_user_id'), 'generated_stories', ['user_id'], unique=False)
    op.create_table('vocab_size_test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('items_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('by_level', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estimated_total', sa.Integer(), nullable=True),
    sa.Column('confirmed_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_size_test_attempts_user_id'), 'vocab_size_test_attempts', ['user_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('context_type', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('context_ref_id', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('generated_stories_per_day', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('estimated_vocabulary_size', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('vocabulary_estimated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'vocabulary_estimated_at')
    op.drop_column('user_profiles', 'estimated_vocabulary_size')
    op.drop_column('plans', 'generated_stories_per_day')
    op.drop_column('chat_sessions', 'context_ref_id')
    op.drop_column('chat_sessions', 'context_type')
    op.drop_index(op.f('ix_vocab_size_test_attempts_user_id'), table_name='vocab_size_test_attempts')
    op.drop_table('vocab_size_test_attempts')
    op.drop_index(op.f('ix_generated_stories_user_id'), table_name='generated_stories')
    op.drop_table('generated_stories')
    # ### end Alembic commands ###
