"""add story reviews and ratings

Revision ID: ef91a7f8e815
Revises: 0347c6bf9b67
Create Date: 2026-07-29 20:13:56.394419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef91a7f8e815'
down_revision: Union[str, Sequence[str], None] = '0347c6bf9b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_id', name='uq_story_reviews_pair')
    )
    op.create_index(op.f('ix_story_reviews_story_id'), 'story_reviews', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_reviews_user_id'), 'story_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_reviews_user_id'), table_name='story_reviews')
    op.drop_index(op.f('ix_story_reviews_story_id'), table_name='story_reviews')
    op.drop_table('story_reviews')
    # ### end Alembic commands ###
