"""add notified columns to cards

Revision ID: f152e414b6a1
Revises: fee7f86416ed
Create Date: 2026-08-10 18:54:16.503482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f152e414b6a1'
down_revision: Union[str, Sequence[str], None] = 'fee7f86416ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('cards', sa.Column('day_before_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('cards', sa.Column('hour_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('cards', sa.Column('due_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('lingo_proposals', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'TJS'::character varying"))
    op.alter_column('lingo_services', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'TJS'::character varying"))
    op.alter_column('practice_test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('unit_test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('word_transcriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('word_transcriptions_word_key'), 'word_transcriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('word_transcriptions_word_key'), 'word_transcriptions', ['word'], postgresql_nulls_not_distinct=False)
    op.alter_column('word_transcriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('unit_test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('practice_test_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lingo_services', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'TJS'::character varying"))
    op.alter_column('lingo_proposals', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'TJS'::character varying"))
    op.drop_column('cards', 'due_notified')
    op.drop_column('cards', 'hour_notified')
    op.drop_column('cards', 'day_before_notified')
    # ### end Alembic commands ###
