"""add word_audio, story_listens, audio columns for TTS narration

Revision ID: f680ea5c5a00
Revises: f152e414b6a1
Create Date: 2026-08-13 23:07:02.684200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f680ea5c5a00'
down_revision: Union[str, Sequence[str], None] = 'f152e414b6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_audio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('accent', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'accent', name='uq_word_audio_word_accent')
    )
    op.create_index(op.f('ix_word_audio_word'), 'word_audio', ['word'], unique=False)
    op.create_table('story_listens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('listened_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'story_id', 'listened_on', name='uq_story_listens_user_story_day')
    )
    op.create_index(op.f('ix_story_listens_story_id'), 'story_listens', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_listens_user_id'), 'story_listens', ['user_id'], unique=False)
    op.add_column('cards', sa.Column('accent', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('audiobooks_per_day', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('accent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'accent')
    op.drop_column('stories', 'audio_url')
    op.drop_column('plans', 'audiobooks_per_day')
    op.drop_column('cards', 'accent')
    op.drop_index(op.f('ix_story_listens_user_id'), table_name='story_listens')
    op.drop_index(op.f('ix_story_listens_story_id'), table_name='story_listens')
    op.drop_table('story_listens')
    op.drop_index(op.f('ix_word_audio_word'), table_name='word_audio')
    op.drop_table('word_audio')
    # ### end Alembic commands ###
