"""add cefr_level to lingo_services

Revision ID: f8402419288e
Revises: 7706aa499df4
Create Date: 2026-08-07 12:03:39.831163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8402419288e'
down_revision: Union[str, Sequence[str], None] = '7706aa499df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lingo_services', sa.Column('cefr_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lingo_services', 'cefr_level')
    # ### end Alembic commands ###
