FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -m appuser
USER appuser

WORKDIR /app/auth_service

EXPOSE 8001

CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
