import asyncio
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select

from app.db.database import AsyncSessionLocal
from app.models.model_content import GrammarExamples, GrammarLessons, GrammarQuestions

# Topic areas from Teaching/Grammars of Levels.md, "C1 to C2" section, expanded to 18
# lessons (9 unit groups x A/B) at the same density as the existing A1-C1 content.
LESSONS = [
    {
        'unit': '1', 'lesson': '1A', 'topic': 'hedging and precision modality',
        'rule_en': "Advanced modals and hedging expressions let you commit to a claim with exactly the right degree of certainty, from near-certainty ('is bound to', 'must') to cautious speculation ('might well', 'could conceivably'). Bare 'I think' sounds vague in formal writing; precise hedges show you have weighed the evidence.",
        'rule_ru': "Продвинутые модальные и смягчающие конструкции позволяют выразить точную степень уверенности — от почти полной ('is bound to', 'must') до осторожного предположения ('might well', 'could conceivably'). Простое 'I think' звучит расплывчато в формальном тексте; точные хеджи показывают, что вы взвесили аргументы.",
        'rule_tg': "Модалҳо ва иборахои таъхидии пешрафта имкон медиҳанд, ки дараҷаи дурустии даъвои шумо аниқ ифода шавад — аз боварии қариб пурра ('is bound to', 'must') то тахмини эҳтиётона ('might well', 'could conceivably'). 'I think'-и оддӣ дар матни расмӣ норавшан садо медиҳад.",
        'structure': "Subject + modal/hedge + verb: is bound to / might well / could conceivably / is unlikely to + infinitive",
        'tip': "'Might well' is stronger than plain 'might' — it signals you find the possibility quite likely, not just conceivable.",
        'examples': [
            "Given the delays, the project is bound to go over budget.",
            "She might well be right about the merger.",
            "The results could conceivably be explained by chance alone.",
            "He is unlikely to admit his mistake in public.",
        ],
        'questions': [
            ("Choose the strongest expression of certainty: The bridge ___ collapse if nothing is done.",
             ['is bound to', 'might', 'could conceivably'], 'is bound to',
             "'Is bound to' expresses near-certainty, stronger than 'might' or 'could conceivably'."),
            ("Choose the most cautious hedge: The data ___ suggest a different explanation, though it's far from certain.",
             ['could conceivably', 'is bound to', 'definitely will'], 'could conceivably',
             "'Could conceivably' hedges a claim as barely possible, the most tentative option here."),
            ("'She ___ well be the best candidate we've seen.' Complete with the correct hedge.",
             ['might', 'could', 'would'], 'might',
             "'Might well' is a fixed collocation for a fairly confident guess; 'could well'/'would well' aren't standard here."),
            ("Choose the correct paraphrase of 'He is unlikely to change his mind.'",
             ["It's improbable that he'll change his mind.", "It's certain he'll change his mind.", "He refuses to change his mind."],
             "It's improbable that he'll change his mind.",
             "'Unlikely to' expresses low probability, matching 'improbable that'."),
            ("Which sentence correctly hedges a claim about the past?",
             ['The delay may well have been caused by a technical fault.', 'The delay is bound to be a technical fault.', 'The delay could conceivably a technical fault.'],
             'The delay may well have been caused by a technical fault.',
             "'May well have been' is the correct modal-perfect form for a past possibility; the third option is missing 'been'."),
        ],
    },
    {
        'unit': '1', 'lesson': '1B', 'topic': 'subtle tense shifts: historic present & free indirect style',
        'rule_en': "The historic present narrates past events as if happening now, for immediacy ('So I open the door, and there he is'). Free indirect style blends a character's voice into third-person narration without a reporting verb or quotation marks, keeping their tense and perspective but dropping 'she thought that'.",
        'rule_ru': "Историческое настоящее время повествует о прошлых событиях так, будто они происходят сейчас, для эффекта живости ('So I open the door, and there he is'). Свободный косвенный стиль передаёт голос персонажа в повествовании от третьего лица без глагола сообщения и кавычек, сохраняя его время и точку зрения, но опуская 'she thought that'.",
        'rule_tg': "Замони ҳозираи таърихӣ воқеаҳои гузаштаро гӯё ҳозир рӯй медиҳанд, нақл мекунад ('So I open the door, and there he is'). Услуби бавоситаи озод овози персонажро дар нақли шахси сеюм бе феъли гуфтан ва нохунак интиқол медиҳад.",
        'structure': "historic present: simple present for past narration; free indirect: third person + past tense, no reporting clause",
        'tip': "Historic present is common in spoken anecdotes and journalism; free indirect style is a literary device — don't mix them in formal writing.",
        'examples': [
            "I'm walking home last night when suddenly this car pulls up beside me.",
            "She stared at the letter. Why had he never told her?",
            'Reporters often switch to the present tense for effect: "The minister enters, visibly shaken."',
            "He wondered whether he would ever see her again — he'd give anything to know.",
        ],
        'questions': [
            ("Identify the historic-present sentence.",
             ['So I walk into the room and everyone stops talking.', 'So I walked into the room and everyone stopped talking.', 'So I have walked into the room.'],
             'So I walk into the room and everyone stops talking.',
             "The historic present uses simple present tense to narrate a past event vividly."),
            ("Which sentence uses free indirect style?",
             ['Would he ever forgive her? She doubted it.', 'She wondered if he would ever forgive her.', '"Will he ever forgive me?" she asked.'],
             'Would he ever forgive her? She doubted it.',
             "Free indirect style presents the character's thought directly, without a reporting verb like 'she wondered'."),
            ("Historic present is most typical in:",
             ['spoken anecdotes and live commentary', 'formal academic essays', 'legal contracts'],
             'spoken anecdotes and live commentary',
             "The historic present creates immediacy, common in storytelling and commentary, not formal writing."),
            ("Choose the free indirect version of 'She thought that she would never finish.'",
             ['Would she ever finish?', 'She thinks she will never finish.', '"I will never finish," she thought.'],
             'Would she ever finish?',
             "Free indirect style removes the reporting clause and turns the thought into the character's own voice."),
            ("Choose the correctly formed historic-present narration.",
             ['Yesterday, he tells me the whole story.', 'Yesterday, he told me the whole story.', 'Yesterday, he telling me the whole story.'],
             'Yesterday, he tells me the whole story.',
             "Despite the past time marker 'yesterday', historic present keeps the verb in the simple present for dramatic effect."),
        ],
    },
    {
        'unit': '2', 'lesson': '2A', 'topic': 'complex noun phrases',
        'rule_en': "Formal written English often packs information into a single noun phrase using multiple pre-modifiers (adjectives, nouns as modifiers) before the head noun, and post-modifiers (relative clauses, prepositional phrases, participle clauses) after it, instead of several short sentences.",
        'rule_ru': "Формальный письменный английский часто вмещает информацию в одну именную группу, используя несколько препозитивных определений (прилагательные, существительные в роли определения) перед главным существительным и постпозитивных определений (относительные придаточные, предложные обороты, причастные обороты) после него, вместо нескольких коротких предложений.",
        'rule_tg': "Забони расмии хаттӣ аксар вақт иттилоотро дар як гурӯҳи исмӣ ҷамъ мекунад — бо якчанд муайянкунандаи пеш аз исми асосӣ ва муайянкунандаи баъд аз он (ҷумлаи нисбӣ, ибораи пешояндӣ, ибораи сифати феълӣ) ба ҷои якчанд ҷумлаи кӯтоҳ.",
        'structure': "(determiner) + pre-modifiers + head noun + post-modifiers",
        'tip': "Reading a complex noun phrase aloud slowly, pausing at the head noun, usually reveals its structure quickly.",
        'examples': [
            "The recently published, peer-reviewed report on climate migration patterns in coastal regions has drawn wide attention.",
            "A previously unknown, remarkably well-preserved manuscript was discovered last month.",
            "The government's long-delayed decision to raise the minimum wage surprised economists.",
            "Employees working under high-pressure deadlines report significantly higher stress levels.",
        ],
        'questions': [
            ("Identify the head noun in 'the recently published, peer-reviewed report on climate migration'.",
             ['report', 'climate', 'migration'], 'report',
             "'Report' is the head noun; everything else pre- or post-modifies it."),
            ("Which sentence uses a complex noun phrase correctly?",
             ['The long-awaited, critically acclaimed film finally opened.', 'The film long-awaited critically acclaimed finally opened.', 'The film that was long-awaited was critically it acclaimed finally opened.'],
             'The long-awaited, critically acclaimed film finally opened.',
             "Pre-modifiers stack directly before the head noun, separated by commas or hyphens as needed."),
            ("Choose the correct post-modifying relative clause for 'the report ___ was published yesterday'.",
             ['which', 'who', 'whom'], 'which',
             "'Which' post-modifies a thing (the report); 'who'/'whom' are for people."),
            ("Which is the most information-dense (most complex) noun phrase?",
             ['a government report', 'the government report', "the government's long-delayed report on housing policy reform"],
             "the government's long-delayed report on housing policy reform",
             "This version stacks a possessive, an adjective, and a post-modifying prepositional phrase — the densest structure."),
            ("Rewrite 'The manuscript was unknown before. It was also well preserved.' as one complex noun phrase.",
             ['a previously unknown, well-preserved manuscript', 'a manuscript unknown previously and it was preserved well', 'the manuscript which unknown and preserved'],
             'a previously unknown, well-preserved manuscript',
             "Both qualities become pre-modifiers stacked before the head noun 'manuscript'."),
        ],
    },
    {
        'unit': '2', 'lesson': '2B', 'topic': 'cleft and pseudo-cleft sentences',
        'rule_en': "A cleft sentence splits one clause into two to focus on a single piece of information: 'It + be + focused element + that/who + rest of clause'. A pseudo-cleft (wh-cleft) instead fronts a wh-clause as subject: 'What/Where/The thing that + clause + be + focus'.",
        'rule_ru': "Cleft-предложение делит одно предложение на два, чтобы выделить одну часть информации: 'It + be + выделяемый элемент + that/who + остальная часть'. Псевдо-cleft (wh-cleft) вместо этого выносит wh-придаточное в позицию подлежащего: 'What/Where + придаточное + be + выделяемый элемент'.",
        'rule_tg': "Ҷумлаи cleft як ҷумларо ба ду ҷудо мекунад, то як қисми иттилоотро таъкид кунад: 'It + be + унсури таъкидшуда + that/who + боқимонда'. Псевдо-cleft (wh-cleft) бошад, ҷумлаи wh-ро ҳамчун мубтадо пеш меорад: 'What + ҷумла + be + унсури таъкидшуда'.",
        'structure': "cleft: It + be + focus + that/who + clause; pseudo-cleft: What/Where + clause + be + focus",
        'tip': "Both structures exist purely for emphasis — the underlying information is identical to the plain sentence.",
        'examples': [
            "It was Maria who first suggested the idea.",
            "It wasn't until midnight that we finally left.",
            "What surprised everyone was how calmly she reacted.",
            "What we need is more time, not more money.",
        ],
        'questions': [
            ("Choose the cleft sentence that focuses on 'Tom' in 'Tom broke the window'.",
             ['It was Tom who broke the window.', 'What Tom broke was the window.', 'Tom, who broke the window.'],
             'It was Tom who broke the window.',
             "The 'It + be + focus + who' pattern is the standard cleft focusing on the agent, Tom."),
            ("Choose the pseudo-cleft version of 'I need more sleep.'",
             ['What I need is more sleep.', 'It is more sleep that I need.', 'More sleep, I need it.'],
             'What I need is more sleep.',
             "The pseudo-cleft fronts a 'What' clause as subject, followed by 'be' and the focused element."),
            ("'It wasn't until she called that ___.' Complete correctly.",
             ['we understood the problem', 'we understand the problem', 'understood we the problem'],
             'we understood the problem',
             "The main clause after a past cleft with 'It wasn't until...that' takes past simple, in normal word order."),
            ("Which sentence is NOT a cleft or pseudo-cleft?",
             ['She left early because she was tired.', 'It was because she was tired that she left early.', 'What made her leave early was tiredness.'],
             'She left early because she was tired.',
             "This is a plain sentence with no fronted focus structure — the other two are cleft/pseudo-cleft versions of it."),
            ("Choose the correctly formed cleft focusing on 'the manager', from 'The manager approved the budget.'",
             ['It was the manager who approved the budget.', 'It was the manager approved the budget.', 'The manager it was who approved the budget.'],
             'It was the manager who approved the budget.',
             "The relative pronoun 'who' is required after the focused person in a cleft sentence."),
        ],
    },
    {
        'unit': '3', 'lesson': '3A', 'topic': 'ellipsis: formal vs informal omission',
        'rule_en': "Ellipsis omits words that are recoverable from context. Informal speech commonly drops subjects and auxiliaries at the start of a question ('Seen him?' = 'Have you seen him?'). Formal writing instead omits a repeated verb in parallel clauses ('She studied law; he, medicine.').",
        'rule_ru': "Эллипсис опускает слова, которые восстанавливаются из контекста. В неформальной речи часто опускаются подлежащее и вспомогательный глагол в начале вопроса ('Seen him?' = 'Have you seen him?'). В формальном письме, напротив, опускается повторяющийся глагол в параллельных предложениях ('She studied law; he, medicine.').",
        'rule_tg': "Эллипсис калимаҳоеро, ки аз матн барқарор мешаванд, партофта мешавад. Дар нутқи ғайрирасмӣ одатан мубтадо ва феъли ёридиҳанда дар аввали савол партофта мешавад ('Seen him?' = 'Have you seen him?'). Дар навиштани расмӣ бошад, феъли такроршаванда дар ҷумлаҳои параллел партофта мешавад.",
        'structure': "informal: (Have you) + past participle...?; formal: clause1, clause2 with shared verb omitted",
        'tip': "Formal ellipsis usually needs a comma where the omitted verb would have been: 'he, medicine' not 'he medicine'.",
        'examples': [
            "(Have you) Finished yet?",
            "(Are you) Coming to the party?",
            "The north wing was renovated in 1990, the south in 2005.",
            "Some praised the decision; others, the courage it took to make it.",
        ],
        'questions': [
            ("What is omitted in the informal question 'Seen him?'",
             ['Have you', 'Did you', 'Will you'], 'Have you',
             "'Seen him?' is short for 'Have you seen him?', with 'Have you' dropped in casual speech."),
            ("Choose the correctly punctuated formal ellipsis.",
             ['She prefers tea; he, coffee.', 'She prefers tea; he coffee.', 'She prefers tea he, coffee.'],
             'She prefers tea; he, coffee.',
             "Formal ellipsis needs both the semicolon between clauses and a comma marking the omitted verb."),
            ("Which sentence uses informal ellipsis?",
             ['Coming?', 'It is coming.', 'The thing that is coming is a storm.'],
             'Coming?',
             "'Coming?' drops the subject and auxiliary ('Are you coming?'), typical of casual spoken English."),
            ("Complete the formal ellipsis: 'The first draft was rejected; the second, ___.'",
             ['approved', 'was approved', 'it was approved'],
             'approved',
             "The repeated verb 'was' is omitted, leaving only the past participle after the comma."),
            ("Which context is formal ellipsis ('he, medicine') most appropriate for?",
             ['an academic essay', 'a text message to a friend', 'a casual phone call'],
             'an academic essay',
             "This structured, parallel omission is a feature of formal written register, not casual speech."),
        ],
    },
    {
        'unit': '3', 'lesson': '3B', 'topic': 'inversion after negative adverbials',
        'rule_en': "Fronting a negative or restrictive adverbial (little, rarely, never, not only, no sooner, under no circumstances) for emphasis triggers subject-auxiliary inversion, exactly as in a question.",
        'rule_ru': "Вынесение отрицательного или ограничительного наречия (little, rarely, never, not only, no sooner, under no circumstances) в начало предложения для эмфазы вызывает инверсию подлежащего и вспомогательного глагола, как в вопросе.",
        'rule_tg': "Пеш овардани зарфи манфӣ ё маҳдудкунанда (little, rarely, never, not only, no sooner, under no circumstances) барои таъкид инверсияи мубтадо ва феъли ёридиҳандаро ба вуҷуд меорад, мисли савол.",
        'structure': "Negative adverbial + aux + subject + verb",
        'tip': "'No sooner...than' and 'hardly...when' are fixed pairs — don't mix them ('no sooner...when' is wrong).",
        'examples': [
            "Little did she know what awaited her.",
            "Not only did he arrive late, but he also forgot the documents.",
            "Rarely have I seen such dedication.",
            "No sooner had we sat down than the phone rang.",
        ],
        'questions': [
            ("Choose the correctly inverted sentence.",
             ['Never have I seen such chaos.', 'Never I have seen such chaos.', 'Never I saw such chaos.'],
             'Never have I seen such chaos.',
             "'Never' at the front triggers auxiliary-subject inversion: 'have I seen', not 'I have seen'."),
            ("Complete: 'Not only ___ the deadline, she also exceeded expectations.'",
             ['did she meet', 'she met', 'she did meet'],
             'did she meet',
             "'Not only' fronted requires inversion with 'did' + subject + base verb."),
            ("Choose the correct fixed pair.",
             ['No sooner had we arrived than it started raining.', 'No sooner had we arrived when it started raining.', 'No sooner we had arrived than it started raining.'],
             'No sooner had we arrived than it started raining.',
             "'No sooner...than' is the fixed pairing; 'when' is used with 'hardly', not 'no sooner'."),
            ("Which sentence correctly uses 'Under no circumstances'?",
             ['Under no circumstances should you sign this.', 'Under no circumstances you should sign this.', 'Under no circumstances you sign this should.'],
             'Under no circumstances should you sign this.',
             "The negative adverbial phrase triggers inversion: 'should you sign', not 'you should sign'."),
            ("Choose the sentence WITHOUT inversion that still means the same as 'Rarely have I seen such skill.'",
             ['I have rarely seen such skill.', 'Rarely I have seen such skill.', 'Have I rarely seen such skill.'],
             'I have rarely seen such skill.',
             "Moving 'rarely' back into normal position removes the need for inversion entirely."),
        ],
    },
    {
        'unit': '4', 'lesson': '4A', 'topic': 'inversion in conditionals without if',
        'rule_en': "In formal English, 'if' can be dropped from conditional clauses that begin with 'had', 'were', or 'should', with the auxiliary or 'were' moving before the subject instead.",
        'rule_ru': "В формальном английском 'if' можно опустить в условных придаточных, начинающихся с 'had', 'were' или 'should', при этом вспомогательный глагол или 'were' перемещается перед подлежащим.",
        'rule_tg': "Дар забони расмии англисӣ, 'if' метавонад аз ҷумлаҳои шартӣ, ки бо 'had', 'were' ё 'should' сар мешаванд, партофта шавад, дар ин ҳолат феъли ёридиҳанда ё 'were' пеш аз мубтадо меояд.",
        'structure': "Had/Were/Should + subject + ..., + main clause",
        'tip': "Only third conditional (had), unreal present (were), and unlikely future (should) allow this — you can't drop 'if' from a zero or real first conditional.",
        'examples': [
            "Had I known, I would have come earlier.",
            "Were she here, she would agree with us.",
            "Should you need anything, just call.",
            "Had they left earlier, they wouldn't have missed the train.",
        ],
        'questions': [
            ("Choose the correct if-less version of 'If I had known, I would have helped.'",
             ['Had I known, I would have helped.', 'Had known I, I would have helped.', 'I had known, would have I helped.'],
             'Had I known, I would have helped.',
             "'Had' moves to the front, before the subject 'I', replacing 'if I had known'."),
            ("Choose the correct if-less version of 'If she were richer, she would travel more.'",
             ['Were she richer, she would travel more.', 'She were richer, would travel more.', 'Were richer she, she would travel more.'],
             'Were she richer, she would travel more.',
             "'Were' fronts before the subject 'she', replacing 'if she were'."),
            ("Which conditional type does NOT allow dropping 'if' this way?",
             ['zero conditional (If water boils, it evaporates.)', 'third conditional (If I had known...)', 'unreal present (If I were you...)'],
             'zero conditional (If water boils, it evaporates.)',
             "If-less inversion only works with 'had', 'were', and 'should' clauses — not zero-conditional 'if + present'."),
            ("Complete: '___ you change your mind, let me know.'",
             ['Should', 'Would', 'Were'], 'Should',
             "'Should you change your mind' is the if-less form of 'If you should change your mind', for an unlikely future."),
            ("Choose the sentence with correct word order.",
             ['Had we arrived on time, we would have caught the flight.', 'We had arrived on time, would have caught the flight.', 'Had arrived we on time, we would have caught the flight.'],
             'Had we arrived on time, we would have caught the flight.',
             "'Had' comes first, then the subject 'we', then the rest of the clause."),
        ],
    },
    {
        'unit': '4', 'lesson': '4B', 'topic': 'register: formal vs informal grammar choices',
        'rule_en': "Register is signalled grammatically as much as through vocabulary: formal English favours full forms, the passive voice, and Latinate verbs ('investigate', 'terminate'); informal English favours contractions, the active voice, and phrasal verbs ('look into', 'end').",
        'rule_ru': "Регистр речи выражается грамматически не меньше, чем лексически: формальный английский предпочитает полные формы, страдательный залог и латинские глаголы ('investigate', 'terminate'); неформальный — сокращения, действительный залог и фразовые глаголы ('look into', 'end').",
        'rule_tg': "Регистр на танҳо бо луғат, балки бо грамматика ҳам ифода мешавад: забони расмӣ шаклҳои пурра, тарзи мафъулӣ ва феълҳои лотинӣ ('investigate')-ро авло медонад; забони ғайрирасмӣ бошад — ихтисорот, тарзи фоилӣ ва феълҳои фразавӣ ('look into')-ро.",
        'structure': "formal: passive/Latinate verb, no contraction; informal: active/phrasal verb, contraction",
        'tip': "Switching mid-text between registers (e.g. 'We shall commence' followed by 'let's get going') reads as inconsistent — pick one register and stay in it.",
        'examples': [
            "The matter will be looked into. (formal) vs We'll look into it. (informal)",
            "The contract was terminated. (formal) vs We ended the contract. (informal)",
            "Applicants are requested to submit documentation by Friday. (formal)",
            "Send your stuff over by Friday, yeah? (informal)",
        ],
        'questions': [
            ("Which sentence is formal register?",
             ['The proposal will be reviewed by the committee.', "We'll get the committee to look at it.", "The committee's gonna check it out."],
             'The proposal will be reviewed by the committee.',
             "Passive voice with no contractions signals formal register."),
            ("Rewrite 'The building was constructed in 1990' in informal register.",
             ['They built the building in 1990.', 'The building has been constructed in 1990.', 'The building was being constructed in 1990.'],
             'They built the building in 1990.',
             "Informal register favours active voice with a general subject ('they') over the passive."),
            ("Which verb pair matches formal → informal?",
             ['terminate → end', 'end → terminate', 'investigate → investigate'],
             'terminate → end',
             "'Terminate' is the Latinate formal verb; 'end' is its everyday informal equivalent."),
            ("Choose the informal contraction-based sentence.",
             ["We'll sort it out by Monday.", 'The matter will be resolved by Monday.', 'Resolution shall occur by Monday.'],
             "We'll sort it out by Monday.",
             "Contractions and the phrasal verb 'sort out' mark this as informal register."),
            ("Which is the most formal way to say 'we found out the problem'?",
             ['the problem was identified', 'we figured out the problem', "we've worked out the problem"],
             'the problem was identified',
             "The passive with a Latinate verb ('identified') is the most formal option here."),
        ],
    },
    {
        'unit': '5', 'lesson': '5A', 'topic': 'fronting and extraposition for emphasis',
        'rule_en': "Fronting moves an object, complement, or adverbial to the start of the clause for emphasis or to link with the previous sentence. Extraposition moves a long subject clause to the end of the sentence, replaced by dummy 'it' at the front, avoiding a heavy subject.",
        'rule_ru': "Вынесение (fronting) перемещает дополнение, определение или обстоятельство в начало предложения для эмфазы или связи с предыдущим предложением. Экстрапозиция переносит длинное придаточное подлежащее в конец предложения, заменяя его формальным 'it' в начале, чтобы избежать тяжёлого подлежащего.",
        'rule_tg': "Пешоварӣ (fronting) пуркунанда, муайянкунанда ё ҳолро ба аввали ҷумла мебарад барои таъкид. Экстрапозитсия ҷумлаи дарози мубтадоро ба охири ҷумла мебарад, ба ҷои он 'it'-и расмиро дар аввал мегузорад.",
        'structure': "fronting: Object/Complement/Adverbial + subject + verb; extraposition: It + be + adjective + that-clause / to-infinitive",
        'tip': "Extraposition is almost always preferred in natural English — 'That he will resign is unlikely' is grammatical but sounds stiff compared to 'It is unlikely that he will resign.'",
        'examples': [
            "This I cannot accept.",
            "Exhausted, she finally sat down.",
            "It is unlikely that he will resign.",
            "It surprised nobody that the plan failed.",
        ],
        'questions': [
            ("Identify the fronted element in 'Money, I don't care about.'",
             ['Money', "I don't care about", 'about'], 'Money',
             "'Money' (the object of 'care about') has been moved to the front for emphasis."),
            ("Choose the extraposed version of 'That she resigned surprised everyone.'",
             ['It surprised everyone that she resigned.', 'She resigned it surprised everyone.', 'Surprised everyone that she resigned it.'],
             'It surprised everyone that she resigned.',
             "The long subject clause 'that she resigned' moves to the end, replaced by dummy 'it' at the front."),
            ("Which sentence uses fronting for emphasis?",
             ['Never before had she felt so free.', 'She had never before felt so free.', 'She felt so free never before.'],
             'Never before had she felt so free.',
             "The adverbial 'never before' is fronted, triggering inversion for emphasis."),
            ("Choose the natural extraposed form of 'To finish on time is essential.'",
             ['It is essential to finish on time.', 'Essential it is to finish on time.', 'To finish it is essential on time.'],
             'It is essential to finish on time.',
             "Extraposing the to-infinitive subject with dummy 'it' is the natural, unmarked English structure."),
            ("Which sentence sounds unnaturally stiff because it avoids extraposition?",
             ['That he lied is obvious.', 'It is obvious that he lied.', "It's obvious he lied."],
             'That he lied is obvious.',
             "Keeping the that-clause as subject instead of extraposing it is grammatical but reads as stiff, formal English."),
        ],
    },
    {
        'unit': '5', 'lesson': '5B', 'topic': 'nominalisation for academic and formal tone',
        'rule_en': "Nominalisation turns a verb or adjective into a noun (decide → decision, analyse → analysis, aware → awareness), a hallmark of academic and formal register. It compresses information into a noun phrase and removes the need for a personal subject.",
        'rule_ru': "Номинализация превращает глагол или прилагательное в существительное (decide → decision, analyse → analysis, aware → awareness) — характерная черта академического и формального стиля. Она сжимает информацию в именную группу и избавляет от необходимости в личном подлежащем.",
        'rule_tg': "Номинализатсия феъл ё сифатро ба исм табдил медиҳад (decide → decision, analyse → analysis) — хусусияти забони академӣ ва расмӣ. Он иттилоотро дар гурӯҳи исмӣ фишурда мекунад ва эҳтиёҷ ба мубтадои шахсиро бартараф мекунад.",
        'structure': "verb/adjective → noun: decide→decision, fail→failure, aware→awareness, intervene→intervention",
        'tip': "Overusing nominalisation makes writing feel bureaucratic and lifeless — use it deliberately in academic contexts, not everywhere.",
        'examples': [
            "They decided to intervene. → Their decision to intervene changed the outcome.",
            "The company failed. → The failure of the company shocked investors.",
            "We are aware of the risks. → Our awareness of the risks informed the plan.",
            "The government intervened quickly. → The government's swift intervention prevented panic.",
        ],
        'questions': [
            ("Choose the nominalised form of 'The team analysed the data carefully.'",
             ["The team's careful analysis of the data...", 'The team analysing the data carefully...', 'The team analyse the data carefully...'],
             "The team's careful analysis of the data...",
             "'Analysed' becomes the noun 'analysis', with 'the team's' as possessive and 'carefully' becoming the adjective 'careful'."),
            ("Which noun correctly corresponds to the verb 'intervene'?",
             ['intervention', 'interveness', 'intervenation'], 'intervention',
             "'Intervene' → 'intervention' is the correct nominalised form."),
            ("Choose the most academic-sounding rewrite of 'They discovered the cause quickly.'",
             ['Their swift discovery of the cause...', 'They discover the cause quick...', 'They were discovering the cause quickly...'],
             'Their swift discovery of the cause...',
             "Nominalising 'discovered' into 'discovery' and 'quickly' into 'swift' produces the academic noun-phrase style."),
            ("Which sentence is overly nominalised and sounds bureaucratic?",
             ['The implementation of the reduction of expenditure necessitated the reallocation of resources.', 'We cut spending, so we had to reallocate resources.', 'Cutting spending meant reallocating resources.'],
             'The implementation of the reduction of expenditure necessitated the reallocation of resources.',
             "Stacking multiple nominalisations in one sentence makes it dense and lifeless — a common overuse pitfall."),
            ("Choose the correct noun form of 'aware'.",
             ['awareness', 'awarement', 'awarity'], 'awareness',
             "'Aware' (adjective) → 'awareness' (noun) is the correct nominalised form."),
        ],
    },
    {
        'unit': '6', 'lesson': '6A', 'topic': 'mixed and layered conditionals',
        'rule_en': "Mixed conditionals combine two different time frames: a past condition with a present result ('If I hadn't missed the flight, I would be there now'), or a present/ongoing condition with a past result ('If she weren't so shy, she would have spoken up yesterday').",
        'rule_ru': "Смешанные условные предложения соединяют два разных временных плана: прошлое условие с настоящим результатом ('If I hadn't missed the flight, I would be there now') или настоящее/постоянное условие с прошлым результатом ('If she weren't so shy, she would have spoken up yesterday').",
        'rule_tg': "Ҷумлаҳои шартии омехта ду замони гуногунро мепайванданд: шарти гузашта бо натиҷаи ҳозира ('If I hadn't missed the flight, I would be there now') ё шарти ҳозира бо натиҷаи гузашта ('If she weren't so shy, she would have spoken up yesterday').",
        'structure': "past→present: If + past perfect, ... would + base verb; present→past: If + past simple, ... would have + past participle",
        'tip': "Decide which clause is the 'condition' and which is the 'result' first — the tense of each depends on its own time frame, not on matching the other clause.",
        'examples': [
            "If I hadn't missed the flight, I would be there now.",
            "If she weren't so shy, she would have spoken up yesterday.",
            "If he had studied medicine, he would be a doctor today.",
            "If I didn't trust him, I wouldn't have lent him the money last week.",
        ],
        'questions': [
            ("Choose the correct mixed conditional: 'If I ___ harder at school, I would have a better job now.'",
             ['had worked', 'worked', 'would work'], 'had worked',
             "The condition is about the past ('at school'), so it needs past perfect, even though the result is present."),
            ("Choose the correct result clause: 'If she weren't so stubborn, she ___ apologised by now.'",
             ['would have', 'would', 'will have'], 'would have',
             "The result refers to a completed past action ('by now'), so it needs 'would have + past participle'."),
            ("Which sentence is a correctly formed mixed conditional?",
             ["If he hadn't left his job, he'd still be earning a good salary.", "If he doesn't leave his job, he'd still be earning a good salary.", "If he hadn't left his job, he'll still be earning a good salary."],
             "If he hadn't left his job, he'd still be earning a good salary.",
             "Past-condition ('hadn't left') + present-result ('he'd still be earning') is the correct mixed-conditional pairing."),
            ("Identify the time frame mismatch type in 'If I weren't afraid of heights, I would have gone skydiving last year.'",
             ['present condition, past result', 'past condition, present result', 'no mismatch, this is a standard third conditional'],
             'present condition, past result',
             "'Weren't afraid' describes an ongoing/present trait, while 'would have gone' refers to a specific past opportunity."),
            ("Complete: 'If they ___ more carefully, they wouldn't be in this mess today.'",
             ['had planned', 'planned', 'have planned'], 'had planned',
             "The condition is about a past action ('planned'), needing past perfect, while the result is present ('today')."),
        ],
    },
    {
        'unit': '6', 'lesson': '6B', 'topic': 'structural ambiguity and disambiguation',
        'rule_en': "Some sentences allow more than one grammatical reading because a modifying phrase can attach to more than one part of the sentence (attachment ambiguity). Careful writers restructure the sentence, reorder words, or add punctuation to remove the ambiguity.",
        'rule_ru': "Некоторые предложения допускают более одного грамматического прочтения, потому что определяющая фраза может относиться к разным частям предложения (неоднозначность присоединения). Внимательные авторы перестраивают предложение, меняют порядок слов или добавляют пунктуацию, чтобы убрать неоднозначность.",
        'rule_tg': "Баъзе ҷумлаҳо якчанд шарҳи грамматикиро иҷозат медиҳанд, зеро ибораи муайянкунанда метавонад ба қисматҳои гуногуни ҷумла пайваст шавад. Муаллифони эҳтиёткор ҷумларо аз нав месозанд ё аломати китобатро илова мекунанд, то ин норавшаниро бартараф кунанд.",
        'structure': "N/A — recognise ambiguous attachment and restructure to remove it",
        'tip': "A classic test: ask 'who or what does this phrase logically describe?' If more than one answer works, the sentence is ambiguous.",
        'examples': [
            "Ambiguous: I saw the man with a telescope.",
            "Clear: Using a telescope, I saw the man.",
            "Clear: I saw the man who had a telescope.",
            "Ambiguous: Visiting relatives can be tiring. Clear: Relatives who visit can be tiring. / Visiting one's relatives can be tiring.",
        ],
        'questions': [
            ("Which phrase in 'I saw the man with a telescope' is ambiguously attached?",
             ['with a telescope', 'I saw', 'the man'], 'with a telescope',
             "'With a telescope' could describe how 'I' saw him, or describe the man himself as having a telescope."),
            ("Choose the version that removes the ambiguity in favour of 'I was using the telescope'.",
             ['Using a telescope, I saw the man.', 'I saw the man who had a telescope.', 'The man with a telescope, I saw.'],
             'Using a telescope, I saw the man.',
             "Fronting the participle clause makes it clear that 'I' was the one using the telescope."),
            ("Which sentence is genuinely ambiguous?",
             ['Flying planes can be dangerous.', 'Planes that fly can be dangerous.', 'Flying a plane can be dangerous.'],
             'Flying planes can be dangerous.',
             "'Flying planes' could mean 'planes that fly' or 'the act of flying planes' — a classic gerund/participle ambiguity."),
            ("Choose the clearest rewrite of 'The teacher told the student he had failed the exam.'",
             ['The teacher told the student, \"You have failed the exam.\"', 'The teacher told the student he had failed the exam quietly.', 'He had failed the exam, the teacher told the student.'],
             'The teacher told the student, "You have failed the exam."',
             "Using direct speech removes the ambiguity of who 'he' refers to (the teacher or the student)."),
            ("What kind of ambiguity does 'the professor's interesting lecture notes' contain?",
             ['is it the notes that are interesting, or the lecture that is interesting?', 'no ambiguity at all', 'ambiguity about who the professor is'],
             'is it the notes that are interesting, or the lecture that is interesting?',
             "'Interesting' could modify 'lecture' or the whole phrase 'lecture notes' — a modifier-scope ambiguity."),
        ],
    },
    {
        'unit': '7', 'lesson': '7A', 'topic': 'parallelism and rhetorical patterning',
        'rule_en': "Rhetorical grammar repeats a grammatical structure for effect. A tricolon lists three parallel items, often building to a climax; anaphora repeats a word or phrase at the start of successive clauses for emphasis and rhythm.",
        'rule_ru': "Риторическая грамматика повторяет одну грамматическую структуру для эффекта. Триколон перечисляет три параллельных элемента, часто нарастая к кульминации; анафора повторяет слово или фразу в начале последовательных предложений для эмфазы и ритма.",
        'rule_tg': "Грамматикаи риторикӣ як сохтори грамматикиро барои таъсир такрор мекунад. Триколон се унсури параллелро номбар мекунад, аксар вақт то кульминатсия боло меравад; анафора калима ё ибораро дар аввали ҷумлаҳои пайдарпай такрор мекунад.",
        'structure': "tricolon: X, Y, and Z (same grammatical form); anaphora: [Phrase] + clause1. [Phrase] + clause2.",
        'tip': "Parallel items must share the same grammatical form (all nouns, all -ing verbs, all infinitives) — mixing forms breaks the pattern and sounds wrong.",
        'examples': [
            "Government of the people, by the people, for the people.",
            "We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields.",
            "She came, she saw, she conquered.",
            "Not out of anger, not out of spite, but out of love.",
        ],
        'questions': [
            ("Which is a correctly formed tricolon?",
             ['Veni, vidi, vici. / I came, I saw, I conquered.', 'I came, I was seeing, I conquered.', 'I came, seeing, and to conquer.'],
             'Veni, vidi, vici. / I came, I saw, I conquered.',
             "All three verbs share the identical grammatical form (simple past), which is what makes the tricolon work."),
            ("Identify the anaphora in this pair of sentences: 'We will not surrender. We will not give up.'",
             ["'We will not'", "'surrender'", "'give up'"], "'We will not'",
             "'We will not' is repeated at the start of both clauses — that repetition is anaphora."),
            ("Which sentence breaks parallel structure?",
             ['She likes reading, writing, and to paint.', 'She likes reading, writing, and painting.', 'She likes to read, to write, and to paint.'],
             'She likes reading, writing, and to paint.',
             "Mixing gerunds ('reading, writing') with an infinitive ('to paint') breaks the parallel grammatical pattern."),
            ("Complete the tricolon in the same grammatical form: 'The plan was bold, ambitious, and ___.'",
             ['risky', 'a risk', 'risking'], 'risky',
             "All three items must be adjectives to match 'bold' and 'ambitious'; 'risky' is the adjective form."),
            ("Why does 'Government of the people, by the people, for the people' work rhetorically?",
             ['identical preposition + noun phrase pattern repeated three times', 'each clause uses a different verb tense', 'it uses no repetition at all'],
             'identical preposition + noun phrase pattern repeated three times',
             "The repeated 'preposition + the people' structure across three phrases is what creates the rhetorical effect."),
        ],
    },
    {
        'unit': '7', 'lesson': '7B', 'topic': 'discourse-level cohesion: advanced linking and signposting',
        'rule_en': "Advanced writing signals logical relationships between whole sentences and paragraphs — not just clauses — using discourse markers like 'that said', 'by the same token', 'crucially', and 'this is not to say that', which guide the reader through the argument.",
        'rule_ru': "Продвинутое письмо обозначает логические связи между целыми предложениями и абзацами (а не только придаточными) с помощью маркеров дискурса, таких как 'that said', 'by the same token', 'crucially', 'this is not to say that', которые ведут читателя через аргументацию.",
        'rule_tg': "Навиштани пешрафта муносибатҳои мантиқии байни ҷумлаҳо ва бандҳоро (на танҳо ҷумлаҳои пайрав) бо аломатҳои дискурс, ба монанди 'that said', 'crucially', 'this is not to say that' нишон медиҳад, ки хонандаро тавассути далел роҳнамоӣ мекунанд.",
        'structure': "[Sentence]. Discourse marker, [sentence].",
        'tip': "Discourse markers work at the level of whole ideas, not single words — place them at the start of a sentence, followed by a comma.",
        'examples': [
            "The plan is ambitious. That said, it is not unrealistic.",
            "Crucially, none of this would have been possible without funding.",
            "This is not to say that the results are conclusive.",
            "The two policies share a goal; by the same token, they share many of the same flaws.",
        ],
        'questions': [
            ("Choose the discourse marker that introduces a concession.",
             ['That said', 'Crucially', 'By the same token'], 'That said',
             "'That said' signals that the following point qualifies or contrasts with what was just stated."),
            ("Which marker highlights the single most important point?",
             ['Crucially', 'That said', 'This is not to say that'], 'Crucially',
             "'Crucially' flags the point that follows as the decisive one in the argument."),
            ("Complete: 'The study had a small sample size. ___, its findings are worth taking seriously.'",
             ['That said', 'By the same token', 'This is not to say that'], 'That said',
             "'That said' introduces a contrasting point after acknowledging a limitation, which fits the context here."),
            ("Which sentence uses 'by the same token' correctly?",
             ['He works hard for his team; by the same token, he expects the same from others.', 'He works hard for his team, by the same token he is lazy.', 'By the same token he works hard.'],
             'He works hard for his team; by the same token, he expects the same from others.',
             "'By the same token' links a similar, parallel point that follows logically — not a contradiction."),
            ("What does 'This is not to say that' typically precede?",
             ['a clarification limiting an overly strong claim just made', 'a completely unrelated new topic', 'a direct quotation'],
             'a clarification limiting an overly strong claim just made',
             "It is used to head off a misreading, clarifying that the previous statement shouldn't be taken too far."),
        ],
    },
    {
        'unit': '8', 'lesson': '8A', 'topic': 'emphatic auxiliary do/does/did for contrast and correction',
        'rule_en': "Emphatic 'do/does/did' stresses the auxiliary to affirm a fact strongly, often contradicting a previous statement, correcting a wrong assumption, or reassuring the listener.",
        'rule_ru': "Эмфатическое 'do/does/did' выделяет вспомогательный глагол, чтобы решительно подтвердить факт — часто опровергая предыдущее утверждение, исправляя неверное предположение или успокаивая собеседника.",
        'rule_tg': "'Do/does/did'-и таъкидӣ феъли ёридиҳандаро таъкид карда, далеро сахт тасдиқ мекунад — аксар вақт барои рад кардани гуфтаи қаблӣ ё ислоҳи тахмини нодуруст.",
        'structure': "Subject + do/does/did (stressed) + base verb",
        'tip': "In writing, emphatic do is often shown with italics or capitals on the auxiliary: 'I DID lock the door.'",
        'examples': [
            "I DID lock the door — I remember clearly.",
            "She does care, she's just bad at showing it.",
            "He did apologise, even if it didn't sound sincere.",
            "We do appreciate your help, honestly.",
        ],
        'questions': [
            ("Which sentence uses emphatic do to correct a wrong assumption?",
             ["A: You never call me. B: I do call you, you just don't answer.", 'A: You never call me. B: Sorry, I forgot.', 'A: You never call me. B: I called you yesterday.'],
             "A: You never call me. B: I do call you, you just don't answer.",
             "'I do call you' directly contradicts and corrects the assumption in A's statement."),
            ("Choose the emphatic form of 'She likes him.'",
             ['She does like him.', 'She is liking him.', 'She likes really him.'], 'She does like him.',
             "Inserting stressed 'does' before the base verb 'like' creates the emphatic form."),
            ("Complete: 'I know you think I forgot, but I ___ remember your birthday.'",
             ['did', 'was', 'have'], 'did',
             "Emphatic 'did' + base verb 'remember' corrects the listener's assumption about the past."),
            ("Which context best suits emphatic do?",
             ['reassuring someone after they doubted you', 'asking a neutral yes/no question', 'describing a routine habit with no emphasis'],
             'reassuring someone after they doubted you',
             "Emphatic do is specifically used to affirm strongly against doubt or contradiction, not for neutral statements."),
            ("Choose the correctly stressed emphatic sentence.",
             ['We do value your feedback.', 'We are doing value your feedback.', 'We value do your feedback.'],
             'We do value your feedback.',
             "Emphatic 'do' precedes the base form of the main verb 'value'."),
        ],
    },
    {
        'unit': '8', 'lesson': '8B', 'topic': 'advanced passive and causative nuance',
        'rule_en': "Beyond the basic passive, 'get' can replace 'be' for an informal, often unexpected or unfortunate passive ('He got fired'). The causative 'have/get something done' emphasizes arranging for someone else to perform an action, and 'get to do' expresses an earned or lucky opportunity.",
        'rule_ru': "Помимо обычного страдательного залога, 'get' может заменять 'be' для неформального, часто неожиданного или неприятного пассива ('He got fired'). Каузатив 'have/get something done' подчёркивает организацию действия чужими руками, а 'get to do' выражает заслуженную или удачную возможность.",
        'rule_tg': "Ба ғайр аз тарзи мафъулии оддӣ, 'get' метавонад ба ҷои 'be' барои мафъулии ғайрирасмии ногаҳонӣ истифода шавад ('He got fired'). Каузативи 'have/get something done' ташкили амалро бо дасти дигарон таъкид мекунад, ва 'get to do' имконияти сазовор ё хушбахтро ифода мекунад.",
        'structure': "get + past participle (informal passive); have/get + object + past participle (causative); get to + infinitive (opportunity)",
        'tip': "'Get' passives usually carry a sense of something happening TO the subject unexpectedly — 'get promoted' feels more personal/surprising than 'be promoted'.",
        'examples': [
            "He got fired last week.",
            "We're having the roof repaired next month.",
            "She finally got to meet her idol.",
            "I got my car stolen while I was on holiday.",
        ],
        'questions': [
            ("Choose the informal 'get' passive equivalent of 'The window was broken.'",
             ['The window got broken.', 'The window was getting broken.', 'The window gets break.'],
             'The window got broken.',
             "'Get' replaces 'be' for an informal, often unexpected passive."),
            ("Which sentence is a correct causative structure?",
             ["We're getting the car serviced tomorrow.", "We're getting the car service tomorrow.", "We're getting service the car tomorrow."],
             "We're getting the car serviced tomorrow.",
             "Causative 'get + object + past participle' — 'get the car serviced' means arranging for someone else to service it."),
            ("Choose the sentence expressing an earned opportunity.",
             ['She got to travel the world for work.', 'She got travelled the world for work.', 'She got to travelling the world for work.'],
             'She got to travel the world for work.',
             "'Get to + infinitive' expresses a lucky or earned opportunity — 'travel' stays in base form."),
            ("What nuance does 'He got promoted' add compared to 'He was promoted'?",
             ['a slightly more informal, personal or surprised tone', 'it means the opposite happened', 'it is grammatically incorrect'],
             'a slightly more informal, personal or surprised tone',
             "'Get' passives tend to feel more informal and personally involved than the neutral 'be' passive."),
            ("Complete the causative: 'I need to ___ my hair cut before the interview.'",
             ['have', 'do', 'make'], 'have',
             "'Have something done' is the standard causative pattern for arranging a service."),
        ],
    },
    {
        'unit': '9', 'lesson': '9A', 'topic': 'idiomatic grammar: phrasal-prepositional verbs',
        'rule_en': "Three-part phrasal-prepositional verbs (verb + adverb particle + preposition) behave as a single fixed unit with their own meaning and grammar: fixed word order, and the object always comes after the whole unit, never in the middle.",
        'rule_ru': "Трёхчастные фразово-предложные глаголы (глагол + наречная частица + предлог) ведут себя как единая неразрывная единица со своим значением и грамматикой: фиксированный порядок слов, дополнение всегда стоит после всей конструкции целиком, никогда посередине.",
        'rule_tg': "Феълҳои фразавӣ-пешояндии сеқисма (феъл + зарраи зарфӣ + пешоянд) ҳамчун як воҳиди ягона бо маънои худ рафтор мекунанд: тартиби калимаҳо собит аст, пуркунанда ҳамеша баъд аз тамоми воҳид меояд.",
        'structure': "verb + particle + preposition + object (never separable)",
        'tip': "Unlike two-part phrasal verbs ('turn it off'), three-part phrasal-prepositional verbs are never separable: 'put up with it', never 'put it up with'.",
        'examples': [
            "I won't put up with this behaviour any longer.",
            "She looks down on people who didn't go to university.",
            "We need to come up with a better plan.",
            "He finally caught up on all his emails.",
        ],
        'questions': [
            ("Choose the correctly formed three-part phrasal-prepositional verb.",
             ["I can't put up with the noise.", "I can't put the noise up with.", "I can't put up the noise with."],
             "I can't put up with the noise.",
             "Three-part phrasal-prepositional verbs are inseparable — the object always follows the whole unit."),
            ("What does 'look down on someone' mean?",
             ['to consider someone inferior', 'to look at someone from above physically', 'to admire someone greatly'],
             'to consider someone inferior',
             "'Look down on' is an idiomatic phrasal-prepositional verb meaning to regard someone as inferior."),
            ("Choose the correct object placement for 'come up with'.",
             ["We came up with a solution.", "We came a solution up with.", "We came up a solution with."],
             "We came up with a solution.",
             "The object 'a solution' must come after the complete three-part unit 'come up with'."),
            ("Which sentence is ungrammatical because it separates a phrasal-prepositional verb?",
             ['She looks the new employee down on.', 'She looks down on the new employee.', 'She always looks down on new employees.'],
             'She looks the new employee down on.',
             "Splitting 'look down on' by inserting the object in the middle is not allowed — it must stay together."),
            ("What does 'catch up on' mean in 'He caught up on his sleep'?",
             ['to do something delayed or missed, now', 'to physically catch something falling', 'to argue about something'],
             'to do something delayed or missed, now',
             "'Catch up on' means to do or deal with something that was neglected or delayed."),
        ],
    },
    {
        'unit': '9', 'lesson': '9B', 'topic': 'fixed grammatical idioms and syntactic flexibility',
        'rule_en': "Some idiomatic patterns are grammatically fixed and don't follow normal rules of word order or article use ('for the life of me', 'come what may', 'be that as it may'). Recognising them as fixed chunks — rather than analysing them word by word — is essential at this level.",
        'rule_ru': "Некоторые идиоматические конструкции грамматически фиксированы и не следуют обычным правилам порядка слов или употребления артиклей ('for the life of me', 'come what may', 'be that as it may'). Распознавание их как готовых блоков, а не анализ по словам, необходимо на этом уровне.",
        'rule_tg': "Баъзе шаклҳои идиоматикӣ аз ҷиҳати грамматикӣ собитанд ва қоидаҳои маъмулии тартиби калимаҳоро риоя намекунанд ('for the life of me', 'come what may'). Шинохтани онҳо ҳамчун блокҳои тайёр, на таҳлили калима ба калима, дар ин сатҳ муҳим аст.",
        'structure': "N/A — fixed idiomatic chunks, memorised as whole units",
        'tip': "Don't try to translate these word-for-word or apply normal grammar rules to them — learn each one as a complete, unchangeable phrase.",
        'examples': [
            "For the life of me, I can't remember his name.",
            "Come what may, we will finish this project.",
            "Be that as it may, the decision stands.",
            "Suffice it to say, the meeting did not go well.",
        ],
        'questions': [
            ("What does 'for the life of me' mean?",
             ['no matter how hard I try', 'for a very long time', 'in order to save my life'],
             'no matter how hard I try',
             "'For the life of me' is a fixed idiom meaning 'no matter how hard I try (I can't)'."),
            ("Choose the correct use of 'be that as it may'.",
             ['He has good reasons; be that as it may, the rule still applies to him.', 'Be that as it may happen, the rule applies.', 'The rule be that as it may applies.'],
             'He has good reasons; be that as it may, the rule still applies to him.',
             "'Be that as it may' is a fixed concessive phrase meaning 'even so' or 'nevertheless', used as a whole unit."),
            ("What does 'come what may' express?",
             ['determination regardless of what happens', 'uncertainty about the future', 'a question about timing'],
             'determination regardless of what happens',
             "'Come what may' means 'whatever happens', expressing firm resolve."),
            ("Choose the sentence that correctly uses 'suffice it to say'.",
             ["Suffice it to say, he was not pleased.", "It suffice to say he was not pleased.", "Suffice to it say he was not pleased."],
             "Suffice it to say, he was not pleased.",
             "'Suffice it to say' is a fixed inverted idiom (from 'let it suffice to say') used as a single introductory phrase."),
            ("Why shouldn't learners analyse 'for the life of me' word by word?",
             ['because its meaning as a fixed idiom is not predictable from the individual words', 'because it contains no verb', "because it's grammatically incorrect"],
             'because its meaning as a fixed idiom is not predictable from the individual words',
             "Fixed idioms carry a meaning that can't be derived by parsing each word separately — they must be learned whole."),
        ],
    },
]


async def seed_grammar(db):
    created_lessons = 0
    skipped_lessons = 0

    for idx, item in enumerate(LESSONS):
        source_key = f'seed:C2:grammar:{idx}'
        existing = (
            await db.execute(select(GrammarLessons).where(GrammarLessons.source_key == source_key))
        ).scalar_one_or_none()

        if existing is not None:
            skipped_lessons += 1
            continue

        lesson = GrammarLessons(
            cefr_level='C2',
            unit=item['unit'],
            lesson=item['lesson'],
            topic=item['topic'],
            rule_en=item['rule_en'],
            rule_ru=item['rule_ru'],
            rule_tg=item['rule_tg'],
            structure=item['structure'],
            tip=item['tip'],
            source_key=source_key,
        )
        db.add(lesson)
        await db.flush()

        for order, text in enumerate(item['examples']):
            db.add(GrammarExamples(lesson_id=lesson.id, text=text, order=order))

        for text_en, options, answer, explanation_en in item['questions']:
            db.add(GrammarQuestions(
                lesson_id=lesson.id,
                type='multiple_choice',
                text_en=text_en,
                options=options,
                answer=answer,
                explanation_en=explanation_en,
            ))

        created_lessons += 1

    return created_lessons, skipped_lessons


async def main():
    async with AsyncSessionLocal() as db:
        created, skipped = await seed_grammar(db)
        await db.commit()
        print(f'grammar lessons: created {created}, skipped {skipped} (already seeded)')


if __name__ == '__main__':
    asyncio.run(main())
